= Comando Coordenadas
:page-en: commands/SetCoords
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Coordenadas( <Objeto>, <x>, <y> )::
  Cambia las coordenadas cartesianas de objetos xref:/Objetos_libres_dependientes_y_auxiliares.adoc[libres] en una Vista 2D
  según las coordenadas dadas. Este comando utiliza los valores de las coordenadas, no sus definiciones, por lo que el objeto permanece libre.

Coordenadas( <Objeto>, <x>, <y>, <z> )::
  Cambia las coordenadas cartesianas de objetos xref:/Objetos_libres_dependientes_y_auxiliares.adoc[libres] en una Vista 3D
  según las coordenadas dadas. Este comando utiliza los valores de las coordenadas, no sus definiciones, por lo que el objeto permanece libre.

[NOTE]
====

* Este comando funciona para puntos en recorridos y regiones. El punto será movido a la posición más cercana posible.

* También funciona con deslizadores, botones, casillas de control, cajas de entrada e imágenes.

* Si la opción "Posición absoluta en pantalla" está seleccionada, entonces _x_, _y_ y _z_ se consideran en pixeles.

====
