= Comando Denominador
:page-en: commands/Denominator
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Denominador( <Función> )::
  Devuelve el denominador de la función.

[EXAMPLE]
====

`++Denominador(5 / (x^2 + 2))++` devuelve _f(x)=(x^2^ + 2)_.

====

Denominador( <Número> )::
  Para un número racional, devuelve su denominador (simplificado). Utiliza un método numérico que limita el comando a números con un
  denominador pequeño. Si la entrada es un número irracional, se obtiene el denominador de su xref:/commands/FracciónContinua.adoc[fracción continua].

[EXAMPLE]
====

* `++Denominador(5 / 3)++` devuelve _3_.
* `++Denominador(10 / 6)++` devuelve _3_.
* `++Denominador(15 / 3)++` devuelve _1_.

====

[NOTE]
====

Ver también los comandos xref:/commands/Numerador.adoc[Numerador] y xref:/commands/TextoFracción.adoc[TextoFracción].

====

== Sintaxis CAS

Denominador( <Expresión> )::
  Da por resultado el numerador de un número racional o expresión.

[EXAMPLE]
====

`++Denominador(2 / 3 + 1 / 15)++` devuelve _15_.

====
