= Comando Derivada
:page-en: commands/Derivative
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Derivada( <Función> )::
  Devuelve la derivada de la función respecto de la variable principal.

[EXAMPLE]
====

`++Derivada(x^3 + x^2 + x)++` devuelve _3x² + 2x + 1_.

====

Derivada( <Función>, <Número> )::
  Devuelve la derivada del número de orden indicado de la función respecto de la variable principal.

[EXAMPLE]
====

`++Derivada(x^3 + x^2 + x, 2)++` devuelve _6x + 2_.

====

Derivada( <Función>, <Variable> )::
  Devuelve la derivada parcial de la función respecto de la variable dada.

[EXAMPLE]
====

`++Derivada(x^3 y^2 + y^2 + xy, y)++` devuelve _2x³y + x + 2y_.

====

Derivada( <Función>, <Variable>, <Número> )::
  Devuelve la derivada parcial de orden _n_ de la función respecto de la variable dada, siendo _n_ el parámetro _Número_.

[EXAMPLE]
====

`++Derivada(x^3 + 3x y, x, 2)++` devuelve _6x_.

====

Derivada( <Curva> )::
  Devuelve la derivada de la curva.

[EXAMPLE]
====

`++Derivada(Curva(cos(t), t sen(t), t, 0, π))++` devuelve la curva _x = -sen(t), y = sen(t) + t cos(t)_.

====

[NOTE]
====

Esto funciona solamente para curvas paramétricas.

====

Derivada( <Curva>, <Número> )::
  Devuelve la derivada de la curva de orden _n_, siendo _n_ el parámetro _Número_.

[EXAMPLE]
====

`++Derivada(Curva(cos(t), t sen(t), t, 0, π), 2)++` devuelve la curva _x = -cos(t), y = 2cos(t) - t sen(t)_.

====

[NOTE]
====

Esto funciona solamente para curvas paramétricas.

====

[NOTE]
====

Se puede utilizar `++f'(x)++` en lugar de `++Derivada(f)++`, o `++f''(x)++` en lugar de `++Derivada(f, 2)++`, y así sucesivamente.

====

== Sintaxis CAS

Derivada( <Expresión> )::
  Devuelve la derivada de la expresión respecto de la variable principal.

[EXAMPLE]
====

`++Derivada(x^2)++` devuelve _2x_.

====

Derivada( <Expresión>, <Variable> )::
  Devuelve la derivada de la expresión respecto de la variable dada.

[EXAMPLE]
====

`++Derivada(a x^3, a)++` devuelve _x³_.

====

Derivada( <Expresión>, <Variable>, <Número> )::
  Devuelve la derivada de orden _n_ de la expresión respecto de la variable dada, siendo _n_ el parámetro _Número_.

[EXAMPLE]
====

* `++Derivada(y x^3, x, 2)++` devuelve _6xy_.
* `++Derivada(x³ + 3x y, x, 2)++` devuelve _6x_.

====
