= Comando DiagramaCaja
:page-en: commands/BoxPlot
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

DiagramaCaja( <Offset_y>, <Escala_y>, <Lista de datos brutos> )::
  Crea un diagrama de caja usando los datos en bruto, cuya posición vertical en el sistema de coordenadas lo controla la
  variable _Offset_y_ y su altura, depende del factor _Escala_y_.

[EXAMPLE]
====

`++DiagramaCaja(0, 1, {2, 2, 3, 4, 5, 5, 6, 7, 7, 8, 8, 8, 9})++`

====

DiagramaCaja( <Offset_y>, <Escala_y>, <Valor inicial>, <Q1>, <Mediana>, <Q3>, <Valor final> )::
  Crea un diagrama de caja para los datos estadísticos dados en el intervalo (_Valor inicial, Valor final_).

DiagramaCaja( <Offset_y>, <Escala_y>, <Lista de datos brutos>, <Atipicidades o no (true/false)> )::
  Esto permite que los valores atípicos se representen con "X" en lugar de incluirse en el diagrama de caja.
  Para este comando, los https://es.wikipedia.org/wiki/Valor_at%C3%ADpico[valores atípicos] son los datos que se
  encuentran por debajo de _Q1 - 1.5 * (Q3 - Q1)_ o por encima de _Q3 + 1.5 * (Q3 - Q1)_
  (ver https://es.wikipedia.org/wiki/Rango_intercuart%C3%ADlico[RIQ]).

DiagramaCaja( <Offset_y>, <Escala_y>, <Lista de datos>, <Lista de frecuencias>, <Atipicidades o no (true/false)> )::
  Esto permite representar fácilmente los datos de una tabla de frecuencias como un diagrama de caja.

