= Comando Envolvente
:page-en: commands/Envelope
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Envolvente( <Trayecto>, <Punto> )::
  Crea la ecuación de la http://en.wikipedia.org/wiki/es:Envolvente_(matem%C3%A1ticas)[envolvente] de un conjunto de
  trayectos mientras el punto está vinculado a otro objeto.

La envolvente es una curva que es tangente a cada miembro de la familia de trayectos en cierto punto.

[EXAMPLE]
====

http://www.geogebra.org/student/m67909[A ladder is leaning against the wall and sliding down.]

El contorno del conjunto de rastros que va dejando desde cierto punto de la escalera, conforma su _envolvente_.
Estrictamente, GeoGebra computa la envolvente de la recta completa que contiene a la escalera como un segmento.
Solamente tales envolventes pueden ser computadas cuando la construcción apropiada conduce a un sistrma de ecuaciones
algebraicas.

====

[NOTE]
====

Ver también los comandos xref:/commands/LugarGeométrico.adoc[LugarGeométrico],
xref:/commands/EcuaciónLugar.adoc[EcuaciónLugar] y el artículo
https://github.com/kovzol/gg-art-doc/tree/master/pdf/english.pdf[GeoGebra Automated Reasoning Tools: A Tutorial].

====
