= Comando GroebnerDegRevLex
:page-en: commands/GroebnerDegRevLex
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

== Sintaxis CAS

GroebnerDegRevLex( <Lista de polinomios> )::
  Establece las bases Gröbner de la lista de polinomios con respecto al orden inverso de grado léxico-gráfico de las
  variables (también conocido como _orden total de grado inverso léxico-gráfico_ o _eliminación por orden_).

[EXAMPLE]
====

`++GroebnerDegRevLex({x^3 - y - 2, x^2 + y + 1})++` devuelve {stem:[ y^{2} - x + 3 y + 3, x y + x + y + 2, x^{2} + y +
1 ]}.

====

GroebnerDegRevLex( <Lista de polinomios>, <Lista de variables> )::
  Establece las bases Gröbner de la lista de polinomios con respecto al orden inverso de grado léxico-gráfico de las
  variables indicadas (también conocido como _orden total inverso de grado léxico-gráfico_ o _eliminación por
  orden_).

[EXAMPLE]
====

`++GroebnerDegRevLex({x^3 - y - 2, x^2 + y + 1}, {y, x})++` devuelve {stem:[ x^{2} + y + 1, y x + y + x + 2, y^{2} + 3y - x + 3]}.

====

[NOTE]
====

Ver también los comandos xref:/commands/GroebnerLex.adoc[GroebnerLex] y
xref:/commands/GroebnerLexDeg.adoc[GroebnerLexDeg].

====
