= Comando GráficoEscalonado
:page-en: commands/StepGraph
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

GráficoEscalonado( <Lista de puntos> )::
  Traza un gráfico escalonado de la lista de puntos dada.  Cada punto se conecta al siguiente punto en la lista mediante un segmento horizontal.

[EXAMPLE]
====

`++GráficoEscalonado({(1, 1), (3, 2), (4, 5), (5, 7)})++`

====

GráficoEscalonado( <Lista de puntos>, <Conectados o no (true/false)> )::
  Traza un gráfico escalonado de la lista dada de puntos. Si _Conectados o no = false_ (falso), entonces se dibuja un segmento horizontal
  hacia la abscisa del siguiente punto, pero no se dibuja un segmento vertical. Si _Conectados o no = true_ (verdadero),
  entonces cada punto se conecta al siguiente punto en la lista mediante un segmento horizontal y un segmento de línea vertical.

[EXAMPLE]
====

`++GráficoEscalonado({(1, 1), (3, 2), (4, 5), (5, 7)}, true)++`

====

GráficoEscalonado( <Lista de abscisas>, <Lista de ordenadas> )::
  Traza un gráfico escalonado de una lista de puntos creada a partir de las listas dadas de coordenadas.
  Cada punto se conecta al siguiente punto en la lista mediante un segmento horizontal.

[EXAMPLE]
====

`++GráficoEscalonado({1, 3, 4, 5}, {1, 2, 5, 7})++`

====

GráficoEscalonado( <Lista de abscisas>, <Lista de ordenadas>, <Conectados o no (true/false)> )::
  Traza un gráfico escalonado de una lista de puntos creada a partir de las listas dadas de coordenadas.
  Si _Conectados o no = false_ (falso), se dibuja un segmento horizontal hacia la abscisa del siguiente punto, pero no se dibuja un segmento vertical.
  Si _Conectados o no = true_ (verdadero), cada punto se conecta al siguiente punto en la lista mediante un segmento horizontal y un segmento vertical.

[EXAMPLE]
====

`++GráficoEscalonado({1, 3, 4, 5}, {1, 2, 5, 7}, true)++`

====

GráficoEscalonado( <Lista de abscisas>, <Lista de ordenadas>, <Conectados o no (true/false)>, <Estilo de punto> )::
  Traza un gráfico escalonado como se describió anteriormente. Los valores de estilo de punto _-2, -1, 0, 1, -1_ determinan
  cómo se trazan los puntos de la siguiente manera:  
  * _0_ = no se trazan puntos  
  * _1_ = puntos sólidos a la derecha  
  * _2_ = puntos sólidos a la derecha, puntos abiertos a la izquierda  
  * _-1_ = puntos sólidos a la izquierda  
  * _-2_ = puntos sólidos a la izquierda, puntos abiertos a la derecha

[EXAMPLE]
====

`++GráficoEscalonado({1, 3, 4, 5}, {1, 2, 5, 7}, false, 1)++`

====

GráficoEscalonado( <Lista de puntos>, <Conectados o no (true/false)>, <Estilo de punto> )::
  Traza un gráfico escalonado como se describió anteriormente.

[EXAMPLE]
====

`++GráficoEscalonado({(1, 1), (3, 2), (4, 5), (5, 7)}, false, 1)++`

====
