= Comando Histograma
:page-en: commands/Histogram
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Histograma( <Lista de límites de clases>, <Lista de alturas> )::
  Crea un histograma con barras de las alturas dadas. Los límites de clases determinan
  el ancho y posición de cada barra del histograma.

[EXAMPLE]
====

`++Histograma({0, 1, 2, 3, 4, 5}, {2, 6, 8, 3, 1})++` crea un histograma con 5 barras de las alturas dadas. La primera barra
es posicionada en el intervalo [_0, 1_], la segunda barra es posicionada en el intervalo [_1, 2_], y así sucesivamente.

====

Histograma( <Lista de límites de clases>, <Lista de datos brutos>, <Usar Densidad o no>(true/false), <Factor de escala de densidad>(opcional) )::
  Crea un histograma utilizando los datos brutos. Los límites de clases determinan el ancho y la posición de cada
  barra del histograma y se utilizan para determinar cuántos elementos de datos pertenecen a cada clase. La altura de la barra se determina de la siguiente manera:

* Si _Usar Densidad o no = true_, altura = (Factor de escala de densidad) * (frecuencia de clase) / (ancho de clase)
* Si _Usar Densidad o no = false_, altura = frecuencia de clase

Por defecto, Usar Densidad o no = true y Factor de escala de densidad = 1. Esto crea un histograma con un área total = n, el número de valores de datos.

[NOTE]
====

Todos los elementos de los datos brutos deben estar dentro del intervalo de los límites de clase; de lo contrario, se devolverá "indefinido".

====

[NOTE]
====

Por convención, se utiliza la regla a ≤ x < b para cada clase, excepto para la última clase, donde se aplica a ≤ x ≤ b.

====

[EXAMPLE]
====

(_Histograma predeterminado_)

`++Histograma({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true)++` crea un histograma con 3 barras, con las
alturas 0.5 (primera barra), 0.2 (segunda barra), y 0.1 (tercera barra).

Este histograma tiene un área total = 0.5*10 + 0.2*10 + 0.1*10 = 8.

====

[EXAMPLE]
====

(_Histograma de conteo_)

`++Histograma({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, false)++` crea un histograma con 3 barras, con las
alturas 5 (primera barra), 2 (segunda barra), y 1 (tercera barra). Este histograma no utiliza el escalado de densidad y
asigna alturas a las barras que equivalen al conteo de valores en cada clase.

====

[EXAMPLE]
====

(_Histograma de frecuencia relativa_)

`++Histograma({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true, 10/ 8)++` crea un histograma con 3 barras, con
las alturas 0.625 (primera barra), 0.25 (segunda barra), y 0.125 (tercera barra). Este histograma utiliza el escalado de densidad
para asignar alturas a las barras que representan la proporción de valores en cada clase.

Si n es el número de valores de datos y las clases tienen un ancho constante w, entonces Factor de escala de densidad = w/n crea un histograma relativo.

====

[EXAMPLE]
====

(_Histograma normalizado_)

`++Histograma({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true, 1/8)++` crea un histograma con 3 barras, con las
alturas .0625 (primera barra), .025 (segunda barra), y .0125 (tercera barra).

Este histograma tiene un área total = .0625*10 + .025*10 + .0125*10 = 1.

Si n es el número de valores de datos, entonces Factor de escala de densidad = 1/n crea un histograma normalizado con un área total = 1.
Esto es útil para ajustar un histograma con una curva de densidad.

====

Histograma( <Acumulada>(true/false), <Lista de límites de clases>, <Lista de datos brutos>, <Usar Densidad o no>(true/false), <Factor de escala de densidad>(opcional) )::
  Si Acumulada es verdadera (_true_), se crea un histograma donde la altura de cada barra es igual a la frecuencia de la clase más la suma de todas las frecuencias anteriores.

[EXAMPLE]
====

 `++Histograma(true, {10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true)++` crea un histograma con 3 barras, con
las alturas 0.5 (primera barra), 0.7 (segunda barra), y 0.8 (tercera barra).

====
