= Comando HistogramaDerecha
:page-en: commands/HistogramRight
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

HistogramaDerecha( <Lista de límites de clases>, <Lista de alturas> )::
  Opera de igual modo que `++Histograma(<Lista de límites de clases>, <Lista de alturas>)++`
  (ver comando xref:/commands/Histograma.adoc[Histograma]), siendo la única diferencia que las
  clases se cierran a derecha.

HistogramaDerecha( <Lista de límites de clases>, <Lista de datos brutos>, <Usar densidad o no (true/false)> , <Factor de escala de densidad> (opcional) )::
  Opera de igual modo que `++Histograma( <Lista de límites de clases>, <Lista de datos brutos>, <Usar densidad o no (true/false)> , <Factor de escala de densidad> (opcional) )++`, con la diferencia ya mencionada. Debe
  tenerse en cuenta la siguiente excepción: si un dato resulta igual al límite derecho de una clase, se cuenta en esta
  clase y no en la siguiente.

HistogramaDerecha( <Acumulada (true/false)>, <Lista de límites de clases>, <Lista de datos brutos>, <Usar densidad o no (true/false)> , <Factor de escala de densidad> (opcional) )::
  Opera de igual modo que `++Histograma(<Acumulada (true/false)>, <Lista de límites de clases>, <Lista de datos brutos>, <Usar densidad o no (true/false)> , <Factor de escala de densidad> (opcional))++`, con la diferencia ya mencionada. Debe
  tenerse en cuenta la siguiente excepción: si un dato resulta igual al límite derecho de una clase, se cuenta en esta
  clase y no en la siguiente.

[NOTE]
====

Por convención se emplea la regla _a < x ≤ b_ para
cada clase excepto para la primera para la cual se considera _a ≤ x ≤ b_

====
