= Comando Icosaedro
:page-en: commands/Icosahedron
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

[.small]##

Icosaedro( <Punto>, <Punto>, <Dirección> )::
  Crea un icosaedro teniendo como arista al segmento determinado por los dos puntos.
  Los otros vértices quedan unívocamente determinados por la dirección dada, la cual debe ser:
  * un vector, un segmento, una recta o una semirrecta *perpendicular* al segmento determinado por los dos puntos
  * un polígono o un plano *paralelo* a dicho segmento.
  El icosaedro creado tendrá:
  * una cara con el segmento como arista en un plano ortogonal al vector/segmento/recta/semirrecta, o
  * una cara con el segmento como arista en un plano paralelo al polígono/plano.

Icosaedro( <Punto>, <Punto>, <Punto> )::
  Crea un icosaedro con los tres puntos de la primera cara. Los puntos deben determinar un triángulo equilátero para que
  el icosaedro se defina.

Icosaedro( <Punto>, <Punto> )::
  Crea un icosaedro con los dos puntos en la primera cara. El tercer punto se crea en forma automática sobre una
  circunferencia, por lo que el icosaedro puede rotarse alrededor de la primera arista.

[NOTE]
====

Icosaedro(A, B) es una forma abreviada de Icosaedro(A, B, C) siendo C = Punto(Circunferencia(PuntoMedio(A, B),
Distancia(A, B) sqrt(3) / 2, Segmento(A, B))).

====

[NOTE]
====

Ver también los comandos xref:/commands/Cubo.adoc[Cubo], xref:/commands/Tetraedro.adoc[Tetraedro],
xref:/commands/Octaedro.adoc[Octaedro], xref:/commands/Dodecaedro.adoc[Dodecaedro].

====
