= Comando LímiteIzquierda
:page-en: commands/LimitBelow
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

LímiteIzquierda( <Función>, <Valor> )::
 Calcula el https://es.wikipedia.org/wiki/L%C3%ADmite_de_una_funci%C3%B3n[límite lateral] izquierdo de la función,
  para el valor indicado de su variable principal.

[EXAMPLE]
====

`++LímiteIzquierda(1 / x, 0)++` da _stem:[-\infty]_ .

====

[NOTE]
====

No todos los límites pueden ser calculados por GeoGebra, por lo que se devolverá _?_ en esos casos (así como cuando el resultado correcto es indefinido).

====

== Sintaxis CAS

LímiteIzquierda( <Expresión>, <Valor> )::
  Da por resultado el límite lateral izquierdo de la expresión dada para el valor indicado para su variable principal.

[EXAMPLE]
====

`++LímiteIzquierda(1 / x, 0)++` da stem:[-\infty] .

====

LímiteIzquierda( <Expresión>, <Variable>, <Valor> )::
  Calcula el límite lateral izquierdo de la expresión multivariable dada para el valor dado de la variable indicada.

[EXAMPLE]
====

`++LímiteIzquierda(1 / a, a, 0)++` da stem:[-\infty] .

====

[NOTE]
====

No todos los límites pueden ser calculados por GeoGebra, por lo que se devolverá _?_ en esos casos (así como cuando el resultado correcto es indefinido).

====

[NOTE]
====

Ver también los comandos xref:/commands/Límite.adoc[Límite] y xref:/commands/LímiteDerecha.adoc[LímiteDerecha].

====
