= Comando Límite
:page-en: commands/Limit
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Limite( <Función>, <Valor> )::
  Calcula el https://es.wikipedia.org/wiki/L%C3%ADmite_de_una_funci%C3%B3n[límite] de la función, para el valor indicado de su variable principal.
  (Esto también puede dar como resultado infinito.)

[EXAMPLE]
====

`++Limite((x^2 + x) /  x^2, +∞)++` da _1_.

====

[NOTE]
====

No todos los límites pueden ser calculados por GeoGebra, por lo que se devolverá _?_ en esos casos (así como cuando el resultado correcto es indefinido).

====

== Sintaxis CAS

Límite( <Expresión>, <Valor> )::
  Da por resultado el límite de la expresión dada para el valor indicado para su variable principal.

[EXAMPLE]
====

`++Límite(a sen(x) / x, 0)++` devuelve _a_.

====

Límite( <Expresión>, <Variable>, <Valor> )::
  Calcula el límite de la expresión para el valor dado de la variable de la función indicada.

[EXAMPLE]
====

`++Límite(a sen(v) / v, v, 0)++` devuelve _a_.

====

[NOTE]
====

* No todos los límites pueden ser calculados por GeoGebra, por lo que se devolverá _?_ en esos casos (así como cuando el resultado correcto es indefinido).
* Si se desea calcular el límite de una xref:/commands/Si.adoc[función definida por partes], se debe usar xref:/commands/LímiteDerecha.adoc[LímiteDerecha] o xref:/commands/LímiteIzquierda.adoc[LímiteIzquierda],
por ejemplo: `++LímiteDerecha(Si(x>1, x^2, -2x), 1)++`
* Ver también los comandos xref:/commands/Asíntota.adoc[Asíntota], xref:/commands/LímiteDerecha.adoc[LímiteDerecha] y
xref:/commands/LímiteIzquierda.adoc[LímiteIzquierda].

====
