= Comando MCDAmpliado
:page-en: commands/ExtendedGCD
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

== Sintaxis CAS

MCDAmpliado( <Entero>,<Entero> )::
  Devuelve una lista que contiene los coeficientes enteros stem:[s, t] de la identidad de Bézout, stem:[as+bt= MCD(a,b)],
  y el máximo común divisor de los enteros dados stem:[a] y stem:[b]. Los resultados se calculan aplicando el https://en.wikipedia.org/wiki/Extended_Euclidean_algorithm[algoritmo de Euclides extendido].

[EXAMPLE]
====

`++MCDAmpliado(240,46)++` devuelve {stem:[-9,47,2]}. (Sustituyendo el resultado en la identidad de Bézout se obtiene: stem:[-9
\cdot 240+47 \cdot 46=2]).

====

MCDAmpliado( <Polinomio>, <Polinomio> )::
  Devuelve una lista que contiene los coeficientes polinómicos stem:[S(x), T(x)] de la identidad de Bézout para polinomios,
  stem:[A(x)S(x) + B(x)T(x) = MCD(A(x), B(x))], y el máximo común divisor de los polinomios dados stem:[A(x)] y stem:[B(x)].
  Los resultados se calculan aplicando el https://en.wikipedia.org/wiki/Extended_Euclidean_algorithm[algoritmo de Euclides extendido].

[EXAMPLE]
====

`++MCDAmpliado(x^2-1,x+4)++` devuelve {stem:[1,-x+4,15]}. (Sustituyendo el resultado en la identidad de Bézout para polinomios
se obtiene: stem:[1 \cdot (x^2-1) + (-x+4) \cdot (x+4) = 15]).

====

[NOTE]
====

* El MCD de dos polinomios no es único (es único hasta un múltiplo escalar).
* Ver también el comando xref:/commands/MCD.adoc[MCD].

====
