= Comando Primero
:page-en: commands/First
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Primero( <Lista> )::
  Devuelve una nueva lista que contiene el primer elemento de la lista dada.

[EXAMPLE]
====

`++Primero({1, 4, 3})++` devuelve _{1}_.

====

[NOTE]
====

Para obtener el primer elemento utiliza `++Elemento({1, 4, 3}, 1)++`.

====

Primero( <Lista>, <Número de elementos> )::
  Devuelve una nueva lista que contiene solamente los primeros _n_ elementos de la lista original.

[EXAMPLE]
====

`++Primero({1, 4, 3}, 2)++` devuelve _{1, 4}_.

====

Primero( <Texto> )::
  Devuelve el primer carácter del texto.

[EXAMPLE]
====

`++Primero("Hola")++` devuelve _"H"_.

====

Primero( <Texto> , <Número de elementos> )::
  Devuelve los primeros _n_ caracteres del texto.

[EXAMPLE]
====

`++Primero("Hola",2)++` devuelve _"Ho"_.

====

Primero( <Lugar geométrico>, <Número de elementos> )::
  Este comando puede utilizarse con:
  * lugares geométricos generados con el comando xref:/commands/ResuelveNEDO.adoc[ResuelveNEDO] - Devuelve la lista de los
  puntos creados en los primeros _n_ pasos del algoritmo de resolución numérica de la ecuación diferencial ordinaria.
  * lugares geométricos generados con los comandos xref:/commands/MenorDistancia.adoc[MenorDistancia],
  xref:/commands/Viajante.adoc[Viajante], xref:/commands/Voronoi.adoc[Voronoi],
  xref:/commands/ÁrbolRecubridorMínimo.adoc[ÁrbolRecubridorMínimo] y xref:/commands/EnvolventeConvexa.adoc[EnvolventeConvexa] -
  Devuelve los vértices del grafo.

[NOTE]
====

Ver también el comando xref:/commands/Último.adoc[Último].

====
