= Comando Simplifica
:page-en: commands/Simplify
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Simplifica( <Función> )::
  Simplifica los términos de función dada, si es posible.

[EXAMPLE]
====

`++Simplifica(x + x + x)++` devuelve la función _f(x) = 3x_.

====

Simplifica( <Texto> )::
  Intenta ordenar las expresiones de texto eliminando signos negativos repetidos, entre otros ajustes.

[EXAMPLE]
====

Para _a_ = _b_ = _c_ = -1 `++Simplifica("f(x) = " + a + "x² + " + b + "x + " + c)++` devuelve el texto _f(x) = -x^2^ - x -
1_.

====

[NOTE]
====

Habitualmente el comando xref:/commands/FórmulaTexto.adoc[FórmulaTexto] produce mejores resultados y es más simple.

====

[NOTE]
====

Este comando requiere de la carga del Sistema Álgebra Computacional (CAS), por lo que puede resultar lenta
en ocasiones y/o equipos. Se puede intentar la alternativa que ofrece el comando
xref:/commands/Polinomio.adoc[Polinomio].

====

== Sintaxis CAS

Simplifica( <Función> )::
  Simplifica los términos de función dada, si es posible. Las variables indefinidas pueden ser incluidas en los términos.

[EXAMPLE]
====

* `++Simplifica(3 * x + 4 * x + a * x)++` devuelve `++ a x + 7x++`.
* `++Asumiendo(x<2,Simplifica(sqrt(x-2sqrt(x-1))))++` devuelve `++-sqrt(abs(x - 1)) + 1++`
* `++Asumiendo(x>2,Simplifica(sqrt(x-2sqrt(x-1))))++` devuelve `++sqrt(x - 1) + 1++`

====

[NOTE]
====

Ver también los comandos xref:/commands/Factoriza.adoc[Factoriza], xref:/commands/Asumiendo.adoc[Asumiendo],
xref:/commands/FraccionesParciales.adoc[FraccionesParciales], xref:/commands/Desarrolla.adoc[Desarrolla],
xref:/commands/Polinomio.adoc[Polinomio].

====


