= Comando Soluciones
:page-en: commands/Solutions
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

[NOTE]
====

A partir de la versión 823, este comando se comporta como el comando xref:/commands/Resuelve.adoc[Resuelve],
con la excepción del formato del resultado: el comando _Soluciones_ devuelve una lista de valores,
mientras que el comando _Resuelve_ devuelve una lista de ecuaciones en la forma _nombre de la variable = valor_.

====

Soluciones( <Ecuación> )::
  Resuelve una ecuación dada para la variable principal y devuelve una lista de todas las soluciones.

[EXAMPLE]
====

`++Soluciones(x^2 = 4x)++` devuelve _{0, 4}_.

====

== Sintaxis CAS


Soluciones( <Ecuación>, <Variable> )::
  Resuelve una ecuación para una variable desconocida dada y devuelve una lista de todas las soluciones.

[EXAMPLE]
====

`++Soluciones(x * a^2 = 4a, a)++` devuelve {stem:[\frac{4}{x},0]}.

====

Soluciones( <Lista de ecuaciones>, <Lista de variables> )::
  Resuelve un conjunto de ecuaciones para un conjunto dado de variables desconocidas y devuelve una lista de todas las soluciones.

[EXAMPLE]
====

* `++Soluciones({x = 4 x + y , y + x = 2}, {x, y})++` devuelve _{{-1, 3}}_, la única solución de _x = 4x + y_ y _y + x
= 2_, mostrada como stem:[\begin{pmatrix}-1&3\end{pmatrix}].
* `++Soluciones({2a^2 + 5a + 3 = b, a + b = 3}, {a, b})++` devuelve _{{-3, 6}, {0, 3}}_, mostrada como
stem:[\begin{pmatrix}-3&6\\0&3\end{pmatrix}].

====

[NOTE]
====

* En ocasiones, puede ser necesario realizar ciertas manipulaciones para que el comando funcione. Por ejemplo
`++ Soluciones(TrigDesarrolla(sin(5/4 π + x) - cos(x - 3/4 π) = sqrt(6) * cos(x) - sqrt(2))) ++`
* Ver también el comando xref:/commands/Resuelve.adoc[Resuelve].

====
