= Comando SumaRectángulos
:page-en: commands/RectangleSum
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

SumaRectángulos( <Función>, <Extremo inferior del intervalo>, <Extremo superior del intervalo>, <Número de Rectángulos>,
<Posición del rectángulo inicial> )::
  Calcula entre el _Extremo inferior del intervalo_ y el _Extremo superior del intervalo_ la suma de rectángulos cuyas
  alturas están dadas por el valor de la función en un punto que dista del comienzo de cada intervalo en una fracción
  _d_ de la longitud del mismo (0 ≤ _d_ ≤ 1), utilizando _n_ rectángulos .
  Cuando _d_ = 0 es esquivalente a la xref:/commands/SumaIzquierda.adoc[_suma izquierda_], y cuando _d_ = 1 calcula la
  _suma derecha_.

[NOTE]
====

* Este comando también representa gráficamente los rectángulos correspondientes a esta suma.
* Este comando está diseñado como una ayuda visual por lo que no proporcionará respuestas precisas si el número de
rectángulos es demasiado grande..
* Ver también los comandos: xref:/commands/SumaSuperior.adoc[SumaSuperior],
xref:/commands/SumaInferior.adoc[SumaInferior] , xref:/commands/SumaIzquierda.adoc[SumaIzquierda] ,
xref:/commands/SumaTrapezoidal.adoc[SumaTrapezoidal].

====
