= Comando TextoAFunción
:page-en: commands/ParseToFunction
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

TextoAFunción( <Texto> )::
  Analiza el texto que contiene la definición de la función y crea la xref:/Funciones.adoc[función] correspondiente.

[EXAMPLE]
====

* `++ TextoAFunción("x^2")++` crea la función _f_(_x_) = __x__^2^_._
* `++ TextoAFunción("t+2/t")++` crea la función _f_(_t_) = _t_ + 2/_t_.

====

TextoAFunción( <Función> , <Texto> )::
  Analiza la cadena de texto y almacena el resultado en la xref:/Funciones.adoc[función] indicada, digamos _f_, que debe
  estar definida y ser xref:/Objetos_libres_dependientes_y_auxiliares.adoc[libre] antes del empleo del comando.

[EXAMPLE]
====

Sean `++ f(x) = 3x² + 2++` y `++ texto1 = "f(x) = 3x + 1"++`. Entonces `++TextoAFunción(f, texto1)++` redefine la
función f como _f(x) = 3x + 1_.

====

TextoAFunción( <Texto>, <Lista de variables> )::
  Analiza el texto que contiene la definición de la función y crea la xref:/Funciones.adoc[función] correspondiente de las variables definidas en la lista.

[EXAMPLE]
====

`++ TextoAFunción("2u+3v",{"u", "v"})++` crea la función _a(u,v) = 2u + 3v_.

====

[NOTE]
====

Ver también el comando xref:/commands/TextoANúmero.adoc[TextoANúmero].

====
