= BacASable
:page-en: 
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]


Accessibilité

La suite calculatrice GeoGebra est conçue dans un souci d'accessibilité ! Grâce à la prise en charge des lecteurs d'écran et à la navigation au clavier, elle répond aux normes WCAG 2.2 AA et s'efforce d'atteindre la norme AAA lorsque cela est possible. L'accessibilité est un effort continu et nous améliorons constamment l'expérience utilisateur sur l'ensemble de nos applications.
 

 

Sur cette page, vous trouverez des informations sur les sujets d'accessibilité suivants :

    Lecteurs d'écran

    Support du Braille

    Navigation au Clavier

    Raccourcis Clavier

    Saisie dans Algèbre

        Saisie Simple

        Saisie Avancée

        Caractères Spéciaux

        Symboles

        Fonctions
    Outils et Commandes


Lecteurs d'écran

Pour une expérience optimale, nous vous recommandons d'utiliser l'une des configurations suivantes :

    Navigateur Chrome avec NVDA ou JAWS

    Navigateur Safari ou Chrome avec VoiceOver

💡 Pour être sûr d'entendre exactement ce que vous tapez, configurez votre lecteur d'écran pour qu'il annonce chaque caractère :

    NVDA:  Preferences → Settings → Keyboard → ☑ Speak typed characters 

    Jaws: Utilities → Settings Center → Typing Echo → ☑ Characters

    VoiceOver: Utility → Verbosity → Text → While typing speak: Characters

Supprt du Braille

Lors de l'utilisation de GeoGebra Calculator Suite avec un afficheur braille, basculez l'affichage algébrique en mode Notation linéaire à l'aide du raccourci clavier Ctrl + D. Ce raccourci permet de faire défiler les modes d'affichage algébrique : Valeur, Description, Définition, Notation linéaire.

Le mode de notation linéaire est optimisé pour la lecture et la modification de données algébriques sur des afficheurs braille. Dans ce mode, la saisie semi-automatique (par exemple, les parenthèses automatiques) est désactivée afin de vous garantir un contrôle total sur vos saisies.

💡 Note: Dans la calculatrice graphique, les étiquettes sont ajoutées automatiquement à toutes les lignes, sauf si vous les saisissez manuellement. L'étiquetage suit une convention simple : les nombres et les calculs numériques sont étiquetés par ordre alphabétique en minuscules, en commençant par a ; les points sont étiquetés par ordre alphabétique en majuscules, en commençant par A ; les fonctions sont étiquetées par ordre alphabétique en minuscules, en commençant par f. Pour saisir des étiquettes manuellement, commencez une nouvelle entrée algébrique comme ceci : a = 3+5, A = (1,1) ou f(x) = x+1.
 

Navigation au Clavier

💡 Utilisez Tab et Maj + Tab comme touches de navigation principales. Les flèches directionnelles servent à déplacer les objets dans le plan de coordonnées 2D, à déplacer ce plan et à modifier les valeurs. La navigation dans les menus reste possible avec les flèches directionnelles.

Action Windows / Mac OS 
Touche Tab : Navigation dans la calculatrice, sélection de l’objet suivant
Maj + Tab : Navigation dans la calculatrice (retour arrière), sélection de l’objet précédent
Espace : Appuyer sur les boutons, ouvrir/fermer les menus, activer/désactiver les éléments de menu.

Lorsqu’un nombre (curseur) est sélectionné, la touche Espace permet de démarrer/arrêter l’animation du curseur.

Touche Entrée : Modifier les objets, confirmer les saisies
Flèches

Augmentez et diminuez la valeur des curseurs, déplacez les points et autres objets vers le haut et vers le bas, vers la gauche et vers la droite.

Dans les menus : parcourir les éléments

Windows : Ctrl + Flèches

Mac : Ctrl + Maj + Flèches (multiplicateur de vitesse x10)

Augmenter et diminuer les valeurs, déplacer les objets 10 fois plus vite

Maj + Flèches (multiplicateur de vitesse x0,1)

Augmenter et diminuer les valeurs, déplacer les objets 10 fois plus lentement

Windows : Alt + Flèches

Mac : Option + Flèches (multiplicateur de vitesse x100)
+ ou - : déplacer les points le long des trajectoires

Touche Menu ou Maj + F10 : ouvrir les menus contextuels

Retour arrière ou Suppr : supprimer l’objet sélectionné

Ctrl + A, puis Suppr : supprimer tous les objets (pour effacer la calculatrice)

Échap Quitter la calculatrice

Raccourcis clavier
Action Windows / Mac OS
Ctrl + Maj + A Afficher/Masquer la fenêtre d'algèbre
Ctrl + Maj + 1 Afficher/Masquer la fenêtre graphique
Ctrl + Maj + U Afficher/Masquer la fenêtre de tableau
Ctrl + D Basculer entre le mode Valeur/Description/Définition/Notation linéaire dans la fenêtre d'algèbre
/ Afficher/Masquer l'objet sélectionné
Ctrl + Z Annuler

Remarque : fonctionne uniquement si l'option Annuler/Rétablir est activée dans la configuration de l'application
Ctrl + Y ou Ctrl + Maj + Z Rétablir

Remarque : fonctionne uniquement si l'option Annuler/Rétablir est activée dans la configuration de l'application
Ctrl + Moins Dézoomer

Remarque : fonctionne uniquement si le zoom est activé dans la configuration de l'application
Ctrl + Plus Zoomer

Remarque : fonctionne uniquement si le zoom est activé dans la configuration de l'application
F3 Copier la définition de l'objet sélectionné dans la barre de saisie
F4 Copier la valeur de l'objet sélectionné dans la barre de saisie
F5 Copier le nom de l'objet sélectionné dans la barre de saisie


💡 Le raccourci F4 permet de lire, copier ou réutiliser le résultat d'un calcul. Appuyez sur F4 pour copier la valeur dans la barre de saisie, puis sur Ctrl+A pour sélectionner l'ensemble du résultat, et enfin sur Ctrl+C pour le copier. Vous pouvez ensuite coller facilement le résultat sous forme linéaire dans d'autres applications comme Word ou Google Docs.

Saisie algébrique



💡 Toutes les fonctions disponibles sur le clavier virtuel sont facilement accessibles via votre clavier physique. Saisissez votre nombre, calcul, fonction ou équation dans la barre de saisie et appuyez sur Entrée pour confirmer.

Barre de saisie de GeoGebra

Barre de saisie de GeoGebra

Saisie simple

Essayez les exemples suivants pour découvrir une interface de saisie fluide et intuitive :

Résultat de la saisie

2 génère un nombre. Vous pouvez sélectionner « Créer un curseur » dans le menu contextuel pour modifier facilement ce nombre.

3 + 5 calcule 3 + 5 et affiche 8.

1 / 4 génère la fraction 14.

x² génère la fonction quadratique x² et l'affiche dans la fenêtre graphique.


Toutes vos entrées seront étiquetées automatiquement. Si vous préférez, vous pouvez également saisir les étiquettes vous-même :

Entrée Résultat

a = 2 créera le nombre 2 et l'affectera à la variable a.

f(x) = x^2 créera la fonction quadratique x^2 et l'affectera au nom de fonction f(x).

 
Vous pouvez utiliser ces étiquettes pour réutiliser les valeurs et les fonctions qui leur sont associées :

Entrée Résultat

f + b donnera x² + 8 et ajoutera une nouvelle étiquette g(x).

 

💡 Appuyez sur Entrée pour modifier une ligne existante dans la fenêtre d'algèbre.

Saisie avancée

Lorsque vous saisissez des expressions plus complexes utilisant des exposants, des fractions ou des éléments similaires, veuillez tenir compte des points suivants :

Parenthèses et expressions

GeoGebra propose une aide syntaxique qui ajoute automatiquement des parenthèses invisibles. Le curseur reste positionné dans une expression jusqu'à ce que celle-ci soit fermée en saisissant une parenthèse ou en appuyant sur la flèche droite. L'aide syntaxique ajoute également automatiquement une parenthèse fermante lorsqu'une parenthèse ouvrante est saisie.

Appuyez sur la touche Flèche droite pour déplacer le curseur hors de l'exposant ou de la fraction et le replacer sur la ligne. Voici quelques exemples :

Saisie saisie : Interprétation : Remarque :

x² + 1 : x² + 1 : Le curseur reste dans l'exposant.

x² + 1 : → Flèche droite : Appuyer sur la touche Flèche droite déplacera le curseur hors de l'exposant.

1/4 + x : → 14 + x : Le curseur reste dans le dénominateur.

1/4 + x : → 14 + x : Appuyer sur la touche Flèche droite déplacera le curseur hors du dénominateur.


💡Vous pouvez également utiliser la parenthèse fermante pour sortir d'un exposant, d'une fraction ou d'une expression similaire.

💡 Lorsque vous utilisez des parenthèses, la parenthèse fermante est ajoutée automatiquement. Vous pouvez la saisir manuellement, ce qui remplacera la parenthèse automatique. Vous pouvez également la passer en appuyant sur la touche Flèche droite.

Espaces et multiplications

GeoGebra interprète les espaces comme des multiplications. C'est pourquoi, dans certains cas, l'ajout d'une espace à votre expression peut avoir une incidence, notamment si vous la collez dans GeoGebra. Voici quelques exemples :

Remarque sur l'interprétation des expressions collées :

1/8*pi (1/8)*pi GeoGebra respecte l'ordre des opérations, ce qui signifie que π ne figure pas au dénominateur.

1/8 pi (1/8)*pi GeoGebra interprète l'espace avant π comme une multiplication, ce qui donne le même résultat que précédemment.

1/8pi 1/(8*pi) Sans espace ni multiplication, GeoGebra interprète 8π comme une seule expression et place donc π au dénominateur.

Copier-coller


Utilisez systématiquement des parenthèses lorsque vous copiez-collez des expressions dans la barre de saisie. GeoGebra interprète les données collées comme une notation linéaire, sans fournir d'aide à la syntaxe. Voici quelques exemples : 
Données collées Interprétation
2^(3/4) 	23/4
2^3/4 	234
sqrt 4^2+9
  	√42+9
sqrt(4^2+9) 	√42+9
sin pi-1/8pi 	sin(π)−18π
sin(pi-1/8pi) 	sin(π−18π)
Caractères spéciaux
Saisie 	Caractère
Win: Alt + a / b / d / …
Mac: Option + a / b / d / … 	Lettres grecques α, β, δ, …
e 	Constante d'Euler ℯ 
i 	Unité imaginaire i 
pi 	Pi π
inf 	Infini ∞
Symboles
Saisie 	Caractère
^ 	Exposant, à la puissance
_ 	Indice
/ 	Fraction
!= 	Différent ≠
<= 	Inférieur ou égal à ≤
>= 	Supérieur ou égal à ≥
== 	Est égal à ≟
&& 	ET Logique
|| 	OU Logique
! 	NON Logique
Fonctions
Saisie 	Fonction
sqrt(x) 	Racine carrée (√) de x
nroot(x,n) 	Racine n-ième de x
abs(x) 	Valeur absolue de x
sin(x) 	Sinus de x
cos(x) 	Cosinus de x
tan(x) 	Tangente de x
ln(x) 	Logarithme népérien de x
log(x) 	Logarithme de x
log(b,x) 	Logarithme en base b de x
floor(x) 	Fonction Plancher de x
ceil(x) 	Fonction Plafond de x

Outils et Commandes

Dans les applications mathématiques GeoGebra, chaque outil possède une commande correspondante qui crée exactement le même objet, offrant ainsi une grande flexibilité d'utilisation. En résumé, les outils sont des représentations visuelles de commandes mathématiques.

Pour utiliser les commandes, commencez simplement à saisir l'action souhaitée dans la barre de saisie. Les commandes GeoGebra sont intuitives et portent généralement un nom d'après leur fonction mathématique. Dès que vous saisissez trois lettres, l'aide syntaxique automatique s'affiche et vous guide vers la commande appropriée et ses paramètres.

Note: L'aide syntaxique n'est pas encore totalement accessible, mais des améliorations sont en cours. En attendant, vous trouverez une liste complète des commandes, incluant l'aide syntaxique, dans le manuel de GeoGebra.

Pour vous familiariser avec les commandes, essayez les exemples suivants :
Saisie 	Fonction
Racines(f) 	Racines de la fonction f
Extremum(f) 	Extremum de la fonction f
Dérivée(f) 	Dérivée de la fonction f (CAS Calculator)
Intégrale(f) 	Intégrale de la fonction f
Intersection(f,g) 	Points d'intersection des fonctions f et g
Droite(A,B) 	Droite passant par les points A et B


Vos commentaires sont importants pour nous.

L'accessibilité est primordiale ! Nous savons que nous pouvons toujours nous améliorer et vos commentaires sont précieux. N'hésitez pas à nous contacter à l'adresse accessibility@geogebra.org pour toute question ou remarque concernant l'accessibilité. Cela nous permettra d'offrir la meilleure expérience possible à tous. Pour toute autre question, veuillez consulter le forum GeoGebra.
 

Dutch Visio logo

Un grand merci à Visio pour son expertise en matière d'accessibilité. Ses précieux conseils nous ont permis d'apporter des améliorations significatives et de poursuivre nos efforts pour offrir une expérience plus inclusive à tous les utilisateurs.


