= Calques
:page-en: Layers
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

[NOTE]
====

Dans GeoGebra, les calques sont utilisés pour déterminer l’objet à sélectionner ou déplacer quand l’utilisateur
clique sur une sélection multiple d’objets.

====

Par défaut, tous les objets sont dessinés dans le calque 0, qui est le calque classique de la vue Graphique. Au total,
10 calques sont accessibles (numérotés de 0 à 9) les calques de numéros élevés étant au-dessus des calques de numéros
inférieurs.

En utilisant l’onglet ‘Avancé’ du Dialogue Propriétés, vous pouvez changer le calque d’un certain objet (numéro de 0 à 9
possibles). Dès que vous changez le numéro du calque d’un objet par un numéro différent de 0 (par ex., calque 3), tous
les nouveaux objets seront dessinés dans le calque de numéro le plus grand.

[NOTE]
====

Après avoir sélectionné un objet, vous pouvez sélectionner tous les objets de même calque en choisissant l’item
‘Sélectionner le calque courant’ (raccourci : [.kcode]#Ctrl# + [.kcode]#L#) dans le menu Éditer.

====

== Autres utilisations des calques :

* Pour l’export SVG les objets sont groupés par calque.
* Les calques peuvent être contrôlés dans les xref:/Exporter_Feuille_de_travail.adoc[appliquettes GeoGebra] en utilisant
l’Interface JavaScript.
