= Exporter vers LaTeX (PGF, PSTricks) et Asymptote
:page-en: Export_to_LaTeX_(PGF_PSTricks)_and_Asymptote
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

== Exporter - Graphique vers PSTricks …

Raccourci Clavier : [.kcode]#Ctrl# + [.kcode]#Maj# + [.kcode]#T# (MacOs : [.kcode]#Cmd# + [.kcode]#Maj# + [.kcode]#T#)

Ce menu vous permet de générer le code http://tug.org/PSTricks/main.cgi/[PSTricks] en vue d'insérer une image de votre
vue xref:/Graphique.adoc[Graphique] dans un document xref:/LaTeX.adoc[LaTeX].

== Exporter - Graphique vers PGF/TikZ …

Ce menu vous permet de générer le code http://sourceforge.net/projects/pgf/[PGF] en vue d'insérer une image de votre vue
xref:/Graphique.adoc[Graphique] dans un document xref:/LaTeX.adoc[LaTeX].

== Exporter - Graphique vers Asymptote …

Ce menu vous permet de générer le code http://asymptote.sourceforge.net/[Asymptote] en vue d'insérer une image de votre
vue xref:/Graphique.adoc[Graphique] dans un document xref:/LaTeX.adoc[LaTeX].

== Limites de ces fonctionnalités d'export :

Actuellement à part pour les gifs animés seuls l'export pour les vues 2D est possible, et les objets suivants ne peuvent
être exportés vers ces formats :

* les courbes implicites ;
* les lieux.
