= Manuel GeoGebra
:page-en: index
:description: Explorez le manuel et le guide de référence en ligne GeoGebra. Accédez facilement aux pages d'aide détaillées pour chaque commande et outil GeoGebra, fournissant des instructions étape par étape et des exemples pour améliorer votre expérience d'apprentissage et d'enseignement des mathématiques.

Bienvenue dans le manuel d'utilisation de GeoGebra.


Ce manuel recense et documente toutes les Commandes et Outils de la dernière version disponible.

À l’intérieur, vous trouverez des explications détaillées de toutes les fonctionnalités clés, y compris des exemples sur la façon d’utiliser efficacement les outils et les commandes.

Sa présentation est basée sur la *version GeoGebra Bureau 5*. Des variantes peuvent apparaitre dans les applications, (regroupement des outils, par exemple), mais cela ne change en rien les fonctionnalités.

Que vous soyez un utilisateur débutant ou avancé, ce manuel vous aidera à maximiser le potentiel de GeoGebra en vous offrant des conseils clairs sur la navigation dans ses fonctionnalités et l'optimisation de vos flux de travail.
