= AyarlaRenk Komut
ifdef::env-github[:imagesdir: /tr/modules/ROOT/assets/images]

AyarlaRenk( <Nesne>, <Kırmızı>, <Yeşil>, <Mavi> )::
  Verilen nesnenin rengini değiştirir. Kırmızı, yeşil ve mavi karşılık gelen renk bileşeninin, en küçük 0 ve en büyük 1
  olabilen miktarını temsil eder. Bu aralığın dışında kalan _t_ sayısı stem:[2\left|\frac\{t}2-\mathrm
  round\left(\frac\{t}2\right)\right|] fonksiyonu kullanılarak dönüştürülür.
AyarlaRenk( <Nesne>, <"Renk"> )::
  Verilen nesnenin rengini değiştirir. xref:/Metinler.adoc[Metin] olarak girilen renk:
  * bir rengin İngilizce adı (bakın /Referans:Renkler.adoc[Referans:Renkler]) olabilir. Bunlardan bazıları Türkçe olarak
  da kullanılabilir ve aşağıda listelenmişlerdir.

[NOTE]
====

Eğer bu komutu GeoGebraBetik de kullanırsanız, renklerin İngilizce adlarını kullanmalısınız

====

* #AARRGGBB veya #RRGGBB türünde bir onaltılık dizgi olabilir. Burada, _AA_ şeffaflığı (00 tamamen şeffaftan FF tamamen
opağa kadar), _RR_ kırmızı bileşeni, _GG_ yeşil bileşeni ve _BB_ mavi bileşeni belirler.

[EXAMPLE]
====

`++AyarlaRenk(metin1, "#80FF0000")++` komutu, var olan _metin1_ metninin rengini % 50 beyaz şeffaflıkta kırmızı olarak
ayarlar.

====

* Siyah
* Koyu Gri
* Gri
* Koyu Mavi
* Mavi
* Koyu Yeşil
* Yeşil
* Kestane Rengi
* Koyu Vişne Rengi
* Kırmızı
* Macenta
* Çivit Mavisi
* Mor
* Kahve Rengi
* Turuncu
* Altın Sarısı

* Kireç Rengi
* Camgöbeği Yeşili
* Turkuaz
* Light Blue
* Açık Deniz Mavisi
* Gümüş
* Açık Gri
* Pembe
* Menekşe
* Sarı
* Açık Sarı
* Açık Turuncu
* Açık
* Açık Menekşe
* Açık Yeşil
* Beyaz

 
