= Normalleştir Komut
ifdef::env-github[:imagesdir: /tr/modules/ROOT/assets/images]

Normalleştir( <Sayı Listesi> )::
  Verilen sayıların _normalleştirilmiş_ şekillerini içeren bir liste verir.

[EXAMPLE]
====

`++Normalleştir({1, 2, 3, 4, 5})++` komutu _\{0, 0.25, 0.5, 0.75, 1}_ sonucunu verir.

====

Normalleştir( <Nokta Listesi> )::
  Verilen noktaların _normalleştirilmiş_ şekillerini içeren bir liste verir.

[EXAMPLE]
====

`++Normalleştir({(1,5), (2,4), (3,3), (4,2), (5,1)})++` komutu _\{(0,1), (0.25,0.75), (0.5,0.5), (0.75,0.25), (1,0)}_
sonucunu verir.

====

[NOTE]
====

*Notlar:*

* Eğer büyük veya küçük sayıları kullanarak hesaplamalar yapıyorsanız (örneğin
xref:/commands/UydurBüyüme.adoc[UydurBüyüme Komutunu] kullanarak) bu sayıları normalleştirmek yuvarlama/taşma
hatalarından kaçınmanızı sağlayabilir.
* Bu komut 3D noktalarına uygulanamaz.
* _Normalleştirme_ işlemi bir _x_ değerini stem:[x \mapsto \frac{x-EnKüçük[liste]}\{EnBüyük[liste]-EnKüçük[liste]}]
doğrusal fonksiyonunu kullanarak [0, 1] aralığına taşır.

====
