= UydurBüyüme Komut
ifdef::env-github[:imagesdir: /tr/modules/ROOT/assets/images]

UydurBüyüme( <Nokta Listesi> )::
  Noktalara uyan stem:[ a b ^ x ] şeklinde bir fonksiyon hesaplar. (Üstel büyümenin anlamını bilmeyen kullanıcılar için
  tıpkı xref:/commands/UydurÜstel.adoc[UydurÜstel]( <Nokta Listesi> ) komutu gibidir).

[EXAMPLE]
====

`++UydurBüyüme({(0, 1), (2, 3), (4, 3), (6, 4)})++` komutu _1.31_ stem:[ \cdot ] _1.23^x^_ sonucunu verir.

====

[NOTE]
====

* xref:/commands/Uydur.adoc[Uydur], xref:/commands/UydurÜstel.adoc[UydurÜstel],
xref:/commands/UydurDoğru.adoc[UydurDoğru], xref:/commands/UydurDoğruX.adoc[UydurDoğruX],
xref:/commands/UydurLog.adoc[UydurLog], xref:/commands/UydurLojistik.adoc[UydurLojistik],
xref:/commands/UydurPolinom.adoc[UydurPolinom], xref:/commands/UydurKuvvet.adoc[UydurKuvvet] ve
xref:/commands/UydurSin.adoc[UydurSin] komutlarına da bakın.
* Eğer büyük/küçük sayılar ile çalışıyorsanız daha doğru bir sonuç için bunları normalleştirmeyi düşünmelisiniz, bakın
xref:/commands/Normalleştir.adoc[Normalleştir Komutu].

====
