= Yay Komut
:page-en: commands/Arc
ifdef::env-github[:imagesdir: /tr/modules/ROOT/assets/images]

Yay( <Çember>, <Nokta M >, <Nokta N> )::
  Verilen çemberin uç noktaları M ve N olan (saatin ters yönünde) yönlendirilmiş yayını verir.

Yay( <Elips>, <Nokta M>, <Nokta N> )::
  Verilen elipsin uç noktaları M ve N olan (saatin ters yönünde) yönlendirilmiş yayını verir.

Yay( <Çember>, <Parametre Değeri>, <Parametre Değeri> )::
  Verilen çemberin, uç noktaları belirtilen parametre değerleri tarafından belirlenen çember yayını verir.

[NOTE]
====

Komut içinde aşağıdaki parametrik ifade kullanılır: _r_ çemberin yarıçapı olmak üzere Çember: (_r_ cos(_t_), _r_
sin(_t_))

====

Yay( <Elips>, <Parametre Değeri>, <Parametre Değeri> )::
  Verilen elipsin, uç noktaları belirtilen parametre değerleri tarafından belirlenen çember yayını verir.

[NOTE]
====

Komut içinde aşağıdaki parametrik ifade kullanılır: _a_ ve _b_ yarı asal ve yarı yedek eksen uzunlukları olmak üzere
Elips: (_a_ cos(_t_), _b_ sin(_t_))

====

[NOTE]
====

Aynı zamanda xref:/commands/ÇevrelÇemberYayı.adoc[ÇevrelÇemberYayı] komutuna da bakın.

====
