= ChiSquared 指令
:page-en: commands/ChiSquared
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

ChiSquared[ <Degrees of Freedom>, x ]::
ChiSquared[ <Degrees of Freedom>, x, <Boolean Cumulative> ]::
ChiSquared[ <Degrees of Freedom>, <Variable Value> ]::

== CAS 視窗

ChiSquared[ <Degrees of Freedom>, x ]::
ChiSquared[ <Degrees of Freedom d>, x ]::
  Creates probability density function (pdf) of https://en.wikipedia.org/wiki/Chi-square_distribution[Chi squared
  distribution] with _d_ degrees of freedom.
ChiSquared[ <Degrees of Freedom>, x, <Boolean Cumulative> ]::
  If _Cumulative_ is true, creates cumulative distribution function of Chi squared distribution, otherwise creates pdf
  of Chi squared distribution.
ChiSquared[ <Degrees of Freedom d>, <Variable Value v> ]::
  Calculates the value of cumulative distribution function of Chi squared distribution at _v_, i.e. the probability
  _P(X≤v)_ where _X_ is a random variable with Chi squared distribution with _d_ degrees of freedom.

[NOTE]
====
Returns the probability for a given _x_-coordinate's value (or area under the Chi squared distribution curve to
the left of the given _x_-coordinate).

====

== CAS Syntax

In xref:/CAS_View.adoc[CAS View] only following syntax is supported:

ChiSquared[ <Degrees of Freedom d>, <Variable Value v> ]::
  Calculates the value of cumulative distribution function (cdf) of Chi squared distribution at _v_, i.e. the
  probability _P(X≤v)_ where _X_ is a random variable with Chi squared distribution with _d_ degrees of freedom.

[EXAMPLE]
====


`++ChiSquared[4, 3]++` yields stem:[\gamma(2, \frac\{3}\{2})], which is approximately _0.44_.

====
