= Circle 指令
:page-en: commands/Circle
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

Circle[ <Point>, <Radius Number> ]::
Circle[ <Point>, <Segment> ]::
Circle[ <Point>, <Point> ]::
Circle[ <Point>, <Point>, <Point> ]::
Circle[Point M, Number r]::
  Yields a circle with center _M_ and radius _r_.
Circle[Point M, Segment]::
  Yields a circle with center _M_ and radius equal to the length of the given segment.
Circle[Point M, Point A]::
  Yields a circle with center _M_ through point _A_.
Circle[Point A, Point B, Point C]::
  Yields a circle through the given points _A_, _B_ and _C_.

[NOTE]
====
See also xref:/s_index_php?title=Compass_Tool_action=edit_redlink=1.adoc[Compass],
xref:/s_index_php?title=Circle_with_Center_through_Point_Tool_action=edit_redlink=1.adoc[Circle with Center through
Point], xref:/s_index_php?title=Circle_with_Center_and_Radius_Tool_action=edit_redlink=1.adoc[Circle with Center and
Radius], and xref:/s_index_php?title=Circle_through_Three_Points_Tool_action=edit_redlink=1.adoc[Circle through Three
Points] tools.

====
