= CSolutions 指令
:page-en: commands/CSolutions
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

此指令只能用在xref:/運算區.adoc[運算區]。

CSolutions[ <Equation> ]::
  Solves a given equation for the variable x and returns a list of all solutions, allowing for complex solutions.
CSolutions[ <Equation>, <Variable> ]::
  Solves an equation for a given unknown variable and returns a list of all solutions, allowing for complex solutions.
CSolutions[ <List of Equations>, <List of Variables> ]::
  Solves a set of equations for a given set of unknown variables and returns a list of all solutions, allowing for
  complex solutions.

[EXAMPLE]
====


`++CSolutions[{y^2 = x - 1, x = 2 * y - 1}, {x, y}]++` yields stem:[\begin\{pmatrix}1 + 2 ί&1 + ί\\1 - 2 ί&1 -
ί\end\{pmatrix}], the complex solutions of _y^2^ = x - 1_ and _x = 2 * y - 1_.

====

[EXAMPLE]
====


`++CSolutions[a^2 = -1, a]++` yields _\{ί, -ί}_, the complex solutions of _a^2^ = -1_.

====

[EXAMPLE]
====


`++CSolutions[x^2 = -1]++` yields _\{ί, -ί}_, the complex solutions of _x^2^ = -1_.

====

[NOTE]
====

*備註：*

* The complex ί is obtained by pressing [.kcode]#ALT # + [.kcode]# i#.
* See also xref:/s_index_php?title=CSolve_Command_action=edit_redlink=1.adoc[CSolve Command] and
xref:/s_index_php?title=Solutions_Command_action=edit_redlink=1.adoc[Solutions Command].

====
