= Frequency 指令
:page-en: commands/Frequency
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

Frequency[ <List of Raw Data> ]::
Frequency[ <Cumulative>, <List of Raw Data>]::
Frequency[ <List of Class Boundaries>, <List of Raw Data>, ]::
Frequency[ <Cumulative>, <List of Class Boundaries>, <List of Raw Data>]::
Frequency[ <List of Class Boundaries>, <List of Raw Data>, <Use Density> , <Density Scale Factor> (optional) ]::
Frequency[ <Boolean Cumulative>, <List of Class Boundaries>, <List of Raw Data>, <Use Density> , <Density Scale Factor>
(optional) ]::

Frequency[ <List of Raw Data> ]::
  Returns a list with a count of the occurrences of each unique value in the given list of data. This input list can be
  numbers or text. The list is sorted in ascending order of the unique values. To get a list of the corresponding unique
  values use the command Unique[ <List of Raw Data> ]

[EXAMPLE]
====
 Enter `++list1 = { "a", "a", "x", "x", "x", "b" }++`. `++Frequency[list1]++` returns the list \{ 2, 1, 3 }.
`++Unique[list1]++` returns the list \{ "a", "b", "x" }.

====

Frequency[ <Cumulative>, <List of Raw Data>]::
  If Cumulative = false, returns the same list as Frequency[ <List of Raw Data> ]
  If Cumulative = true, returns a list of cumulative frequencies for Frequency[ <List of Raw Data> ]

[EXAMPLE]
====
 Enter `++list1 = { 0, 0, 0, 1 , 1, 2 }++`. `++Frequency[true, list1]++` returns the list \{ 3, 5, 6 }.
`++Frequency[false, list1]++` returns the list \{ 3, 2, 1}. `++Unique[list1]++` returns the list \{ 0, 1, 2 }

====

Frequency[<List of Class Boundaries>, <List of Raw Data> ]::
  Returns a list of the counts of values from the given data list that lie within the intervals formed by the given
  class boundaries. All intervals except the highest interval are of the form [a, b). The highest interval has the form
  [a, b].

[EXAMPLE]
====
 `++Frequency[{1,2,3},  {1,1,2,3}]++` returns the list \{ 2, 2 }.

====

Frequency[ <Cumulative>,<List of Class Boundaries>,<List of Raw Data>]::
  If Cumulative = false, returns the same list as Frequency[ <List of Class Boundaries>, <List of Raw Data> ]
  If Cumulative = true, returns a list of cumulative frequencies for Frequency[ <List of Class Boundaries>, <List of Raw
  Data> ]

Frequency[<List of Class Boundaries>, <List of Raw Data>, <Use Density> , <Density Scale Factor> (optional) ]::
  Returns a list of frequencies for the corresponding
  xref:/s_index_php?title=Histogram_Command_action=edit_redlink=1.adoc[Histogram Command].

Frequency[ <Boolean Cumulative>, <List of Class Boundaries>, <List of Raw Data>, <Use Density> , <Density Scale Factor>
(optional) ]::
  Returns a list of frequencies for the corresponding
  xref:/s_index_php?title=Histogram_Command_action=edit_redlink=1.adoc[Histogram Command].
