= Gamma 指令
:page-en: commands/Gamma
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

Gamma[ <Alpha>, <Beta>, x ]::
Gamma[ <Alpha>, <Beta>, x, <Boolean Cumulative> ]::
Gamma[ <Alpha>, <Beta>, <Variable Value> ]::

== CAS 視窗

Gamma[ <Alpha>, <Beta>, x ]::
Gamma[ <Number α>, <Number β>, x ]::
  Creates probability density function (pdf) of https://en.wikipedia.org/wiki/Gamma_distribution[gamma distribution]
  with parameters _α, β_.
Gamma[ <Number α>, <Number β>, x, <Boolean Cumulative> ]::
  If _Cumulative_ is true, creates cumulative distribution function of gamma distribution, otherwise creates pdf of
  gamma distribution.
Gamma[ <Number α>, <Number β>, <Variable Value v> ]::
  Calculates the value of cumulative distribution function of gamma distribution at _v_, i.e. the probability _P(X≤v)_
  where _X_ is a random variable with gamma distribution given by parameters _α, β_.

[NOTE]
====
Returns the probability for a given _x_-coordinate's value (or area under the gamma distribution curve to the
left of the given _x_-coordinate).

====

== CAS Syntax

In xref:/CAS_View.adoc[CAS View] only following syntax is supported:

Gamma[<Number α>, <Number β>, <Variable Value v>]::
  Calculates the value of cumulative distribution function of gamma distribution at _v_, i.e. the probability _P(X≤v)_
  where _X_ is a random variable with gamma distribution given by parameters _α, β_.
