= HyperGeometric 指令
:page-en: commands/HyperGeometric
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

HyperGeometric[ <Population Size>, <Number of Successes>, <Sample Size> ]::
HyperGeometric[ <Population Size>, <Number of Successes>, <Sample Size>, <Boolean Cumulative> ]::
HyperGeometric[ <Population Size>, <Number of Successes>, <Sample Size>, <Variable Value>, <Boolean Cumulative> ]::

== CAS 視窗

HyperGeometric[ <Population Size>, <Number of Successes>, <Sample Size> ]::
HyperGeometric[ <Population Size>, <Number of Successes>, <Sample Size>]::
  Returns a bar graph of a https://en.wikipedia.org/wiki/Hypergeometric_distribution[Hypergeometric distribution].
  _Parameters:_
  _Population size_: number of balls in the urn
  _Number of Successes_: number of white balls in the urn
  _Sample Size_: number of balls drawn from the urn

The bar graph shows the probability function of the number of white balls in the sample.

HyperGeometric[ <Population Size>, <Number of Successes>, <Sample Size>, <Boolean Cumulative> ]::
  Returns a bar graph of a Hypergeometric distribution when _Cumulative_ = false.
  Returns a bar graph of a cumulative Hypergeometric distribution when _Cumulative_ = true.
  First three parameters are same as above.

HyperGeometric[ <Population Size>, <Number of Successes>, <Sample Size>, <Variable Value v>, <Boolean Cumulative> ]::
  Let X be a Hypergeometric random variable.
  Returns P( X = _v_) when _Cumulative_ = false.
  Returns P( X ≤ _v_) when _Cumulative_ = true.
  First three parameters are same as above.

== CAS Syntax

In xref:/CAS_View.adoc[CAS View] only one syntax is allowed:

HyperGeometric[ <Population Size>, <Number of Successes>, <Sample Size>, <Variable Value v>, <Boolean Cumulative> ]::
  Let X be a Hypergeometric random variable.
  Returns P( X = _v_) when _Cumulative_ = false.
  Returns P( X ≤ _v_) when _Cumulative_ = true.
  First three parameters are same as above.

[EXAMPLE]
====


Assume you select two balls out of ten balls, two of which are white, without putting any back.

* `++HyperGeometric[10, 2, 2, 0, false]++` yields stem:[\frac\{28}\{45}], the probability of selecting zero white balls,
* `++HyperGeometric[10, 2, 2, 1, false]++` yields stem:[\frac\{16}\{45}], the probability of selecting one white ball,
* `++HyperGeometric[10, 2, 2, 2, false]++` yields stem:[\frac\{1}\{45}], the probability of selecting both white balls,
* `++HyperGeometric[10, 2, 2, 3, false]++` yields _0_, the probability of selecting three white balls.
* `++HyperGeometric[10, 2, 2, 0, true]++` yields stem:[\frac\{28}\{45}], the probability of selecting zero (or less)
white balls,
* `++HyperGeometric[10, 2, 2, 1, true]++` yields stem:[\frac\{44}\{45}], the probability of selecting one or less white
balls,
* `++HyperGeometric[10, 2, 2, 2, true]++` yields _1_, the probability of selecting tow or less white balls and
* `++HyperGeometric[10, 2, 2, 3, true]++` yields _1_, the probability of selecting three or less white balls.

====
