= LogNormal 指令
:page-en: commands/LogNormal
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

LogNormal[ <Mean>, <Standard Deviation>, x ]::
LogNormal[ <Mean>, <Standard Deviation>, x, <Boolean Cumulative>]::
LogNormal[ <Mean>, <Standard Deviation>, <Variable Value> ]::
LogNormal[ <Mean μ>, <Standard Deviation σ>, x ]::
  Creates probability density function (pdf) of https://en.wikipedia.org/wiki/Log-normal_distribution[log-normal
  distribution] with parameters _μ, σ_.
LogNormal[ <Mean μ>, <Standard Deviation σ>, x, <Boolean Cumulative> ]::
  If _Cumulative_ is true, creates cumulative density function of LogNormal distribution, otherwise creates pdf of
  log-normal distribution.
LogNormal[ <Mean μ>, <Standard Deviation σ>, <Variable Value v> ]::
  Calculates the value of cumulative distribution function of log-normal distribution at _v_, i.e. the probability
  _P(X≤v)_ where _X_ is a random variable with log-normal distribution given by parameters _μ, σ_.

[NOTE]
====
Returns the probability for a given _x_-coordinate's value (or area under the log-normal distribution curve to
the left of the given _x_-coordinate).

====

== CAS Syntaxes

In xref:/CAS_View.adoc[CAS View] only following syntax is supported:

LogNormal[ <Mean μ>, <Standard Deviation σ>, <Variable Value v>]::
  Calculates the value of cumulative distribution function of log-normal distribution at _v_, i.e. the probability
  _P(X≤v)_ where _X_ is a random variable with log-normal distribution given by parameters _μ, σ_.
