= Normal 指令
:page-en: commands/Normal
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

Normal[ <Mean>, <Standard Deviation>, x ]::
Normal[ <Mean>, <Standard Deviation>, x, <Boolean Cumulative>]::
Normal[ <Mean>, <Standard Deviation>, <Variable Value> ]::

== CAS 視窗

Normal[ <Mean>, <Standard Deviation>, x ]::
Normal[ <Mean μ>, <Standard Deviation σ>, <x> ]::
  Creates probability density function (pdf) of https://en.wikipedia.org/wiki/Normal_distribution[normal distribution].
Normal[ <Mean μ>, <Standard Deviation σ>, <x>, <Boolean Cumulative> ]::
  If _Cumulative_ is true, creates cumulative distribution function of normal distribution, otherwise creates pdf of
  normal distribution.
Normal[ <Mean μ>, <Standard Deviation σ>, <Variable Value v> ]::
  Calculates the function _Φ((x – μ) / σ)_ at _v_ where _Φ_ is the cumulative distribution function for _N(0,1)_.

[NOTE]
====
Returns the probability for a given _x_-coordinate's value (or area under the normal distribution curve to the
left of the given _x_-coordinate).

====

== CAS Syntaxes

In xref:/CAS_View.adoc[CAS View] only following syntax is supported:

Normal[ <Mean μ>, <Standard Deviation σ>, <Variable Value x> ]::
  Calculates the function _Φ((x – μ) / σ)_ where _Φ_ is the cumulative distribution function for _N(0,1)_.

[EXAMPLE]
====


`++Normal[2, 0.5, 1]++` yields stem:[0.5 erf(-\sqrt\{2}) + 0.5].

====
