= RandomNormal 指令
:page-en: commands/RandomNormal
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

RandomNormal[ <Mean>, <Standard Deviation> ]::
RandomNormal[ <Mean>, <Standard Deviation> ]::
  Generates a random number from a normal distribution with mean and standard deviation.

[EXAMPLE]
====


`++RandomNormal[3, 0.1]++` yields a random value from a normal distribution with a mean of _3_ and standard deviation of
_0.1_.

====

[NOTE]
====

*備註：*

See also xref:/s_index_php?title=RandomBinomial_Command_action=edit_redlink=1.adoc[RandomBinomial Command] and
xref:/s_index_php?title=RandomPoisson_Command_action=edit_redlink=1.adoc[RandomPoisson Command].

====

== CAS Syntax

RandomNormal[ <Mean>, <Standard Deviation> ]::
  Generates a random number from a normal distribution with mean and standard deviation.

[EXAMPLE]
====


`++RandomNormal[3, 0.1]++` yields a random value from a normal distribution with a mean of _3_ and standard deviation of
_0.1_.

====

[NOTE]
====

*備註：*

See also xref:/s_index_php?title=RandomBinomial_Command_action=edit_redlink=1.adoc[RandomBinomial Command] and
xref:/s_index_php?title=RandomPoisson_Command_action=edit_redlink=1.adoc[RandomPoisson Command].

====
