= RandomPoisson 指令
:page-en: commands/RandomPoisson
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

RandomPoisson[ <Mean> ]::

== CAS 視窗

RandomPoisson[ <Mean> ]::
RandomPoisson[ <Mean> ]::
  Generates a random number from a Poisson distribution with given mean.

[EXAMPLE]
====


`++RandomPoisson[3]++` yields a random value from a Poisson distribution with a mean of _3_.

====

[NOTE]
====

*備註：*

See also xref:/s_index_php?title=RandomBinomial_Command_action=edit_redlink=1.adoc[RandomBinomial Command] and
xref:/s_index_php?title=RandomNormal_Command_action=edit_redlink=1.adoc[RandomNormal Command].

====

== CAS Syntax

RandomPoisson[ <Mean> ]::
  Generates a random number from a Poisson distribution with given mean.

[EXAMPLE]
====


`++RandomPoisson[3]++` yields a random value from a Poisson distribution with a mean of _3_.

====

[NOTE]
====

*備註：*

See also xref:/s_index_php?title=RandomBinomial_Command_action=edit_redlink=1.adoc[RandomBinomial Command] and
xref:/s_index_php?title=RandomNormal_Command_action=edit_redlink=1.adoc[RandomNormal Command].

====
