= RandomBinomial 指令
:page-en: commands/RandomBinomial
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

RandomBinomial[ <Number of Trials>, <Probability> ]::

== CAS 視窗

RandomBinomial[ <Number of Trials>, <Probability> ]::
RandomBinomial[ <Number n of Trials>, <Probability p> ]::
  Generates a random number from a binomial distribution with _n_ trials and probability _p_.

[EXAMPLE]
====


`++RandomBinomial[3, 0.1]++` gives _j ∈ \{0, 1, 2, 3}_, where the probability of getting _j_ is the probability of an
event with probability _0.1_ occuring _j_ times in three tries.

====

== CAS Syntax

RandomBinomial[ <Number n of Trials>, <Probability p> ]::
  Generates a random number from a binomial distribution with _n_ trials and probability _p_.

[EXAMPLE]
====


`++RandomBinomial[3, 0.1]++` gives _j ∈ \{0, 1, 2, 3}_, where the probability of getting _j_ is the probability of an
event with probability _0.1_ occuring _j_ times in three tries.

====

[NOTE]
====

*備註：*

See also xref:/s_index_php?title=RandomNormal_Command_action=edit_redlink=1.adoc[RandomNormal Command] and
xref:/s_index_php?title=RandomPoisson_Command_action=edit_redlink=1.adoc[RandomPoisson Command].

====
