= Nástroj Pravděpodobnostní kalkulačka
:page-en: Probability_Calculator
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

Po kliknutí na tento nástroj se zobrazí dialog pro výpočet a znázornění rozdělení pravděpodobnosti.

* Pro změnu rozdělení klikneme na rozbalovací menu rozdělení a zvolíme jedno ze seznamu. Poté nastavíme parametry
rozdělení v sousedních textových polích.
* Pro výpočet pravděpodobnosti klikneme na rozbalovací menu pravděpodobnost a zvolíme druh intervalu. Poté nastavíme
interval v sousedních textových polích. Pravděpodobnost můžeme určit také pří pohybování body po ose x grafu.

*Možnosti*

Pravděpodobnostní kalkulačka má nabídku možností, která umožňuje změnu nastavení a exportování grafu. Panel možností se
zobrazí po kliknutí na tlačítko otevřít v titulním panelu nebo po dvojitém kliknutí na titulní panel. V panelu možnosti
můžeme upravit zaokrouhlování, zobrazit růst pravděpodobnosti a exportovat graf.

*Táhni a Pusť*

Je-li myš umístěna v horní části nákresy, kurzor se změní na symbol ruky. Takto můžeme graf přetáhnout z nákresny 1 na
nákresnu 2 a vytvořit nový průběh funkce. Stejně tak můžeme přetáhnou obrázek do jiné aplikace.
