= Nástroj Průsečíky dvou objektů
:page-en: tools/Intersect
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

Průsečíky dvou objektů se mohou vytvářet dvěma způsoby. ( viz také příkaz xref:/commands/Prusecik.adoc[Prusecik] ).

* Označením dvou objektů budou vytvořeny _všechny_ průsečíky (pokud to lze).
* Kliknutím na společný bod dvou objektů bude vytvořen právě tento _jeden_ průsečík.

[NOTE]
====

Pro úsečky, polopřímky a oblouky lze v záložce _Základní_ v dialogu xref:/Dialog_Vlastnosti.adoc[Vlastnosti]
specifikovat, chceme-li _Povolit vnější průsečíky_. Povolením vnějších průsečíků zobrazíme i průsečíky, které leží na
prodloužení daného objektu. Například prodloužením úsečky a polopřímky je přímka.

====

[NOTE]
====

Někdy může být užitečné zobrazit pouze výřez protínajících se objektů v okolí průsečíku. K tomu klikneme pravým
tlačítkem myši na průsečík a zaškrtneme _Zobrazit úseky protínajících se čar_ v záložce _Základní_ v dialogu
_Vlastnosti_. Protínající se objekty jsou mimo okolí průsečíku skryty.

====
