= Nástroj Úhel
:page-en: tools/Angle
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

S tímto nástrojem můžete vytvořit úhel několika různými způsoby (podívejte se také na příkaz
xref:/commands/Uhel.adoc[Úhel]):

* Klikněte na tři body pro vytvoření úhlu mezi těmito body. Druhý vybraný bod je vrcholem úhlu.
* Klikněte na dvě úsečky pro vytvoření úhlu mezi nimi.
* Klikněte na dvě přímky pro vytvoření úhlu mezi nimi.
* Klikněte na dva vektory pro vytvoření úhlu mezi nimi.
* Klikněte na mnohoúhelník pro vytvoření všech úhlů tohoto mnohoúhelníku.

[NOTE]
====

Pokud byly vrcholy mnohoúhelníku vytvořeny proti směru hodinových ručiček, nástroj "Úhel" vytvoří vnitřní úhly tohoto
mnohoúhelníku.

====

[NOTE]
====

Úhly jsou vytvářeny _proti směru hodinových ručiček_. Proto je u nástroje "Úhel" důležité v jakém pořadí jsou objekty
vybírány. Jestliže chcete omezit maximální velikost úhlu na 180°, odškrtněte "Povolit nekonvexní úhel" na záložce
"Základní" v dialogu xref:/Dialog_Vlastnosti.adoc[Vlastnosti].

====
