= Comments:Metszéspont eszköz
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Két alakzat metszéspontja két módon is létrehozható (lásd még a xref:/commands/Metszéspont.adoc[Metszéspont] parancsot).

* Ha kijelöljük a két alakzatot, létrejön az összes metszéspont (ha ez lehetséges).
* Közvetlenül a két alakzat metszéspontjára kattintva csak ez az _egyedüli metszéspont_ jön létre.

[NOTE]
====

*Jegyzet:* Néha hasznos lehet, ha a metszőalakzatoknak csak a metszéspont közelébe eső része látszik. Ennek
beállításához kattintsunk a metszéspontra jobb gombbal, majd a "Tulajdonságok" párbeszédablak "Alap" fülén kapcsoljuk be
a "Metszésvonal kiemelése" opciót. Ekkor a metsző alakzatok rejtettek lesznek.

====

== Kieső metszéspontok

Szakaszok, félegyenesek, ívek esetén, beállíthatjuk a _Kieső metszéspontok engedélyezése_ opciót a
xref:/Tulajdonságok_párbeszédablak.adoc[Tulajdonságok párbeszédablak] "Alap" fülén. Így azok a metszéspontok is
megkaphatók, melyek az alakzaton kívül fekszenek. Például egy szakasz vagy félegyenes meghosszabbításán.
