= Szög eszköz
:page-en: tools/Angle
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Ezzel az eszközzel különböző szögeket hozhat létre.

* Jelöljön ki három, _A_, _B_ és _C_ pontot, hogy létrehozza a három pont által meghatározott szöget. A _B_ pont a szög
csúcsa.
* Jelöljön ki két szakaszt hogy létrehozza a közbezárt szöget. A szög adott esetben a meghosszabbított szakaszokon
látható.
* Jelöljön ki két egyenest hogy létrehozza a közbezárt szöget.
* Jelöljön ki két vektort hogy létrehozza a közbezárt szöget.
* Jelöljön ki egy sokszöget, hogy létrehozza annak összes szögét.

[NOTE]
====

*Jegyzet:* Egy háromszögnél a belső szögek kerülnek megrajzolásra. Egy sokszögnél, amelynek háromnál több csúcsa van és
azok az óramutató járásával ellentétes irányban lettek létrehozva, szintén a belső szögek kerülnek megrajzolásra.

====

[NOTE]
====

*Jegyzet:* A GeoGebra a szögeket pozitív irányban hozza létre (az óramutató járásával ellentétes irányban), emiatt a
kijelölt objektumok sorrendje a szög szempontjából mérvadó. Egy szög nagysága viszont korlátozható maximum 180°-ra a
xref:/Tulajdonságok_párbeszédablak.adoc[Tulajdonságok] menüpontban.

====
