= GeoGebraPrim
:page-en: GeoGebraPrim
ifdef::env-github[:imagesdir: /zh/modules/ROOT/assets/images]

GeoGebraPrim is a version of GeoGebra for primary school pupils. You can find it as webstart application here:
http://www.geogebra.org/webstart/4.0/GeoGebraPrim.jnlp

Following features are intended to simplify the use of GeoGebra for the pupils:

* Restricted set of xref:/Tools.adoc[Tools] available
* All available Tools visible at once
* Larger Font size
* Larger / Thicker Objects
* Just the xref:/Graphics_View.adoc[Graphics View] showing
* Easier to xref:/s_index_php?title=Selecting_objects_action=edit_redlink=1.adoc[select objects]
* xref:/s_index_php?title=Labels_and_Captions_action=edit_redlink=1.adoc[Labeling] of objects disabled
* xref:/Numbers_and_Angles.adoc[Angles] always between 0° and 180° by default
* Rounding to nearest whole number

[NOTE]
====
GeoGebra and GeoGebraPrim are actually the same application -- you can switch between these two interfaces via
Perspectives submenu in xref:/Options_Menu.adoc[Options Menu]. All commands of GeoGebra are available in GeoGebraPrim.

====
