= A szerkesztés lépései
:page-en: Construction_Protocol
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

A "Nézet" menüben "A szerkesztés lépései" menüpontot választva érhetjük el az interaktív felületet. "A szerkesztés
lépései" egy olyan táblázatot jelent, melyben a szerkesztés valamennyi lépése látható, a szerkesztés újrajátszható
lépésről lépésre. A GeoGebra ablak alján megjeleníthetjük a xref:/Navigációs_eszköztár.adoc[Navigációs eszköztárat], ha
jobb gombbal kattintunk a "Rajzlapon" és a helyi menüből a __Navigációs eszköztár__at választjuk.

== Navigáció és módosítás A szerkesztés lépéseiben

Navigálásra használhatjuk a billentyűzetet:

* [.kcode]#↑# a felfelé mutató nyíl az előző lépésre ugrik.
* [.kcode]#↓# a lefelé mutató nyíl a következő lépésre ugrik.
* [.kcode]#Home# a Home billentyű a szerkesztés elejére ugrik.
* [.kcode]#End# az End billentyű a szerkesztés végére ugrik.
* [.kcode]#Delete# a Delete billentyű törli a kijelölt szerkesztési lépést.

[NOTE]
====

*Jegyzet:* Hatással lehet más objektumokra is, melyek függnek a kijelölt objektumtól/szerkesztési lépéstől.

====

Ugyanígy az egeret is alkalmazhatjuk a navigálásban:

* Kettős kattintással kijelölhetünk egy szerkesztési lépést.
* Bármely oszlop fejlécére duplán kattintva a szerkesztés elejére ugrik.
* Az egérrel húzva elmozdíthatunk egy adott sort/szerkesztési lépést.

[NOTE]
====

*Jegyzet:* Nem minden esetben engedélyezett, az objektumok függőségi viszonyai határozzák meg.

====

* Egy soron jobb gombbal kattintva, az éppen kijelölt objektum helyi menüje jelenik meg.

[NOTE]
====

*Jegyzet:* Bármely pozícióba beilleszthető újabb szerkesztési lépés. Jelöljük ki azt a lépést, amelyik elé be szeretnénk
szúrni az újat. Hagyjuk nyitva A szerkesztés lépései ablakot amíg az új objektumot létrehozzuk. Ez az új lépés azonnal
bekerül a kijelölt pozícióba a szerkesztési lépések közé.

====

A szerkesztési lépések eszköztárának első ikonjára kattintva kiválaszthatjuk a listából, hogy mely információk legyenek
láthatóak. A _Töréspont_ opció lehetőséget ad arra, hogy bizonyos lépéseket töréspontként definiáljunk, pl. néhány
objektum csoportba foglalásához. A xref:/Navigációs_eszköztár.adoc[Navigációs eszköztárral] a szerkesztési lépéseken
végighaladva, a csoportba foglalt elemek együtt jelennek meg.

== A szerkesztés lépéseinekk exportálása weblapként

A GeoGebra lehetőséget ad arra, hogy __A szerkesztés lépései__t weblapként exportáljuk. Nyissuk ki __A szerkesztés
lépései__t a "Nézet" menüből, majd a megjelenő eszköztár harmadik ikonját (_Exportálás weblapként_) válasszuk.

A szerkesztés lépéseinek exportálásakor megadhatjuk a __Cím__et, __Szerző__t és a __Dátumo__t és beszúrhatjuk képként a
xref:/Geometria_ablak.adoc[Rajzlapot] és az xref:/Algebra_nézet.adoc[Algebra nézetet]. Választhatjuk még a __Színezett
szerkesztés lépései__t. Ekkor __A szerkesztés lépései__ben az objektumok a rajzlapnak megfelelő színben fognak
megjelenni.

[NOTE]
====

*Jegyzet:* Az exportált HTML fájl bármely Internet böngészővel megjeleníthető (pl. Firefox, Internet Explorer) és
szerkeszthető bármely szövegszerkesztővel (pl. OpenOffice Writer).

====
