= Alakzat információk
:page-en: Tooltips
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Az Alakzat információk azt a szöveget jelentik, mely megjelenik közvetlenül az egér mellett, amikor az egy adott
objektumra mutat a xref:/Geometria_ablak.adoc[Geometria ablakban]. A
xref:/Tulajdonságok_párbeszédablak.adoc[Tulajdonságok párbeszédablak] "Haladó" fülén ötféle módból választhatunk:

Automatikus::
  Az Alakzat információk funkció csak nyitott xref:/Algebra_nézet.adoc[Algebra nézet] esetén aktív. Tartalmazza az
  alakzat típusát és nevét, xref:/Szabad_Függő_és_Segéd_alakzatok.adoc[függő alakzatok] esetén az alakzat leírását.
Be::
  Az Alakzat információk megjelennek akkor is, ha az Algebra nézet zárva van. Tartalma ugyanaz, mint az "Automatikus"
  beállításnál.
Ki::
  Nem jelennek meg az Alakzat információk.
Címke::
  Az alakzat xref:/Címkék_és_feliratok.adoc[Címke]-je jelenik meg az Alakzat információkban. A Címke a Tulajdonságok
  párbeszédablak Alap fülén adható meg.
Szomszédos cella::
  Ha az alakzat a xref:/Táblázatkezelő_nézet.adoc[Táblázatkezelő] egy cellája, akkor a tőle jobbra levő cella tartalma
  kerül az Alakzat információkba.

A xref:/Beállítások_párbeszédablak.adoc[Beállítások párbeszédablak] Haladó fülén megadható még az Alakzat információk
nyelve és megjelenésének időtartama.
