= Egyenlőtlenségek
:page-en: Inequalities
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

A GeoGebra támogatja az egy vagy két ismeretlenes egyenlőtlenségeket. Az xref:/Algebra_nézet.adoc[Algebra nézetben] nem
korlátozottak az egyenlőtlenségek, de csak bizonyos egyenlőtlenségek jeleníthetők meg a
xref:/Geometria_ablak.adoc[Rajzlapon]:

* polinomiális egyismeretlenes egyenlőtlenség, pl. _x^3 > x + 1_ vagy _y^2>y_,
* másodfokú kétismeretlenes egyenlőtlenség, pl. _x^2 + y^2 + x*y ≤ 4_,
* elsőfokú egyismeretlenes egyenlőtlenség, pl.. _2x > sin(y)_ vagy _y < sqrt(x)_.

Az egyenlőtlenségek jelölésére használhatók a <, >, ≤, ≥ relációs jelek. Megengedett <= és => használata is. Az
egyenlőtlenségek közötti "és" (konjunkció, ∧) illetve "vagy" (diszjunkció, ∨) műveletek is használhatóak, pl. _(x>y) ∧
(x+y<3)_ is kirajzoltatható.

Ha az egyenlőtlenség megoldását, illetve valamely intervallumot szeretnénk az x-tengelyen" látni, jelöljük be a z
egyenlőtlenség xref:/Tulajdonságok_párbeszédablak.adoc[Tulajdonságok párbeszédablakának] "Stílus" fülén a "Mutatás az
x-tengelyen _opciót ._

Az egyenlőtlenségek a függvényekhez hasonlóak. A xref:/Parancssor.adoc[Parancssorba] a(x,y) beírásával kipróbálható,
hogy _x_ és _y_ kiegyenlítik-e az "a" egyenlőtlenséget, ha A egy adott pont, akkor is értelmezhető az _a(A)_ kifejezés.
Egy pont hozzárendelhető egy intervallumhoz a xref:/commands/BelsőPont.adoc[BelsőPont parancs]-csal. Ha _b_ egy
egyismeretlenes egyenlőtlenség, pl. _x_-re, akkor Pont[b] eredménye egy olyan pont, az x-tengelyen, mely a "b"
egyenlőtlenséget kielégíti.
