= Eszköztár
:page-en: Toolbar
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Az eszköztár alapvetően a xref:/Menüsor.adoc[Menüsor] alatt található. Minden xref:/Nézetek.adoc[nézetnek], amelyet egy
egyéni ablakban nyit meg, saját eszköztára van, amely az ablak felső részén található. Minden eszköztár
eszközcsoportokra van osztva, amelyek egy vagy több xref:/Eszközök.adoc[eszközt] tartalmaznak. Az eszköztárt át lehet
helyezni a főablak más részére. Az elrendezést a xref:/Nézet_menü.adoc[Nézet menü] _Elrendezés..._ pontja alatt tudja
megadni.

== Segítség az eszköztárban

Az eszköztár jobb részén mindig található egy rövid segítség az éppen kiválasztott eszközhöz. Ha ez nem jelenik meg,
állítsa az ablak méretét nagyobbra. Amint más nézetet aktivál a GeoGebra ablakban, megváltozik az eszköztár. Ha a
táblázatkezelő nézetet vagy a CAS nézetet külön ablakban nyitja meg, úgy az automatikusan tartalmazza az adott
eszköztárt.

== Az eszköztár testreszabása

Mindhárom eszköztár testre szabható az xref:/Eszközök_menü.adoc[Eszközök menü] _Eszköztár testreszabása..._ menüpontban.
A listán kiválaszthatja azokat az eszközöket, amelyeket testre szeretne szabni. Ha egy eszközt el szeretne távolítani az
eszköztárból, válassza ki a bal oldali listán, majd kattintson a _Töröl_ gombra. Egy eszköz hozzáadásához válassza ki a
megfelelő eszközt a jobb oldali listán. Ha ezt az eszközt új eszközcsoportként szeretné létrehozni, válassza ki azt az
eszközcsoportot, amelyet az új eszközcsoport bal oldali szomszédjaként szeretne, majd kattintson a _Beilleszt_ gombra.
Ha az eszközt egy létező eszközcsoporthoz szeretné hozzáadni, nyissa meg az adott eszközcsoportot, majd jelölje ki azt
az eszközt, amely alá be szeretné illeszteni az új eszközt és kattintson a _Beilleszt_ gombra. Ha át szeretne helyezni
egy eszközt egy másik csoportba, akkor azt előbb törölni kell, majd beilleszteni az új csoportba.

[NOTE]
====

*Jegyzet:* Az eszköztár alapbeállításainak visszaállításához kattintson az _Alap eszköztár beállítás visszaállítása_
gombra, amely a párbeszédablak bal alsó részén található.

====
