= Exportálás weblapként
:page-en: Embedding_in_Webpages
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Ha weboldalt szeretne létrehozni, amely a GeoGebra munkáját tartalmazza, akkor fel kell töltenie
xref:/Munkalap_mentése_párbeszédablak.adoc[dinamikus munkalapként a GeoGebra-ra]. A generált kódot ezután egy
szövegszerkesztő program (pl. Notepad) segítségével elmentheti html-fájlként számítógépén.

== Haladó beállítások

A _Haladó beállítások..._ gomb lehetővé teszi a dinamikus munkalap funkcióinak megváltoztatását (pl. visszaállítás gomb
mutatása), valamint a felhasználói felület módosítását (az xref:/Eszköztár.adoc[Eszköztár] mutatását, szélesség és
magasság megadását, stb).

*Funkciók*:

* _Jobb egérgomb, zoomolás és billentyűzet engedélyezése_: Lehetővé teszi, hogy jobb egérgombbal a rajzlapra vagy
objektumokra kattinva megnyissa pl. a xref:/Tulajdonságok_párbeszédablak.adoc[Tulajdonságok párbeszédablakot], az
xref:/tools/Alakzat_mutatása_elrejtése.adoc[alakzat mutatását/elrejtését], xref:/Nyomvonal.adoc[Nyomvonal]
megjelenítését, stb.

* _Feliratok mozgatásának engedélyezése_: Lehetővé teszi az objektumok és pontok feliratának elmozgatását.

* _Szerkesztés alapállapotba hozása ikon megjelenítése_: Megjelenít egy visszaállítás gombot a munkalap jobb felső
sarkában, amely visszaállítja a munkalap eredeti állapotát.

* _Shift-vonszolás és zoomolás engedélyezése_: Lehetővé teszi a [.kcode]#Shift#-billentyűs vonszolást, valamint a
munkalap kinagyítását/kicsinyítését.

*Felhasználói felület*:

* _Menüsor mutatása_: Menüsor mutatása interaktív appletben.

* _Eszköztár mutatása_: Eszköztár mutatása interaktív appletben, a geometriai eszközök használatának engedélyezésével.

* _Parancssor mutatása_: Parancssor mutatása az interaktív applet alsó részén, az algebrai bevitelek és parancsok
használatának engedélyezésével.

[NOTE]
====

*Jegyzet:* Ha az applet mérete túl kicsi, úgy előfordulhat, hogy a munkalap elérhetetlen lesz a felhasználók számára.

====

[NOTE]
====

*Jegyzet:* Ha aktiválja a menüsort, az eszköztárt és a parancssort, akkor feltétlenül állítsa be az interaktív applet
méretét.

====
