= Mentés LaTeX-be (PGF, PSTricks) és Asymptote kódba
:page-en: Export_to_LaTeX_PGF_PSTricks_and_Asymptote
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

:toc:

== Export - Rajzlap mint GIF...

Ez az opció lehetővé teszi egy https://en.wikipedia.org/wiki/Animated_GIF#Animated_GIF[animált GIF] elmentését, ha a
dinamikus munkalap egy csúszkától függ. A megjelenő párbeszédablakban megadhatja az animált csúszka nevét, a képek
követési idejét, valamint beállíthatja a végtelen lejátszást.

== Export - Rajzlap mint PSTricks…

[.kcode]#Ctrl# + [.kcode]#Shift# + [.kcode]#T# (Mac OS: [.kcode]#Cmd# + [.kcode]#Shift# + [.kcode]#T#

Ebben a menüpontban elmentheti rajzlapját http://tug.org/PSTricks/main.cgi/[PSTricks] képként, amely engedélyezi a
xref:/LaTEX.adoc[LaTEX] szövegek beágyazását.

== Export - Rajzlap mint PGF/TiKZ…

Ebben a menüpontban elmentheti rajzlapját http://sourceforge.net/projects/pgf/[PGF] képként, amely szintén a
xref:/LaTEX.adoc[LaTEX]-es képformátumok közé tartozik.

== Export - Rajzlap Asymptote kódként…

Lehetővé teszi a rajzlap elmentését http://asymptote.sourceforge.net/[Asymptote] képként.

== Az exportálás határai

A következő objektumokat nem lehet a fenti formátumokban elmenteni:

* implicit görbék
* mértani helyek
