= Nyomtatási beállítások
:page-en: Printing_Options
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

== Nyomtatási beállítások

=== Rajzlap nyomtatása

A GeoGebra xref:/Geometria_ablak.adoc[rajzlapot] ki is lehet nyomtatni. A xref:/Fájl_menü.adoc[Fájl menüben] a
_Nyomtatási kép_ menüpont kiválasztása után megadhatja a megnyíló párbeszédablakban a dokumentum címét, szerzőjét és a
dátumot. Megadható továbbá a nyomtatás mérete cm-ben, illetve a papír elrendezése (fekvő vagy álló formátum).

[NOTE]
====

*Jegyzet:* A nyomtatási kép a dokumentum megváltoztatása után az [.kcode]#Enter#-rel frissíthető.

====

=== A szerkesztési lépések nyomtatása

Ha ki szeretné nyomtatni a xref:/A_szerkesztés_lépései.adoc[A szerkesztés lépéseit], tartalmazó protokollt, előbb meg
kell nyitnia a megfelelő párbeszédablakot a _Szerkesztés lépései_ menüpont kiválasztásával a _Nézet_ menüben. Ezután
elérhető a _Szerkesztés lépései_ nyomtatási előnézete a _Fájl_ menüben. Itt szintén megadhatja a dokumentum címét,
szerzőjét, a dátumot illetve a nyomtatási méretet és a papír elrendezését.

[NOTE]
====

*Jegyzet:* A szerkesztési lépések különböző oszlopait (sorszám, név, definíció, érték, címke) a _Nézet_ menüben
láthatóvá teheti vagy elrejtheti.

====
