= Dynamische kleuren
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Je kunt in GeoGebra de kleur van een object bepalen in de tab _Kleur_ van het
xref:/Eigenschappen_dialoogvenster.adoc[Eigenschappenvenster]. Je kunt de kleur van een object ook dynamisch maken: -
open het eigenschappenvenster van het object - selecteer de tab _Geavanceerd_. Het onderdeel _Dynamische Kleuren_ heeft
drie invulvakken waarin je een waarde kan toekennen aan de kleuren _Rood_, _Groen_, en _Blauw_.

[NOTE]
====

* De RGB waarden van de hoofdkleuren zie je rechts in worden naast het kleurvoorbeeld in de tab _Kleur_ van het
xref:/Eigenschappen_dialoogvenster.adoc[Eigenschappenvenster]. Het getal dat je moet ingeven in de invulvakken van
dynamische kleuren verkrijg je door elke RGB-waarde te delen door 255.
* Dynamische kleuren kan je definiëren met een getal tussen 0 en 1.

====

\{\{Example|

* Creëer drie xref:/tools/Schuifknop.adoc[Schuifknoppen] a, b, en c binnen een interval van 0 tot 1.
* Creëer een veelhoek waarvan je de kleur laat afhangen van de waarden van de schuifknoppen.
* Open het xref:/Eigenschappen_dialoogvenster.adoc[Eigenschappenvenster] van de veelhoek en typ de namen van de
schuifknoppen in de invulvakken van de kleuren _Rood_, _Groen_ en _Blauw_ .
* Sluit het _Eigenschappenvenster_ en verander de waarden van de schuifknoppen. Zo zie je hoe elke kleurencomponent de
kleur van de veelhoek beïnvloedt.

== RGB / HSV / HSL

Je kunt kleuren definiëren met verschillende kleurenmodellen. Naast
http://en.wikipedia.org/wiki/nl:RGB-kleursysteem[RGB] ondersteunt GeoGebra ook de kleurenmodellen
http://en.wikipedia.org/wiki/nl:HSV_(kleurruimte)[HSV] en http://en.wikipedia.org/wiki/nl:HSL_(kleurruimte)[HSL], die je
kunt selecteren in de drop-downlijst van het onderdeel _Dynamische Kleuren_ in de tab _Geavanceerd_ van het
_Eigenschappenvenster_ .

[EXAMPLE]
====

Om het punt _A_ alle mogelijke kleuren van de regenboog te geven, selecteer het kleurenmodel _HSV_, geef _Verzadiging_
en _Waarde_ de waarde 1, en _Nuancering_ `++x(A)++`.

====
