= Eporteer naar LaTeX (PGF, PSTricks) en Asymptote
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

/Sjabloon:Publishing.adoc[Sjabloon:Publishing]

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] When the dynamic construction depends on a slider, this menu item allows you
to save the xref:/s_index_php?title=Graphics_View_action=edit_redlink=1.adoc[Graphics View] as an
https://en.wikipedia.org/wiki/Animated_GIF#Animated_GIF[Animated GIF]. Just drag a selection rectangle around the
portion of the construction you need to export (or resize the GeoGebra window), then select File -> Export -> Graphics
View as Animated GIF. A dialog will let you choose the animating slider name, as well as the timing between frames and
the option to display the animation as loop.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] This menu item allows you to save the Graphics View as a
http://tug.org/PSTricks/main.cgi/[PSTricks] picture file, which is a xref:/LaTeX.adoc[LaTeX] picture format.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] This menu item allows you to save the Graphics View as a
http://sourceforge.net/projects/pgf/[PGF] picture file, which is a xref:/LaTeX.adoc[LaTeX] picture format.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] This menu item allows you to save the Graphics View as a
http://asymptote.sourceforge.net/[Asymptote] picture file.

== Limits of these export functions

Apart from Animated GIF export, these exports work only for the 2D View and the following object types can't be exported

* implicit curves
* loci
