= Exporteer uitleg bij tekenvenster
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Je opent dit dialoogvenster via het submenu _Exporteren_ van het menu xref:/Bestandsmenu.adoc[Bestand]. Selecteer
_Tekenvenster als afbeelding (png, eps)….)_ en kies het gewenste beeldformaat: png, pdf, eps, svg en emf. Sneltoets:
/Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (Mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Via dit dialoogvenster kan je het xref:/Tekenvenster.adoc[Tekenvenster] als een afbeelding bewaren op je computer. In
het dialoogvenster kan je de afbeeldingsformaat kiezen, de schaal (in cm) en de resolutie (in dpi) van de afbeelding
vastleggen en al dan niet de optie _Transparant' aanvinken._

[NOTE]
====

Je kunt punten Export_1 en Export_2 creëren om de rechthoek te bepalen die geëxporteerd wordt, anders wordt het getoonde
Tekenvenster geëxporteerd.

====

Bij het exporteren van het xref:/Tekenvenster.adoc[Tekenvenster] als een afbeelding, kan je kiezen uit verschillende
formaten:

PNG – https://en.wikipedia.org/wiki/nl:Portable_Network_Graphics[Portable Network Graphics]::
  Dit is een pixel-grafisch formaat. Hoe hoger de resolutie (dpi), hoe hoger de kwaliteit (300 dpi volstaat meestal).
  PNG afbeeldingen herschaal je best niet om kwaliteitsverlies te voorkomen.
  PNG zijn heel geschikt voor gebruik op webpagina's (HTML) en in tekstverwerkers.

[NOTE]
====

Wanneer je een PNG bestand in een tekstverwerkingsbestand plakt, zorg er dan voor dan je de afmeting instelt op 100 %.
Anders wordt de gegeven schaal (in cm) veranderd.

====

EPS – https://en.wikipedia.org/wiki/nl:Encapsulated_PostScript[Encapsulated Postscript]::
  Is een vector-graphisch formaat. EPS afbeeldingen kan je herschalen zonder kwaliteitsverlies. EPS afbeeldingen zijn
  heel geschikt om te gebruiken in vector graphische programma's (b. v. Corel Draw) of xref:/LaTeX.adoc[LaTeX]-teksten.
  De resolutie van een EPS is altijd 72dpi. Deze waarde wordt enkel gebruikt om de ware afmeting van een afbeelding in
  centimeters te berekenen en heeft geen effect op de kwaliteit van de afbeelding.

[NOTE]
====

De optie _Transparant_ is niet mogelijk in EPS voor ingekleurde veelhoeken en kegelsnedes.

====

PDF – https://en.wikipedia.org/wiki/nl:Portable_Document_Format[Portable Document Format]::
  (zie EPS formaat hierboven)

[NOTE]
====

Bij SVG en PDF export bestaat de optie om teksten te exporteren als wijzigbare tekten of vormen. Hierbij wordt de tekst
opgeslagen als tekst of als Bézier curven.

====

SVG – https://en.wikipedia.org/wiki/nl:Scalable_Vector_Graphics[Scalable_Vector_Graphics]::
  (zie EPS formaat hierboven)

EMF – https://en.wikipedia.org/wiki/Windows_Metafile[Enhanced Metafile]::
  (zie EPS formaat hierboven)
