= Exporteer naar LaTeX (PGF, PSTricks) en Asymptote
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

/Sjabloon:Publishing.adoc[Sjabloon:Publishing]

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] Wanneer de dynamische constructie afhangt van een schuifknop, kan je met dit
menu-item het xref:/Tekenvenster.adoc[Tekenvenster] bewaren als een
https://en.wikipedia.org/wiki/nl:Graphics_Interchange_Format#Animated_GIF[Animated GIF]. Sleep een selectierechthoek
rond het deel van de constructie dat je wil exporteren (of pas het scherm aan). Selecteer dan Bestand -> Exporteren ->
Tekenvenster als Animated GIF. In een dialoogvenster kan je de naam van de schuifknop, de tijdsduur tussen de
verschillende schermen en de optie om de animatie in een herhaling te tonen.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] Met dit menu-item kan je het tekenvenster opslaan als een
http://tug.org/PSTricks/main.cgi/[PSTricks] afbeelding, wat een xref:/LaTeX.adoc[LaTeX] afbeeldingenformaat is.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] Met dit menu-item kan je het tekenvenster opslaan als een
http://sourceforge.net/projects/pgf/[PGF] afbeelding, wat een xref:/LaTeX.adoc[LaTeX] afbeeldingenformaat is.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] Met dit menu-item kan je het tekenvenster opslaan als een
http://asymptote.sourceforge.net/[Asymptote] afbeelding.

== Beperkingen aan deze exportfuncties

Behalve het exporteren als Animated GIF, werkt het exporteren enkel voor het 2D Tekenvenster. Bovendien kan je volgende
types niet exporteren:

* impliciete krommen
* meetkundige plaatsen
