= Helpmenu
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

[NOTE]
====

De volgende 4 menu-items werken enkel indien je computer toegang heeft tot het internet. Wanneer je geen
internetverbinding hebt, kan je de /Sjabloon:Pdflink.adoc[Sjabloon:Pdflink] downloaden. In plaats van handleidingen te
lezen, kan je ook de http://www.geogebra.org/cms/nl/help[Instuctiehandleiding] downloaden.

====

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] Met dit menu-item open je de HTML-versie van de GeoGebra help (de
xref:/Hoofdpagina.adoc[Handleiding] in de GeoGebraWiki) in je internetbrowser.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] Met dit menu-item open je de
http://wiki.geogebra.org/en/Tutorial:Main_Page[Instructiehandleiding] van de GeoGebraWiki in je internetbrowser.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] Dit menu opent http://www.geogebra.org/forum[GeoGebra Gebruikersforum] in je
webbrowser. Je kunt er vragen en problemen posten en beantwoorden

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem] Dit menu opent een dialoogvenster met informatie over de huidige versie van
GeoGebra, licentievoorwaarden, een lijst van personen die het Geogebra-project dragen (ontwikkelaars, vertalers,
enz...).
