= Installatiehandleiding
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Wanneer je van plan bent om GeoGebra te installeren op meerdere toestellen, ben je misschien geïnteresseerd in
xref:/GeoGebra_massa_installatie.adoc[GeoGebra massa installatie]

== Windows

Je kunt GeoGebra voor Windows op twee manieren installeren:

* http://www.geogebra.org/download/index.php?os=win[GeoGebra Installer for Windows] (aanbevolen)
* http://www.geogebra.org/download/index.php?os=win&portable=true[GeoGebra Portable for Windows] (draait b.v. van op een
USB geheugenstick)

Noteer dat de Installer automatisch zal updaten naar nieuwere versies.

== MacOS X

GeoGebra voor Mac OS X wordt op twee manieren aangeboden:

* https://itunes.apple.com/us/app/geogebra/id845142834[GeoGebra in the Mac App Store] (aanbevolen)
* http://www.geogebra.org/download/index.php?os=mac[GeoGebra Portable for OSX].

Noteer dat de Mac App Store automatisch zal updaten naar nieuwere versies.

== Linux

Volgende GeoGebra Linux installers zijn beschikbaar:

* http://www.geogebra.org/download/deb.php?arch=amd64[64 bit] / http://www.geogebra.org/download/deb.php?arch=i386[32
bit] installers voor op *.deb* gebaseerde systemen (Debian, Ubuntu)
* http://www.geogebra.org/download/rpm.php?arch=amd64[64 bit] / http://www.geogebra.org/download/rpm.php?arch=i386[32
bit] installers voor op *.rpm* gebaseerde systemen (Red Hat, openSUSE)
* http://www.geogebra.org/download/index.php?os=linux&portable=true[Portable Linux] bundle voor 64 en 32 bit Linux
systemen

=== Opslag

De .deb en .rpm installers zullen automatisch de officiële GeoGebra opslag toevoegen aan het package management system
op het werkstation workstation. Dit laat een automatische update toe van GeoGebra elke keer er een nieuwe versie wordt
uitgebracht. Noteer dat de portable versie niet automatisch geupdated wordt.

Wanneer je GeoGebra wil opnemen in je eigen Linux verdeling, kan je best de officiële GeoGebra
opslag(http://www.geogebra.net/linux/) toevoegen aan je package management system. De GPG sleutel vind je op
http://www.geogebra.net/linux/office@geogebra.org.gpg.key. De naam van het pakket is *geogebra5* terwijl vorige versies
(4.0, 4.2 and 4.4) *geogebra* heten (en *geogebra44* voor 4.4) en eerst moeten verwijderd worden.

== Alle versies

[cols=",,,",options="header",]
|===
|Versie |Windows |Mac OS X |Linux
|4.4 |http://www.geogebra.org/download/index.php?os=win&ver=4.4[Installer]
http://www.geogebra.org/download/index.php?os=win&ver=4.4&portable=true[Portable]
|http://www.geogebra.org/download/index.php?os=mac&ver=4.4[Portable]
|http://www.geogebra.org/download/index.php?os=linux&ver=4.4&portable=true[Portable]

|5.0 |http://www.geogebra.org/download/index.php?os=win&ver=5.0[Installer]
http://www.geogebra.org/download/index.php?os=win&ver=5.0&portable=true[Portable]
|http://www.geogebra.org/download/index.php?os=mac&ver=5.0[Portable]
|http://www.geogebra.org/download/index.php?os=linux&ver=5.0&portable=true[Portable]

|recentste |http://www.geogebra.org/download/index.php?os=win[Installer]
http://www.geogebra.org/download/index.php?os=win&portable=true[Portable]
|http://www.geogebra.org/download/index.php?os=mac[Portable]
|http://www.geogebra.org/download/index.php?os=linux&portable=true[Portable]
|===

== Ondersteunde platformen en Probleemoplossing

Controleer de link:https://www.geogebra.org/m/pfmrng8g#material/ndsjjrv9[de FAQ]
voor meer informatie en ga naar https://reddit.com/r/geogebra[het forum] voor ondersteuning.
