= Meetkundige Objecten
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

== Types van Meetkundige objecten

GeoGebra works with many types of geometric objects

* xref:/Punten_en_Vectoren.adoc[Punten en Vectoren]
* xref:/Rechten_en_assen.adoc[Rechten en assen]
* xref:/Kegelsneden.adoc[Kegelsneden]
* xref:/Functies.adoc[Functies]
* xref:/Krommen.adoc[Krommen]
* xref:/Ongelijkheden.adoc[Ongelijkheden]
* xref:/Intervallen.adoc[Intervallen]
== Paden

Lijsten met punten, meetkundige plaatsen en sommige van de hierboven vermelde objecten (rechten, kegelsneden, bogen,
veelhoeken, functies, ongelijkheden in een variabele, intervallen) worden beschouwd als _paden_. Met het commando
xref:/commands/Punt.adoc[Punt] kan je een punt definiëren op een pad. Elk punt op een pad heeft een pad-parameter, dit
is een getal tussen 0 en 1. Deze parameter vind je met het commando xref:/commands/PadParameter.adoc[PadParameter].

[NOTE]
====

xref:/Lijsten.adoc[Lijsten] van andere paden zijn ook paden.

====

== Regio's

Je kunt een punt ook bepalen binnen een _regio_ (veelhoek, kegelsnede, boog, ongelijkheid met twee variabelen) met het
commando xref:/commands/Puntbinnen.adoc[Puntbinnen] of de knop xref:/tools/Punt_op_object.adoc[Punt op object].

[NOTE]
====

Zie ook de knop xref:/tools/Vasthechten_Losmaken_van_punt.adoc[Vasthechten / Losmaken van punt Macro].

====
