= Menu bewerken
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Hiermee kan je stap voor stap voorbije acties ongedaan maken.

[NOTE]
====

Je kunt ook de knop rechts van de xref:/Gereedschappenbalk.adoc[Knoppenbalk] gebruiken.

====

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Hiermee kan je stap voor stap voorbije acties opnieuw maken.

[NOTE]
====

Je kunt ook de knop rechts van de xref:/Gereedschappenbalk.adoc[Knoppenbalk] gebruiken.

====

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Kopieert de geselecteerde objecten naar het interne klembord van GeoGebra's.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Plakt de objecten in het interne klembord van GeoGebra in het actieve Tekenvenster. Klik met de muis op de plaats waar
je wil plakken (Wanneer je je muis in de nabijheid van een bestaand beweegt, zullen de objecten aan dit punt aangehecht
worden).

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Hiermee open je het xref:/Eigenschappen_dialoogvenster.adoc[Eigenschappenvenster] waarin je de eigenschappen kunt
wijzigen van alle objecten in het GeoGebra bestand.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Hiermee selecteer je alle gecreëerde objecten in het GeoGebra bestand.

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Hiermee selecteer je alle gecreëerde objecten in dezelfde laag van het GeoGebra bestand als het geselecteerde object.

[NOTE]
====

Selecteer een object op de gewenste laag voor je dit menu-item gebruikt.

====

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Hiermee selecteer je alle objecten die afhangen van het geselecteerde object.

[NOTE]
====

Selecteer eerst een object voor je dit menu-item gebruikt.

====

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Hiermee selecteer je alle objecten waarvan een geselecteerd object afhangt.

[NOTE]
====

Selecteer eerst een object voor je dit menu-item gebruikt.

====

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Maakt de selectie van geselecteerde objecten ongedaan en selecteert alle niet-geselecteerde objecten.
/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Keert het tonen of verbergen van de geselecteerde objecten om. /Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Keert het tonen of verbergen van de labels van de geselecteerde objecten om. /Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsencombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] (mac OS: /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode])

Hiermee kopieer je het xref:/Tekenvenster.adoc[Tekenvenster] naar het klembord van je computer. Hierna kan je het in
andere documenten plakken (b. v. een tekstverwerkingsdocument).

/Sjabloon:Menuitem.adoc[Sjabloon:Menuitem]

Toetsen /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode]

Hiermee verwijder je geseleteerde objecten en de objecten die ervan afhankelijk zijn.

[NOTE]
====

Selecteer eerst een of meerdere objecten (b. v. gebruik een selectierechthoek).

====
