= Objecten benoemen
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Bij het creëren van objecten via het xref:/Invoerveld.adoc[Invoerveld] kan je objecten benoemen:

* xref:/Punten_en_Vectoren.adoc[Punten]: In GeoGebra wordt de naam van punten steeds met een hoofdletter geschreven. Typ
in het xref:/Invoerveld.adoc[Invoerveld] de naam (b. v. A, P) en een gelijkheidsteken voor de coördinaten of commando's.

[EXAMPLE]
====

`++C = (2, 4)++`, `++ P = (1; 180°)++`

====

* xref:/Punten_en_Vectoren.adoc[Vectoren]: Om vectoren te onderscheiden van punten, schrijf je hun naam met een kleine
letter. Typ in het xref:/Invoerveld.adoc[Invoerveld] de naam (b. v. u, v) en een gelijkheidsteken voor de coördinaten of
commando's.

[EXAMPLE]
====

`++v = (1, 3)++`, `++ u = (3; 90°)++`

====

* xref:/Rechten_en_assen.adoc[Rechten], cirkels, en xref:/Kegelsneden.adoc[kegelsneden]: Deze objecten kan je benoemen
door achter hun naam een dubbelpunt te typen.

[EXAMPLE]
====

`++g: y = x + 3++`, `++c: (x-1)^2 + (y – 2)^2 = 4++`, `++hyp: x^2 – y^2 = 2++`

====

* xref:/Functies.adoc[Functies]: Functies benoem je als volgt: `++f(x) =++` or `++g(x)=++` voor de vergelijking of
commando's.

[EXAMPLE]
====

`++h(x) = 2 x + 4++`, `++q(x) = x^2, gon(x) = sin(x)++`

====

[NOTE]
====

* Wanneer je zelf geen naam geeft aan objecten, dan zal GeoGebra nieuwe objecten benoemen in alfabetische volgorde.
* Je kan bij het geven van een naam ook gebruik maken van indexen. Zo typ je A~1~ als `++A_1++` en s~AB~ als
`++s_{AB}++`.

====

== Gereserveerde labels

Volgende labels kan je niet gebruiken voor objecten: x, y, z, xAs, yAs, zAs, abs, sgn, sqrt, exp, log, ln, ld, lg, cos,
sin, tan, acos, arcos, arccos, asin, arcsin, atan, arctan, cosh, sinh, tanh, acosh, arcosh, arccosh, asinh, arcsinh,
atanh, arctanh, atan2, erf, floor, ceil, round, random, conjugate, arg, gamma, gammaRegularized, beta, betaRegularized,
sec, csc, cosec, cot, sech, csch, coth

In de lijst met symbolen van het Invoerveld vind je speciale karakters voor volgende constanten:

* π - pi, wat je ook kunt typen als /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode]
* ℯ - het getal van Euler, b.v. voor de exponentiële functie ℯ^x, wat je ook kunt typen als
/Sjabloon:KeyCode.adoc[Sjabloon:KeyCode]
* ί - de imaginaire eenheid, b.v. voor complexe getallen als z = 3 + ί, wat je ook kunt typen als
/Sjabloon:KeyCode.adoc[Sjabloon:KeyCode]

Wanneer e en i nog niet werden toegekend als namen voor objecten, worden ze automatisch gelezen als ℯ en ί .

== Objecten hernoemen

De gemakkelijkste manier om een object te hernoemen is er op te klikken en onmiddellijk zijn nieuwe naam te typen.

Je kunt een object ook hernoemen door rechts te klikken op het object en _Naam wijzigen_ te selecteren in het
contextmenu of door het xref:/Eigenschappen_dialoogvenster.adoc[Eigenschappenvenster] van het object te openen en de
nieuwe naam te typen in het tekstvak _Naam_ in de tab _Basis_.

[NOTE]
====

* Scripts met objecten waarvan je de naam wordt verandert, moet je nadien manueel aanpassen. De naamsverandering wordt
niet automatisch doorgevoerd in het script.
* Wanneer je aan en object een naam toekent die reeds in gebruik was, dan wordt de naam van dit eerste object
automatisch aangepast. Wanneer je b.v. de naam van een punt _B_ verandert in _A_ terwijl een punt A al bestond, krijgt
het eerdere punt als nieuwe naam _A_1_.

====

Zie ook xref:/Labels_en_titels.adoc[Labels en titels].
