= Ongelijkheden
:page-en: Inequalities
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

GeoGebra ondersteunt ongelijkheden in een of twee variabelen. Er zijn geen beperkingen voor ongelijkheden in het
xref:/Algebra_venster.adoc[Algebra venster], maar in het xref:/Tekenvenster.adoc[Tekenvenster] kan je slechts specifieke
ongelijkheden tekenen:

* veeltermongelijkheden in een variabele, b.v. _x^3 > x + 1_ of _y^2>y_,
* kwadratische ongelijkheden in twee variabelen, b.v. _x^2 + y^2 + x*y ≤ 4_,
* lineaire ongelijkheden in een variabele, b.v. _2x > sin(y)_ of _y < sqrt(x)_.

Je kunt volgende ongelijheidstekens gebruiken: <, >, ≤, ≥. Ook de symbolen <= en => gelden. Je kunt ook ongelijkheden
tekenen met ingebouwde _EN_- en _OF_- voorwaarden, b.v. _(x>y)&&(x+y<3)_.

Ongelijkheden zijn gelijkaardig aan functies. Je kunt testen of _x_ en _y_ voldoen aan de ongelijkheid _a_ door _a(x,y)_
in het xref:/Invoerveld.adoc[Invoerveld], te typen. Voor een punt _A_ is ook de syntax _a(A)_ geldig. Je kunt een punt
beperken tot de regio van de ongelijkheid met het commando xref:/commands/Puntbinnen.adoc[Puntbinnen]. Voor een
ongelijkheid _b_ in een variabele, b.v. in _x_, beperkt Punt[b] het punt tot dat deel van de x-as dat voldoet aan de
ongelijkheid _b_.
