= Opties afdrukken
:page-en: Printing_Options
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

xref:/Sjabloon__Publishing.adoc[Sjabloon:Publishing]

== het Tekenvenster afdrukken

Je kunt het xref:/Tekenvenster.adoc[Tekenvenster] van GeoGebra afdrukken. Je vindt het item _Afdrukvoorbeeld_ in het
menu xref:/Bestandsmenu.adoc[Bestand]. In het dialoogvenster _Afdrukvoorbeeld_ kan je Titel, Auteur en Datum invullen.
Je kunt ook de schaal van je afdruk instellen (in cm) en de afdrukstand wijzigen (Staand of Liggend).

[NOTE]
====

Klik op xref:/Sjabloon__KeyCode.adoc[Sjabloon:KeyCode] om na aangebrachte wijzigingen het afdrukvoorbeeld te updaten.

====

== Het Constructie-overzicht afdrukken

Je moet in het menu xref:/Beeld_Menu.adoc[Beeld] het xref:/Constructie_Protocol.adoc[Constructie-overzicht] eerst
openen (en activeren) om het te kunnen afdrukken. Selecteer daarna _Afdrukvoorbeeld_.

Voor het afdrukken kan je in het dialoogvenster _Afdrukken_ de Auteur vermelden, de papiermarges en oriëntatie wijzigen.

[NOTE]
====

Je kunt de verschillende kolommen (Naam, Definitie, Commando, Algebra en Stoppunt) aan- of uitvinken in de eerste knop
van de knoppenbalk van het Constructie-overzicht.

====
