= Regressie
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Je kunt met GeoGebra op verschillende manieren aan regressie analyse doen:

== Scherm Data analyse

Selecteer twee kolommen met gekoppelde cijfergegevens in het xref:/Rekenblad.adoc[Rekenblad] en klik op de knop
_Regressieanalyse_ in de _Opmaakwerkbalk_. In een dialoogvenster zie je de grafiek en de statistische regressieanalyse
van de gegevens. Het dialoogvenster heeft vier deelschermen: een statistisch scherm, een datascherm en twee grafische
schermen. Het tweede scherm kan je openen via het menu opties.

Het dialoogvenster opent met een puntenplot van de gegevens. In het drop-down menu onder de grafiek kan je verschillende
regressiemodellen kiezen. Het gekozen model wordt getekend en onderaan zie je de bijhorende vergelijking.

== Regressiecommando's

In de commando's van GeoGebra zijn verschillende regressiemodellen ingebouwd:

Het functioneel verband tussen punten die (ongeveer) op een rechte liggen, doe je met het commando _Regressielijn[
<Lijst met punten> ]_

Regressielijn[ <Lijst met punten> ]

Geeft de vergelijking van de lineaire regressierechte (y in functie van x) van de punten.

Kan je het verband tussen punten die benaderen door een veelterm, dan kan je de volgende commando's gebruiken

[EXAMPLE]
====

`++Regressielijn[{(-2, 1), (1, 2), (2, 4), (4, 3), (5, 4)}]++` geeft _0.4x + 2_.

====

_VeeltermRegr[ <Lijst met punten>, <Graad van veelterm> ]_ of _Veeltermfunctie[ <Lijst met punten> ]_.

VeeltermRegr[ <Lijst met punten>, <Graad van veelterm> ]::
  Berekent de regressieveelterm van graad _n_.
Veeltermfunctie[ <Lijst met punten> ]::
  Berekent de veeltermfunctie waarvan de grafiek een goede functiebenadering is voor de gegeven punten.

[EXAMPLE]
====

`++Veeltermfunctie[(-1, -1), (0, 1), (1, 1), (2, 5)]++` geeft _f(x) = x^3^ - x^2^ + 1_.

====

[EXAMPLE]
====

`++VeeltermRegr[{(-1, -1), (0, 1), (1, 1), (2, 5)}, 3]++` geeft _f(x) = x^3^ - x^2^ + 1_.

====

Andere regressiemodellen zijn PassendeGroei[ <Lijst met punten> ] voor exponentiële groeimodellen van de vorm a. b^x en
SinRegr[ <Lijst met punten> ] voor sinusoïdale schommelingen.

Zie ook de commando's xref:/commands/Regressielijn.adoc[Regressielijn],
xref:/commands/VeeltermRegr.adoc[Veeltermregressie], xref:/commands/PassendeGroei.adoc[Passende Groei],
xref:/commands/SinRegr.adoc[Sinusregressie], xref:/commands/Vrijevormkromme.adoc[Vrijevormkromme].
