= Tooltips
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Tooltips zijn teksten die verschijnen naast je muisaanwijze wanneer je hem over een object in het
xref:/Tekenvenster.adoc[Tekenvensterbeweegt]. In de tab _Geavanceerd_ van het
xref:/Eigenschappen_dialoogvenster.adoc[Eigenschappenvenster] kan je vijf types van tooltip kiezen:

Automatisch::
  Tooltips worden enkel getoond als het xref:/Algebra_venster.adoc[Algebra venster] actief is. Tooltips bevatten het
  objecttype en de naam ; bij xref:/Vrije_afhankelijke_en_hulpobjecten.adoc[afhankelijke objecten] bevat de tooltip ook
  de beschrijving van het object.
Aan::
  Tooltips worden altijd getoond, of het Algebra venster nu getoond wordt of niet. De inhoud is hetzelfde als bij
  _Automatisch_.
UIt::
  Tooltips worden niet getoond.
Titel::
  De xref:/Labels_en_titels.adoc[TItel] van het object wordt gebruikt als tooltip. Je kunt de Titel bepalen in het tab
  _Basis_ van het _Eigenschappenvenster_.
Volgende cel::
  Wanneer het object een cel is van het xref:/Rekenblad.adoc[Rekenblad], wordt de volgende cel gebruikt als tooltip.

In de tab _Geavanceerd_ van het dialoogvenster xref:/Opties_uitleg.adoc[Opties] kan je de taal en een timeout kieze voor
tooltips.
