= 대상 이름 붙이기
:page-en: Naming_Objects
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

입력창에서 개체를 생성할 때 개체에 특정 이름을 지정할 수 있습니다.

* 점 : 지오지브라에서는 점의 이름은 항상 대문자로 지정됩니다.(예: A, P) 점에 특정 이름을 넣기 위해서는
`++이름 = 좌표++`로 입력하시면 됩니다. [.example]##
+
[EXAMPLE]
+
====
+
*예 :* `++A = (2, 4) ++`, `++P = (1, 180°)++`
+
====
* 벡터 : 점과 벡터를 구별하기 위해 벡터는 소문자 이름을 가져야 합니다.(예: v, u) 점과 같이 좌표나 명령어 앞에 이름과
함께 등호를 입력하시면 됩니다.`++이름 = 좌표/명령어++` [.example]##
+
[EXAMPLE]
+
====
+
*예 :* `++v = (1, 3)++`, `++u = (3, 90°)++`
+
====
* 선, 원 및 원뿔형 단면 : 이 개체의 이름은 콜론(:)을 방정식이나 명령어 앞에 입력하여 이름을 지정할 수 있습니다.
[.example]##
+
[EXAMPLE]
+
====
+
*예 :* g : y = x + 3, `++c : (x-1)^2 + (y-2)^2 = 4++`, `++hyp : x^2 - y^2 = 2++`
+
====
* 함수 : 함수의 이름을 입력하여 함수의 이름을 지정할 수 있습니다. [.example]##
+
[EXAMPLE]
+
====
+
*예 :* `++f(x) = 2x + 4++`, `++g(x) = x^2++`, `++trig(x) = sin(x)++`
+
====
+
[NOTE]
====

*노트 :*

** 개체에 수동으로 이름을 지정하지 않으면 지오지브라는 새 개체의 이름을 사전 순으로 할당합니다.
** 밑줄을 사용하여 개체 이름 내에 인덱스(아래첨자)를 만들 수 있습니다. 예를 들어, A~1~를 만들기 위해서는 `++A_1++`를
입력하고, S~AB~를 만들기 위해 `++S_{AB}++`를 입력창에 입력합니다.

====

== 사용할 수 없는 레이블

개체에 사용할 수 없는 레이블(이름)들은 다음과 같습니다. : x, y, z, xAxis, yAxis, zAxis, abs, sgn, sqrt, exp, log, ln,
ld, lg, cos, sin, tan, acos, arcos, arccos, asin, arcsin, atan, arctan, cosh, sinh, tanh, acosh, arcosh, arccosh, asinh,
arcsinh, atanh, arctanh, atan2, erf, floor, ceil, round, random, conjugate, arg, gamma, gammaRegularized, beta,
betaRegularized, sec, csc, cosec, cot, sech, csch, coth

_입력창의_ 기호 목록을 보면 다음 상수에 대한 특수 문자를 찾을 수 있습니다.

* *π* - 원주율 상수 pi. [.kcode]##Alt##+[.kcode]##p##로도 입력할 수 있습니다.
* *ℯ* - Euler 수. 지수 함수 ℯ^x의 경우 [.kcode]##Alt##+[.kcode]##e##로도 입력할 수 있습니다.
* *ί* - z = 3 + ί 와 같은 복소수의 허수 단위. [.kcode]##Alt##+[.kcode]##i##로도 입력할 수 있습니다.

변수 이름으로 e와 i가 아직 사용되지 않았다면, 입력창에 입력되는 e와 i는 자동으로 ℯ(Euler 수)와 ί(허수 단위)로 읽힙니다.

== 개체 이름 바꾸기

기존 개체의 이름을 변경하는 가장 쉬운 방법은 개체를 선택하고 새 개체의 이름을 입력하는 것입니다.

또한 마우스 오른쪽 클릭하여 나오는 메뉴에서 "이름 바꾸기" 옵션을 선택하거나 개체의 설정사항을 열고 기본 탭에서 이름 입력
필드에 새 이름을 입력하여 개체의 이름을 바꿀 수 있습니다.

[NOTE]
====

*노트 :*

* 개체가 다른 개체를 종속하는 있는 경우, 종속성 문제는 대개 자동으로 해결됩니다. 예를 들어, B가 A에 종속된 경우, A의
이름이 C로 변경된다면 B는 자동적으로 C에 종속되기 바뀝니다. 하지만, 스크립팅에서 지정된 개체의 이름을 변경한 경우
수동으로 변경해야 합니다.
* 이미 다른 개체에서 사용 중인 이름을 또 사용한 경우 기본 개체의 이름이 변경됩니다. 예를 들어, B의 이름을 A로 변경하고
점 A가 이미 있는 경우 기존의 점 A는 A~1~로 변경됩니다.

====

http://wiki.geogebra.org/ko/%EB%A0%88%EC%9D%B4%EB%B8%94%EA%B3%BC_%EC%BA%A1%EC%85%98[레이블과 캡션]을 참고하여 더 공부해
보세요.
