= 도구
:page-en: Tools
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

도구를 활용하면 새로운 대상을 만들 수 있다. 모든 도구는 같은 기능을 가지는 xref:/명령.adoc[명령]을 갖고 있으며, 명령을
사용하면 도구로 하는 것보다 복잡한 설정을 할 수 있다.

구성 도구나 모드는 xref:/도구바.adoc[도구 상자]의 버튼을 클릭하면 사용가능하다. 비슷한 도구들이 담겨있는 도구상자를
열려면, 아이콘의 오른쪽 아래에 있는 역삼각형을 클릭한다. xref:/도구_메뉴.adoc[도구 메뉴]를 사용해도 도구를 선택할 수
있다.

기본적으로 12개의 도구상자가 순서대로 나열된다.

* xref:/tools/이동.adoc[이동 도구]
* xref:/tools/점.adoc[점 도구]
* xref:/tools/직선.adoc[직선 도구]
* xref:/tools/기타_직선.adoc[특별한 선 도구]
* xref:/tools/다각형.adoc[다각형 도구]
* xref:/tools/원과_호.adoc[원과 호 도구]
* xref:/tools/원뿔곡선(이차곡선).adoc[원뿔곡선(이차곡선) 도구]
* xref:/tools/측정.adoc[측정 도구]
* xref:/tools/변환.adoc[변환 도구]
* xref:/tools/기타_대상.adoc[특별한 대상 도구]
* xref:/tools/움직이는_대상.adoc[상호작용 대상 도구]
* xref:/tools/일반.adoc[일반 도구]
* xref:/tools/사용자_설정.adoc[사용자 설정 도구]

도구 상자의 순서를 바꿀 수 있으며, /s_index_php?title=Reference:File_Format_action=edit_redlink=1.adoc[지오지브라
워크시트 (*.ggb)] 에 저장할 수 있다. 자세한 사항은 xref:/도구바.adoc[도구 상자 사용자 설정] 을 참고하라.

[NOTE]
====

대부분의 도구를 사용할 때, 기하창의 빈 공간을 클릭하면 점을 만들 수 있다.

====

xref:/CAS_창.adoc[CAS 창] 과 xref:/스프레드시트_창.adoc[스프레드시트 창] 에서는 xref:/tools/CAS.adoc[CAS 도구] 와
xref:/tools/스프레드시트.adoc[스프레드시트 도구] 가 각각 나타난다.
