= 도구바
:page-en: Toolbar
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

도구상자는 xref:/메뉴바.adoc[메뉴] 아래에 위치하고 있다. 개별적인 xref:/보기.adoc[창]들은 각각의 도구를 상단에 가지고
있다. 도구바는 개별적인 도구상자를 포함하고 있으며, 각각의 도구상자는 여러 xref:/도구.adoc[도구]를 담고 있다.
xref:/보기_메뉴.adoc[보기 메뉴]의 "레이아웃..."에서 도구상자의 위치를 변경할 수 있다.

== 도구 도움말

xref:/보기_메뉴.adoc[보기 메뉴]의 "레이아웃..."에서 도구 도움말을 보이거나 보이지 않도록 할 수 있다. 일반적으로 도구
도움말은 도구상자의 오른편에 위치하며, 현재 선택된 도구의 사용법이 나타난다. 기본적으로 마우스를 선택된 도구 위에 놓으면
도구의 사용법이 나타난다.

== 다른 창에서의 도구상자

지오지브라는 xref:/기하창.adoc[기하창], xref:/스프레드시트_창.adoc[스프레드시트 창], xref:/CAS_창.adoc[CAS 창]의
도구상자가 있다. 지오지브라에서 다른 xref:/보기.adoc[창]을 실행하면, 도구상자가 자동으로 변경된다. 예를 들어,
스프레드시트 창이나 CAS 창을 열면, 그에 따른 도구상자가 나타난다.

== 도구상자 사용자 설정

xref:/도구_메뉴.adoc[도구 메뉴]에서 __도구상자 사용자 설정…__을 선택하면 도구상자를 원하는 대로 설정할 수 있다. 드롭다운
리스트에서 도구상자를 선택하여 편집할 수 있다. 도구상자에서 도구를 제거하려면, 나타나는 대화상자의 왼편에서 해당 도구를
선택한 후, "제거" 버튼을 클릭한다. 도구를 포함시키려면, 오른 편의 리스트에서 선택한다. 새 도구상자에 도구를 추가하려면,
왼편에서 도구상자를 선택하고, "추가" 버튼을 클릭한다. 도구를 기존의 도구상자에 추가하려면, 왼편의 도구상자를 열고,
원하는 도구를 선택한다. 도구를 다른 도구상자로 이동시키려면, 도구를 제거하고 다시 추가해야 한다.

[NOTE]
====

화면 왼편 아래에 있는 "기본 도구상자로 되돌리기" 버튼을 클릭하여 도구상자를 기본설정으로 되돌릴 수 있다.

====

xref:/워크시트_대화상자_내보내기.adoc[상호작용이 가능한 워크시트] 에서 도구상자를 보이거나 감추는 것은
/s_index_php?title=Reference:Applet_Parameters_action=edit_redlink=1.adoc[도구상자 사용자설정] 변수로 설정된다.
