= 레이블과 캡션
:page-en: Labels_and_Captions
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

지오지브라의 각 개체에는 고유한 레이블(라벨/이름표/Label)이 있습니다. 하나 이상의 문자로 레이블을 붙일 수 있으며, 첨자도
붙일 수 있습니다. 자세한 내용은 http://wiki.geogebra.org/en/Naming_Objects[개체의 이름 지정]을 참조하세요.

== 레이블 표시 및 숨기기

기하창에서 개체의 레이블을 여러 가지 방법으로 보이거나 숨길 수 있습니다.

* 개체를 선택한 후 마우스 오른쪽 버튼으로 컨택스트 메뉴를 열어 "이름 보이기"를 선택하면 레이블이 표시되며, 선택을
해제하면 레이블이 숨겨집니다.(디폴트로 선택되어져 있습니다.)
* 원하는 개체의 설정사항 > 기본 탭 > 이름 보이기를 선택 혹은 선택 해제하세요.

== 이름과 값

지오지브라에서 모든 개체는 기하창에서 개체의 레이블을 지정하는데 사용할 수 있는 고유한 이름을 가집니다. 또한 개체는
값이나 이름과 값을 모두 사용하여 레이블을 지정할 수 있습니다. 개체의 설정사항 > 기본 탭 > 이름 보이기 : 오른쪽의
드롭다운 메뉴에서 이름, 이름과 값, 값, 캡션(캡션의 값은 해당 탭에서 설정할 수 있습니다. 캡션에 대한 설명은 하단에
나옵니다.)으로 레이블의 설정을 변경할 수 있습니다.

[NOTE]
====

*노트 :* 점의 값은 좌표이지만 함수의 값은 방정식입니다.

====

== 캡션

때로는 여러 개체에 동일한 레이블을 지정해야 하는 경우가 있습니다.(예: 사각형의 네 모서리에 레이블을 지정하는 경우) 이
경우, 지오지브라는 위에서 언급한 옵션 이외에도 복수의 개체에 캡션을 제공합니다. 설정사항 > 기본 탭 > 캡션 텍스트
필드에서 개체의 원하는 문자를 입력하여 캡션을 설정할 수 있습니다. 캡션 값을 설정 후, 하단의 "이름 보이기" 오른쪽의
드롭다운 메뉴에서 "캡션"을 선택하여 적용합니다.(캡션의 텍스트 필드를 입력하면 자동으로 이름 보이기 드롭다운 메뉴가
"캡션"으로 설정이 됩니다.)

캡션으로 특정한 값을 넣고 싶을 때는 다음 자릿값을 사용할 수 있습니다.

[cols=",",options="header",]
|===
|자릿값 |의미
|%c |스프레드 시트의 A1셀에 (1, 2)를 입력하고 오른쪽 셀인 B1에 "포인트"라고 입력한다. 그러면 자동적으로 기하창에 점 A1이
(1, 2)에 찍힌다. 이 때, 캡션값을 %c로 바꾸면 B1의 셀에 입력한 "포인트"라는 글자가 A1이란 이름 대신 보이게 된다. 만약
B1의 값을 변경한 후 값을 업데이트 하려면 [.kcode]##F9##이나 [.kcode]##Ctrl##+[.kcode]##R##을 누르면 된다.

|%v |값(value)

|%n |이름(name)

|%x |x좌표(또는, ax + by + cz = 0 에서의 x의 계수 a)

|%y |y좌표(또는, ax + by + cz = 0 에서의 y의 계수 b)

|%z |z좌표(또는, ax + by + cz = 0 에서의 z의 계수 c)
|===

[EXAMPLE]
====

*예 :* 기하창에서 (1, 2)에 점 A를 찍은 후, 캡션을 "점 %n은 %v 좌표를 갖는다."라고 설정해보자. 그러면 기하창에 "점 A는
(1, 2) 좌표를 갖는다."라는 캡션을 볼 수 있을 것이다.

====

== 캡션에서의 LaTeX

만약, 이름에 LaTeX 수식을 입력하기 위해서는 설정사항 > 기본> 캡션 입력 필드에서 LaTeX 수식을 두 개의 "$" 기호 사이에
입력하면 된다. 예를 들어, `++$ x^{2} $++` 와 같이 입력한 후, 이름 보이기에서 "캡션"을 선택하면
[.mathquillggb-embedded-latex]##\mathrm\{\mathsf\{ x^\{2} }}##과 같은 수식이 캡션에 나타남을 보실 수 있을 겁니다.

[EXAMPLE]
====

**예 :**만약 [.mathquillggb-embedded-latex]##\mathrm\{\mathsf\{ \frac\{a}\{b} }}##와 같은 아름다운 LaTeX 수식을 사용하기
위해서는, 캡션 입력 필드에 **`++$\frac{a}{b}$++`**와 같이 입력하면 된다.

====
