= 보이기 위한 조건
:page-en: Conditional_Visibility
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

특정 개체를 그냥 보이거나 숨기는 것 외에도 어떤 특정 조건에 따라 보이거나 숨기기 할 수 있습니다. 예를 들어, '마우스
오른쪽 버튼 > 대상보이기'를 선택하거나, '대상을 보이거나 감추기 위한 체크상자'를 이용하거나, '마우스 오른쪽 버튼 >
설정사항 > 고급기능'에서 '대상이 나타나기 위한 조건'을 설정할 수 있습니다.

==  특정 조건에 따라 숨기기 

지오지브라의 상단 아이콘 중 슬라이더 아이콘에서 더 보기를 클릭하면 '대상을 보이거나 감추기 위한 체크상자' 아이콘이
있습니다. 이 체크상자를 클릭하면 특정 개체들이 보이거나 숨겨지게 할 수 있습니다.

혹은, 슬라이더나 입력창에서 논리변수(`++a = true ++`혹은`++a = false++`)를 만든 후, 숨기기를 원하는 개체의 '설정사항 >
고급기능 > 대상이 나타나기 위한 조건'에서 `++ a ++`라고 입력하며, a의 값이 true일 경우 대상이 보이게 되고 false일 경우
숨겨지게 됩니다.

사실 체크상자도 논리변수의 하나로 볼 수 있습니다. 체크상자가 하나 만들어 지면 대수창에 논리변수가 하나 만들어 지며
체크상자를 체크한 경우가 true, 체크를 해제한 경우를 false라고 볼 수 있습니다.

==  대상이 나타내는 조건으로 변경하기 

'설정사항 > 고급기능 > 대상이 나타나기 위한 조건'에서 a가 꼭 논리변수일 필요는 없습니다. 예를 들어, 정수 a와 b
슬라이더를 이용하여 '대상을 나타나기 위한 조건'을 설정할 수 있습니다.

[EXAMPLE]
====

*예 :*

* a의 값이 1보다 이상인 경우에 대상이 보이게 하려면 - `++ a >= 1++`
* a의 값이 1인 경우 대상이 보이게 하려면 - `++ a == 1++`
* a의 값이 1이 아닌 경우 대상이 보이게 하려면 - `++ a != 1 ++`
* a의 값이 1 또는 -1인 경우 대상이 보이게 하려면 - `++ a==1 || a==-1 ++`
* a의 값이 1이고, b의 값이 2인 경우 대상이 보이게 하려면 - `++ a==1 && b==2 ++`

====

[NOTE]
====

*참고*

'보이기설정' 명령어를 통해 대상을 숨기거나 보이게 할 수 있습니다. 예를 들어, 점 A를 기하창1에서 보이게 하기 위해서는
`++보이기설정[ A , 1 , true ]++` 를 입력창에 입력합니다. 또는 점 A를 기하창2에서 보이지 않게 하기 위해서는
`++ 보이기설정[ A , 2 , false ]++`를 입력하면 됩니다.

====
