= 애니메이션
:page-en: Animation
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

==  애니메이션 

지오지브라를 사용하면 숫자/각도뿐 아니라 개체(선분, 선, 함수, 곡선 등)에 종속 된 점도 애니메이션할 수 있습니다. 자동으로
애니메이션을 적용하기 위해서는 숫자/각도를 기하창에 슬라이더로 표시해야 합니다.

지오지브라에서 숫자/각도/점 등을 애니메이션하기 위해서는 마우스 오른쪽 버튼을 클릭하한 후 나오는 컨텍스트 메뉴에서
'애니메이션 시작'을 선택합니다. 애니메이션을 멈추기 위해서는 '애니메이션 시작'의 선택을 해제하면 됩니다.

[NOTE]
====

....
   노트 :  숫자/각도/종속된 점 등에 애니메이션을 적용한 후 기하창의 왼쪽 하단 모서리를 보면 애니메이션 단추가 나타나 일시중지나 계속 재생을 선택할 수 있습니다.
....

====

설정사항 > 슬라이더 탭에서 애니메이션의 동작을 변경할 수 있습니다.

한편, 애니메이션의 속도도 제어할 수 있습니다.

[NOTE]
====

....
   노트 :  속도가 1이면 애니메이션 슬라이더 간격으로 한 번 실행될 때, 약 10초가 소요됨을 의미합니다.
....

====

애니메이션 주기가 반복되는 방식을 결정할 수도 있습니다.

⇔ 진동::
  애니메이션의 감소와 증가가 번갈아 나타납니다.
⇒ 증가::
  슬라이더 값이 항상 증가합니다. 슬라이더의 최댓값에 도달하면 다시 최솟값으로 점프하고 애니메이션을 계속합니다.
⇐ 감소::
  슬라이더 값이 항상 감소합니다. 슬라이더의 최솟값에 도달하면 최댓값으로 점프하고 다시 애니메이션을 계속합니다.
⇒ 증가(1회)::
  슬라이더 값이 증가합니다. 하지만 슬라이더가 최댓값에 도달하면 이 값에서 멈추고 애니메이션이 끝납니다.

[NOTE]
====

....
   노트 :  자동 애니메이션이 활성화 되는 동안 지오지브라의 다른 기능들은 완전히 유지됩니다. 애니메이션이 재생되는 동안 다른 지오지브라의 개체나 구성들을 자유로이 변경할 수 있습니다.
....

====

==  수동 애니메이션 

숫자, 각도, 점의 위치 등을 수동으로 변경하기 위해서는 이동도구를 선택하십시오. 그런 다음 변경할 대상을 클릭한 후
키보드의 [.kcode]#+# 또는 [.kcode]#-# 키 또는 화살표 키를 누릅니다. 이 키들 중 하나를 계혹 누르면 수동 애니메이션을
생성할 수 있습니다.

[EXAMPLE]
====

*예 :* P=(2, t, t,)와 같이 점의 좌표가 숫자 t에 의존하는 경우 t가 이동함에 따라 점 P는 직선을 따라 연속적으로 변화한다.

====

[NOTE]
====

이 개체의 설정사항의 슬라이더 탭에서 슬라이더의 증가량을 조정할 수 있습니다.

====

== 키보드 단축키

* [.kcode]##Shift##+ 화살표 키를 사용하면 한 스텝에 0.1 단위만큼 변화합니다.
* [.kcode]##Ctrl##+ 화살표 키를 사용하면 한 스텝에 10 단위만큼 변화합니다.
* [.kcode]##Alt##+ 화살표 키를 사용하면 한 스텝에 100 단위만큼 변화합니다.

[NOTE]
====

*노트 :* [.kcode]#+# 또는 [.kcode]##-##키를 사용하여 한 줄의 한 지점을 그 줄을 따라 이동할 수도 있습니다.

====
