= 움직이는 대상
:page-en: Action_Objects
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

스크립트를 이용한 반응하는 창을 만들 경우 움직이는 대상 만들기를 이용할 수 있습니다. 움직이는 대상에는 네 가지 유형이
있습니다.

== 대상을 보이거나 감추기 위한 체크 상자

체크 상자는 논리 값(boolean)을 그래픽으로 표현한 것입니다. 상단의 아이콘에서 '대상을 보이거나 감추기 위한 체크 상자'를
클릭한 후 연결을 원하는 대상을 드롭다운 목록에서 선택해보세요. 체크 상자를 선택하면 개체가 보일 것이고, 해제하면 숨겨질
것입니다.

== 입력상자

입력상자는 스크립트의 텍스트 입력으로 작동합니다. 화면 상단의 입력상자 아이콘을 클릭하여 입력 상자를 만들 수 있습니다.
입력상자 아이콘을 선택한 후 나오는 대화창에서 연결한 대상을 클릭하면 됩니다. 입력 상자의 텍스트를 변경하고 입력 상자를
선택할 때 마다 새로고침이 됩니다. 삽입된 값은 %0 변수를 사용하여 접근 제어할 수 있습니다.

[EXAMPLE]
====

*예 :* `++ a = a + %0++` 스크립트가 있는 입력상자는 숫자a를 입력된 값만큼 증가시킵니다. a가 자유로운 개체(종속되지
않은)인 경우에만 작동합니다.

====

== 버튼

버튼을 클릭하면 스크립트를 실행합니다. 스크립트는 다른 개체(예: 이미지)를 클릭하여 시작될 수 있지만 버튼을 사용하면 좀더
직관적으로 지오지브라 창을 만들 수 있습니다. 상단의 버튼 아이콘을 클릭하여 버튼을 만들 수 있습니다.

== 드롭다운 목록

목록을 드롭다운으로 보고 싶으면 다음과 같이 하면 됩니다.

* 리스트를 선택한 후 마우스 설정사항의 기본 탭에서 '드롭다운 리스트로 그리기'를 체크하면 됩니다.
* 리스트를 선택한 후 마우스로 끌어 스프레드 시트 창에 넣거나 컨텍스트 메뉴의 '스프레드 시트에 넣기'를 클릭한다. 스프레드
시트창에 기록된 리스트의 설정사항의 기본 탭에서 '드롭다운 리스트로 그리기'를 체크하면 됩니다.

선택된 드롭다운 목록은 '선택된원소[<리스트>]', 혹은 '선택된인덱스[<리스트>]' 명령어를 통해 확인할 수 있습니다.
