= Befehle
:page-en: Commands
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Mit Hilfe von Befehlen können Sie neue Objekte erzeugen und bestehende Objekte verändern. Beachten Sie die Liste, die
rechts auf dieser Seite angezeigt wird. Dort wurden alle Befehle in Bezug auf ihr Anwendungsfeld kategorisiert.
Alternativ können Sie auch die für weitere Details durchsuchen.

[NOTE]
====

Drücken Sie nach jeder Eingabe die Eingabetaste um das entsprechende Objekt zu erzeugen.

====

[NOTE]
====

Sie können das Ergebnis eines Befehls benennen, indem Sie die gewünschte Beschriftung und ein Gleichheitszeichen (=) vor
dem Befehl eingeben. Im folgenden Beispiel wird der Schnittpunkt mit S benannt.

====

[EXAMPLE]
====

Um den Schnittpunkt von zwei Geraden g und h zu erzeugen können Sie folgendes eingeben: `++S = Schnittpunkt[g, h]++`
(siehe xref:/commands/Schnittpunkt.adoc[Befehl Schnittpunkt])

====

[NOTE]
====

Sie können auch Beschriftungen mit Indizes vergeben: für A~1~ geben Sie `++A_1++` ein, S~AB~ wird durch `++S_{AB}++`
erzeugt. Diese Eingaben entsprechen der xref:/LaTeX.adoc[LaTeX Syntax].

====
