= Dynamisches Arbeitsblatt
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Mit GeoGebra können Sie aus Ihren Dateien interaktive Webseiten, so genannte dynamische Arbeitsblätter, erstellen. Nach
Auswahl der Option _Export_ im Menü Datei können Sie den Export-Dialog für Dynamische Arbeitsblätter durch Auswahl der
Option _Dynamisches Arbeitsblatt als Webseite (html)..._ öffnen.

* Im oberen Bereich des Export-Dialogs können ein _Titel_, der _Autor_ und das _Datum_ des Dynamischen Arbeitsblattes
eingegeben werden.
* Auf der Karte _Allgemein_ kann Text oberhalb und unterhalb des Applets einfügt werden (z. B. eine Beschreibung der
Konstruktion und Aufgaben für Ihre SchülerInnen). Hier können Sie auch festlegen, ob die Konstruktion direkt in die
Webseite eingebunden oder durch eine Schaltfläche geöffnet werden soll.
* Auf der Karte _Erweitert_ können Sie die Funktionalität der dynamischen Konstruktion verändern (z. B. ein Symbol zum
Zurücksetzen der Konstruktion einblenden, Doppelklick soll das Anwendungsfenster öffnen) und ihre Benutzeroberfläche
anpassen (z. B. Werkzeugleiste einblenden, Höhe und Breite des Applets verändern).

[NOTE]
====

Falls das interaktive Applet zu groß ist um auf einem Computer-Bildschirm mit Standardauflösung (1024 x 768) angezeigt
zu werden, empfehlen wir, es vor dem eigentlichen Export als dynamisches Arbeitsblatt zu verkleinern.

====

Die exportierte HTML Datei (z. B. _Kreis.html_) kann mit jedem Internet-Browser (z. B. Mozilla, Internet Explorer,
Safari) geöffnet werden. Damit das interaktive Applet auch funktioniert muss http://www.java.com[Java] auf Ihrem
Computer installiert sein. Falls Sie dynamische Arbeitsblätter in Ihrem Schulnetzwerk verwenden möchten, sollten Sie
Ihren Netzwerk-Administrator darum bitten, falls nötig Java auf den Computern zu installieren.

[NOTE]
====

Dynamische Arbeitsblätter können mit vielen Textverarbeitungsprogrammen editiert werden (z. B. FrontPage, OpenOffice
Writer) indem Sie die entsprechende HTML Datei öffnen und verändern.

====

== Erweiterte Einstellungen

*Funktionalität*:

* _Rechtsklick aktivieren_: Ermöglicht es das xref:/Kontext_Menü.adoc[Kontext-Menü] durch einen Rechtsklick auf ein
Objekt zu öffnen. Man kann außerdem xref:/Tastenkombinationen.adoc[Tastenkombinationen] verwenden.
* _Ziehen von Beschriftungen aktivieren_: Mithilfe dieser Funktion können Sie Beschriftungen von Objekten bewegen
* _Symbol zum Zurücksetzen der Konstruktion anzeigen_: Im oberen rechten Eck wird ein Zurücksetzen-Button angezeigt, um
die Konstruktion auf ihren Ausgangszustand zurückzusetzen.
* _Doppelklick öffnet Anwendungsfenster_: Mittels Doppelklick auf das Arbeitsblatt wird ein GeoGebra-Fenster geöffnet.
* _Schaltfläche zum Öffnen des Anwendungsfensters_: Mittels eines Buttons kann man ein eigenständiges GeoGebra-Fenster
öffnen.
* _Verwende Browser für JavaScript Skripten_: Dadurch wird JavaScript in Ihrem Brwoser aktiviert.

*Benutzeroberfläche*:

* _Menüleiste anzeigen_: Auf dem dynamischen Arbeitsblatt wird die Menüleiste angezeigt.
* _Speichern, Drucken und Rückgängig aktivieren_: Es ist möglich die Funktionen _speichern_, _drucken_ und _rückgängig_
bereitzustellen.
* _Werkzeugleiste anzeigen_: Auf dem dynamischen Arbeitsblatt wird die Werkzeugleiste angezeigt, um geometische
Werkzeuge verwenden zu können.
* _Hilfe für Werkzeugleiste anzeigen_: In Kombination mit der Werkzeugleiste es es auch möglich die Hilfe anzeigen zu
lassen.
* _Eingabezeile anzeigen_: Im unteren Bereich des dynamischen Arbeitsblattes wird die Eingabezeile angezeigt, um
algebraische Eingaben und Befehle zu ermöglichen.
* _Neuskalierung erlaubt_: Beeinflusst das Vergrößern und Verkleinern im Browser, so dass auch die Konstruktion
vergrößert bzw. verkleinert wird.
* _Breite und Höhe des dynamischen Arbeitsblattes_: Hier können Sie die Breite bzw. Höhe des Arbeitsblattes festlegen.

[NOTE]
====

Falls Sie die Größe des Arbeitsblattes ändern, könnten wichtige Bereiche für den Benutzer nicht sichtbar sein.

====

[NOTE]
====

Falls Sie die Menüleiste, Werkzeugleiste oder Eingabezeile anzeigen, sollten Sie die Größe des Arbeitsblattes
dementsprechend anpassen.

====

*Dateien*:

* _HTML 5 einbinden_: verwendet HTML 5 in Ihrem Arbeitsblatt
* _inklusive *.jar Dateien_: Erzeugt nicht nur eine html-datei, sondern auch alle *.jar Dateien.
* _Enfernt Zeilenumbrüche_: falls Zeilenumbrüche vorkommen, werden diese entfernt
* _Datei-Dropdown_: Sie können auswählen, ob die exportierte Datei eine html, MediaWiki, GoogleGadget oder Moodle Datei
ist.
* _Als eine Datei_: Es wird ein dynamisches Arbeitsblatt aus einer Datei erzeugt.
* _Als eine Datei (Tabs)_: Hier kann mehr als ein Arbeitsblatt im Browser angezeigt werden. Um zwischen den Aufgaben zu
navigieren, werden Tabs verwendet.
* _verlinkte Dateien_: Erzeugt verlinkte Arbeitsblätter bei denen man mittels _Nächstes_ und _Zurück_ zwischen den
Arbeitsblättern wechselt.

[NOTE]
====

Um mehrere dynamische Arbeitsblätter zu exportieren, müssen Sie mehr als eine Konstruktion erzeugen _Datei_ - _Neues
Fenster_ oder [.kcode]#Strg# + [.kcode]#N#.

====
