= Linien und Achsen
:page-en: Lines_and_Axes
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

== Linien

Linien können als eine lineare Gleichung in x und y oder in parametrischer Form in der
xref:/Eingabezeile.adoc[Eingabezeile] eingegeben werden. In beiden Fällen können Sie zuvor definierte Variablen (z.B.:
Zahlen, Punkte, Vektoren) in die Gleichung einsetzen.

[NOTE]
====

Sie können die Linie benennen, in dem Sie in der Eingabezeile vor die Gleichung den Namen, gefolgt von einem
Doppelpunkt, eingeben.

====

[EXAMPLE]
====

* Tippen Sie die lineare Gleichung `++g: 3x + 4y = 2++` ein, um die Linie g zu erhalten.
* Definieren Sie den Parameter t (z.B.: t = 3) und geben Sie danach die Linie g in parametrischer Form
`++g: X = (-5, 5) + t (4, -3)++` ein.
* Definieren Sie die Parameter k = 2 und d = -1. Danach können Sie die gewöhnliche Geradengleichung `++h: y = k*x + d++`
eintippen und erhalten eine Linie h.

====

== Achsen

Bei Befehlen sind die beiden Koordinatenachsen unten den Namen _xAchse_ und _yAchse_ abrufbar.

[EXAMPLE]
====

Der Befehl `++Senkrechte[A, xAchse]++` konstruiert eine zur _x_-Achse senkrechte Gerade durch den Punkt _A_.

====
