= Regresjonsanalyse Verktøy
:page-en: tools/Two_Variable_Regression_Analysis
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Vel to kolonnar med taldata i par frå xref:/Rekneark.adoc[reknearket] og trykk på dette verktøyet. Det vert då opna ein
dialogboks (*Datakjelde*) der du kan endre på data og velje kva data representerar. Trykk på _Analyser_ for å opne ein
ny dialogboks (*Dataanalyse*) som lagar grafar og finn to-variabel statistiske verdiar frå dataverdiane. Dialogboksen
har fire panel: eit statistikkpanel, eit datapanel og to grafpanel. Dei forskjellige panela kan verte opna og lukka
under stilmenyen som du finn under verktøymenyen.

Dialogboksen opnar med eit punktdiagram. I menyen under grafen kan du velje forskjellige regresjonsmodellar. Når ein
modell er valt vil regresjonskurva verte teikna og likninga for kurva vert vist.

Når du held musepekaren mot toppen av eit av grafpanela vil den verte endra til ei hand. Du kan då trykkje ned og halde
inne venstre musknapp og dra grafen over i xref:/Grafikkfelt.adoc[grafikkfeltet].

[NOTE]
====

*Merk:* Sjå også kommandoen xref:/commands/Reg.adoc[Reg].

====
