= Skjering mellom to objekt Verktøy
:page-en: tools/Intersect
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Verktøyet kan finne skjeringspunkt mellom to objekt på to måtar:

* Vel to objekt for å finne alle skjeringspunkt mellom dei to objekta (dersom mogleg)
* Ved å trykke direkte på eit skjeringspunkt vert kun dette eine skjeringspunktet laga.

[NOTE]
====

*Merk:* Nokre gongar kan det vere nyttig å berre vise den delen av dei to overlappande objekta som er i området rundt
eit skjeringspunkt. For å gjere det høgreklikkar du på skjeringspunktet, går til xref:/Eigenskapar.adoc[Eigenskapar] og
hukar av _Vis skjeringslinjer (kryss)_ under fana _Basis_.

====

For linjestykke, strålar og sirkelboger kan du velje om du vil tillete skjeringspunkt i forlenginga av objekta. Det gjer
du ved å huke av for _Tillat skjeringar i forlengingane_ under fana _Basis_ i xref:/Eigenskapar.adoc[dialogboks for
eigenskapar] for objektet.

[NOTE]
====

*Merk:* Sjå også kommandoen xref:/commands/Skjering.adoc[Skjering].

====
