= Vinkel Verktøy
:page-en: tools/Angle
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Ved bruk av dette verktøyet kan du lage vinklar på fleire måtar:

* Trykk på tre punkt for å lage vinkelen mellom punkta. Det andre punktet vert toppunkt i vinkelen.
* Trykk på to linjer/linjestykke for å lage vinkelen mellom linjene/linjestykka.
* Trykk på to vektorar for å lage vinkelen mellom dei.
* Trykk på ein mangekant for å lage alle vinklane på mangekanten.

[NOTE]
====

*Merk:*

* Dersom mangekanten vart laga mot klokka vil verktøyet gje deg dei indre vinklane.
* Dersom mangekanten vart laga med klokka vil verktøyet gje deg dei ytre vinklane.
* Vinklar vert laga mot klokka (positiv dreieretning). Derfor vil rekkefølgja du vel objekt i vere relevant for dette
verktøyet. Dersom du vil begrense vinkelen til 180° brukar du nedtrekksmenyen du finn under fana _Basis_ i
xref:/Eigenskapar.adoc[dialogboks for eigenskapar] for vinkelen.

====

[NOTE]
====

*Merk:* Sjå også kommandoen xref:/commands/Vinkel.adoc[Vinkel].

====
