= Kalkulator vjerojatnosti alat
:page-en: Probability_Calculator
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Klikom na ovaj alat otvara se dijaloški okvir za izračun i grafički prikaz razdiobe vjerojatnosti.

* Kako bi promijenili razdiobu, otvorite padajući izbornik i izaberite željenu razdiobu s liste. Tada prilagodite
parametre razdiobe u odgovarajućim tekstualnim poljima.
* Za izračunavanje vjerojatnosti kliknite na padajući izbornik vjerojatnosti i odaberite tip intervala. Tada prilagodite
rubove intervala u odgovarajućim tekstualnim poljima. To možete postići i pomičući točke na x-osi grafa. U nekim je
slučajevima moguće zadati i vjerojatnost (kod jednostranih intervala), tada će kalkulator izračunati granicu intervala
za zadanu vjerojatnost.

*Postavke*

Kalkulator vjerojatnosti ima traku za stilove s mogućnošću izmjene postavki i izvoza grafa. Kako biste otvorli traku
stilova, kliknite na gumb za otvaranje trake stilova (gore desno, mala strelica). Iz trake stilova možete podešavati
zaokruživanje, koristiti kumulativnu vjerojatnost ili izvesti graf. Izvoz grafa može se napraviti i desnim klikom miša
na sam graf.

*Povlači i ispusti*

Kada je miš pozicioniran na vrh grafičkog prozora kursor se mjenja u oblik ruke. Tada možete povući graf u Grafički
prikaz 1 ili 2 kako biste načinili novi graf ili pak možete povlačiti crtež grafa u drugi program koji će preuzeti
crtež.
