= Olovka alat
:page-en: tools/Pen
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Alat Olovka omogućava korisniku da piše ili crta slobodnom rukom po xref:/Grafički_prikaz.adoc[grafičkom prikazu]. Taj
alat je posebno koristan kada se GeoGebra koristi za prezentacije ili na _pametnoj ploči_. Kako biste dodali bilješku
pisanu slobodnom rukom, odaberite područje na grafičkom prikazu, nacrtajte prvo pravokutnik pomoću alata
xref:/tools/Pomicanje.adoc[pomicanje], ili označite sliku na kojoj ćete crtati. Kako biste završili, izaberite novi
alat.

GeoGebra sprema bilješke iz grafičkog prikaza kao xref:/tools/Umetanje_slike.adoc[sliku], tako da možete s njima raditi
svaku operaciju kao i sa slikama (pomicati, okretati, brisati, itd.).

Zadana boja olovke je crna, no svojstva olovke (boju, stil i debljinu) možete mijenjati koristeći
xref:/Prikazi.adoc[traku za stil], označivši prvu ikonicu u traci Grafičkog prikaza.

== Brisanje

Kako biste brisali djelove vaših bilješki koje ste napravili u grafičkom prikazu pomoću alata Olovka, pritisnite i
držite pritisnutu desnu tipku miša dok ga pomičete preko bilješki koje želite izbrisati. Brisanje je gotovo kada
otpustite tipku miša. Ako želite izbrisati sliku u koju je vaš prostoručni crtež spremljen, morate aktivirati
xref:/Algebarski_prikaz.adoc[pomoćne objekte] u algebarskom prikazu. Tamo treba pronaći naziv slike, npr. slika1. Desnom
tipkom miša označite naziv slike i iz padajućeg izbornika izaberite Izbriši.
