= Sjecište dvaju objekata alat
:page-en: tools/Intersect
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Sjecište dvaju objekata možete konstruirati na dva načina (pogledajte i naredbu xref:/commands/Sjecište.adoc[Sjecište]):

* Odaberete li dva objekta bit će konstruirana sva njihova sjecišta (ukoliko je moguće).
* Izravnim klikom na mjesto gdje se sijeku dva objekta dobivamo samo to _određeno sjecište_.

[NOTE]
====

Ponekad je korisno prikazati samo dio objekata koji se sijeku, u okolini sjecišta. da biste to postigli desnim klikom
miša na točku odaberite opciju _Pokaži dijelove crta oko sjecišta_ na kartici _Osnovno_
xref:/Dijaloški_okvir_Svojstva.adoc[dijaloškog okvira Svojstva], a zatim možete sakriti objekte koji se sijeku.

====

== Udaljena sjecišta

Za dužine, zrake ili lukove možete naglasiti želite li omogućiti _Sjecište u produžetku_ na kartici _Osnovno_
xref:/Dijaloški_okvir_Svojstva.adoc[dijaloškog okvira Svojstva]. Tako možete dobiti sjecište koje leži na produžetku
objekta. Na primjer, produžetak dužine ili zrake je pravac.
