= Umetanje teksta alat
:page-en: tools/Text
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Pomoću ovog alata možete u xref:/Grafički_prikaz.adoc[grafičkom prikazu] izraditi statični ili dinamični tekst, ili
LaTeX formule.

Najprije morate odrediti položaj teksta na jedan od slijedećih načina:

* klikom na grafički prikaz izradit ćete novi tekst na tom mjestu.
* klikom na točku izradit ćete tekst čiji je položaj vezan uz tu točku.

[NOTE]
====

Na kartici _Osnovno_ xref:/Dijaloški_okvir_Svojstva.adoc[dijaloškog okvira Svojstva] teksta, položaj teksta možete
postaviti kao apsolutan na zaslonu ili relativan u koordinatnom sustavu.

====

Nakon toga, otvara se dijaloško polje u koje možete unositi tekst, statični, dinamični, ili mješoviti.

*Statičan tekst* kojeg ukucavate direktno u polje _Uredi_ nije ovisan niti o jednom matematičkom objektu i promjene u
konstrukciji neće se odražavati na taj tekst.

*Dinamičan tekst* sadrži vrijednosti objekta koje se automatski prilagođavaju promjenama vezanim uz promjene objekta.
Kako biste izradili dinamični tekst, označite odgovarajući objekt iz padajuće liste _Objekti_. U polju _Uredi_ pokazat
će se odgovarajući naziv objekta okružen sivim pravokutnikom, a njegova je vrijednost prikazana u polju _Pretpregled_.
Desni klik na sivi pravokutnik omogućava vam izbor "Definicije" ili "Vrijednosti" za svaki dinamički objekt.

Mješovit tekst je kombinacija statičnog i dinamičnog teksta.

S takvim objektima moguće je raditi algebarske operacije ili primijeniti na njih posebne naredbe, samo kliknite na sivi
pravokutnik i ukucajte algebarsku operaciju ili GeoGebra xref:/commands/Tekst_naredbe.adoc[tekstualnu naredbu]. Rezultat
tih operacija biti će prikazan kao dinamičan tekst u grafičkom prikazu.

Vizualno najljepši tekstovi izgledaju ako se u formulama koristi LaTex formatiranje. Njegova upotreba je jednostavna i
intuitivna: označite okvirić _LaTeX formula_, i izaberite željeni predložak iz padajuće liste. Možete izabrati i mnoštvo
matematičkih simbola i operatora iz padajuće liste _Simboli_.

== Pogledajte još

* xref:/Tekstovi.adoc[Tekstovi]
* xref:/LaTeX.adoc[LaTeX]
* xref:/commands/Tekst_naredbe.adoc[Tekst naredbe]
