= Komplexní čísla
:page-en: Complex_Numbers
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

GeoGebra nepodporuje přímo komplexní čísla, ale můžeme použít xref:/Body_a_vektory.adoc[body a vektory] k simulaci
operací s komplexními čísly.

[EXAMPLE]
====

Vložíme-li komplexní číslo 3 + 4i do Vstupního pole, dostaneme bod (3, 4) v Nákresně. Souřadnice bodu se v Algebraickém
pohledu zobrazí jako 3 + 4i.

====

[NOTE]
====

V xref:/Algebraické_okno.adoc[algebraickém okně] můžeme jakýkoliv bod zobrazit jako komplexní číslo. Otevřeme
xref:/Dialog_Vlastnosti.adoc[Dialog Vlastnosti] bodu a vybereme ze seznamu Souřadnice na kartě Algebra položku Komplexní
číslo.

====

Není-li proměnná již definována, je rozpoznána jako uspořádaná dvojice i = (0, 1) nebo komplexní číslo 0 + 1i. Toto také
znamená, že proměnnou můžeme používat, chceme-li zapsat komplexní číslo do Vstupního pole (např. q = 3 + 4i).

[EXAMPLE]
====

Sčítání a odčítání:

* (2 + 1i) + (1 – 2i) dostaneme komplexní číslo 3 – 1i.
* (2 + 1i) - (1 – 2i) dostaneme komplexní číslo 1 + 3i.

====

[EXAMPLE]
====

Násobení a dělení:

* (2 + 1i) * (1 – 2i) dostaneme komplexní číslo 4 – 3i.
* (2 + 1i) / (1 – 2i) dostaneme komplexní číslo 0 + 1i.

====

[NOTE]
====

Násobíme-li obvyklým způsobem (2, 1)*(1, -2) dostaneme skalární součin dvou vektorů.

====

GeoGebra také rozpoznává výrazy obsahující xref:/Čísla_a_úhly.adoc[reálná] a komplexní čísla.

[EXAMPLE]
====

* 3 + (4 + 5i) dostaneme komplexní číslo 7 + 5i.
* 3 - (4 + 5i) dostaneme komplexní číslo -1 - 5i.
* 3 / (0 + 1i) dostaneme komplexní číslo 0 - 3i.
* 3 * (1 + 2i) dostaneme komplexní číslo 3 + 6i.

====
