= Přístupnost
:page-en: Accessibility
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

[NOTE]
====

Pro příklady zajištění přístupnosti appletů a pro více informací viz https://www.geogebra.org/m/r2EF8uRx[GeoGebra Accessibility].

====

Při tvorbě appletů je důležité myslet na zajištění jejich co největší přístupnosti pro všechny studenty.

:toc:

== Velikost písma, barvy & kontrast

Použití velkých fontů s dobrým kontrastem je důležité. Než začnete tvořit applet, zvolte dostatečně čitelnou velikost písma v Nastavení -> Velikost písma. Chcete-li učinit najednou všechno písmo větší a všechny čáry silnější, můžete k tomu použít klávesovou zkratku [.kcode]#Ctrl# + [.kcode]#2#. Užitečná je i klávesová zkratka [.kcode]#Ctrl# + [.kcode]#3#, jejímž použitím se všechny objekty obarví černě a zbaví se výplně.

Ideálně používejte tmavé barvy na bílém pozadí, spolu s tlustými čarami. Čistě
https://snook.ca/technical/colour_contrast/colour.html#fg=FF0000,bg=FFFFFF[červená (Red)] a
https://snook.ca/technical/colour_contrast/colour.html#fg=00FF00,bg=FFFFFF[zelená (Green)] nemají dostatečný kontrast, proto používejte některé tmavší odstíny, např. https://snook.ca/technical/colour_contrast/colour.html#fg=0000FF,bg=FFFFFF[modrá (Blue)],
https://snook.ca/technical/colour_contrast/colour.html#fg=226600,bg=FFFFFF[tmavě zelená (Dark Green)],
https://snook.ca/technical/colour_contrast/colour.html#fg=990033,bg=FFFFFF[tmavě červená (Dark Red)]

Pokud používáte barvy k odlišení jinak podobných objektů, zvažte odlišení jednoho z nich ještě použitím jiného typu čar, např. přerušovaných (dashed lines). Existují také webové stránky, na kterých můžete prověřit vhodnost vámi zvoleného barevného schématu, viz např. https://www.vischeck.com/

== Posuvníky

Dělejte posuvníky co nejdelší možné, aby je mohli dobře používat i studenti s méně dobrou jemnou motorikou. Za úvahu také stojí možnost přidat ke koncům posuvníku tlačítka "zmenšit" ("decrement") a "zvětšit" ("increment") (při každém stisknutí takového tlačítka se zmenší nebo zvětší hodnota proměnné posuvníku o stanovený krok; tlačítka je třeba vytvořit).

== Klávesové zkratky

Pokud je v nákresně zobrazeno více objektů, studenti mohou mezi nimi cyklicky přecházet opakovaným tisknutím klávesy [.kcode]#Tab#. Pokud si přejete, aby některý z objektů nemohl být takto vybrán, *deaktivujte* v nabídce Nastavení -> Pro pokročilé *volbu "Výběr povolen"*. V desktopové verzi je možné tuto volbu nastavit hromadně pro *jiné objekty než* Tlačítka / Posuvníky / Zaškrtávací políčka / Body / Textová pole pomocí kombinace kláves [.kcode]#Ctrl# + [.kcode]#Shift# + [.kcode]#D#.

Pro pohybování posuvníky či body, pokud jsou vybrány, mohou být použity klávesové šipky [.kcode]#Doleva#, [.kcode]#Doprava#, [.kcode]#Nahoru#, [.kcode]#Dolů#.

[.kcode]#Mezerník# může být použit k aktivaci tlačítka, přepnutí zaškrtávacího políčka, nebo ke spuštění/zastavení animace posuvníku

Klávesa [.kcode]#Escape# může být použita k opuštění pracovní plochy appletu, a klávesa [.kcode]#Enter# zase k návratu do ní (což je užitečné, pokud máme na jedné stránce více appletů)

Klávesy [.kcode]#+# a [.kcode]#−# mohou být použity k pohybování bodu po dané trajektorie (např. po kružnici)

Applety GeoGebry jsou také plně dotykové, takže studenti mohou v případě potřeby použít applet na speciálním velkém tabletu.

== Tooltips

You can provide custom tooltips for certain objects by using the _Caption_ property, and changing how the tooltip is
shown: xref:/Tooltips.adoc[Tooltips]

== Screen Readers

You can have some text attached to the Graphics Views so that it is read by a screen reader.

If you make a text object in GeoGebra called `++altText++`, `++altText2++`, `++altText3D++` then it will be attached to
Graphics View 1, Graphics View 2, Graphics View 3D respectively.
