= Zápis konstrukce
:page-en: Construction_Protocol
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

Interaktivní Zápis konstrukce lze zobrazit výběrem položky Zápis konstrukce z nabídky Zobrazit nebo klávesovou zkratkou
[.kcode]##Ctrl##+[.kcode]##Shift##+[.kcode]#L#. Zápis konstrukce je tabulka, která ukazuje všechny kroky konstrukce, a
která s využitím xref:/Navigační_panel.adoc[Navigačního panelu] umožňuje znovu provádět celou konstrukci krok po kroku.

== Navigace v Zápisu konstrukce a jeho úpravy

V Zápisu konstrukce se lze pohybovat pomocí klávesnice:

* Klávesou [.kcode]#↑# šipka nahoru pro přechod k předchozímu kroku konstrukce.
* Klávesou [.kcode]#↓# šipka dolů pro přechod k následujícímu kroku konstrukce.
* Klávesou [.kcode]#Home# pro přechod na začátek Zápisu konstrukce.
* Klávesou [.kcode]#End# pro přechod na konec Zápisu konstrukce.
* Klávesou [.kcode]#Delete# lze smazat vybraný krok konstrukce.

[NOTE]
====

Vymazání konstrukčního kroku může ovlivnit i další objekty, které na daném konstrukčním kroku/objektu závisí.

====

V Zápisu konstrukce se lze pohybovat pomocí myši:

* Dvojklikem na řádek je proveden výběr konstrukčního kroku.
* Dvojklik na záhlaví kteréhokoliv sloupce provede přechod na začátek Zápisu konstrukce.
* Přetažením řádku myší na jinou pozici v Zápisu konstrukce (metoda „táhni a pusť“, drag&drop).

[NOTE]
====

Kvůli možným závislostem mezi různými objekty není vždy možné přetáhnout vybraný konstrukční krok na vybranou pozici.

====

* Stiskem pravého tlačítka myši lze zobrazit kontextovou nabídku pro vybraný krok konstrukce.

[NOTE]
====

Na libovolnou pozici Zápisu konstrukce lze vložit další konstrukční krok. Vyberte položku Zápisu konstrukce, pod kterou
chcete vložit nový konstrukční krok. Během vytváření nového objektu nechte okno Zápisu konstrukce otevřené. Takto nově
vytvořený konstrukční krok je okamžitě vložen na požadované místo v zápisu konstrukce.

====

Pomocí sloupce Bod zastavení v Zápisu konstrukce lze některé konstrukční kroky definovat jako Body zastavení. Tím dojde
k seskupení několika konstrukčních kroků. Tato skupina konstrukčních kroků poté bude při procházení konstrukce pomocí
xref:/Navigační_panel.adoc[Navigačního panelu] zobrazena najednou.

[NOTE]
====

Sloupce Zápisu konstrukce lze zobrazit či skrýt pomocí nabídky Sloupce na nástrojové liště Zápisu konstrukce, případně z
kontextové nabídky Zápisu konstrukce, kterou lze zobrazit pravým klikem do prázdné oblasti Zápisu konstrukce nebo na
záhlaví sloupců.

====

== Export Zápisu konstrukce jako webové stránky

Geogebra umožňuje exportovat Zápis konstrukce jako webovou stránku. Nejprve zobrazte okno Zápisu konstrukce pomocí
nabídky Zobrazit nebo klávesovou zkratkou [.kcode]##Ctrl##+[.kcode]##Shift##+[.kcode]#L#. Poté zvolte na nástrojové
liště Zápisu konstrukce nebo v jeho kontextové nabídce položku Exportovat jako webovou stránku (html).

V okně exportu Zápisu konstrukce lze vložit název, autora a datum konstrukce a zvolit zda bude do exportovaného souboru
vložen obrázek xref:/Grafický_pohled.adoc[Grafického pohledu] či obrázky všech otevřených náhledů. Dále lze zvolit, zda
má být Zápis konstrukce exportován jako barvený, kdy barvy jednotlivých objektů v zápisu konstrukce odpovídají barvám
objektů v Grafickém pohledu.

[NOTE]
====

Výsledný HTML soubor lze prohlížet v libovolném internetovém prohlížeči (např. Firefox, Internet Explorer, Opera) a lze
ho editovat v mnoha textových editorech (např. OpenOffice Writer).

====

[NOTE]
====

Originální anglická verze: /s_index_php?title=En:Manual:Construction_Protocol_action=edit_redlink=1.adoc[Construction
Protocol].

====
