= AreEqual Command
:page-en: commands/AreEqual
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

AreEqual( <Object>, <Object> )::
  Decides if the objects are equal.

Normally this command computes the result numerically. This behavior can be changed by using the
xref:/commands/Prove.adoc[Prove] command.

[EXAMPLE]
====

`++AreEqual(Circle((0, 0),1),x^2+y^2=1)++` yields _true_ since the two circles have the same center and radius.

====

[NOTE]
====

*Notes:*

* `++AreEqual(Segment((1, 2), (3, 4)), Segment((3, 4), (1, 6)))++` is different from
`++Segment((1, 2), (3, 4)) == Segment((3, 4), (1, 6))++` as the latter compares just the lengths
* See also xref:/commands/AreCollinear.adoc[AreCollinear], xref:/commands/AreConcyclic.adoc[AreConcyclic],
xref:/commands/AreConcurrent.adoc[AreConcurrent], xref:/commands/AreCongruent.adoc[AreCongruent],
xref:/commands/ArePerpendicular.adoc[ArePerpendicular], xref:/commands/AreParallel.adoc[AreParallel],
xref:/commands/IsTangent.adoc[IsTangent] commands.

====
