= BetaDist Command
:page-en: commands/BetaDist
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

BetaDist( <Number α>, <Number β>, <Variable value> )::
  Calculates the value of the cumulative distribution function of a https://en.wikipedia.org/wiki/Beta_distribution[Beta distribution] with parameters _α, β_ at the variable value _v_, that is the probability _P(X≤v)_ where _X_ is a random variable with a beta distribution with parameters _α_ and _β_

BetaDist( <Number α>, <Number β>, <Variable value>, <Boolean Cumulative> )::
  If _Cumulative_ is _true_, calculates the value of the cumulative distribution function of a Beta distribution with parameters _α_ and _β_ at the variable value _v_. If _Cumulative_ is _false_, it calculates the value of the probability density function (pdf) of the corresponding beta distribution at _v_.


BetaDist(<Number α>, <Number β>, x, <Boolean Cumulative>)::
  If _Cumulative_ is _true_, creates the cumulative distribution function of a beta distribution with parameters _α_ and _β_, otherwise it creates the probability density function (pdf) of the corresponding Beta distribution.

[NOTE]
====
See also xref:/commands/InverseBeta.adoc[InverseBeta] command.
====
