= BetaDist Command
:page-en: commands/BetaDist
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

BetaDist( <Number α>, <Number β>, <Variable value> )::
  Creates the cumulative distribution function (cdf) of a beta distribution with parameters _α, β_ at _v_, that is the probability _P(X≤v)_ where _X_ is a random variable with a beta distribution with parameters _α_ and _β_

BetaDist( <Number α>, <Number β>, <Variable value>, <Boolean Cumulative> )::
  If Cumulative is true, creates the cumulative distribution function of a beta distribution with parameters _α_ and _β_ at the variable value _v_. If Cumulative is false, it creates the probability density function (pdf) of the corresponding beta distribution at _v_.


BetaDist(<Number α>, <Number β>, x, <Boolean Cumulative>)::
  If Cumulative is true, creates the cumulative distribution function of a beta distribution with parameters _α_ and _β_, otherwise it creates the probability density function (pdf) of the corresponding Beta distribution.

[NOTE]
====
See also xref:InverseBeta.adoc[InverseBeta] command.
====
