= BinomialDist Command
:page-en: commands/BinomialDist
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

BinomialDist( <Number of Trials>, <Probability of Success> )::
  Returns a bar graph of a http://en.wikipedia.org/wiki/Binomial_distribution[Binomial distribution].
  The parameter _Number of Trials_ specifies the number of independent Bernoulli trials and the parameter _Probability
  of Success_ specifies the probability of success in one trial.

BinomialDist( <Number of Trials>, <Probability of Success>, <Boolean Cumulative> )::
  Returns a bar graph of a Binomial distribution when _Cumulative_ = false.
  Returns a graph of a cumulative Binomial distribution when _Cumulative_ = true.
  First two parameters are same as above.

BinomialDist( <Number of Trials>, <Probability of Success>, <Variable Value>, <Boolean Cumulative> )::
  Let X be a Binomial random variable and let v be the variable value.
  Returns P( X = _v_) when _Cumulative_ = false.
  Returns P( X ≤ _v_) when _Cumulative_ = true.
  First two parameters are same as above.

BinomialDist( <Number of Trials>, <Probability of Success>, <List of values>)::
  Calculates P(_u_ ≤ X ≤ _v_) by applying the previous syntax (with _Cumulative_ = false) and adding the values obtained when the elements of the _List of values_ are used as _variable values_.

[EXAMPLE]
====

`++BinomialDist(10, 0.2, {1,2,3})++` yields _0.77175_, and is equivalent to `++BinomialDist(10, 0.2, 1, false)++` + `++BinomialDist(10, 0.2, 2, false)++` + `++BinomialDist(10, 0.2, 3, false)++`

====


[NOTE]
====

The syntaxes `++BinomialDist(10, 0.2, {1,2,3})++` and  `++BinomialDist(10, 0.2, 1..3)++` are equivalent.

====



== CAS Syntax


BinomialDist( <Number of Trials>, <Probability of Success>, <Variable Value>, <Boolean Cumulative> )::
  Let X be a Binomial random variable and let v be the variable value.
  Returns P( X = _v_) when _Cumulative_ = false.
  Returns P( X ≤ _v_) when _Cumulative_ = true.

[EXAMPLE]
====

You can plot a graph with eg `++f(x):=BinomialDist(100,x,36,true)-BinomialDist(100,x,23,true)++`

====

[EXAMPLE]
====

Assume transfering three packets of data over a faulty line. The chance an arbitrary packet transfered over this line
becomes corrupted is stem:[\frac{1}{10}], hence the propability of transfering an arbitrary packet successfully is
stem:[\frac{9}{10}].

* `++BinomialDist(3, 0.9, 0, false)++` yields _stem:[\frac{1}{1000}]_, the probability of none of the three packets
being transferred successfully.
* `++BinomialDist(3, 0.9, 1, false)++` yields _stem:[\frac{27}{1000}]_, the probability of exactly one of three
packets being transferred successfully.
* `++BinomialDist(3, 0.9, 2, false)++` yields _stem:[\frac{243}{1000}]_, the probability of exactly two of three
packets being transferred successfully.
* `++BinomialDist(3, 0.9, 3, false)++` yields _stem:[\frac{729}{1000}]_, the probability of all three packets being
transferred successfully.
* `++BinomialDist(3, 0.9, 0, true)++` yields _stem:[\frac{1}{1000}]_, the probability of none of the three packets
being transferred successfully.
* `++BinomialDist(3, 0.9, 1, true)++` yields _stem:[\frac{7}{250}]_, the probability of at most one of three packets
being transferred successfully.
* `++BinomialDist(3, 0.9, 2, true)++` yields _stem:[\frac{271}{1000}]_, the probability of at most two of three
packets being transferred successfully.
* `++BinomialDist(3, 0.9, 3, true)++` yields _1_, the probability of at most three of three packets being transferred
successfully.
* `++BinomialDist(3, 0.9, 4, false)++` yields _0_, the probability of exactly four of three packets being transferred
successfully.
* `++BinomialDist(3, 0.9, 4, true)++` yields _1_, the probability of at most four of three packets being transferred
successfully.

====

BinomialDist( <Number of Trials>, <Probability of Success>, <List of values>)::
  Calculates P(_u_ ≤ X ≤ _v_) by applying the previous syntax (with _Cumulative_ = false) and adding the values obtained when the elements of the _List of values_ are used as _variable values_.

[EXAMPLE]
====

`++BinomialDist(10, 0.2, {1,2,3})++` yields stem:[\frac{1507328}{1953125}], and is equivalent to `++BinomialDist(10, 0.2, 1, false)++` + `++BinomialDist(10, 0.2, 2, false)++` + `++BinomialDist(10, 0.2, 3, false)++`

====
