= ChiSquaredTest Command
:page-en: commands/ChiSquaredTest
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

ChiSquaredTest( <Matrix> )::
  Performs a https://en.wikipedia.org/wiki/Chi-squared_test[chi-squared test] that compares the given matrix of observed
  counts against the matrix of expected counts determined by the hypothesis of independence.
  The matrix of expected counts is calculated internally. Each expected count is found from the row and column totals of
  the given matrix of observed counts using the rule:
  stem:[ \text{expected count} = \frac{\text{row total} × \text{column total}}{\text{total observed counts}} ]

Results are returned in list form as _{Probability value, chi-squared test statistic}_.

[EXAMPLE]
====

`++ChiSquaredTest({{1, 2, 1}, {3, 2, 3}})++` yields _{0.69, 0.75}_.

====

ChiSquaredTest( <Observed List>, <Expected List> )::
  Performs a https://en.wikipedia.org/wiki/Goodness_of_fit[Goodness of Fit test] that compares the given list of observed
  counts against the given list of expected counts. To compute the probability, _n_-1 degrees of freedom are assumed,
  where _n_ is the number of elements in each list. For lists of different sizes the result is undefined.
  Results are returned in list form as _{Probability value, chi-squared test statistic}_.

[EXAMPLE]
====

`++ChiSquaredTest({1, 2, 3, 4}, {3, 2, 4, 2})++` yields _{0.31, 3.58}_.

====

ChiSquaredTest( <Observed Matrix>, <Expected Matrix> )::
  Performs a https://en.wikipedia.org/wiki/Chi-squared_test[chi-squared test] that compares the given matrix of observed
  counts against the given matrix of expected counts. To compute the probability, stem:[(r-1)\cdot(c-1)] degrees of freedom are assumed,
  where _r_ and _c_ are the number of rows and columns in each matrix. For matrices of different size the result is undefined.
  Results are returned in list form as _{Probability value, chi-squared test statistic}_.

[EXAMPLE]
====

`++ChiSquaredTest({{1, 2, 1}, {3, 2, 3}}, {{2, 3, 2}, {4, 2, 3}})++` yields _{0.45, 1.58}_.

====

ChiSquaredTest( <List>, <List>, <Degrees of Freedom> )::
  Performs a https://en.wikipedia.org/wiki/Goodness_of_fit[Goodness of Fit test] that compares the given list of observed
  counts against the given list of expected counts, using a specific number of degrees of freedom.
  Results are returned in list form as _{Probability value, chi-squared test statistic}_.
  For lists of different sizes the result is undefined.

[EXAMPLE]
====

`++ChiSquaredTest({1, 2, 3, 4}, {3, 2, 4, 2}, 2)++` yields _{0.17, 3.58}_.

====
