= Coefficients Command
:page-en: commands/Coefficients
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Coefficients( <Polynomial> )::
  Yields the list of all coefficients stem:[a_k,a_{k-1},\ldots,a_1, a_0] of the polynomial
  stem:[a_k x^k+a_{k-1}x^{k-1}+\cdots+a_1 x+a_0].

[EXAMPLE]
====

`++Coefficients(x^3 - 3 x^2 + 3 x)++` yields _{1, -3, 3, 0}_.

====

Coefficients( <Conic> )::

Returns the list of the coefficients _a_, _b_, _c_, _d_, _e_, _f_ of a conic in standard form: stem:[a\cdot x^2 + b\cdot
y^2 + c + d\cdot x\cdot y + e\cdot x + f\cdot y = 0]

[NOTE]
====

For a line in implicit form _l: ax + by + c = 0_ it is possible to obtain the coefficients using the syntax _x_(_l_),
_y_(_l_), _z_(_l_).

====

[EXAMPLE]
====

Given line `++l: 3x + 2y - 2 = 0++`:


* `++x(l)++` returns 3
* `++y(l)++` returns 2
* `++z(l)++` returns -2

====

[NOTE]
====

For non-polynomial curves obtained using one the fitting commands e.g. `++f(x) = FitExp(l1)++`, the command 
`++Coefficients(f)++` will return the list of the calculated parameters.

====

== CAS Syntax

Coefficients( <Polynomial> )::
  Yields the list of all coefficients of the polynomial in the main variable.

[EXAMPLE]
====

`++Coefficients(x^3 - 3 x^2 + 3 x)++` yields _{1, -3, 3, 0}_.

====

Coefficients( <Polynomial>, <Variable> )::
  Yields the list of all coefficients of the polynomial in the given variable.

[EXAMPLE]
====

* `++Coefficients(a^3 - 3 a^2 + 3 a, a)++` yields _{1, -3, 3, 0}_.
* `++Coefficients(a^3 - 3 a^2 + 3 a, x)++` yields {__a__³ - 3 __a__² + 3 _a_}.

====
