= Coefficients Command

Coefficients( <Polynomial> )::
  Yields the list of all coefficients stem:[a_k,a_\{k-1},\ldots,a_1, a_0] of the polynomial
  stem:[a_kx^k+a_\{k-1}x^\{k-1}+\cdots+a_1x+a_0].

[EXAMPLE]
====

`Coefficients(x^3 - 3 x^2 + 3 x)` yields _\{1, -3, 3, 0}_, the list of all coefficients of stem:[x^3 - 3 x^2 + 3 x].

====

Coefficients( <Conic> )

Returns the list of the coefficients _a_, _b_, _c_, _d_, _e_, _f_ of a conic in standard form: stem:[a\cdot x^2 + b\cdot
y^2 + c + d\cdot x\cdot y + e\cdot x + f\cdot y = 0]

[NOTE]
====

For a line in implicit form _l: ax + by + c = 0_ it is possible to obtain the coefficients using the syntax _x_(_l_),
_y_(_l_), _z_(_l_).

[EXAMPLE]
====

Given `line: 3x + 2y - 2 = 0`:

* `x(line)` returns 3
* `y(line)` returns 2
* `z(line)` returns -2

====

====

[NOTE]
====

There's a special mode (for non-polynomials) for the output of the fitting commands eg if `f(x) = FitExp(l1)` then
`Coefficients(f)` will return the calculated parameters

====

== [#CAS_Syntax]#CAS Syntax#

Coefficients( <Polynomial> )::
  Yields the list of all coefficients of the polynomial in the main variable.

[EXAMPLE]
====

`Coefficients(x^3 - 3 x^2 + 3 x)` yields _\{1, -3, 3, 0}_, the list of all coefficients of stem:[x^3 - 3 x^2 + 3 x].

====

Coefficients( <Polynomial>, <Variable> )::
  Yields the list of all coefficients of the polynomial in the given variable.

[EXAMPLE]
====

* `Coefficients(a^3 - 3 a^2 + 3 a, a)` yields _\{1, -3, 3, 0}_, the list of all coefficients of stem:[a^3 - 3 a^2 + 3 a]
* `Coefficients(a^3 - 3 a^2 + 3 a, x)` yields \{__a__³ - 3 __a__² + 3 _a_}.

====
