= ContingencyTable Command
:page-en: commands/ContingencyTable
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

ContingencyTable( <List of Text>, <List of Text> )::
  Draws a https://en.wikipedia.org/wiki/Contingency_table[Contingency Table] created from the two given lists. Unique
  values from the first list are used as row values in the table. Unique values from the second list are used as column
  values in the table.

ContingencyTable( <List of Text>, <List of Text>, <Options> )::
  Draws a https://en.wikipedia.org/wiki/Contingency_table[Contingency Table] created from the two given lists as
  described above. The text _Options_ controls the display of optional calculations within the table.

[NOTE]
====

Possible values for _Options_ are "|", "_", "+", "e", "k", "=".

* "|" = show column percentages
* "_" = show row percentages
* "+" = show total percentages
* "e" = show expected counts
* "k" = show Chi Squared contributions
* "=" = show results of a Chi Squared test

====

ContingencyTable( <List of Row Values>, <List of Column Values>, <Frequency Table> )::
  Draws a https://en.wikipedia.org/wiki/Contingency_table[Contingency Table] using the given list of row values, column
  values and corresponding frequency table.

[EXAMPLE]
====

`++ContingencyTable({"Males","Females"},{"Right-handed", "Left-handed"},{{43,9},{44,4}})++` yields the corresponding
Contingency Table.

====

ContingencyTable( <List of Row Values>, <List of Column Values> <Frequency Table>, <Options> )::
  Draws a https://en.wikipedia.org/wiki/Contingency_table[Contingency Table] using the given list of row values, column
  values and corresponding frequency table. The text _Options_ controls the display of optional calculations within the
  table as described above.

[EXAMPLE]
====

`++ContingencyTable({"Males","Females"},{"Right-handed", "Left-handed"},{{43,9},{44,4}},"_")++` yields the corresponding
Contingency Table showing the row percentages.

====
