= Derivative Command

Derivative( <Function> )::
  Returns the derivative of the function with respect to the main variable.
  +

[EXAMPLE]

====

*Example:* `Derivative(x^3 + x^2 + x)` yields _3x² + 2x + 1_.

====

Derivative( <Function>, <Number> )::
  Returns the __n__^th^ derivative of the function with respect to the main variable, whereupon _n_ equals <Number>.
  +

[EXAMPLE]

====

*Example:* `Derivative(x^3 + x^2 + x, 2)` yields _6x + 2_.

====

Derivative( <Function>, <Variable> )::
  Returns the partial derivative of the function with respect to the given variable.
  +

[EXAMPLE]

====

*Example:* `Derivative(x^3 y^2 + y^2 + xy, y)` yields _2x³y + x + 2y_.

====

Derivative( <Function>, <Variable>, <Number> )::
  Returns the __n__^th^ partial derivative of the function with respect to the given variable, whereupon _n_ equals
  <Number>.
  +

[EXAMPLE]

====

*Example:* `Derivative(x^3 + 3x y, x, 2)` yields _6x_.

====

Derivative( <Curve> )::
  Returns the derivative of the curve.
  +

[EXAMPLE]

====

*Example:* `Derivative(Curve(cos(t), t sin(t), t, 0, π))` yields curve _x = -sin(t), y = sin(t) + t cos(t)_.

====

Derivative( <Curve>, <Number> )

Returns the __n__^th^ derivative of the curve, whereupon _n_ equals <Number>.

[EXAMPLE]

====

*Example:* `Derivative(Curve(cos(t), t sin(t), t, 0, π), 2)` yields curve _x = -cos(t), y = 2cos(t) - t sin(t)_.

====

[NOTE]

====

*Note:* This only works for parametric curves.

====

[NOTE]

====

*Note:* This only works for parametric curves.

====

[NOTE]

====

*Note:* You can use `f'(x)` instead of `Derivative(f)`, or `f''(x)` instead of `Derivative(f, 2)`, and so on.

====

== [#CAS_Syntax]#CAS Syntax#

Derivative( <Expression> )::
  Returns derivative of an expression with respect to the main variable.
  +

[EXAMPLE]

====

*Example:* `Derivative(x^2)` yields _2x_.

====

Derivative( <Expression>, <Variable> )::
  Returns derivative of an expression with respect to the given variable.
  +

[EXAMPLE]

====

*Example:* `Derivative(a x^3, a)` yields _x³_.

====

Derivative( <Expression>, <Variable>, <Number> )::
  Returns the __n__^th^ derivative of an expression with respect to the given variable, whereupon _n_ equals <Number>.
  +

[EXAMPLE]

====

*Examples:*

* `Derivative(y x^3, x, 2)` yields _6xy_.
* `Derivative(x³ + 3x y, x, 2)` yields _6x_.

====
