= Dodecahedron Command

Dodecahedron( <Point>, <Point>, <Direction> )::
  Creates a dodecahedron having the segment between two points as an edge.
  +
  The other vertices are univocally determined by the given direction, that needs to be:
  +
  * a vector, a segment, a line, a ray *orthogonal* to the segment, or
  * a polygon, a plane *parallel* to the segment.
  +
  The created dodecahedron will have:
  +
  * a face with the segment as an edge in a plane orthogonal to the given vector/segment/line/ray, or
  * a face with the segment as an edge in a plane parallel to the polygon/plane.

Dodecahedron( <Point>, <Point>, <Point>)::
  Creates a dodecahedron with three (adjacent) points of the first face. The points have to start a regular pentagon for
  the dodecahedron to be defined.

Dodecahedron( <Point>, <Point>)::
  Creates a dodecahedron with two (adjacent) points of the first face, and the third point automatically created on a
  circle, so that the dodecahedron can rotate around its first edge.

[NOTE]
====

Dodecahedron(A, B) is a shortcut for Dodecahedron(A, B, C) with C = Point(Circle(((1 - sqrt(5)) A + (3 + sqrt(5)) B) /
4, Distance(A, B) sqrt(10 + 2sqrt(5)) / 4, Segment(A, B))).

====

[NOTE]
====

See also xref:/commands/Cube.adoc[Cube], xref:/commands/Tetrahedron.adoc[Tetrahedron],
xref:/commands/Icosahedron.adoc[Icosahedron], xref:/commands/Octahedron.adoc[Octahedron] commands.

====
