= DotPlot Command
:page-en: commands/DotPlot
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

DotPlot( <List of Raw Data> )::
  Returns a dot plot for the given list of numbers, as well as the list of the dot plot points. If a number _n_ appears
  in the list of raw data _k_ times, the returned list contains points _(n, 1), (n, 2), ..., (n, k)_.

[EXAMPLE]
====

`++DotPlot({2, 5, 3, 4, 3, 5, 3})++` yields _{(2, 1), (3, 1), (3, 2), (3, 3), (4, 1), (5, 1), (5, 2)}_.

====

DotPlot( <List of Raw Data>, <Stack Adjacent Dots (optional)>, <Scale Factor (optional)> )::
  Returns a dot plot for the given list of data, as well as the list of the dot plot points. If a data _n_ appears in
  the list of raw data _k_ times, the returned list contains points _(n, 1), (n, 2),..., (n, k)_.
  If you choose a _Scale Factor s_, the returned list contains points _(n, 1s), (n, 2s), ..., (n, ks)_.
  _Stack Adjacent Dots_ means a Boolean Value (true or false): If you choose _true_, points (which are close to each
  other) are stacked. If you choose _false_, the result will be the same as without _<Stack Adjacent Dots (optional)>_.

The command DotPlot will also work with a list of text.

[EXAMPLE]
====

`++DotPlot({"Red", "Red", "Red", "Blue", "Blue"})++` yields _{(1, 1), (1, 2), (2, 1), (2, 2), (2, 3)}_.

====

[NOTE]
====

If you use a list of text the DotPlot command will put the result in alphabetical order. (e.g. _Blue_ appears two times,
_Red_ three times and B comes before R in the alphabet, so you get _(1, 1), (1, 2)_ for _Blue_ and _(2, 1), (2, 2), (2,
3)_ for _Red_.)

====
