= Execute Command

Execute( <List of Texts> )::
  Executes list of commands entered as texts.

[NOTE]

====

*Note:* Please note that you always need to use English (US) commands within this list of texts, no matter which
language option you selected for GeoGebra.

====

[EXAMPLE]

====

*Examples:*

* `Execute({"A=(1,1)","B=(3,3)","C = Midpoint(A, B)"})` creates points _A, B_ and their midpoint _C_.
* `Execute(Join({"f_{1} = 1", "f_{2} = 1"}, Sequence("f_{"+(i + 2) + "} = f_{" + (i+1) + "} + f_{"+ i +"}", i, 1, 10)))`
creates first 10 elements of http://en.wikipedia.org/wiki/Fibonacci_sequence[Fibonacci sequence].

====

Execute( <List of Texts>, <Parameter>, ... , <Parameter> )::
  Replaces %1 for the first parameter, %2 for the second parameter and so on in each text in list. Up to 9 parameters
  can be specified. After the replacement, resulting scripts are executed.
  +

[EXAMPLE]

====

*Example:* `Execute({"Segment(%1,%2)","Midpoint(%1,%2)"}, A, B)` creates the segment _AB_ and its midpoint.

====

[NOTE]

====

*Note:* If you need to use a quote (`"`) then you can use `UnicodeToLetter(34)`

====

[NOTE]

====

*Note:* Command names *must be in English (US)* in the texts for this command to work.

====
