= Exponential Command
:page-en: commands/Exponential
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Exponential( <Lambda>, x )::
  Creates cumulative density function (cdf) of http://en.wikipedia.org/wiki/Exponential_distribution[exponential
  distribution] with parameter _lambda_.
Exponential( <Lambda>, x, <Boolean Cumulative> )::
  If _Cumulative_ is true, creates cumulative distribution function (cdf) of exponential distribution, otherwise creates
  pdf of Exponential distribution.
Exponential( <Lambda>, <Variable Value> )::
  Calculates the value of cumulative distribution function of Exponential distribution at variable value _v_, i.e. the
  probability _P(X ≤ v)_ where _X_ is a random variable with Exponential distribution with parameter _lambda_.

[NOTE]
====

Returns the probability for a given _x_-coordinate's value (or area under the Exponential distribution curve to the left
of the given _x_-coordinate).

====

== CAS Syntax

Exponential( <Lambda>, <Variable Value> )::
  Calculates the value of cumulative distribution function of exponential distribution at variable value _v_, i.e. the
  probability _P(X ≤ v)_ where _X_ is a random variable with Exponential distribution with parameter _lambda_.

[EXAMPLE]
====

`++Exponential(2, 1)++` yields _stem:[1 - \frac{1}{e^{2} } ]_, which is approximately _0.86_.

====
