= First Command

First( <List> )::
  Gives a new list that contains the first element of the given list.

[EXAMPLE]
====

`++First({1, 4, 3})++` yields _\{1}_.

====

First( <List>, <Number n of elements> )

Gives a new list that contains just the first _n_ elements of the given list.

[EXAMPLE]
====

`++First({1, 4, 3}, 2)++` yields _\{1, 4}_.

====

[NOTE]
====

To get the first element use `++Element({1, 4, 3}, 1)++`.

====

First( <Text> )::
  Gives first character of the text.

[EXAMPLE]
====

`++First("Hello")++` yields _"H"_.

====

First( <Text> , <Number n of elements> )::
  Gives the first _n_ characters of the text.

[EXAMPLE]
====

`++First("Hello",2)++` yields _"He"_.

====

First( <Locus>, <Number n of elements> )::
  This command is useful for
  +
  * loci generated by xref:/commands/NSolveODE.adoc[NSolveODE Command] - It returns list points that were created in the
  first _n_ steps of the numeric ODE-solving algorithm.
  * loci generated using xref:/commands/ShortestDistance.adoc[ShortestDistance Command],
  xref:/commands/TravelingSalesman.adoc[TravelingSalesman Command], xref:/commands/Voronoi.adoc[Voronoi Command],
  xref:/commands/MinimumSpanningTree.adoc[MinimumSpanningTree Command] and xref:/commands/ConvexHull.adoc[ConvexHull
  Command] Commands - It returns vertices of the graph.

[NOTE]
====

See also xref:/commands/Last.adoc[Last Command].

====
