= FormulaText Command
:page-en: commands/FormulaText
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

FormulaText( <Object> )::
  Returns the formula that defines the object as a LaTeX text. Values are substituted for variables by default.

[EXAMPLE]
====

Let _a = 2_ and _f(x) = a x^2^_. `++FormulaText(f)++` returns _2 x^2^_ (as a LaTeX text).

====

[NOTE]
====

In GeoGebra Classic v.5, the command `++FormulaText($1)++` returns the content of cell 1 of the CAS View as a LaTeX text.

====


FormulaText( <Object>, <Boolean for Substitution of Variables> )::

  Returns the formula that defines the object as a LaTeX text. The Boolean variable determines if values are substituted for
  variables (_true_) or if variable names are shown in the text (_false_).

[EXAMPLE]
====

Let _a = 2_ and _f(x) = a x^2^_.

`++FormulaText(f, true)++` returns _2 x^2^_ (as a LaTeX text).

`++FormulaText(f, false)++` returns _a x^2^_ (as a LaTeX text).

====

FormulaText( <Object>, <Boolean for Substitution of Variables>, <Boolean Show Name> )::
 Returns the formula that defines the object as a LaTeX text. The first Boolean variable determines if values are substituted for
  variables (_true_) or if variable names are shown in the text (_false_), the second Boolean variable determines if the
  object name is shown in the text (_true_) or not (_false_).

[EXAMPLE]
====

Let _a = 2_ and _f(x) = a x^2^_.

`++FormulaText(f, true, true)++` returns _f(x) = 2 x^2^_ (as a LaTeX text).

`++FormulaText(f, false, false)++` returns _a x^2^_ (as a LaTeX text).

====
