= FrequencyPolygon Command

[NOTE]
====

Frequency polygon is a line graph drawn by joining all the midpoints of the top of the bars of a histogram. Therefore
usage of this command is the same as usage of xref:/commands/Histogram_Command.adoc[Histogram Command].

====

FrequencyPolygon( <List of Class Boundaries>, <List of Heights> )::
  Creates a frequency polygon with vertices in given heights. The class boundaries determine the x-coordinate of each
  vertex.

[EXAMPLE]
====

`FrequencyPolygon({0, 1, 2, 3, 4, 5}, {2, 6, 8, 3, 1})` creates the corresponding line graph.

====

FrequencyPolygon( <List of Class Boundaries>, <List of Raw Data>, <Boolean Use Density>, <Density Scale Factor
(optional)> )::
  Creates a frequency polygon using the raw data. The class boundaries determine the x-coordinates of vertices and are
  used to determine how many data elements lie in each class. The y-coordinate of a vertex is determined as follows
  +
  * If _Use Density = true_, height = (Density Scale Factor) * (class frequency) / (class width)
  * If _Use Density = false_, height = class frequency
  +
  By default, Use Density = true and Density Scale Factor = 1.

FrequencyPolygon( <Boolean Cumulative>, <List of Class Boundaries>, <List of Raw Data>, <Boolean Use Density> , <Density
Scale Factor (optional)> )::
  If Cumulative is true this creates a frequency polygon where each vertex y-coordinate equals the frequency of the
  class plus the sum of all previous frequencies.

[NOTE]
====

For further examples see xref:/commands/Histogram_Command.adoc[Histogram Command].

====
