= Frequency Command

Frequency( <List of Raw Data> )::
  Returns a list with a count of the occurrences of each unique value in the given list of data. This input list can be
  numbers or text. The list is sorted in ascending order of the unique values. To get a list of the corresponding unique
  values use the xref:/commands/Unique_Command.adoc[Unique Command].
  +

[EXAMPLE]

====

Enter `list1 = { "a", "a", "x", "x", "x", "b" }`. `Frequency(list1)` returns the list _\{ 2, 1, 3 }_. `Unique(list1)`
returns the list _\{ "a", "b", "x" }_.

====

Frequency( <Boolean Cumulative>, <List of Raw Data> )::
  If _Cumulative_ = _false_, returns the same list as Frequency( <List of Raw Data> )
  +
  If _Cumulative_ = _true_, returns a list of cumulative frequencies for Frequency( <List of Raw Data> ) .
  +

[EXAMPLE]

====

Enter `list1 = { 0, 0, 0, 1, 1, 2 }`. `Frequency(true, list1)` returns the list _\{ 3, 5, 6 }_.
`Frequency(false, list1)` returns the list _\{ 3, 2, 1}_. `Unique(list1)` returns the list _\{ 0, 1, 2 }_.

====

Frequency( <List of Class Boundaries>, <List of Raw Data> )::
  Returns a list of the counts of values from the given data list that lie within intervals of the form [a, b), where
  _a_ and _b_ are all the couples of consecutive numbers in the given class boundaries list. The highest interval has
  the form [a, b].
  +

[EXAMPLE]

====

`Frequency({1, 2, 3},  {1, 1, 2, 3})` returns the list _\{ 2, 2 }_.

====

Frequency( <List of Text>, <List of Text> )::
  Returns a contingency matrix containing counts of paired values from the two lists. The rows of the matrix correspond
  to the unique values in the first list, and the columns correspond to the unique values in the second list. To get a
  list of the unique values for each list use the command xref:/commands/Unique_Command.adoc[Unique Command].
  +

[EXAMPLE]

====

Let `list1 = {"a", "b", "b", "c", "c", "c", "c"}` and `list2 =  {"a", "b", "a", "a", "c", "c", "d"}`. Then
`Frequency(list1, list2)` returns the matrix stem:[\begin\{pmatrix} 1 & 0 & 0 & 0\\ 1 &1 & 0 &0 \\ 1 & 0 & 2 & 1 \\
\end\{pmatrix}]

====

[NOTE]

====

See also the xref:/commands/ContingencyTable_Command.adoc[ContingencyTable] command.

====

Frequency( <Boolean Cumulative>, <List of Class Boundaries>,<List of Raw Data> )::
  If _Cumulative_ = _false_, returns the same list as Frequency( <List of Class Boundaries>, <List of Raw Data> )
  +
  If _Cumulative_ = _true_, returns a list of cumulative frequencies for Frequency( <List of Class Boundaries>, <List of
  Raw Data> )

Frequency( <List of Class Boundaries>, <List of Raw Data>, <Use Density> , <Density Scale Factor> (optional) )::
  Returns a list of frequencies for the corresponding xref:/commands/Histogram_Command.adoc[Histogram Command].
  +
  If _Use density_ = _false_, returns the same list as Frequency( <List of Class Boundaries>, <List of Raw Data> )
  +
  If _Use density_ = _true_, returns the list of frequencies of each class.
  +

[EXAMPLE]

====

Let `data = {1, 2, 2, 2, 3, 3, 4, 4, 4, 4}` be the list of raw data and `classes={0, 2, 5}` the list of class
boundaries. Then `Frequency(classes, data, false)` and `Frequency(classes, data)` both return the list _\{1, 9}_, while
`Frequency(classes, data, true)` returns the list _\{0.5, 3}_.

====

Frequency( <Boolean Cumulative>, <List of Class Boundaries>, <List of Raw Data>, <Use Density> , <Density Scale Factor>
(optional) )::
  Returns a list of frequencies for the corresponding xref:/commands/Histogram_Command.adoc[Histogram Command].
