= Function Command
:page-en: commands/Function
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Function( <List of Numbers> )::
  Yields the following function: The first two numbers determine the start _x_-value and the end _x_-value. The rest of
  the numbers are the _y_-values of the function in between in equal distances.

[EXAMPLE]
====

* `++Function[{2, 4, 0, 1, 0, 1, 0}]++` yields a triangular wave between _x = 2_ and _x = 4_.
* `++Function[{-3, 3, 0, 1, 2, 3, 4, 5}]++` yields a linear equation with slope _= 1_ between _x = -3_ and _x = 3_.

====

Function( <Expression>, <Parameter Variable 1>, <Start Value>, <End Value>, <Parameter Variable 2>, <Start Value>, <End Value> )::
  Restricts the visualization of the representative surface of a function of two variables in 3D space.

[EXAMPLE]
====

The expression `++a(x, y) = x + 0y++` creates a function of two variables, whose graph in 3D space is the
*[.underline]#plane#* _z_ = _a_(_x_, _y_) = _x_.`++Function[u, u, 0, 3, v, 0, 2] ++` creates the function of two
variables _b_(_u_, _v_) = _u_, whose graph in 3D space is the *[.underline]#rectangle#* Polygon[(0, 0, 0), (3, 0, 3),
(3, 2, 3), (0, 2, 0)] contained in plane _z_ = _a_(_x_,_y_) = _x_.

====
