= FutureValue Command
:page-en: commands/FutureValue
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

FutureValue( <Rate>, <Number of Periods>, <Payment>, <Present Value (optional)>, <Type (optional)> )::
  Returns the future value of an investment based on periodic, constant payments and a constant interest rate.

* *<Rate>* Interest rate per period.
* *<Number of Periods>* Total number of payment periods in an annuity.
* *<Payment>* The amount paid in each period.
* *<Present Value (optional)>* Total amount that a series of future payments is worth now. If you do not enter a value,
it is assumed to be 0.
* *<Type (optional)>* Indicates when payments are due. If you do not enter a value or you enter 0 the payment is due at
the end of the period. If you enter 1 it is due at the beginning of the period.

[EXAMPLE]
====

`++FutureValue(10%/12, 15, -200, 0, 1)++` yields a future value of 3207.99.

====

[NOTE]
====

Make sure that you are consistent about the units you use for `++<Rate>++` and `++<Number of Periods>++`. If you make
monthly payments on a four-year loan at an annual interest rate of 10 percent, use 10%/12 for rate and 4*12 for number
of payments.

====

[NOTE]
====

For all arguments, cash paid out is represented by negative numbers and cash received by positive numbers.

====

[NOTE]
====

See also xref:/commands/Payment.adoc[Payment], xref:/commands/Rate.adoc[Rate], xref:/commands/PresentValue.adoc[Present
Value] and xref:/commands/Periods.adoc[Periods] commands.

====
