= Gamma Command
:page-en: commands/Gamma
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Gamma( <Alpha>, <Beta>, <Variable Value> )::
  Calculates the value of the cumulative distribution function of a http://en.wikipedia.org/wiki/Gamma_distribution[Gamma distribution] at _variable value v_, i.e. the
  probability _P(X ≤ v)_ where _X_ is a random variable with a Gamma distribution defined by the parameters _alpha_ and _beta_.

[NOTE]
====

This syntax returns the probability at a given value, that is the area under the Gamma distribution curve to the left of the given _x_-coordinate.

====


Gamma( <Alpha>, <Beta>, <Variable Value>, <Boolean Cumulative> )::
  If _Cumulative = true_, calculates the value of the cumulative distribution function of a Gamma distribution with given _alpha_ and _beta_ at the given _variable value_, otherwise it calculates the probability density function of the distribution at _variable value_.

Gamma( <Alpha>, <Beta>, x, <Boolean Cumulative> )::
  If _Cumulative = true_, creates the cumulative density function (cdf) of a Gamma distribution with given _alpha_ and _beta_, othewise it creates the probability density function (pdf) of the distribution.
