= If Command
:page-en: commands/If
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

If( <Condition>, <Then> )::
  Yields a copy of the object _Then_ if the condition evaluates to _true_, and an undefined object if it evaluates to
  _false_.

[EXAMPLE]
====

* Let _n_ = 3. `++If(n==3, x + y = 4)++` yields line _x_ + _y_ = 4, because the condition on number _n_ is met.
* Let _n_ = 4. `++If(n==3, x + y = 4)++` creates an _undefined_ object, because the condition on number _n_ is not met .

====

If( <Condition>, <Then>, <Else> )::
  Yields a copy of object _Then_ if the condition evaluates to _true_, and a copy of object _Else_ if it evaluates to
  _false_. *Both objects _must_ be of the same type.*

[EXAMPLE]
====

Let _n_ be a number. `++If(n==3, x + y = 4, x - y = 4)++` yields line _x_ + _y_ = 4 when _n_ = 3, and line _x_ - _y_ = 4
for all _n_ not equal to 3.

====

If( <Condition 1>, <Then 1>, <Condition 2>, <Then 2>, ... , <Else (optional)> )::
  Yields a copy of "Then 1" when first condition is satisfied, "Then 2" if second condition is satisfied etc. If none of
  the conditions are satisfied and Else is given, this command yields a copy of Else. Otherwise undefined is returned.

[EXAMPLE]
====

`++If(a ≟ 1, "Matthew", a ≟ 2,"Larry", a ≟ 3, "Vivian", "Alex")++` When __a__=1 this returns the text "Matthew", for
__a__=2' it returns "Larry", for __a__=3 "Vivian" and for all other values of _a_ it yields "Alex".

====

== Conditional Functions

The *If* command can be used to create conditional functions. Such conditional functions may be used as arguments in any
command that takes a function argument, such as xref:/commands/Derivative.adoc[Derivative],
xref:/commands/Integral.adoc[Integral], and xref:/commands/Intersect.adoc[Intersect].

[EXAMPLE]
====

* `++f(x) = If(x < 3, sin(x), x^2)++` yields a piecewise function that equals _sin(x)_ for _x < 3_ and _x^2^_ for _x ≥
3_.
* `++f(x) = If(0 <= x <= 3, sin(x))++` yields a function that equals _sin(x)_ for x between 0 and 3 (and undefined
otherwise).

[NOTE]
====

A shorter syntax for this is `++f(x) = sin(x), 0 <= x <= 3++`

====

* `++f(x) =If(x<-1,x²,-1<=x<=1,1,-x²+2)++` yields the piecewise function stem:[f(x) = \left\\{\begin\{matrix}\{}
x^\{2}& : &x < -1\\ 1& :& -1 ≤ x ≤ 1\\ -x^\{2} + 2& : &\text\{otherwise} \end\{matrix}\right ].

====

== Multivariate Conditional Functions

The *If* command can also be used to create multivariate conditional functions. In this case, the definition of the
pieces of the given function must contain all the variables of the given function.

[EXAMPLE]
====

Let `++sliderVal = 1++` be a slider in the interval [1,3]. The command
`++f(x,y,a,b,c) = If(sliderVal==1, x + 0y +a + 0b + c, sliderVal==2, 0x+ y^2 + 0a +2b +0c, x + y + 0a + b +0c)++` yields
a multivariate function that equals _x+a+c_ when the slider value is 1, _y^2^ + 2b_ when the slider value is 2, and _x +
y + b_ when the slider value is 3.

====

[NOTE]
====

* Derivative of _If(condition, f(x), g(x))_ gives _If(condition, f'(x), g'(x))_. It does not do any evaluation of limits
at the critical points.
* See section: xref:/Boolean_values.adoc[Boolean values] for the symbols used in conditional statements.

====

== If Command in Scripting

*If* command can be used in scripts to perform different actions under certain conditions.

[EXAMPLE]
====

Let _n_ be a number, and _A_ a point. The command `++If(Mod(n, 7) == 0, SetCoords(A, n, 0), SetCoords(A, n, 1))++`
modifies the coordinates of point _A_ according to the given condition. In this case it would be easier to use
`++ SetCoords(A, n, If(Mod(n, 7) == 0,0,1))++`.

====

[NOTE]
====

Arguments of *If* must be Objects or xref:/commands/Scripting_Commands.adoc[Scripting Commands], not assignments. Syntax
`++b = If(a > 1, 2, 3)++` is correct, but _b = 2_ or _b = 3_ would not be accepted as parameters of *If*.

====
