= IntersectPath Command

IntersectPath( <Line>, <Polygon> )::
  Creates the intersection path between line and polygon.
  +

[EXAMPLE]

====

`IntersectPath(a, triangle)` creates a segment between the first and second intersection point of line _a_ and polygon
_triangle_.

====

IntersectPath( <Polygon>, <Polygon> )::
  Creates the intersection polygon between two given polygons.
  +

[EXAMPLE]

====

`IntersectPath(quadrilateral, triangle)` creates a new polygon as intersection of the two given polygons.

====

[NOTE]

====

The new polygon can either be a quadrilateral, a pentagon or a hexagon. This depends on the position of the vertices of
the given polygons.

====

IntersectPath( <Plane>, <Polygon> )::
  Creates the intersection path between plane and polygon.
  +

[EXAMPLE]

====

`IntersectPath(a, triangle)` creates a segment between the first and second intersection point of plane _a_ and polygon
_triangle_ in the plane of the polygon.

====

IntersectPath( <Plane>, <Quadric> )::
  Creates the intersection path between plane and quadric.
  +

[EXAMPLE]

====

`IntersectPath(a, sphere)` creates a circle as intersection between plane _a_ and quadric _sphere_.

====

[NOTE]

====

See also xref:/commands/Intersect_Command.adoc[Intersect] and xref:/commands/IntersectConic_Command.adoc[IntersectConic]
commands.

====
