= LogNormal Command
:page-en: commands/LogNormal
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

LogNormal( <Mean>, <Standard Deviation>, <Variable Value> )::
  Evaluates the cumulative distribution function of a log-normal distribution at _variable value_, i.e. calculates the
  probability _P(X ≤ v)_ where _X_ is a random variable with a log-normal distribution defined by the given parameters _mean_ and
  _standard deviation_.

LogNormal( <Mean>, <Standard Deviation>, <Variable Value>, <Boolean Cumulative> )::
  If _Cumulative = true_, evaluates the cumulative distribution function of a log-normal distribution with given _mean_ and _standard deviation_ at the given _variable value_, otherwise it evaluates the probability density function of the distribution at _variable value_.

LogNormal( <Mean>, <Standard Deviation>, x, <Boolean Cumulative> )::
  If _Cumulative = true_, creates the cumulative density function (cdf) of a log-normal distribution with given _mean_ and _standard deviation_, otherwise it creates the probability density function (pdf) of the distribution.


[NOTE]
====

This syntax returns the probability at a given value, that is the area under the log-normal distribution curve to the left of the given _x_-coordinate.

====
