= LogNormal Command
:page-en: commands/LogNormal
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

LogNormal( <Mean>, <Standard Deviation>, x )::
  Creates cumulative density function (cdf) of http://en.wikipedia.org/wiki/Log-normal_distribution[log-normal
  distribution] with parameters mean _μ_ and standard deviation _σ_.
LogNormal( <Mean>, <Standard Deviation>, x, <Boolean Cumulative> )::
  If _Cumulative_ is true, creates cumulative density function of log-normal distribution, otherwise creates pdf of
  log-normal distribution.
LogNormal( <Mean>, <Standard Deviation>, <Variable Value> )::
  Calculates the value of cumulative distribution function of log-normal distribution at variable value _v_, i.e. the
  probability _P(X ≤ v)_ where _X_ is a random variable with log-normal distribution given by parameters mean _μ_ and
  standard deviation _σ_.

[NOTE]
====

Returns the probability for a given _x_-coordinate's value (or area under the log-normal distribution curve to the left
of the given _x_-coordinate).

====
