= PathParameter Command

PathParameter( <Point On Path> )::
  Returns the parameter (i.e. a number ranging from _0_ to _1_) of the point that belongs to a
  xref:/Geometric_Objects.adoc[path].
  +

[EXAMPLE]

====

Let `++f(x) = x² + x - 1++` and `++A = (1, 1)++` is a point attached to this function. `++PathParameter(A)++` yields _a
= 0.47_.

====

In the following table stem:[f(x)=\frac\{x}\{1+|x|}] is a function used to map all real numbers into interval (-1,1) and
stem:[\phi(X,A,B)=\frac\{\overrightarrow\{AX}\cdot\overrightarrow\{AB}}\{|AB|^2}] is a linear map from line AB to reals
which sends A to 0 and B to 1.

[cols=",",]
|===
|Line AB |stem:[\frac\{f(\phi(X,A,B))+1}2]

|Ray AB |stem:[f(\phi(X,A,B))]

|Segment AB |stem:[\phi(X,A,B)]

|Circle with center _C_ and radius _r_ |Point stem:[X=C+(r\cdot cos(\alpha),r\cdot sin(\alpha))], where
stem:[\alpha\in(-\pi,\pi)] has path parameter stem:[\frac\{\alpha+\pi}\{2\pi}]

|Ellipse with center _C_ and semiaxes stem:[\vec\{a}], stem:[\vec\{b}] |Point stem:[X=C+\vec\{a}\cdot
cos(\alpha)+\vec\{b}\cdot sin(\alpha)], where stem:[\alpha\in(-\pi,\pi)] has path parameter
stem:[\frac\{\alpha+\pi}\{2\pi}]

|Hyperbola |Point stem:[X = C \pm \vec\{a} ·cosh(t) + \vec\{b} ·sinh(t)] has path parameter stem:[ \frac\{f(t)+1}\{4}]
or stem:[\frac\{f(t)+3}\{4}]

|Parabola with vertex V and direction of axis stem:[\vec\{v}]. |Point stem:[V+\frac\{1}\{2}p\cdot t^2\cdot
\vec\{v}+p\cdot t \cdot \vec\{v}^\{\perp}] has path parameter stem:[\frac\{f(t)+1}2].

|Polyline A~1...A~n~~ |If X lies on A~k~A~k+1~, path parameter of _X_ is stem:[\frac\{k-1+\phi(X,A,B)}\{n-1}]

|Polygon A~1...A~n~~ |If X lies on A~k~A~k+1~ (using A~n+1~=A~1~), path parameter of _X_ is
stem:[\frac\{k-1+\phi(X,A,B)}\{n}]

|List of paths L=\{p~1~,...,p~n~} |If X lies on p~k~ and path parameter of X w.r.t. p~k~ is _t_, path parameter of _X_
w.r.t._L_ is stem:[\frac\{k-1+t}\{n}]

|List of points L=\{A~1~,...,A~n~} |Path parameter of A~k~ is stem:[\frac\{k-1}\{n}]. Point[L,t] returns
stem:[A_\{\lfloor tn\rfloor+1}].

|Locus |

|Implicit polynomial |No formula available.
|===
