= PresentValue Command
:page-en: commands/PresentValue
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

PresentValue( <Rate>, <Number of Periods>, <Payment>, <Future Value (optional)>, <Type (optional)> )::
  Returns the total amount of payments of an investment.

* *<Rate>* Interest rate per period.
* *<Number of Periods>* Total number of payments for the loan.
* *<Payment>* The amount paid in each period.
* *<Future Value (optional)>* A cash balance you want to attain after the last payment. If you do not enter a future
value, it is assumed to be 0.
* *<Type (optional)>* Indicates when payments are due. If you do not enter a value or you enter 0 the payment is due at
the end of the period. If you enter 1 it is due at the beginning of the period.

[EXAMPLE]
====

`++PresentValue(12%/12, 4*12, -100, 5000, 0)++` yields a present value of 696.06.

`++PresentValue(12%/12, 4*12, -100, 5000, 1)++` yields a present value of 734.07.

====
[NOTE]
====

Make sure that you are consistent about the units you use for `++<Rate>++` and `++<Number of Periods>++`. If you make
monthly payments on a four-year loan at an annual interest rate of 12 percent, use 12%/12 for rate and 4*12 for number
of payments.

====

[NOTE]
====

For all arguments, cash paid out is represented by negative numbers and cash received by positive numbers.

====

[NOTE]
====

See also xref:/commands/Payment.adoc[Payment], xref:/commands/Periods.adoc[Periods], xref:/commands/Rate.adoc[Rate] and
xref:/commands/FutureValue.adoc[Future Value] commands.

====
