= RandomUniform Command

RandomUniform( <Min>, <Max> )::
  Returns random real number from http://en.wikipedia.org/wiki/Uniform_distribution_(continuous)[uniform distribution]
  on interval [_min_, _max_].

[EXAMPLE]
====

`++RandomUniform(0, 1)++` returns a random number between _0_ and _1_

====

RandomUniform( <Min>, <Max>, <Number of Samples n> )::
  Returns a list of _n_ random real numbers from http://en.wikipedia.org/wiki/Uniform_distribution_(continuous)[uniform
  distribution] on interval [_min_, _max_].

[EXAMPLE]
====

`++RandomUniform(0, 1, 3)++` returns a list of three random numbers between _0_ and _1_

====

[NOTE]
====

*Notes:*

* `++RandomUniform(0,1)++` is equivalent to `++random()++` (see xref:/Predefined_Functions_and_Operators.adoc[Predefined
Functions and Operators]).
* See also xref:/commands/SetSeed_Command.adoc[SetSeed], xref:/commands/RandomBetween_Command.adoc[RandomBetween],
xref:/commands/RandomElement_Command.adoc[RandomElement], xref:/commands/RandomBinomial_Command.adoc[RandomBinomial],
xref:/commands/RandomNormal_Command.adoc[RandomNormal] , xref:/commands/RandomPoisson_Command.adoc[RandomPoisson]
commands.

====
