= Rate Command
:page-en: commands/Rate
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Rate( <Number of Periods>, <Payment>, <Present Value>, <Future Value (optional)>, <Type (optional)>, <Guess (optional)>
)::
  Returns the interest rate per period of an annuity.

* *<Number of Periods>* Total number of payments for the loan.
* *<Payment>* The amount paid in each period.
* *<Present Value>* Total amount that a series of future payments is worth now.
* *<Future Value (optional)>* A cash balance you want to attain after the last payment. If you do not enter a future
value, it is assumed to be 0.
* *<Type (optional)>* Indicates when payments are due. If you do not enter a value or you enter 0 the payment is due at
the end of the period. If you enter 1 it is due at the beginning of the period.
* *<Guess (optional)>* Your guess for what the rate will be.

[EXAMPLE]
====

`++Rate(5*12, -300, 10000)++` yields a monthly rate of 0.02 (2%).

[NOTE]
====

If you make monthly payments on a five-year loan use 5*12 for `++<Number of Periods>++`.

[NOTE]
====

For all arguments, cash paid out is represented by negative numbers and cash received by positive numbers..

====

[NOTE]
====

See also xref:/commands/Payment.adoc[Payment], xref:/commands/Periods.adoc[Periods],
xref:/commands/PresentValue.adoc[Present Value] and xref:/commands/FutureValue.adoc[Future Value] commands.

====
