= SetValue Command
:page-en: commands/SetValue
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

SetValue( <Boolean>, <0|1> )::
  Sets the state of a boolean / check box : 1 = true, 0 = false

[EXAMPLE]
====

If _b_ is a boolean, `++ SetValue(b,1)++` sets the boolean _b_ as _true_.

====

SetValue( <Object>, <Object> )::
  Let _A_ be the first and _B_ the second object. If _A_ is a xref:/Free_Dependent_and_Auxiliary_Objects.adoc[free
  object] or a xref:/Points_and_Vectors.adoc[Point] restricted to xref:/Geometric_Objects.adoc[Path or Region], its
  value is set to current value of _B_ (i.e. _A_ doesn't change value if _B_ is changed afterwards).

[EXAMPLE]
====

If _f_ is a function, `++SetValue(f, RandomElement({cos(x), 3x+2, ln(x)}))++` defines, at random, f as being one of the
functions proposed in the list.

====

SetValue( <List>, <Number>, <Object> )::
  Let _n_ be the _<Number>_. The command SetValue sets the n-th element of a free list to the current value of the
  object. Number _n_ can be at most 1 + length of L.

SetValue( <Dependent Object>, ? )::
  This is a special syntax that will set a dependent object to undefined without needing to fully redefine it using
  `++=++`.

SetValue( <xref:/Action_Objects.adoc[drop-down list]>, <Number n > )::
  Set _n_ as xref:/commands/SelectedIndex.adoc[the index of the selected element] in the drop-down list.
