= Simplify Command
:page-en: commands/Simplify
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Simplify( <Function> )::
  Simplifies the terms of the given function, if possible.

[EXAMPLE]
====

`++Simplify(x + x + x)++` yields the function _f(x) = 3x_.

====

Simplify( <Text> )::
  Attempts to tidy up text expressions by removing repeated negatives etc.

[EXAMPLE]
====

For _a_ = _b_ = _c_ = -1 `++Simplify("f(x) = " + a + "x² + " + b + "x + " + c)++` yields the text _f(x) = -x^2^ - x -
1_.

====

[NOTE]
====

The xref:/commands/FormulaText.adoc[FormulaText Command] normally produces better results and is simpler.

====

[NOTE]
====

This command needs to load the Computer Algebra System, so can be slow on some computers. Try using the
xref:/commands/Polynomial.adoc[Polynomial Command] instead.

====

== CAS Syntax

Simplify( <Function> )::
  Simplifies the terms of the given function, if possible. Undefined variables can be included in the terms.

[EXAMPLE]
====

*Examples:*

* `++Simplify(3 * x + 4 * x + a * x)++` yields `++ a x + 7x++`.
* `++Assume(x<2,Simplify(sqrt(x-2sqrt(x-1))))++` yields `++-sqrt(abs(x - 1)) + 1++`
* `++Assume(x>2,Simplify(sqrt(x-2sqrt(x-1))))++` yields `++sqrt(x - 1) + 1++`

====

[NOTE]
====

See also xref:/commands/Factor.adoc[Factor Command], xref:/commands/Assume.adoc[Assume Command],
xref:/commands/PartialFractions.adoc[PartialFractions Command], xref:/commands/Expand.adoc[Expand Command],
xref:/commands/Polynomial.adoc[Polynomial Command].

====
