= TDistribution Command
:page-en: commands/TDistribution
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

TDistribution( <Degrees of Freedom>, <Variable Value> )::
  Evaluates the cumulative distribution function of a t-distribution at _variable value v_, i.e. calculates the
  probability _P(X ≤ v)_ where _X_ is a random variable with a t-distribution with the given _degrees of freedom_.

[EXAMPLE]
====

`++TDistribution(10, 0)++` yields _0.5_.

====

[NOTE]
====

This syntax returns the probability at a given value, that is the area under the t-distribution curve to the left of the given _x_-coordinate.


====
TDistribution( <Degrees of Freedom>, <Variable Value>, <Boolean Cumulative> )::
  If _Cumulative = true_, evaluates the cumulative distribution function of a t-distribution with given _degrees of freedom_ at the given _variable value_, otherwise it evaluates the probability density function of the distribution at _variable value_.


TDistribution( <Degrees of Freedom>, x, <Boolean Cumulative> )::
  If _Cumulative = true_, creates the cumulative density function (cdf) of a https://en.wikipedia.org/wiki/Student%27s_t-distribution[t-distribution] with given _degrees of freedom_, otherwise it creates the probability density function (pdf) of the distribution.


== CAS Syntax

TDistribution( <Degrees of Freedom>, <Variable Value> )::
  Evaluates the cumulative distribution function of a t-distribution at _variable value v_, i.e. calculates the
  probability _P(X ≤ v)_ where _X_ is a random variable with a t-distribution with the given _degrees of freedom_.

[EXAMPLE]
====

`++TDistribution(10, 0)++` yields _0.5_.

====
