= TDistribution Command

TDistribution( <Degrees of Freedom>, x )::
  Creates cumulative density function (cdf) of http://en.wikipedia.org/wiki/Student%27s_t-distribution[t-distribution]
  with given degrees of freedom.
TDistribution( <Degrees of Freedom>, x, <Boolean Cumulative> )::
  If _Cumulative_ is true, creates cumulative distribution function of t-distribution, otherwise creates pdf of
  t-distribution.
TDistribution( <Degrees of Freedom>, <Variable Value> )::
  Calculates the value of cumulative distribution function of t-distribution at _variable value v_, i.e. the probability
  _P(X ≤ v)_ where _X_ is a random variable with t-distribution with given degrees of freedom.

[EXAMPLE]
====

`TDistribution(10, 0)` yields _0.5_.

====

[NOTE]
====

Returns the probability for a given _x_-coordinate's value (or area under the t-distribution curve to the left of the
given _x_-coordinate).

====

== [#CAS_Syntax]#CAS Syntax#

TDistribution( <Degrees of Freedom>, <Variable Value> )::
  Calculates the value of cumulative distribution function of t-distribution at _variable value v_, i.e. the probability
  _P(X ≤ v)_ where _X_ is a random variable with t-distribution with given degrees of freedom.

[EXAMPLE]
====

`TDistribution(10, 0)` yields _0.5_.

====
