= TMean2Estimate Command

TMean2Estimate( <List of Sample Data 1>, <List of Sample Data 2>, <Level>, <Boolean Pooled> )::
  Calculates a t confidence interval estimate of the difference between two population means using the given sample data
  sets and confidence _Level_.
  +
  If _Pooled_ = true, then population variances are assumed equal and sample standard deviations are combined in
  calculation.
  +
  If _Pooled_ = false, then population variances are not assumed equal and sample standard deviations are not combined.
  +
  Results are returned in list form as _\{lower confidence limit, upper confidence limit}_.

TMean2Estimate( <Sample Mean 1>, <Sample Standard Deviation 1>, <Sample Size 1>, <Sample Mean 2>, <Sample Standard
Deviation 2>, <Sample Size 2>, <Level>, <Boolean Pooled> )::
  Calculates a t confidence interval estimate of the difference between two population means using the given sample
  statistics and confidence _Level_. _Pooled_ is defined as above. Results are returned in list form as _\{lower
  confidence limit, upper confidence limit}_.
