= TriangleCurve Command
:page-en: commands/TriangleCurve
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

TriangleCurve( <Point P>, <Point Q>, <Point R>, <Equation in A, B, C> )::
  Creates implicit polynomial, whose equation in
  http://en.wikipedia.org/wiki/Barycentric_coordinate_system_(mathematics)[barycentric coordinates] with respect to
  points _P_, _Q_, _R_ is given by the fourth parameter; the barycentric coordinates are referred to as _A_, _B_, _C_.

[EXAMPLE]
====

If _P_, _Q_, _R_ are points, `++TriangleCurve(P, Q, R, (A - B)*(B - C)*(C - A) = 0)++` gives a cubic curve consisting of
the medians of the triangle _PQR_.

====

[EXAMPLE]
====

`++TriangleCurve(A, B, C, A*C = 1/8)++` creates a hyperbola such that tangent, through _A_ or _C_, to this hyperbola
splits triangle _ABC_ in two parts of equal area.

====

[EXAMPLE]
====

`++TriangleCurve(A, B, C, A² + B² + C² - 2B C - 2C A - 2A B = 0)++` creates the
http://en.wikipedia.org/wiki/Steiner_inellipse[Steiner inellipse] of the triangle _ABC_, and
`++TriangleCurve(A, B, C, B C + C A + A B = 0)++` creates the http://en.wikipedia.org/wiki/Steiner_ellipse[Steiner
circumellipse] of the triangle _ABC_.

====

[NOTE]
====

The input points can be called _A_, _B_ or _C_, but in this case you cannot use e.g. _x(A)_ in the equation, because _A_
is interpreted as the barycentric coordinate.

====
