= Triangular Command

Triangular( <Lower Bound>, <Upper Bound>, <Mode>, x )::
  Creates cumulative density function of http://en.wikipedia.org/wiki/Triangular_distribution[triangular distribution]
  with parameters _lower Bound, upper Bound, Mode_.
Triangular( <Lower Bound>, <Upper Bound>, <Mode>, x, <Boolean Cumulative> )::
  If _Cumulative_ is true, creates cumulative distribution function of triangular distribution, otherwise creates
  probability density function of triangular distribution.
Triangular( <Lower Bound>, <Upper Bound>, <Mode>, <Variable Value> )::
  Calculates the value of cumulative distribution function of triangular distribution at _Variable Value v_, i.e. the
  probability _P(X≤v)_ where _X_ is a random variable with triangular distribution given by parameters _lower Bound,
  upper Bound, Mode_.
  +

[EXAMPLE]
====

`Triangular(0, 5, 2, 2)` yields _0.4_.

====

[NOTE]
====

Returns the probability for a given _x_-coordinate's value (or area under the triangular distribution curve to the left
of the given _x_-coordinate).

====
