= Weibull Command
:page-en: commands/Weibull
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Weibull( <Shape>, <Scale>, x )::
  Creates cumulative density function (cdf) of http://en.wikipedia.org/wiki/Weibull_distribution[Weibull distribution]
  with parameters shape _k_ and scale _λ_
Weibull( <Shape>, <Scale>, x, <Boolean Cumulative> )::
  If _Cumulative_ is true, creates cumulative distribution function of Weibull distribution, otherwise creates pdf of
  Weibull distribution.
Weibull( <Shape>, <Scale>, <Variable Value> )::
  Calculates the value of cumulative distribution function of Weibull distribution at variable value _v_, i.e. the
  probability _P(X ≤ v)_ where _X_ is a random variable with Weibull distribution given by parameters shape _k_ and
  scale _λ_.

[EXAMPLE]
====

* `++Weibull(0.5, 1, 0)++` yields _0_.
* `++Weibull(0.5, 1, 1)++` yields _stem:[1 - \frac{1} { e } ]._

====

[NOTE]
====

Returns the probability for a given _x_-coordinate's value (or area under the Weibull distribution curve to the left of
the given _x_-coordinate).

====
