= Intervals
:page-en: Intervals
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

An interval is a set of numbers between upper and lower bound. To create an interval, type e.g. `++2 < x < 3++` in
xref:/Input_Bar.adoc[Input Bar]. Interval in previous example is open. You can also define closed (`++2 ≤ x ≤ 3++`) and
semi-closed (`++2 ≤ x < 3++`) intervals.

[NOTE]
====

See also xref:/Boolean_values.adoc[Boolean values].

====

To determine whether number _c_ belongs to interval _r_ type `++r(c)++` into the Input Bar, the result will be a Boolean
value. Generalization of intervals are xref:/Inequalities.adoc[Inequalities].

== Commands for intervals

* xref:/commands/Min.adoc[Min], xref:/commands/Max.adoc[Max], xref:/commands/Midpoint.adoc[Midpoint] for an interval
with lower bound _a_ and upper bound _b_ return numbers _a_, _b_ and stem:[\frac{a+b}2] respectively. The result
doesn't depend on whether the interval is open, closed or semi-closed.
* xref:/commands/Point.adoc[Point] returns a moveable xref:/Points_and_Vectors.adoc[point] whose x-coordinate belongs to
the interval and y-coordinate is 0.
* xref:/commands/PointIn.adoc[PointIn] returns a moveable point whose x-coordinate belongs to the interval and
y-coordinate may be changed arbitrarily.
