= Линии и оски
:page-en: Lines_and_Axes
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

== Линии

Можете да внесете линија како линеарна равенка со x и y или во параметарски обликво xref:/Поле_за_внес.adoc[Поле за
внес]. Во двата случаи претходно дефинирани променливи (на пример броеви, точки, вектори) може да се користат во рамките
на равенката.

[NOTE]
====

Можете да внесете име на линијата во почетокот на внесување проследено со две точки.

====

[EXAMPLE]
====

* Внесете `++g: 3x + 4y = 2++` за да влезат во линија g како линеарна равенка.
* Можете да внесете линија во параметарски облик на тој начин: `++g: X = (-5, 5) + t (4, -3)++`
* Дефинирање на параметрите m = 2 и b = -1. Потоа, можaт да влезат во равенката `++h: y = m*x + b++` да се добие линија
h за y во пресечен облик.

====

== Оски

Двете координатни оски се достапни во команди со користење на имиња _x-оска_ и _y-оска"._

[EXAMPLE]
====

Командата `++Нормала[A, x-оска]++` конструира нормална линија на x-оската преку одредена точка А

====
