= Aanhechtenkopie Commando
:page-en: commands/AttachCopyToView
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Aanhechtenkopie( <Object>, <View 0|1|2> )::
  Als _View = 0_ wordt een kopie gemaakt van een gegeven object. Voor _View = 1_ of _View = 2_ creëert het commando een
  afhankelijke kopie van het gegeven object met een vaste afmeting in het gegeven xref:/Tekenvenster.adoc[Tekenvenster]
  .
Aanhechtenkopie( <Object>, <View 0|1|2>, <Punt 1>, <Punt 2>, <Schermpunt 1>, <Schermpunt 2> )::
  Als _View = 0_ wordt een kopie gemaakt van een gegeven object. Voor _View = 1_ of _View = 2_ creëert het commando een
  afhankelijke kopie van het gegeven object waarbij de afmeting in het gegeven xref:/Tekenvenster.adoc[Tekenvenster]
  wordt aangepast volgens de affiene transformatie die "Punt1" afbeeldt op een punt waarvan de schermcoördinaten (in
  pixels) gelijk zijn aan _Schermpunt 1_, en _Punt 2_ op een punt waarvan de schermcoördinaten gelijk zijn aan
  _Schermpunt 2_.

[EXAMPLE]
====

Bijvoorbeeld: `++veelhoek = Veelhoek((0, 0), (1, 0), (1, 1), (0, 1))++`. Wanneer Tekenvenster 1 actief is, creëert
`++Aanhechtenkopie(veelhoek, 1, (0, 0), (1, 1), (0, 0), (100, 100))++` een vierkant _100px x 100px_ in de
linkerbovenhoek van het Tekenscherm.

====

[EXAMPLE]
====

Bijvoorbeeld: `++veelhoek = Veelhoek((0, 0), (1, 0), (1, 1), (0, 1))++`. Wanneer Tekenvenster 1 actief is, creëert
`++Aanhechtenkopie(veelhoek, 1)++` een vierkant met dezelfde afmeting op dezelfde plaats.

====
