= Aanvangswaarde Commando
:page-en: commands/PresentValue
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Aanvangswaarde( <Rentevoet>, <Aantal perioden>, <Termijn>, <Eindwaarde (optioneel)>, <Type (optioneel)> )::
  Berekent de aanvangswaarde van een http://en.wikipedia.org/wiki/nl:Annu%C3%AFteit[Annuïteit].

* *<Rentevoet>* Rentevoet per periode.
* *<Aantal perioden>* Totaal aantal betalingen in het verloop van de annuïteit.
* *<Termijn>* Het bedrag dat elke periode betaald wordt.
* *<Eindwaarde (optioneel)>* Het saldo na de laatste betaling. Wanneer je geen waarde ingeeft, wordt het gelijkgesteld
aan 0.
* *<Type (optioneel)>* Geeft aan wanneer de betalingen gebeuren. Wanneer je niets invult (of 0) gebeuren de betalingen
op het einde van elke periode (postnumerando. Vul je 1 in dan gebeuren de betalingen in het begin van elke periode
(prenumerando)

[EXAMPLE]
====

`++Aanvangswaarde( 12%/12, 4*12, -100, 5000, 0 )++` geeft 696.06.

`++Aanvangswaarde( 12%/12, 4*12, -100, 5000, 1 )++` geeft 734.07.

====

[NOTE]
====

Zorg er voor dat de eenheden die je gebruikt voor `++<Rentevoet>++` en `++<Aantal perioden>++` overeenkomen. Bij
maandelijkse betalingen met een gegeven jaarlijkse rentevoet over een looptijd van 4 jaar, moet je zowel rentevoet en
aantal periodes omrekenen naar maanden.

====

[NOTE]
====

Voor alle argumenten, worden betalingen voorgesteld door negatieve getallen en ontvangsten door positieve getallen.

====

[NOTE]
====

Zie ook de commando's xref:/commands/Termijn.adoc[Termijn], xref:/commands/Rentevoet.adoc[Rentevoet],
xref:/commands/Eindwaarde.adoc[Eindwaarde] en xref:/commands/Perioden.adoc[Perioden].

====
