= Chi Kwadraat Test Commando
:page-en: commands/ChiSquaredTest
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Chi_Kwadraat_Test( <Matrix> )::
  Voert een https://en.wikipedia.org/wiki/Chi-squared_test[chi-kwadraat test] uit die de gegeven matrix met
  waarnemingswaarden vergeljikt met de matrix met de verwachtingswaarden, bepaald door de onafhankelijkheidshypothese.
  De matrix met de verwachtingswaarden wordt intern berekend. Elke verwachtingswaarde wordt berekend a.d.h.v. de rij- en
  kolomtotalen van de gegeven matrix met waarnemingswaarden met de formule:
  stem:[ \text\{verwachtingswaarde} = \frac\{\text\{rijtotaal} × \text\{kolomtotaal}}\{\text\{totaal waargenomen}} ]

De resultaten worden getoond in een lijst in de vorm _\{verwachtingswaarde, chi-kwadraat test}_.

Chi_Kwadraat_Test( <Lijst>, <Lijst> )

Voert een https://en.wikipedia.org/wiki/Goodness_of_fit[Goodness of Fit test] uit die de gegeven lijst met
waarnemingswaarden vergelijkt met de gegeven lijst met verwachtingswaarden.

De resultaten worden getoond in een lijst in de vorm _\{verwachtingswaarde, chi-kwadraat test}_.

Chi_Kwadraat_Test( <Matrix>, <Matrix> )

Voert een https://en.wikipedia.org/wiki/Chi-squared_test[chi-kwadraat test] uit die de gegeven matrix met
waarnemingswaarden vergelijkt met de gegeven matrix met verwachtingswaarden.

De resultaten worden getoond in een lijst _\{verwachtingswaarde, chi-kwadraat test}_.

[EXAMPLE]
====

`++Chi_Kwadraat_Test({{1, 2, 1}, {3, 2, 3}}, {{2, 3, 2}, {4, 2, 3}})++` geeft _\{0.45, 1.58}_.

====

[EXAMPLE]
====

`++Chi_Kwadraat_Test({1, 2, 3, 4}, {3, 2, 4, 2})++` geeft _\{0.31, 3.58}_.

====

[EXAMPLE]
====

`++Chi_Kwadraat_Test({{1, 2, 1}, {3, 2, 3}}++` geeft _\{0.69, 0.75}_.

====
