= COplossingen Commando
:page-en: commands/CSolutions
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

== CAS Syntax

COplossingen( <Vergelijking> )::
  Lost een gegeven vergelijking op voor de hoofdveranderlijke en toont een lijst van de oplossingen, waaronder complexe.
COplossingen( <Vergelijking>, <Variabele> )::
  Lost een gegeven vergelijking op voor een gegeven variabele en toont een lijst van de oplossingen, waaronder complexe.
COplossingen( <Lijst met vergelijkingen>, <List met variabelen> )::
  Lost een gegeven lijst met vergelijkingen op voor een gegeven lijst variabelen en toont een lijst van de oplossingen,
  waaronder complexe.

[EXAMPLE]
====

`++COplossingen({y^2 = x - 1, x = 2 * y - 1}, {x, y})++` geeft stem:[\begin\{pmatrix}1 + 2 ί&1 + ί\\1 - 2 ί&1 -
ί\end\{pmatrix}], de complexe oplossingen van _y^2^ = x - 1_ and _x = 2 * y - 1_.

====

[EXAMPLE]
====

`++CSolutions(a^2 = -1, a)++` geeft _\{ί, -ί}_, de complexe oplossingen van _a^2^ = -1_.

====

[EXAMPLE]
====

`++COplossingen(x^2 = -1)++` geeft _\{ί, -ί}_, de complexe oplossingen van _x^2^ = -1_.

====

[NOTE]
====

* Het complexe ί typ je als /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode].

====
