= Coëfficiënten Commando
:page-en: commands/Coefficients_Command
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Coëfficiënten( <Veelterm> )::
  Creëert de lijst van alle coëfficiënten stem:[a_k,a_\{k-1},\ldots,a_1, a_0] van de veelterm
  stem:[a_kx^k+a_\{k-1}x^\{k-1}+\cdots+a_1x+a_0].
Coëfficiënten( <Kegelsnede> )::
  Creëert de lijst van de coëfficiënten _a_, _b_, _c_, _d_, _e_, _f_ van een kegelsnede in de standaardvorm:
  stem:[a\cdot x^2 + b\cdot y^2 + c + d\cdot x\cdot y + e\cdot x + f\cdot y = 0]

[EXAMPLE]
====

`++Coëfficiënten(x^3 - 3 x^2 + 3 x)++` geeft _\{1, -3, 3, 0}_, de lijst van alle coëfficiënten van stem:[x^3 - 3 x^2 + 3
x].

====

[NOTE]
====

Voor de vergelijking van een rechte in de vorm _l_: _ax_ + _by_ + _c_ = 0 verkrijg je de coëfficiënten met de syntax
_x_(_l_), _y_(_l_), _z_(_l_).

[EXAMPLE]
====

`++rechte: 3x + 2y - 2 = 0++`: `++x(rechte)++` geeft 3, `++y(rechte)++` geeft 2, en `++z(rechte)++` geeft -2

====

====

== CAS venster

Coëfficiënten( <Veelterm> )::
  Creëert de lijst van alle coëfficiënten van de veelterm in de hoofdveranderlijke.
Coëfficiënten( <Veelterm>, <Variabele> )::
  Creëert de lijst van alle coëfficiënten van de veelterm in de gegeven veranderlijke.

[EXAMPLE]
====

* `++Coëfficiënten(a^3 - 3 a^2 + 3 a, a)++` geeft _\{1, -3, 3, 0}_, de lijst van alle coëfficiënten van stem:[a^3 - 3
a^2 + 3 a]
* `++Coëfficiënten(a^3 - 3 a^2 + 3 a, x)++` geeft \{__a__³ - 3 __a__² + 3 _a_}.

====

[EXAMPLE]
====

`++Coëfficiënten(x^3 - 3 x^2 + 3 x)++` geeft _\{1, -3, 3, 0}_, de lijst van alle coëfficiënten van stem:[x^3 - 3 x^2 + 3
x].

====
