= Eenheidsvector Commando
:page-en: commands/UnitVector
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Eenheidsvector( <Vector> )::
  Geeft een vector met lengte 1 met dezelfde richting en zin als een gegeven (en vooraf gedefinieerde) vector.
Eenheidsvector( <Rechte> )::
  Geeft de richtingsvector van de gegeven rechte met lengte 1.
Eenheidsvector( <Lijnstuk> )::
  Geeft de richtingsvector van het gegeven lijnstuk met lengte 1.

[EXAMPLE]
====

Met `++s = Lijnstuk((1,1),(4,5))++`.

geeft `++Eenheidsvector(s)++` _stem:[\begin\{pmatrix}0.6\\0.8\end\{pmatrix}]_.

====

[EXAMPLE]
====

`++Eenheidsvector(3x + 4y = 5)++` geeft _stem:[\begin\{pmatrix}0.8\\-0.6\end\{pmatrix}]_.

====

[EXAMPLE]
====

Voor _v=stem:[\begin\{pmatrix}3\\4\end\{pmatrix}]_ geeft `++Eenheidsvector(v)++`
_stem:[\begin\{pmatrix}0.6\\0.8\end\{pmatrix}]_.

====

== CAS venster

Eenheidsvector( <Vector> )::
  Geeft een vector met lengte 1 met dezelfde richting en zin als een gegeven vector.

[EXAMPLE]
====

`++Eenheidsvector((2, 4, 4))++` geeft _(stem:[\frac\{1}\{3}], stem:[\frac\{2}\{3}], stem:[\frac\{2}\{3}])_.

====

[EXAMPLE]
====

`++Eenheidsvector((a, b))++` geeft _(stem:[\frac\{a}\{\sqrt\{a^\{2} + b^\{2}}}], stem:[\frac\{b}\{\sqrt\{a^\{2} +
b^\{2}}}])_.

====
