= Erlang Commando
:page-en: commands/Erlang
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Erlang( λ, k, x )::
  Creëert de kansdichtheidsfunctie (pdf) van de https://en.wikipedia.org/wiki/Erlang_distribution[Erlang verdeling] met
  als parameters _k_ en _λ_.
Erlang( λ, k, <Waarde Variabele> )::
  Creëert de waarde van de kansdichtheidsfunctie (pdf) van de Erlang verdeling met als waarde _v_, dit is de kans _P(X ≤
  v)_ waarbij _X_ een willekeurige variabele is met een Erlang verdeling met als parameters _k_ en _λ_.
Erlang( λ, k, x, <Logisch Cumulatief> )::
  Wanneer _Cumulatief_ gelijk is aan 'true', creëert het de cumulatieve dichtheidsfunctie van de Erlang verdeling,
  anders de pdf van de Erlang verdeling.

[NOTE]
====

Geeft de kans voor een gegeven _x_-coördinaat (of oppervlakte onder de grafiek van de Erlang verdeling links van de
gegeven _x_-coördinaat).

====

== CAS Venster

Erlang( λ, k, x )::
  Creëert de kansdichtheidsfunctie (pdf) van de https://en.wikipedia.org/wiki/Erlang_distribution[Erlang verdeling] met
  als parameters _k_ en _λ_.
Erlang( λ, k, x, <Logisch Cumulatief> )::
  Wanneer _Cumulatief_ gelijk is aan 'true', creëert het de cumulatieve dichtheidsfunctie van de Erlang verdeling,
  anders de pdf van de Erlang verdeling.
Erlang( λ, k, <Waarde Variabele> )::
  Creëert de waarde van de kansdichtheidsfunctie (pdf) van de Erlang verdeling met als waarde _v_, dit is de kans _P(X ≤
  v)_ waarbij _X_ een willekeurige variabele is met een Erlang verdeling met als parameters _k_ en _λ_.

[NOTE]
====

Geeft de kans voor een gegeven _x_-coördinaat (of oppervlakte onder de grafiek van de Erlang verdeling links van de
gegeven _x_-coördinaat).

====
