= ExpRegr Commando
:page-en: commands/FitExp_Command
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

ExpRegr( <Lijst van punten> )::
  Berekent de exponentiële regressiekromme in de vorm stem:[a \cdot ℯ^\{bx}].

[EXAMPLE]
====

`++ExpRegr({(0, 1), (2, 4)})++` geeft stem:[ℯ^\{0.69x}].

====

== CAS Venster

ExpRegr( <Lijst van punten> )::
  Berekent de exponentiële regressiekromme in de vorm stem:[a \cdot ℯ^\{bx}].

[EXAMPLE]
====

`++ExpRegr({(0, 1), (2, 4)})++` geeft stem:[ℯ^\{0.69x}].

====

[NOTE]
====

* Wil je het antwoord in de vorm stem:[ a \cdot b^x ], gebruik dan het commando
xref:/commands/PassendeGroei.adoc[PassendeGroei Commando].
* Het getal van Euler ℯ krijg je met de toetscode /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode].
* Zie ook xref:/commands/LogistischeRegr.adoc[Logistische regressie], xref:/commands/LogRegr.adoc[Logaritmische
regressie], xref:/commands/MachtsRegr.adoc[Machtsregressie], xref:/commands/PassendeGroei.adoc[Passende groei],
xref:/commands/Regressielijn.adoc[Lineaire regressie], xref:/commands/SinRegr.adoc[Sinusregressie] en
xref:/commands/VeeltermRegr.adoc[Veeltermregressie].

====
