= Frequentiepolygoon Commando
:page-en: commands/FrequencyPolygon
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

[NOTE]
====

Een frequentiepolygoon is een lijngrafiek die de middens van de bovenste lijnstukken van de staven van een histogram
verbindt. Het gebruik van dit commando is dus hetzelfde als het gebruik van xref:/commands/Histogram.adoc[Histogram
Commando].

====

Frequentiepolygoon( <Lijst met klassengrenzen>, <Lijst met hoogtes> )::
  Creëert een frequentiepolygoon door de punten volgens de gegeven hoogtes. De klassengrenzen bepalen de x-coördinaat
  van elk punt.
Frequentiepolygoon( <Lijst met klassengrenzen>, <Lijst met waarnemingstetallen>, <Boolean Gebruiksdichtheid>,
<Dichtheidsschaalfactor> )::
  Creëert een frequentiepolygoon vanuit de waarnemingstetallen. De klassengrenzen bepalen de x-coördinaten van de punten
  en worden gebruikt om te bepalen hoeveel waarnemingsgetallen tot elke klasse behoren. De y-coördinaat van een punt
  word al volgt bepaald:

* Als _Gebruiksdichtheid = true_, hoogte = (Dichtheidsschaalfactor) * (klassenfrequentie) / (klassenbreedte)
* Als _Gebruiksdichtheid = false_, hoogte = klassenfrequentie

Standaard is de Gebruiksdichtheid = true en de Dichtheidsschaalfactor= 1.

Frequentiepolygoon( <Boolean Cumulative>, <Lijst met klassengrenzen>, <Lijst met waarnemingstetallen>, <Boolean
Gebruiksdichtheid>, <Dichtheidsschaalfactor> )

Als _Cumulatief = true_ creëert het een frequentiepolygoon waarbij de y-coördinaat van elk punt gelijk is aan de
klassenfrequentieof plus de som van alle vorige frequenties.

[NOTE]
====

Voor voorbeelden zie xref:/commands/Histogram.adoc[Histogram Commando].

====
