= FVerdeling Commando
:page-en: commands/FDistribution
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

FVerdeling( <Aantal Vrijheidsgraden Teller>, <Aantal Vrijheidsgraden Noemer>, x )::
  Creëert de kansdichtheidsfunctie (pdf) of https://en.wikipedia.org/wiki/F-distribution[F-verdeling] met als parameters
  _t, n_ (_t_ voor _Aantal Vrijheidsgraden Teller_, _n_ voor _Aantal Vrijheidsgraden Noemer_).
FVerdeling( <Aantal Vrijheidsgraden Teller>, <Aantal Vrijheidsgraden Noemer>, x, <Logisch Cumulatief> )::
  Als _Cumulatief_ = true, creëert het de cumulatieve dichtheidsfunctie van de F-verdeling, anders creëert het de pdf
  van de F-verdeling.
FVerdeling( <Aantal Vrijheidsgraden Teller>, <Aantal Vrijheidsgraden Noemer>, <Waarde Variabele> )::
  Berekent de waarde van de cumulatieve dichtheidsfunctie van de F-verdeling voor _Waarde Variabele v_, dit is de kans
  _P(X≤v)_ waarbij _X_ een willekeurige variabele is met F-verdeling, bepaald door de parameters _t, n_ (_t_ voor
  _Aantal Vrijheidsgraden Teller_, _n_ voor _Aantal Vrijheidsgraden Noemer_).

[NOTE]
====

Geeft de kans voor een gegeven _x_-coördinaat (of oppervlak onder de grafiek van de F-verdeling links van de gegeven
_x_-coördinaat).

====

== CAS Venster

Berekent de waarde van de cumulatieve dichtheidsfunctie van de F-verdeling voor _Waarde Variabele v_, dit is de kans
_P(X≤v)_ waarbij _X_ een willekeurige variabele is met F-verdeling, bepaald door de parameters _t, n_ (_t_ voor _Aantal
Vrijheidsgraden Teller_, _n_ voor _Aantal Vrijheidsgraden Noemer_).
