= GoniometrieCombineer Commando
:page-en: commands/TrigCombine
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

GoniometrieCombineer( <Uitdrukking> )::
  Vormt een goniometrische uitdrukking met producten van goniometrische functies om tot een uitdrukking zonder producten
  maar met sommen van variabelen.
GoniometrieCombineer( <Uitdrukking>, <Doelfunctie> )::
  Vormt een goniometrische uitdrukking met producten van goniometrische functies om tot een uitdrukking zonder producten
  maar met sommen van variabelen, waarbij de voorkeur wordt gegeven aan de gegeven doelfunctie.

[EXAMPLE]
====

`++GoniometrieCombineer(sin(x) + cos(x), sin(x))++` geeft stem:[ \{\sqrt{2} sin \left( x + \frac{1}\{4} \pi \right)}
].

====

[EXAMPLE]
====

`++GoniometrieCombineer(sin(x) + cos(x))++` geeft stem:[ \{\sqrt{2} cos \left( x - \frac{1}\{4} \pi \right)} ].

====

[EXAMPLE]
====

`++GoniometrieCombineer(sin(x) cos(3x))++` geeft stem:[\{\frac{1}\{2} sin \left( 4 x \right) - \frac{1}\{2} sin \left(
2 x \right)}].

====

== CAS Venster

GoniometrieCombineer( <Uitdrukking> )::
  Vormt een goniometrische uitdrukking met producten van goniometrische functies om tot een uitdrukking zonder producten
  maar met sommen van variabelen.

[EXAMPLE]
====

`++GoniometrieCombineer(sin(p) cos(3p))++` geeft stem:[\{\frac{1}\{2} sin \left( 4 p \right) - \frac{1}\{2} sin
\left( 2 p \right)}].

====

GoniometrieCombineer( <Uitdrukking>, <Doelfunctie> )::
  Vormt een goniometrische uitdrukking met producten van goniometrische functies om tot een uitdrukking zonder producten
  maar met sommen van variabelen, waarbij de voorkeur wordt gegeven aan de gegeven doelfunctie.

[EXAMPLE]
====

`++GoniometrieCombineer(sin(p) + cos(p), sin(x))++` geeft stem:[ \{\sqrt{2} sin \left( p + \frac{1}\{4} \pi \right)}
].

====

[NOTE]
====

Zie ook xref:/commands/GoniometrieWerkuit.adoc[Goniometrie_Werkuit Commando] en
xref:/commands/Gonio_Vereenvoudig.adoc[GonioVereenvoudig Commando].

====
