= IntegraalTussen Commando
:page-en: commands/IntegralBetween
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

IntegraalTussen( <Functie>, <Functie>, <Start x-Waarde>, <Eind x-Waarde> )::
  Geeft de bepaalde integraal van de verschilfunctie _f(x) ‐ g(x)_ van twee functies _f_ en _g_ over het interval _[a,
  b]_, waarbij _a_ het eerste getal is en _b_ het tweede, naar de hoofdveranderlijke.
IntegraalTussen( <Functie>, <Functie>, <Start x-Waarde>, <Eind x-Waarde>, <Logisch Evalueer> )::
  Geeft de bepaalde integraal van de verschilfunctie _f(x) ‐ g(x)_ van twee functies _f_ en _g_ over het interval _[a,
  b]_, waarbij _a_ het eerste getal is en _b_ het tweede, naar de hoofdveranderlijke en kleurt ook de overeenkomende
  oppervlakte in als _Evaluate_ = _true_. Wanneer _Evaluate_ = _false_ wordt de overeenkomende oppervlakte ingekleurd
  maar wordt de waarde van de integraal value niet berekend.

[NOTE]
====

Dit commando kleurt ook de oppervlakte tussen de grafieken van _f_ en _g_ in.

====

== CAS venster

IntegraalTussen( <Functie>, <Functie>, <Beginwaarde interval>, <Eindwaarde interval> )::
  Geeft de bepaalde integraal van de verschilfunctie _f(x) ‐ g(x)_ van twee functies _f_ en _g_ over het interval
  _[Beginwaarde, Eindwaarde]_ naar de hoofdveranderlijke.
IntegraalTussen( <Functie>, <Functie>, <Variabele>, <Beginwaarde>, <Eindwaarde> )::
  Geeft de bepaalde integraal van de verschilfunctie _f(x) ‐ g(x)_ van twee functies _f_ en _g_ over het interval
  _[Beginwaarde, Eindwaarde]_ naar de gegeven veranderlijke.

[EXAMPLE]
====

`++IntegraalTussen(a * sin(t), a * cos(t), t, π / 4, π * 5 / 4)++` geeft stem:[2 \sqrt\{2} a].

====

[EXAMPLE]
====

`++IntegraalTussen(sin(x), cos(x), π / 4, π * 5 / 4)++` geeft stem:[2 \sqrt\{2}].

====
