= Kegelsnedeboog Commando
:page-en: commands/Arc_Command
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Kegelsnedeboog( <Cirkel>, <Punt M>, <Punt N> )::
  Geeft de boog (in tegenwijzerzin) van de gegeven cirkel, met eindpunten M en N.

Kegelsnedeboog( <Ellips>, <Punt M>, <Punt N> )::
  Geeft de kegelsnedeboog (in tegenwijzerzin) van de gegeven ellips, met eindpunten M en N.

Kegelsnedeboog( <Cirkel>, <Parameter Waarde>, <Parameter Waarde> )::
  Geeft de kegelsnedeboog (in tegenwijzerzin) van de gegeven cirkel waarvan de eindpunten bepaald zijn door de waarden
  van de parameters.

[NOTE]
====

Zo vind je bijvoorbeeld voor een:Cirkel: (_r_ cos(_t_), _r_ sin(_t_)) met _r_ de straal van de cirkel.

====

Kegelsnedeboog( <Ellips>, <Parameter Waarde>, <Parameter Waarde> )::
  Geeft de kegelsnedeboog (in tegenwijzerzin) van de gegeven ellips waarvan de eindpunten bepaald zijn door de waarden
  van de parameters.

[NOTE]
====

Zo vind je bijvoorbeeld voor een::Ellipse: (_a_ cos(_t_), _b_ sin(_t_)) met _a_ and _b_ de halve lengtes van de hoofdas
en nevenas.

====

[NOTE]
====

Zie ook de commando's xref:/commands/CirkelboogDriePunten.adoc[Cirkelboog door drie punten] en
xref:/commands/CirkelboogMetMiddelpunt.adoc[Cirkelboog met middelpunt].

====
