= Logistisch Commando
:page-en: commands/Logistic
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Logistisch( <Gemiddelde>, <Schaal>, x )::
  Creëert de kansdichtheidsfunctie (pdf) van de http://en.wikipedia.org/wiki/Logistic_distribution[logistische
  verdeling] met als parameters gemiddelde _μ_ en schaal _s_.
Logistisch( <Gemiddelde>, <Schaal>, <Variabele Waarde> )::
  Berekent de waarde van de cumulatieve dichtheidsfunctie van de logistische verdeling voor een variabele _v_, dit is de
  kans _P(X ≤ v)_ waarbij _X_ een willekeurige variabele is met een logistische verdeling bepaald door de parameters
  gemiddelde _μ_ en schaal _s_.
Logistisch( <Gemiddelde>, <Schaal>, x, <Boolean Cumulatief> )::
  Als _Cumulatief_ = true, wordt de cumulatievedichtheidsfunctie gecreërd, anders de pdf van de logistische verdeling.

[NOTE]
====

geeft de kans voor een gegeven _x_-coördinaat (of oppervlakte onder de grafiek van de logistische dichtheidsfunctie
links van de gegeven _x_-coördinaat).

====

== CAS Venster

Logistisch( <Gemiddelde>, <Schaal>, x )::
  Creëert de kansdichtheidsfunctie (pdf) van de http://en.wikipedia.org/wiki/Logistic_distribution[logistische
  verdeling] met als parameters gemiddelde _μ_ en schaal _s_.
Logistisch( <Gemiddelde>, <Schaal>, <Variabele Waarde> )::
  Berekent de waarde van de cumulatieve dichtheidsfunctie van de logistische verdeling voor een variabele _v_, dit is de
  kans _P(X ≤ v)_ waarbij _X_ een willekeurige variabele is met een logistische verdeling bepaald door de parameters
  gemiddelde _μ_ en schaal _s_.
Logistisch( <Gemiddelde>, <Schaal>, x, <Boolean Cumulatief> )::
  Als _Cumulatief_ = true, wordt de cumulatievedichtheidsfunctie gecreërd, anders de pdf van de logistische verdeling.

[NOTE]
====

geeft de kans voor een gegeven _x_-coördinaat (of oppervlakte onder de grafiek van de logistische dichtheidsfunctie
links van de gegeven _x_-coördinaat).

====
