= Oplossingen Commando
:page-en: commands/Solutions
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Dit commando is alleen maar beschikbaar in xref:/CAS_venster.adoc[CAS venster]..

== CAS Syntax

Oplossingen( <Vergelijking> )::
  Lost een gegeven vergelijking op en geeft een lijst van alle oplossingen.
Oplossingen( <Vergelijking>, <Variabele> )::
  Lost een gegeven vergelijking op naar een gegeven variabele en geeft een lijst van alle oplossingen.
Oplossingen( <Lijst van vergelijkingen>, <Lijst van variabelen> )::
  Lost een lijst van vergelijkingen op voor een lijst van variabelen en geeft een lijst van alle oplossingen.

[EXAMPLE]
====

* `++Oplossingen({x = 4 x + y , y + x = 2}, {x, y})++` geeft _\{\{-1, 3}}_, de enige oplossing van _x = 4x + y_ and _y +
x = 2_, displayed as stem:[\begin{pmatrix}-1&3\end{pmatrix}].
* `++Oplossingen({2a^2 + 5a + 3 = b, a + b = 3}, {a, b})++` geeft _\{\{0, 3}, \{-3, 6}}_, getoond als
stem:[\begin{pmatrix}0&3\\-3&6\end{pmatrix}].

====

[EXAMPLE]
====

`++Oplossingen(x * a^2 = 4a, a)++` geeft stem:[\\{\frac{4}\{x},0\}], de oplossingen van _xa^2^ = 4a_.

====

[EXAMPLE]
====

`++Oplossingen(x^2 = 4x)++` geeft _\{4, 0}_, de oplossingen van _x^2^ = 4x_.

====

[NOTE]
====

* Soms moet je de uitdrukking manipuleren om de automatische oplosser te doen werken, bijvoorbeeld:
`++ Oplossingen(GoniometrieWerkuit[sin(5/4 π + x) - cos(x - 3/4 π) = sqrt(6) * cos(x) - sqrt(2)]) ++`
* Zie ook het commando xref:/commands/Oplossen.adoc[Oplossen].

====
