= Perioden Commando
:page-en: commands/Periods_Command
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Perioden( <Rentevoet>, <Termijn>, <Aanvangswaarde>, <Eindwaarde (optioneell)>, <Type (optioneell)> )::
  Berekent het aantal perioden van een http://en.wikipedia.org/wiki/nl:Annu%C3%AFteit[Annuïteit].

* *<Rentevoet>* Rentevoet per periode.
* *<Termijn>* Het bedrag dat elke periode betaald wordt.
* *<Aanvangswaarde (optioneel)>* Het bedrag dat een reeks toekomstige betalingen nu waard is.
* *<Eindwaarde(optioneel)>* Het eindsaldo na de laatste betaling. Wanneer je geen waarde ingeeft, wordt het
gelijkgesteld aan 0.
* *<Type (optioneel)>* Geeft aan wanneer de betalingen gebeuren. Wanneer je niets invult (of 0) gebeuren de betalingen
op het einde van elke periode (postnumerando. Vul je 1 in dan gebeuren de betalingen in het begin van elke periode
(prenumerando)

[EXAMPLE]
====

`++Perioden(10%/12, -200, -400, 10000)++` geeft als aantal betalingen 39.98.

`++Perioden(10%/12, -200, -400, 10000, 1)++` geeft 39.7.

====

[NOTE]
====

Zorg er voor dat de eenheden die je gebruikt voor `++<Rentevoet>++` en `++<Aantal perioden>++` overeenkomen. Bij
maandelijkse betalingen met een gegeven jaarlijkse rentevoet over een looptijd van 4 jaar, moet je zowel rentevoet en
aantal periodes omrekenen naar maanden.

====

[NOTE]
====

Voor alle argumenten, worden betalingen voorgesteld door negatieve getallen en ontvangsten door positieve getallen.

====

[NOTE]
====

Zie ook de commando's xref:/commands/Termijn.adoc[Termijn], xref:/commands/Rentevoet.adoc[Rentevoet],
xref:/commands/Aanvangswaarde.adoc[Aanvangswaarde] en xref:/commands/Eindwaarde.adoc[Eindwaarde].

====
