= Rentevoet Commando
:page-en: commands/Rate
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Rentevoet( <Aantel perioden>, <Termijn>, <Aanvangswaarde>, <Eindwaarde (optioneel)>, <Type (optioneel)>, <Gok
(optioneel)> )::
  Berekent de rentevoet van een http://en.wikipedia.org/wiki/nl:Annu%C3%AFteit[Annuïteit].

* *<Aantal perioden>* Totaal aantal betalingen in het verloop van de annuïteit.
* *<Termijn>* Het bedrag dat elke periode betaald wordt.
* *<Aanvangswaarde (optioneel)>* Het bedrag dat een reeks toekomstige betalingen nu waard is.
* *<Eindwaarde (optioneel)>* Het saldo na de laatste betaling. Wanneer je geen waarde ingeeft, wordt het gelijkgesteld
aan 0.
* *<Type (optioneel)>* Geeft aan wanneer de betalingen gebeuren. Wanneer je niets invult (of 0) gebeuren de betalingen
op het einde van elke periode (postnumerando. Vul je 1 in dan gebeuren de betalingen in het begin van elke periode
(prenumerando)
* *<Gok (optioneell)>* Een gok voor het resultaat.

[EXAMPLE]
====

`++Rentevoet(5*12, -300, 10000)++` geeft een maandelijkse rentevoet van 0.02 (2%).

====

[NOTE]
====

Zorg er voor dat de eenheden die je gebruikt voor `++<Rentevoet>++` en `++<Aantal perioden>++` overeenkomen. Bij
maandelijkse betalingen met een gegeven jaarlijkse rentevoet over een looptijd van 4 jaar, moet je zowel rentevoet en
aantal periodes omrekenen naar maanden.

====

[NOTE]
====

Voor alle argumenten, worden betalingen voorgesteld door negatieve getallen en ontvangsten door positieve getallen.

====

[NOTE]
====

Zie ook de commando's xref:/commands/Termijn.adoc[Termijn], xref:/commands/Eindwaarde.adoc[Eindwaarde],
xref:/commands/Aanvangswaarde.adoc[Aanvangswaarde] en xref:/commands/Perioden.adoc[Perioden].

====
