= Schijfdiagram Commando
:page-en: commands/PieChart
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Schijfdiagram(< Lijst met frequenties >)::
  Creëert een schijfdiagram vanuit een lijst met frequenties. De volledige schijf staat voor 100%, de gegeven data
  worden getoond als cirkelsectoren.

[EXAMPLE]
====

`++Schijfdiagram({20, 15, 40, 5, 10, 20})++` creëert een schijfdiagram met als middelpunt de oorspring (0,0) en straal
3.

====

Schijfdiagram(< Lijst met frequenties >, < Middelpunt >, < Straal >)::
  Creëert een schijfdiagram met gegeven middelpunt en straal vanuit een lijst met frequenties. De volledige schijf staat
  voor 100%, de gegeven data worden getoond als cirkelsectoren.

[EXAMPLE]
====

`++Schijfdiagram({20, 15, 40, 5, 10, 20},(3,3),5)++` creëert een schijfdiagram met middelpunt (3,3) en straal 5.

====

[NOTE]
====

Selecteer de tab _Kleur_ in het dialoogvenster _Eigenschappen_ van het schijfdiagram om voor iedere sector een
aangepaste kleur te kiezen en de tab _Stijl_ om een aangepaste opvulling te selecteren.

====
