= Schuifknop Commando
:page-en: commands/Slider
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Schuifknop( <Min>, <Max>, <Toename>, <Snelheid>, <Breedte>, <Hoek>, <Horizontaal>, <Animatie>, <Boolean Random> )

Creëert een xref:/tools/Schuifknop.adoc[schuifknop]. Je kunt volgende parameters bepalen:

* _Min_, _Max_: bepaalt de intervalbreedte van de schuifknop - Deze parameters zijn verplicht.
* _Toename_: de standaardwaarde van deze parameter is 0.1
* _Snelheid_: bepaalt de snelheid van de schuifknop, wanneer ze getoond wordt in een animatie - standaard: 1
* _breedte_: bepaalt de breedte van de schuifknop in pixels - standaard: 200
* _Hoek_: bepaalt (met _true_ or _false_) of de schuifknop al dan niet verwijst naar een hoek. - standaard: _false_
* _Horizontaal_: bepaalt of een schuifknop horizontaal (_true_) of verticaal (_false_) getoond wordt - standaard: _true_
* _Animatie_: bepaalt of er op de schuifknop al dan niet een animatie geplaatst wordt - standaard: _false_
* _Random_: bepaalt of de schuifknop continue waarden aanneemt binnen het interval [Min, Max] (_false_), of willekeurige
waarden binnen hetzelfde interval (_true_) - standaard: _false_
