= SetBackgroundColor Commando
:page-en: commands/SetBackgroundColor_Command
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

SetBackgroundColor( <Object>, <Rood>, <Groen>, <Blauw> )::
  Bepaalt de achtergrondkleur van een gegeven object. Voor de kleuren _Rood_, _Groen_ en _Blauw_ geef je een getal
  tussen 0 en 1 dat aangeeft in welke mate die basiskleur bijdraagt tot de kleur van het object.
SetBackgroundColor( <Object>, <"Kleur"> )::
  Bepaalt de achtergrondkleur van een gegeven object. Hieronder zie je een lijst met in het Nederlands aanvaarde
  kleurnamen als o.a. _Rood_, _Groen_, _Blauw_ en _Zwart_ aanvaard.

[NOTE]
====

Gebruik in _scripting_ de Engelse kleurnamen als _Red_, _Green_, _Blue_ en _Black_.

====

* Zwart
* Donkergrijs
* Grijs
* Donkerblauw
* Blauw
* Donkergroen
* Groen
* Bruin-rood
* Dieprood
* Rood
* Magenta
* Indigo
* Purper
* Bruin
* Oranje
* Goud

* Limoengroen
* Cyaan
* Turkoois
* Lichtblauw
* Aqua
* Zilver
* Lichtgrijs
* Roze
* Violet
* Geel
* Lichtgeel
* Lichtoranje
* Lichtviolet
* Lichtpurper
* Lichtgroen
* Wit

 
