= Spiegeling Commando
:page-en: commands/Reflect
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Spiegeling( <Meetkundig object>, <Punt> )::
  Maakt een puntspiegeling van het meetkundig object t.o.v. een gegeven punt.
Spiegeling( <Meetkundig object>, <Rechte> )::
  Maakt een lijnspiegeling van een meetkundig object of bijvoorbeeld een afbeelding ten opzichte van een gegeven rechte.
Spiegeling( <Meetkundig object>, <Cirkel> )::
  Spiegelt het meetkundig object ten opzichte van een cirkel
Spiegeling( <Meetkundig object>, <Vlak> )::
  Spiegelt het meetkundig object ten opzichte van een vlak.

[NOTE]
====

Wanneer je een veelhoek spiegelt t.o.v. een rechte worden ook de gespiegelde hoekpunten en lijnstukken gecreëerd.

====

[NOTE]
====

Wanneer je een veelhoek spiegelt t.o.v. een punt worden ook de gespiegelde hoekpunten en lijnstukken gecreëerd.

====

[NOTE]
====

Zie ook de knoppen xref:/tools/Puntspiegeling.adoc[Punstspiegeling], xref:/tools/Lijnspiegeling.adoc[Lijnspiegeling] ,
en xref:/tools/Inversie_van_punt.adoc[Inversie van punt].

====
