= Termijn Commando
:page-en: commands/Payment
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Termijn( <Rentevoet>, <Aantal perioden>, <Aanvangswaarde>, <Eindwaarde (optioneel)>, <Type (optioneel)> )::
  Berekent de termijn van een http://en.wikipedia.org/wiki/nl:Annu%C3%AFteit[Annuïteit].

* *<Rentevoet>* Rentevoet per periode.
* *<Aantal perioden>* Totaal aantal betalingen in het verloop van de annuïteit.
* *<Aanvangswaarde (optioneel)>* Het bedrag dat een reeks toekomstige betalingen nu waard is.
* *<Eindwaarde (optioneel)>* Eindsaldo na de laatste betaling. Wanneer je geen waarde ingeeft, wordt het gelijkgesteld
aan 0.
* *<Type (optioneel)>* Geeft aan wanneer de betalingen gebeuren. Wanneer je niets invult (of 0) gebeuren de betalingen
op het einde van elke periode (postnumerando. Vul je 1 in dan gebeuren de betalingen in het begin van elke periode
(prenumerando).

[EXAMPLE]
====

`++Termijn(6%/12, 10, 10000, 0,1)++` geeft een maandelijks bedrag van -1022.59 om een lening af te betalen.

====

[NOTE]
====

Zorg er voor dat de eenheden die je gebruikt voor `++<Rentevoet>++` en `++<Aantal perioden>++` overeenkomen. Bij
maandelijkse betalingen met een gegeven jaarlijkse rentevoet over een looptijd van 4 jaar, moet je zowel rentevoet en
aantal periodes omrekenen naar maanden.

====

[NOTE]
====

Voor alle argumenten, worden betalingen voorgesteld door negatieve getallen en ontvangsten door positieve getallen.

====

[NOTE]
====

Zie ook de commando's xref:/commands/Eindwaarde.adoc[Eindwaarde], xref:/commands/Rentevoet.adoc[Rentevoet],
xref:/commands/Aanvangswaarde.adoc[Aanvangswaarde] en xref:/commands/Perioden.adoc[Perioden].

====
