= TMean2Estimate Commando
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

TMean2Estimate( <Lijst met steekproefgegevens 1>, <Lijst met steekproefgegevens 2>, <Niveau>, <Boolean Pooled> )::
  Berekent een t betrouwbaarheidsinterval van de verschillen tussen de twee steekproefgemiddelden met een
  betrouwbaarheid _Niveau_.
  Als _Pooled_ = true, wordt aangenomen dat de steekproefvarianties gelijk zijn en worden de
  steekproefstandaardafwijkingen gecombineerd in de berekening.
  Als _Pooled_ = false, wordt aangenomen dat de steekproefvarianties niet gelijk zijn en worden de
  steekproefstandaardafwijkingen niet gecombineerd in de berekening.
  De resultaten worden getoond als een lijst in de vorm _\{onderste betrouwbaarheidslimiet, bovenste
  betrouwbaarheidslimiet}_.
TMean2Estimate( <Steekproefgemiddelde 1>, <Steekproef standaardafwijking 1>, <Steekproefgrootte 1>,
<Steekproefgemiddelde 2>, <Steekproef standaardafwijking 2>, <Steekproefgrootte 2>, <Level>, <Boolean Pooled> )::
  Berekent een t betrouwbaarheidsinterval van de verschillen tussen de twee steekproefgemiddelden met een
  betrouwbaarheid _Niveau_. _Pooled_ wordt gedefinieerd als hierboven.
  De resultaten worden getoond als een lijst in de vorm _\{onderste betrouwbaarheidslimiet, bovenste
  betrouwbaarheidslimiet}_.
