= TSchattingTweeGemiddelden Commando
:page-en: commands/TMean2Estimate
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

TSchattingTweeGemiddelden( <Lijst 1 met gegevens>, <Lijst 1 met gegevens>, <Niveau>, <Booleaans gepoold> )::
  Berekent een t betrouwbaarheidsinterval van het verschil tussen de twee steekproefgemiddelden vanuit de gegevens
  lijsten en het betrouwbaarheidsniveau.
  Als _gepoold_ = true, dan wordt aangenomen van de steekproefvarianties gelijk zijn en de steekproef
  standaardafwijkingen worden gecombineerd in de berekening.
  Als _gepoold_ = false, dan wordt aangenomen van de steekproefvarianties niet gelijk zijn. De steekproef
  standaardafwijkingen worden niet gecombineerd.
  De resultaten worden getoond in een lijst in een vorm _\{ondergrens betrouwbaarheid, bovengrens betrouwbaarheid}_.

TSchattingTweeGemiddelden( <Steekproefgemiddelde 1>, <Steekproef standaardafwijking 1>, <Steekproefgrootte 1>,
<Steekproefgemiddelde 2>, <Steekproef standaardafwijking 2>, <Steekproefgrootte 2>, <Niveau>, <Booleaans gepoold> )::
  Berekent een t betrouwbaarheidsinterval van het verschil tussen de twee steekproefgemiddelden vanuit de gegeven
  beschrijvende maten en het betrouwbaarheidsniveau. _gepoold_ wordt gedefinieerd als hierboven. De resultaten worden
  getoond in een lijst in een vorm _\{ondergrens betrouwbaarheid, bovengrens betrouwbaarheid}_.
