= Type Commando
:page-en: commands/Type
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Type( <Object> )

Voor kegelsneden en kwadrieken geeft dit commanbdo als resultaat het getal dat overeenstemt met het type
kegelsnede/kwadriek volgens onderstaande tabel. In deze context is een lege kegelsnede (of kwadriek) er een waarin alle
coëfficiënten bepaald zijn, maar waar waarbij de kegelsnede (of kwadriek) geen punten bevat, b.v. x^2^+y^2^=-1. Voor
kegelsneden onderscheid GeoGebra dubbele rechten (speciaal geval van evenwijdige rechten met onderlinge afstand 0) en
enkele rechte (speciaal geval van een cirkel met oneindige straal als resultaat van de inversie van een cirkel). Bij
kwadrieken bestaat dit onderscheid niet.

[EXAMPLE]
====

`++Type(x²+y²=1)++` geeft 4 wat staat voor een cirkel.

====

[cols=",,",options="header",]
|===
|Value |Type van kegelsnede |Type van kwadriek
|1 |Enkel punt |Enkel punt
|2 |Snijdende rechten |
|3 |Ellips |Ellipsoïde
|4 |Cirkel |Bol
|5 |Hyperbool |
|6 |Leeg |Leeg
|7 |Dubbele rechte |
|8 |Evenwijdige rechten |
|9 |Parabool |Paraboloïde
|10 | |
|===
