= Uitzoomen Commando
:page-en: commands/ZoomOut
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Uitzoomen( <Schaalfactor> )::
  Zoomt het xref:/Tekenvenster.adoc[Tekenvenster] uit met de gegeven factor. Het middelpunt van het scherm is het
  zoomcentrum.
Uitzoomen( <Schaalfactor>, <Centrum> )::
  Zoomt het xref:/Tekenvenster.adoc[Tekenvenster] uit met de gegeven factor. De tweede parameter bepaalt het
  zoomcentrum.

[EXAMPLE]
====

`++Uitzoomen(2, (0, 0))++` zoomt het tekenvenster uit met factor 2 en de oorsprong als zoomcentrum

====

[EXAMPLE]
====

`++Uitzoomen(2)++` zoomt het tekenvenster uit met factor 2.

====

[NOTE]
====

* `++Uitzoomen(t)++` en `++Uitzoomen(t, A)++` komen overeen met respectievelijk `++Inzoomen(1/t)++` en
`++Inzoomen(1/t, A)++`.
* Wanneer meerdere tekenvensters getoond worden, wordt het actieve venster gebruikt.
* Zie ook de commando's xref:/commands/Inzoomen.adoc[Inzoomen], xref:/commands/SetActiveView.adoc[SetActiveViewo],
xref:/commands/Pan.adoc[Pan].

====
