= UpdateConstructie Commando
:page-en: commands/UpdateConstruction
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

UpdateConstructie( )::
  Herberekent alle objecten, zodat b.v. alle toevalsgetallen opnieuw gegenereerd worden.
  Dit is hetzelfde als de toetscombinaties /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] of
  /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode].

[NOTE]
====

Wanneer je het tekenvenster wil hernieuwen, bijvoorbeeld om het spoor van een object te verwijderen kan je het commando
`++Inzoomen[1]++` gebruiken, wat overeenkomt met de toetscombinatie /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode].

Zie ook de commado's xref:/commands/SetActiveView.adoc[SetActiveView[1]] of
xref:/commands/SetActiveView.adoc[SetActiveView[2]] wanneer je twee tekenvensters gebruikt.

====

UpdateConstructie( <Aantal keer> )::
  Voert het commando `++UpdateConstructie[ ]++` _Aantal keer_ uit.

[EXAMPLE]
====

`++UpdateConstructie(2)++` updatet twee keer de construction (b.v. om het resultaat van meerdere worpen met een
dobbelsteen op te nemen in het rekenvenster).

====
