= Variantie Commando
:page-en: commands/Variance
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Variantie( <Lijst met waarnemingsgetallen> )::
  Berekent de variantie stem:[ \sigma^\{2} ] (voor een populatie) van de elementen in de lijst.
Variantie( <Lijst met waarnemingsgetallen>, <Lijst van de frequenties> )::
  Berekent de variantie stem:[ \sigma^\{2} ] (voor een populatie) van de elementen in de lijst, rekening houdend met hun
  frequenties.
Variantie( <Lijst met waarden van een stochast>, <Lijst met kansen> )::
  Berekent de variantie Var(X) van een kansverdeling met gegeven waarden van een stochast X en hun respectievelijke
  kansen.

[EXAMPLE]
====

`++Variantie({1, 2, 3}, {0.2, 0.5, 0.3} )++` geeft _0.49_.

====

[EXAMPLE]
====

`++Variantie({1, 2, 3} , {1, 2, 1})++` geeft _0.5_.

====

[EXAMPLE]
====

`++Variantie({1, 2, 3})++` geeft _0.67_.

====

== CAS venster

Variantie( <Lijst met waarnemingsgetallen> )::
  Berekent de variantie van de elementen in de lijst. Wanneer de lijst onbepaalde variabelen bevat, geeft het de formule
  om de variantie te berekenen.

[EXAMPLE]
====

* `++Variantie({1, 2, a})++` geeft _stem:[\frac\{2 a^\{2} - 6 a + 6}\{9}]_.
* `++Variantie({1, 2, a} {20, 3, 1})++` geeft _stem:[\frac\{2 a² - 52 a + 632}\{9}]_.

====

Variantie( <Lijst met waarden van een stochast>, <Lijst met kansen> )::
  Berekent de variantie Var(X) van een kansverdeling met gegeven waarden van een stochast X en hun respectievelijke
  kansen.

[EXAMPLE]
====

`++Variantie({1, 2, 3}, {0.2, 0.5, 0.3} )++` geeft stem:[ \frac\{49}\{100} ]

====
