= Veelhoekslijn Commando
:page-en: commands/Polyline_Command
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Veelhoekslijn( <Punt>, ..., <Punt> )::
  Creëert een open veelhoekslijn (een verbonden rij van lijnstukken) met een eerste hoekpunt (het eerste in de lijst) en
  een laatste hoekpunt (het laatste in de lijst).

[NOTE]
====

De lengte van de veelhoekslijn kan je aflezen in het xref:/Algebra_venster.adoc[Algebra venster].

====

Veelhoekslijn( <Lijst met punten> )::
  Creëert een open veelhoekslijn (een verbonden rij van lijnstukken) met een eerste hoekpunt (het eerste in de lijst) en
  een laatste hoekpunt (het laatste in de lijst).

[NOTE]
====

* De lengte van de veelhoekslijn kan je aflezen in het xref:/Algebra_venster.adoc[Algebra venster].
* Het is ook mogelijk een discontinue veelhoekslijn te tekenen:

[EXAMPLE]
====

`++Veelhoekslijn( (1, 3), (4, 3), (?,?), (6, 2), (4, -2), (2, -2))++` geeft de waarde _9.47_ in het _Algebra_ venster,
en de overeenkomende veelhoekslijn wordt getoond in het _Tekenvenster_.

====

====

[NOTE]
====

Zie ook het commando xref:/commands/Veelhoek.adoc[Veelhoek] .

====
