= Z Gemiddelde Test Commando
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Z_Gemiddelde_Test( <Lijst van de steekproefgegevens>, <σ>, <Gemiddelde Nulhypothese>, <Staart> )::
  Voert een Z test uit op een populatiegemiddelde met de gegeven lijst en de standaardafwijking _Gemiddelde
  Nulhypothese_ is het aangenomen poplatiegemiddelde in de nul hypothese. _Staart_ heeft als mogelijke waarden "<", ">"
  , "≠". Deze bepalen de hypothesen als volgt.
  "<" = populatiegemiddelde < _Gemiddelde Nulhypothese_
  ">" = populatiegemiddelde > _Gemiddelde Nulhypothese_
  "≠" = populatiegemiddelde ≠ _Gemiddelde Nulhypothese_

Het resultaat wordt getoond als een lijt van de vorm \{Waarschijnlijkheidswaarde, Z test}.

Z_Gemiddelde_Test( <Steekproefgemiddelde>, <σ>, <Steekproefomvang>, <Gemiddelde Nulhypothese>, <Significantie_niveau> )

Voert een Z test uit op een populatiegemiddelde met de gegeven maten . _Gemiddelde Nulhypothese_ en _Staart_ worden
gedefinieerd als hierboven.

Het resultaat wordt getoond als een lijt van de vorm \{Waarschijnlijkheidswaarde, Z test}.
