= Zipf Commando
:page-en: commands/Zipf
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Zipf( <Aantal elementen>, <Exponent> )::
  Geeft een staafdiagram van een http://en.wikipedia.org/wiki/Zipf%27s_law[Zipf distributionverdeling].
  Parameters:
  * _Aantal elementen_: aantal elementen waarvan we de rang bestuderen
  * _Exponent_: exponent die de verdeling bepaalt

Zipf( <Aantal elementen>, <Exponent>, <Boolean Cumulatief> )::
  Geeft de grafiek van de Zipf verdeling als _Cumulatief_ = false.
  Geeft de grafiek van de cumulatieve Zipf verdeling als _Cumulatief_ = true.
  De eerste twee parameters zijn hetzelfde als hierboven.
Zipf( <Aantal elementen>, <Exponent>, <Variabele waarde>, <Boolean Cumulative> )::
  X is een willekeurige variabele met Zipf verdeling.
  Geeft P( X = _v_) als _Cumulatief_ = false.
  Geeft P( X ≤ _v_) als _Cumulatief_ = true.
  De eerste twee parameters zijn hetzelfde als hierboven.

== CAS venster

Zipf( <Aantal elementen>, <Exponent>, <Toevalsveranderlijke>, <Cumulatieve_aan> )::
  X is een willekeurige variabele met Zipf verdeling.
  Geeft P( X = _v_) als _Cumulatief_ = false.
  Geeft P( X ≤ _v_) als _Cumulatief_ = true

[EXAMPLE]
====

`++Zipf( 10, 1 , 5, false)++` geeft _stem:[\frac\{504}\{7381}]_.

====
