= ZToetsGemiddelde Commando
:page-en: commands/ZMeanTest
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

ZToetsGemiddelde( <Lijst met populatiewaarden>, <σ>, <Geschatte gemiddelde>, <Staart> )::
  Voert een Z-test uit op een populatiegemiddelde vanuit de gegevens en de standaardafwijking. _Geschatte gemiddelde_ is
  het populatiegemiddelde, aangenomen in de nulhypothese. _Staart_ heeft als mogelijke waarden "<", ">" , "≠". Deze
  specifiëren de aannamen als volgt:
  "<" = populatiegemiddelde < _Geschatte gemiddelde_
  ">" = populatiegemiddelde > _Geschatte gemiddelde_
  "≠" = populatiegemiddelde ≠ _Geschatte gemiddelde_

De resultaten worden getoond in een lijst als {Kanswaarde, Z test statistiek}.

ZToetsGemiddelde( <Steekproefgemiddelde>, <σ>, <Steekproefgrootte>, <Geschatte gemiddelde>, <Staart> )::
  Voert een Z-test uit op een populatiegemiddelde vanuit de beschrijvende maten en de populatie standaardafwijking.
  _Geschatte gemiddelde_ en _Staart_ worden gedefinieerd als hierboven.
  De resultaten worden getoond in een lijst als \{Kanswaarde, Z test statistiek}.
