= BinomiálisEloszlás parancs
:page-en: commands/BinomialDist
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

BinomiálisEloszlás[ <Kísérletek száma>, <Siker valószínűsége> ]::
  Oszlopdiagramot rajzol a binomiális eloszláshoz.
  _Paraméterek:_
  _Kísérletek száma_: a független Bernoulli kísérletek száma
  _Siker valószínűsége_: a sikeres esemény bekövetkezésének valószínűsége

BinomiálisEloszlás[ <Kísérletek száma>, <Siker valószínűsége>, <Eloszlásfüggvény logikai értéke> ]::
  Ha a _logikai érték_ hamis, oszlopdiagramot rajzol a Binomiális eloszláshoz,
  Ha a _logikai érték_ igaz, megrajzolja a Binomiális eloszlásfüggvény oszlopdiagrammját.
  Az első két paraméter megegyezik a fentivel.
BinomiálisEloszlás[ <Kísérletek száma>, <Siker valószínűsége>, <Változó értéke>, <Eloszlásfüggvény logikai értéke> ]::
  Legyen X egy binomiális eloszlású véletlen valószínűségi változó.
  Meghatározza P(X=__v__) valószínűséget, ha a _logikai érték_ = hamis.
  Meghatározza P(X≤__v__) valószínűséget, ha a _logikai érték_ = igaz.
  Az első két paraméter megegyezik a fentivel.

== CAS nézet

BinomiálisEloszlás[ <Kísérletek száma>, <Siker valószínűsége>, <Változó értéke>, <Eloszlásfüggvény logikai értéke> ]

xref:/CAS_nézet.adoc[CAS nézet]-ben csak az alábbi szintakszis engedélyezett.

Legyen X egy binomiális eloszlású véletlen valószínűségi változó.

Meghatározza P(X=__v__) valószínűséget, ha a _logikai érték_ = hamis.

Meghatározza P(X≤__v__) valószínűséget, ha a _logikai érték_ = igaz.

[EXAMPLE]
====

3 adatállományt továbbítunk egy hibás kapcsolaton keresztül. Annak a valószínűsége, hogy egy tetszőleges adatállomány
megsérül a továbbítás soránstem:[\frac\{1}\{10}], miközben az adatállomány sikeres továbbításának
valószínűségestem:[\frac\{9}\{10}].

* `++BinomiálisEloszlás[3, 0.9, 0, false]++` egyenlő _stem:[\frac\{1}\{1000}]_, a valószínűsége annak, hogy egyetlen
adatállományt sem sikerül továbbítani,
* `++BinomiálisEloszlás[3, 0.9, 1, false]++` egyenlő _stem:[\frac\{27}\{1000}]_, a valószínűsége annak, hogy pontosan
egyetlen adatállományt sikerül továbbítani,
* `++BinomiálisEloszlás[3, 0.9, 2, false]++` egyenlő__stem:[\frac\{243}\{1000}]__, a valószínűsége annak, hogy pontosan
két adatállományt sikerül továbbítani,
* `++BinomiálisEloszlás[3, 0.9, 3, false]++`egyenlő _stem:[\frac\{729}\{1000}]_, a valószínűsége annak, hogy mind a
három adatállományt sikerül továbbítani.
* `++BinomiálisEloszlás[3, 0.9, 0, true]++` egyenlő _stem:[\frac\{1}\{1000}]_, a valószínűsége annak, hogy egyetlen
adatállományt sem sikerül továbbítani,
* `++BinomiálisEloszlás[3, 0.9, 1, true]++` egyenlő _stem:[\frac\{7}\{250}]_, a valószínűsége annak, hogy legfeljebb egy
adatállományt sikerül továbbítani,
* `++BinomiálisEloszlás[3, 0.9, 2, true]++` egyenlő _stem:[\frac\{271}\{1000}]_, a valószínűsége annak, hogy legfeljebb
két adatállományt sikerül továbbítani,
* `++BinomiálisEloszlás[3, 0.9, 3, true]++`egyenlő _1_, a valószínűsége annak, hogy legfeljebb három adatállományt
sikerül továbbítani.
* `++BinomiálisEloszlás[3, 0.9, 4, false]++` egyenlő _0_, a valószínűsége annak, hogy pontosan négy adatállományt
sikerül továbbítani három közül,
* `++BinomiálisEloszlás[3, 0.9, 4, true]++`egyenlő _1_, a valószínűsége annak, hogy legfeljebb négy adatállományt
sikerül továbbítani.

====
