= Háttérszín parancs
:page-en: commands/SetBackgroundColor
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Háttérszín[ <Alakzat>, <Piros>, <Zöld>, <Kék> ]::
  Az adott alakzat háttérszínének beállítására szolgál. Használható szövegek és munkalapon szereplő alakzatok esetén. A
  piros, zöld és kék színek keverési arányát 0 és 1 közötti számmal adhatjuk meg. Az intervallumon kívül eső _t_ számok
  a stem:[2\left|\frac{t}2-\mathrm round\left(\frac{t}2\right)\right|] függvénnyel képezhetők le.
Háttérszín[ <Alakzat>, "Szín" ]::
  Az adott alakzat háttérszínének beállítására szolgál. Használható szövegek és munkalapon szereplő alakzatok esetén. A
  szín xref:/Szövegek.adoc[szöveggel] adható meg. A parancsban száznál több szín angol elnevezése használható (lásd
  http://wiki.geogebra.org/en/Reference:Colors[ReferenceColors]). Közülük több más nyelveken is használható, mint a
  lista mutatja.

* fekete
* sötétszürke
* szürke
* sötétkék
* kék
* sötétzöld
* zöld
* gesztenye
* kárminvörös
* piros
* skarlátvörös
* indigókék
* lila
* barna
* narancssárga
* arany

* limette
* ciánkék
* türkizkék
* világoskék
* vízkék
* ezüst
* világosszürke
* rózsaszín
* ibolyakék
* sárga
* világossárga
* világosnarancs
* világoskék
* világoslila
* világoszöld
* fehér

 
