= Kapcsolat parancs
:page-en: commands/Relation
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Kapcsolat[ <Lista> ]::
  Felugró ablakban információt ad a lista alakzatai közötti viszonyról (legfeljebb 4 alakzat adható meg).
Kapcsolat[ <Alakzat>, <Alakzat> ]::
  Felugró ablakban információt ad az alakzatok közötti viszonyról.

Ez a parancs lehetővé teszi, hogy megállapítsuk, vajon

* két egyenes merőleges-e,
* két egyenes párhuzamos-e,
* két (vagy több) alakzat egyenlő-e,
* egy pont adott kúpszeleten fekszik-e,
* egy egyenesnek és egy kúpszeletnek mi a viszonya (két pontban metszi, érinti, nem metszi),
* három pont egy egyenesre esik-e,
* három egyenes egy ponton megy-e át (esetleg párhuzamosak),
* négy pont egy körre illeszkedik-e (esetleg egy egyenesre esnek).

A fentiek közül bizonyos vizsgálatok szimbolikusan is elvégezhetőek. Ha a GeoGebra lehetőséget ad ilyen vizsgálatra,
akkor a megjelenő "Bővebben..." gombra kattintva lehet általánosítani a konkrét esetre jellemző összefüggést.
Előfordulhat, hogy a kapcsolat csak bizonyos feltételek esetén teljesül (a GeoGebra igyekszik ezt is megállapítani olyan
elvi pontossággal, ahogyan lehet).

[NOTE]
====

*Jegyzet:* Lásd még a xref:/tools/Kapcsolat_két_alakzat_között.adoc[Kapcsolat két alakzat között] eszközt.

====
