= Kocka parancs
:page-en: commands/Cube
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Kocka[ <Pont>, <Pont>, <Irány> ]::
  Creates a cube having the segment between the two points as an edge.
  The other vertices are uniquely determined by the given direction, that should be one of:
  * a vector, a segment, a line, a ray *orthogonal* to the segment, or
  * a polygon, a plane *parallel* to the segment.
  The created cube will have:
  * a face with the segment as an edge in a plane orthogonal to the given vector/segment/line/ray, or
  * a face with the segment as an edge in a plane parallel to the polygon/plane.

Kocka[ <Pont>, <Pont>, <Pont>]::
  Creates a cube with three (adjacent) points of the first face. The points have to start a square for the cube to be
  defined.

Kocka[ <Pont>, <Pont>]::
  Creates a cube with two (adjacent) points of the first face, and the third point automatically created on a circle, so
  that the cube can rotate around its first edge.

[NOTE]
====

*Jegyzet:* Cube[A, B] is a shortcut for Cube[A, B, C] with C = Point[Circle[B, Distance[A, B], Segment[A, B]]].

====

[NOTE]
====

*Jegyzet:* Lásd továbbá a xref:/commands/Tetraéder.adoc[Tetraéder], xref:/commands/Oktaéder.adoc[Oktaéder],
xref:/commands/Ikozaéder.adoc[Ikozaéder] és xref:/commands/Dodekaéder.adoc[Dodekaéder] parancsokat.

====
