= MegoldKomplex parancs
:page-en: commands/CSolve
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

Ez a parancs csak xref:/CAS_nézet.adoc[CAS nézetben] érhető el..

== CAS Syntax

MegoldKomplex[ <Egyenlet> ]::
  Megoldja a megadott egyenletet az x változóhoz és létrehoz egy listát, amely az összes megoldást tartalmazza. Komplex
  megoldások is lehetségesek.

[EXAMPLE]
====

`++MegoldásKomplex[x^2 = -1]++` eredménye _\{ί, -ί}_, vagyis az _x^2^ = -1_ egyenlet komplex megoldásait tartalmazó
lista.

====

MegoldKomplex[ <Egyenlet>, <Változó> ]::
  Megoldja a megadott egyenletet a megadott ismeretlen változóhoz és létrehoz egy listát, amely az összes megoldást
  tartalmazza. Komplex megoldások is lehetségesek.

[EXAMPLE]
====

`++MegoldásokKomplex[a^2 = -1, a]++` eredménye _\{ί, -ί}_, vagyis az _a^2^ = -1_ egyenlet komplex megoldásait tartalmazó
lista.

====

MegoldKomplex[ <Egyenletek listája>, <Változók listája> ]::
  Megoldja a megatott egyenletrendszert a megadott ismeretlen változókhoz és létrehoz egy listát, amely az összes
  megoldást tartalmazza. Komplex megoldások lehetségesek.

[EXAMPLE]
====

`++MegoldásokKomplex[{y^2 = x - 1, x = 2 * y - 1}, {x, y}]++` eredménye a követzekő lista: stem:[\begin{pmatrix}1 + 2
ί&1 + ί\\1 - 2 ί&1 - ί\end{pmatrix}].

====

[NOTE]
====

*Jegyzet:*

* A komplex egységet (ί) a következő billentyűzetkombinációval kapja meg: [.kcode]#ALT# + [.kcode]#i#.
* Lásd a [.mw-selflink .selflink]#MegoldKomplex# és a xref:/commands/Megoldások.adoc[Megoldások] parancsokat.

====
