= TöröttVonal parancs
:page-en: commands/Polyline
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

TöröttVonal[ <Pontok listája> ]::
  Létrehoz egy nyitott (sorban összekötött szakaszokból álló) törött vonalat. A lista első pontja a törött vonal első,
  az utolsó pontja annak az utolsó csatlakozási pontja.

[NOTE]
====

*Jegyzet:* A törött vonal hosszát az xref:/Algebra_nézet.adoc[algebra nézet] mutatja.

====

TöröttVonal[ <Pont>,..., <Pont> ]::
  Létrehoz egy nyitott (sorban összekötött szakaszokból álló) törött vonalat. Az első megadott pont a törött vonal első,
  az utolsó megadott pont annak utolsó csatlakozási pontja.

[NOTE]
====

*Jegyzet:* A törött vonal hosszát az xref:/Algebra_nézet.adoc[algebra nézet] mutatja.

====

[NOTE]
====

*Jegyzet:*

* A GeoGebra 4-es verziójától lehetséges zárt törött vonal létrehozása is.

[EXAMPLE]
====

`++TöröttVonal[ (1, 3), (4, 3), (?,?), (6, 2), (4, -2), (2, -2)]++` eredménye _f = 9.47_ .

====

* Lásd a xref:/commands/Sokszög.adoc[Sokszög] parancsot.

====
