= VéletlenszámBinomiálisEloszlás parancs
:page-en: commands/RandomBinomial
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

VéletlenszámBinomiálisEloszlás[ <Kísérletek száma>, <Siker valószínűsége> ]::
  Létrehozza azon binomiális eloszlás egy véletlenszerű valószínűségi változóját, amely kísérleteinek száma _n_ és
  valószínűsége _p_.

[EXAMPLE]
====

`++ VéletlenszámBinomiálisEloszlás[3, 0.1]++` eredménye _j ∈ \{0, 1, 2, 3}_, melynél annak valószínűsége, hogy a _j_
valószínűségi változót megkapjuk, egyenlő azzal a _0.1_-es valószínűséggel, amely három kísérletből _j_-szer lép fel.

====

== CAS nézet

VéletlenszámBinomiálisEloszlás[ <Kísérletek száma>, <Siker valószínűsége>::
  Létrehozza azon binomiális eloszlás egy véletlenszerű valószínűségi változóját, amely kísérleteinek száma _n_ és
  valószínűsége _p_.

[EXAMPLE]
====

`++ VéletlenszámBinomiálisEloszlás[3, 0.1]++` eredménye _j ∈ \{0, 1, 2, 3}_, melynél annak valószínűsége, hogy a _j_
valószínűségi változót megkapjuk, egyenlő azzal a _0.1_-es valószínűséggel, amely három kísérletből _j_-szer lép fel.

====

[NOTE]
====

*Jegyzet:* Lásd továbbá a http://wiki.geogebra.org/en/SetSeed_Command[SetSeed],
xref:/commands/Véletlenszám.adoc[Véletlenszám], xref:/commands/VéletlenElem.adoc[VéletlenElem],
xref:/commands/VéletlenszámNormálisEloszlás.adoc[VéletlenszámNormálisEloszlás],
xref:/commands/VéletlenszámPoissonEloszlás.adoc[VéletlenszámPoisson] és
xref:/commands/VéletlenszámEgyenletesEloszlás.adoc[VéletlenszámEgyenletesEloszlás] parancsokat.

====
