= VéletlenszámNormálisEloszlás parancs
:page-en: commands/RandomNormal
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

VéletlenszámNormálisEloszlás[ <Átlag>, <Szórás> ]::
  Létrehozza egy adott átlagú és szórású normális eloszlás egy véletlenszerű számát.

[EXAMPLE]
====

`++ VéletlenszámNormálisEloszlás[3, 0.1]++` eredménye a _3_ átlagú és _0.1_-es szórású normális eloszlás egy
véletlenszerű száma.

====

== CAS nézet

VéletlenszámNormálisEloszlás[ <Átlag>, <Szórás> ]::
  Létrehozza egy adott átlagú és szórású normális eloszlás egy véletlenszerű számát.

[EXAMPLE]
====

`++ VéletlenszámNormálisEloszlás[3, 0.1]++` eredménye a _3_ átlagú és _0.1_-es szórású normális eloszlás egy
véletlenszerű száma.

====

[NOTE]
====

*Jegyzet:*

Lásd továbbá http://wiki.geogebra.org/en/SetSeed_Command[SetSeed], xref:/commands/Véletlenszám.adoc[Véletlenszám],
xref:/commands/VéletlenElem.adoc[VéletlenElem],
xref:/commands/VéletlenszámBinomiálisEloszlás.adoc[VéletlenszámBinomiálisEloszlás],
xref:/commands/VéletlenszámPoissonEloszlás.adoc[VéletlenszámPoissonElolszlás],
xref:/commands/VéletlenszámEgyenletesEloszlás.adoc[VéletlenszámEgyenletesEloszlás].

====
