= VéletlenszámPoissonEloszlás parancs
:page-en: commands/RandomPoisson
ifdef::env-github[:imagesdir: /hu/modules/ROOT/assets/images]

VéletlenszámPoissonEloszlás[ <Átlag> ]::
  Létrehozza egy megadott átlagú Poisson-eloszlás egy véletlenszerű számát.

[EXAMPLE]
====

`++ VéletlenszámPoissonEloszlás[3]++` eredménye egy _3_ átlagú Poisson-eloszlás egy véletlenszerű száma.

====

== CAS nézet

VéletlenszámPoissonEloszlás[ <Átlag> ]::
  Létrehozza egy megadott átlagú Poisson-eloszlás egy véletlenszerű számát.

[EXAMPLE]
====

`++ VéletlenszámPoissonEloszlás[3]++` eredménye egy _3_ átlagú Poisson-eloszlás egy véletlenszerű száma.

====

[NOTE]
====

*Jegyzet:*

Lásd továbbá http://wiki.geogebra.org/en/SetSeed_Command[SetSeed], xref:/commands/Véletlenszám.adoc[Véletlenszám],
xref:/commands/VéletlenElem.adoc[VéletlenElem],
xref:/commands/VéletlenszámBinomiálisEloszlás.adoc[VéletlenszámBinomiálisEloszlás],
xref:/commands/VéletlenszámNormálisEloszlás.adoc[VéletlenszámNormálisEloszlás],
xref:/commands/VéletlenszámEgyenletesEloszlás.adoc[VéletlenszámEgyenletesEloszlás].

====
