= BinomialDist コマンド
:page-en: commands/BinomialDist
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

BinomialDist( <試行回数>, <成功確率> )::
  https://ja.wikipedia.org/wiki/%E4%BA%8C%E9%A0%85%E5%88%86%E5%B8%83[二項分布] の棒グラフを返す．
  _試行回数_ パラメータは独立したベルヌーイ試行の回数を指定し，_成功確率_
  パラメータは1回の試行における成功の確率を指定する．

BinomialDist( <試行回数>, <成功確率>, <累積の真偽値> )::
  _累積の真偽値_ = false なら，二項分布の棒グラフを返す．
  _累積の真偽値_ = true なら，累積二項分布の棒グラフを返す．
  最初の2つのパラメーターは上記と同じ．

BinomialDist( <試行回数>, <成功確率>, <変数値>, <累積の真偽値> )::
  Xを二項分布の確率変数とし，_v_ をその変数値とする．
  _累積の真偽値_ = false なら， P( X = _v_ ) を返す．
  _累積の真偽値_ = true なら， P( X ≤ _v_ ) を返す．
  最初の2つのパラメーターは上記と同じ．

BinomialDist( <試行回数>, <成功確率>,<値のリスト>)::
前の構文（_累積の真偽値_ = false）を適用し，値のリストの要素を変数値として使用したときに得られる値を加算することで，P(_u_ ≤ X ≤ _v_)を返す．

[EXAMPLE]
====

`++BinomialDist(10, 0.2, {1,2,3})++` は _0.77175_ を返す．これは `++BinomialDist(10, 0.2, 1, false)++` + `++BinomialDist(10, 0.2, 2, false)++` + `++BinomialDist(10, 0.2, 3, false)++` と同等である．

====

[NOTE]
====

`++BinomialDist(10, 0.2, 1..3)++` と `++BinomialDist(10, 0.2, {1, 2, 3})++` は同等である．

====



== CAS での書式


BinomialDist( <試行回数>, <成功確率>, <変数値>, <累積の真偽値> )::
  Xを二項分布の確率変数とし，変数値を _v_ とする．
  _累積の真偽値_ = false なら， P( X = _v_ ) を返す．
  _累積の真偽値_ = true なら， P( X ≤ _v_ ) を返す．

[EXAMPLE]
====

`++f(x):=BinomialDist(100,x,36,true)-BinomialDist(100,x,23,true)++` でグラフを描くことができる．

====

[EXAMPLE]
====

故障した回線を通じて3パケットのデータを転送すると仮定する．この回線で転送される任意のパケットが破損する確率はstem:[\frac{1}{10}]であるとき，任意のパケットが正常に転送される確率はstem:[\frac{9}{10}]となる．このとき：

* `++BinomialDist(3, 0.9, 0, false)++` は _stem:[\frac{1}{1000}]_
を返す．これは，3つのパケットのどれもが正常に転送されない確率．
* `++BinomialDist(3, 0.9, 1, false)++` は _stem:[\frac{27}{1000}]_
を返す．これは，3つのパケットのうち，ちょうど１つが正常に転送される確率．
* `++BinomialDist(3, 0.9, 2, false)++` は _stem:[\frac{243}{1000}]_
を返す．これは，3つのパケットのうち，ちょうど２つが正常に転送される確率．
* `++BinomialDist(3, 0.9, 3, false)++` は _stem:[\frac{729}{1000}]_
を返す．これは，3つのパケット全部が正常に転送される確率．
* `++BinomialDist(3, 0.9, 0, true)++` は _stem:[\frac{1}{1000}]_
を返す．これは，3つのパケットのどれもが正常に転送されない確率．
* `++BinomialDist(3, 0.9, 1, true)++` は _stem:[\frac{7}{250}]_
を返す．これは，3つのパケットのうち，最大１つが正常に転送される確率．
* `++BinomialDist(3, 0.9, 2, true)++` は _stem:[\frac{271}{1000}]_
を返す．これは，3つのパケットのうち，最大2つが正常に転送される確率．
* `++BinomialDist(3, 0.9, 3, true)++` は _1_ を返す．これは，3つのパケットのうち，最大3つが正常に転送される確率．
* `++BinomialDist(3, 0.9, 4, false)++` は _0_ を返す．これは，3つのパケットのうち，ちょうど4つが正常に転送される確率．
* `++BinomialDist(3, 0.9, 4, true)++` は _1_ を返す．これは，3つのパケットのうち，最大4つが正常に転送される確率．

====

BinomialDist( <試行回数>, <成功確率>,<値のリスト>)::
前の構文（_累積の真偽値_ = false）を適用し，値のリストの要素を変数値として使用したときに得られる値を加算することで，P(_u_ ≤ X ≤ _v_)を返す．

[EXAMPLE]
====

`++BinomialDist(10, 0.2, {1,2,3})++` は stem:[\frac{1507328}{1953125}] を返す．これは `++BinomialDist(10, 0.2, 1, false)++` + `++BinomialDist(10, 0.2, 2, false)++` + `++BinomialDist(10, 0.2, 3, false)++` と同等である．

====
