= Frequency コマンド
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

Frequency( <生データのリスト> )::
  指定されたデータリストから，各一意な値の出現回数をカウントしたリストを返す．この入力リストは数値でもテキストでも構わない．リストは一意な値の昇順にソートされる．対応する一意な値のリストを得るには，xref:/commands/Unique.adoc[Unique
  コマンド]を使用する．

[EXAMPLE]
====

リストを `++list1 = { "a", "a", "x", "x", "x", "b" }++`とする． `++Frequency(list1)++` はリスト _\{ 2, 1, 3 }_ を返す．
`++Unique(list1)++` はリスト _\{ "a", "b", "x" }_ を返す．

====

Frequency( <累積の真偽値>, <生データのリスト> )::
  _累積の真偽値_ = __false__の場合， Frequency( <生データのリスト> ) と同じリストを返す．
  _累積の真偽値_ = _true_ の場合， Frequency( <生データのリスト> ) の累積度数のリストを返す．

[EXAMPLE]
====

リストを`++list1 = { 0, 0, 0, 1, 1, 2 }++`とするとき， `++Frequency(true, list1)++` はリスト _\{ 3, 5, 6 }_ を返す．
`++Frequency(false, list1)++` はリスト _\{ 3, 2, 1}_ を返す． `++Unique(list1)++` はリスト _\{ 0, 1, 2 }_ を返す．

====

Frequency( <階級境界値のリスト>, <生データのリスト> )::
  与えられたデータリストから，[a, b) の形の区間内にある値のカウントのリストを返す．ここで，_a_ と _b_
  は与えられた階級境界値のリストの連続する数値の全てのペアである．最も高い区間は [a, b] の形をしている．

[EXAMPLE]
====

`++Frequency({1, 2, 3},  {1, 1, 2, 3})++` 出力：リスト _\{ 2, 2 }_.

====

Frequency( <テキストのリスト>, <テキストのリスト> )::
  2つのリストからペアになった値のカウントを含む分割表を返す．この表の行は最初のリストの一意な値に対応し，列は二番目のリストの一意な値に対応する．各リストの一意な値のリストを取得するには，xref:/commands/Unique.adoc[Unique
  コマンド]を使用する．

[EXAMPLE]
====

`++list1 = {"a", "b", "b", "c", "c", "c", "c"}++` ， `++list2 =  {"a", "b", "a", "a", "c", "c", "d"}++`とするとき，
`++Frequency(list1, list2)++` は行列 stem:[\begin{pmatrix} 1 & 0 & 0 & 0\\ 1 &1 & 0 &0 \\ 1 & 0 & 2 & 1 \\
\end{pmatrix}] を返す．

====

[NOTE]
====

こちらも参照： xref:/commands/ContingencyTable.adoc[ContingencyTable] コマンド．

====

Frequency( <累積の真偽値>, <階級境界値のリスト>,<生データのリスト> )::
  If _累積の真偽値_ = _false_ の場合， Frequency( <階級境界値のリスト>, <生データのリスト> ) と同じリストを返す．
  If _累積の真偽値_ = _true_ の場合， Frequency( <階級境界値のリスト>, <生データのリスト> ) の累積度数のリストを返す．

Frequency( <階級境界値のリスト>, <生データのリスト>, <密度を用いる真偽値> , <密度スケール因子> (optional) )::
  対応するxref:/commands/Histogram.adoc[Histogram コマンド]に基づく度数リストを返す．
  _密度を用いる真偽値_ = _false_ の場合， Frequency( <階級境界値のリスト>, <生データのリスト>) と同じリストを返す．
  _密度を用いる真偽値_ = _true_ の場合， 各クラスの度数のリストを返す．　(密度スケール因子) × (階級の度数) / (階級幅)．

[EXAMPLE]
====

生データのリストを `++data = {1, 2, 2, 2, 3, 3, 4, 4, 4, 4}++` ，階級境界値のリストを`++classes={0, 2, 5}++`
とするとき，`++Frequency(classes, data, false)++` と `++Frequency(classes, data)++` はともに，リスト _\{1, 9}_
を返す．一方， `++Frequency(classes, data, true)++` はリスト _\{0.5, 3}_ を返す．

====

Frequency( <累積の真偽値>, <階級境界値のリスト>, <生データのリスト>, <密度を用いる真偽値> , <密度スケール因子>
(optional) )::
  対応するxref:/commands/Histogram.adoc[Histogram コマンド]に基づく度数リストを返す．
