= Histogram コマンド
:page-en: commands/Histogram
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

Histogram( <階級境界値のリスト>, <高さのリスト> )::
  与えられた高さの棒でヒストグラムを描く．階級の境界は，ヒストグラムの各棒の幅と位置を決める．

[EXAMPLE]
====

`++Histogram({0, 1, 2, 3, 4, 5}, {2, 6, 8, 3, 1})++` 与えられた高さの５つの棒をもつヒストグラムを作る．最初の棒は区間
[_0, 1_]，２番目の棒は区間 [_1, 2_]，・・・

====

Histogram(<階級境界値のリスト>, <生データのリスト>, <密度使用フラグ>, <密度スケール因子 (オプション)> )::
  生データを用いてヒストグラムを描く．階級の境界は，ヒストグラムの各棒の幅と位置を決めるのに使われ，各階級に含まれるデータの個数も求めるのに使われる．棒の高さは以下の通りに求められる

* _密度使用フラグ = true_ の場合，高さ = (密度スケール因子) × (階級の度数) / (階級幅)
* _密度使用フラグ = false_ の場合，高さ = 階級の度数

デフォルトでは， 密度使用フラグ = true ， 密度スケール因子 = 1．
これにより，総面積＝n（データ値の数）のヒストグラムが作成される．

[NOTE]
====

生データのすべての要素は，階級の境界の区間内になければならない．そうでない場合は "undefined "が返される．

====

[NOTE]
====

慣習として、これは最後の階級を除き，各階級においてa≦x＜bという規則を用いる．ただし、最後の階級ではa≦x≦bとする．

====

[EXAMPLE]
====

(_デフォルト ヒストグラム_)

`++Histogram({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true)++`
は，高さ0.5（1番目の棒），0.2（2番目の棒），0.1（3番目の棒）の3つの棒を持つヒストグラムを作成する．

このヒストグラムの総面積は，0.5*10 + 0.2*10 + 0.1*10 = 8．

====

[EXAMPLE]
====

(_度数 ヒストグラム_)

`++Histogram({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, false)++`
は，高さ5（1番目の棒），2（2番目の棒），1（3番目の棒）の3つのバーを持つヒストグラムを作成する．このヒストグラムは密度を用いず，各棒の高さは各階級に含まれる値の個数に等しい．

====

[EXAMPLE]
====

(_相対度数 ヒストグラム_)

`++Histogram({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true, 10/ 8)++` は，高さ 0.625（最初の棒），0.25（2
番目の棒），0.125（3 番目の棒）の 3
本の棒を持つヒストグラムを作成する．このヒストグラムは，密度を用いて，各棒の高さは各階級の相対度数に等しい．

データの個数が n で，階級の幅が一定の wであるとき，密度スケール因子を w/n とすれば，相対ヒストグラムができる．

====

[EXAMPLE]
====

(_正規化 ヒストグラム_)

`++Histogram({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true, 1/8)++` は，高さ 0.625（最初の棒），0.25（2
番目の棒），0.125（3 番目の棒）の 3 本の棒を持つヒストグラムを作成する．

このヒストグラムの総面積は， .0625*10 + .025*10 + .0125*10 = 1．

データの個数がnであるとき，密度スケール因子を1/nとすると，面積が1になるように正規化されたヒストグラムができる．これはヒストグラムに密度曲線を当てはめるのに便利である．

====

Histogram( <累積の真偽値>, <階級境界値のリスト>, <生データのリスト>, <密度使用フラグ> , <密度スケール因子(オプション)> )::
  各棒の高さがその階級の度数（累積の真偽値=false）と累積度数（累積の真偽値=true）に等しいヒストグラムを作成する．

[EXAMPLE]
====

 `++Histogram(true, {10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true)++` ，高さ 0.5（最初の棒），0.7（2
番目の棒），0.8（3 番目の棒）の 3 本の棒を持つヒストグラムを作成する．

====
