= If コマンド
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

If( <条件>, <成立時> )::
  この条件が _true_ と評価される場合は，オブジェクト _成立時_ の コピーを返す．条件が _false_
  と評価される場合は，未定義のオブジェクトを返す．

[EXAMPLE]
====

* _n_ = 3 とするとき， `++If(n==3, x + y = 4)++` は，直線 _x_ + _y_ = 4, を返す． （ _n_ の条件が _true_ であるから．）
* _n_ = 4 とするとき， `++If(n==3, x + y = 4)++` は， _未定義_ オブジェクトを返す．（ _n_ の条件が _false_
であるから．）

====

If( <条件>, <成立時>, <不成立時> )::
  条件が _true_ と評価された場合はオブジェクト _成立時_ のコピーを，_false_ と評価された場合はオブジェクト _不成立時_
  のコピーを返す．*両方のオブジェクトは同じ型でなければならない．*
If( <条件 1>, <成立時 1>, <条件 2>, <成立時 2>, ... , <不成立時 (オプション)> )::
  最初の条件が満たされると _成立時 1_ のコピーを，2番目の条件が満たされると _成立時 2_
  のコピーを返す．どの条件も満たされないとき，_不成立時_ が指定されている場合は，このコマンドは _不成立時_
  のコピーを返す．それ以外の場合は未定義を返す．

[EXAMPLE]
====

`++If(a ≟ 1, "Matthew", a ≟ 2,"Larry", a ≟ 3, "Vivian", "Alex")++` __a__=1 ならテキスト "Matthew" を返す． __a__=2
ならテキスト "Larry" を返す．__a__=3 ならテキスト "Vivian"，それ以外の _a_ の値なら "Alex" を返す．

====

[EXAMPLE]
====

_n_ を数値としたとき， `++If(n==3, x + y = 4, x - y = 4)++` のコマンドは，_n=3_ のとき，直線 _x_ + _y_ = 4
を返し，そうでないときは，直線 _x_ - _y_ = 4 を返す．

====

[NOTE]
====

この書式は CAS ビューではサポートされていない．

====

== 条件付き関数

*If*
コマンドは条件付き関数を作成するために使用できる．そのような条件付き関数は，xref:/commands/Derivative.adoc[Derivative],
xref:/commands/Integral.adoc[Integral], xref:/commands/Intersect.adoc[Intersect]
などの関数引数を取る任意のコマンドで引数として使用可能である．

[EXAMPLE]
====

* `++f(x) = If(x < 3, sin(x), x^2)++` は，_x < 3_ では _sin(x)_， _x ≥ 3_ では _x^2^_ の区分関数を返す．
* `++f(x) = If(0 <= x <= 3, sin(x))++` は， 0 と 3 の間で _sin(x)_，それ以外は未定義の関数を返す．

[NOTE]
====

これを短くした書式は以下の通り： `++f(x) = sin(x), 0 <= x <= 3++`

====

* `++f(x) =If(x<-1,x²,-1<=x<=1,1,-x²+2)++` は，区分関数 stem:[f(x) = \left\\{\begin\{matrix}\{} x^\{2}& : &x < -1\\
1& :& -1 ≤ x ≤ 1\\ -x^\{2} + 2& : &\text\{otherwise} \end\{matrix}\right ] を返す．

====

[NOTE]
====

*Notes:*

* _If(条件, f(x), g(x))_ の導関数は，_If(条件, f'(x), g'(x))_ を与える．これは特異点での極限の評価を行なわない．
* 条件文で使用される記号については，セクションxref:/真偽値.adoc[真偽値]を参照のこと．

====

== スクリプトのIf コマンド

*If* コマンドは，スクリプトの中で特定の条件下で異なる処理を実行するために使用することができる．

[EXAMPLE]
====

_n_ を数値， _A_ を点とする．コマンド `++If(Mod(n, 7) == 0, SetCoords(A, n, 0), SetCoords(A, n, 1))++` は _A_
の座標を与えられた条件で変える．これは `++ SetCoords(A, n, If(Mod(n, 7) == 0,0,1))++` の方が簡単な書式である．

====

[NOTE]
====

**If**の引数は，オブジェクトまたはxref:/commands/スクリプティング.adoc[スクリプティング_コマンド]でなければならず，代入は適切でない．書式
`++b = If(a > 1, 2, 3)++` は正しいが，_b = 2_ や _b = 3_ は**If**のパラメータとしては適切でない．

====
