= LocusEquation コマンド
:page-en: commands/LocusEquation
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

LocusEquation( <軌跡> )::
  軌跡の方程式を計算し，それを陰関数の曲線としてプロットする．
LocusEquation( <軌跡の点Q>, <点P>)::
  動点 _P_ に応じた点 _Q_ の描く軌跡の方程式を計算し，陰関数の曲線としてプロットする．

[EXAMPLE]
====

軌跡としての放物線を構築てみよう：自由点 _A_ と _B_ を作成し，それらを通る直線 _d_
を引く（これが放物線の準線になる）．焦点となる自由点 _F_ を作成する．次に，直線 _d_ 上に移動点 _P_ を作成し，_P_
を通って _d_ に垂直な直線 _p_ を引く．また，線分 _FP_ の垂直二等分線として直線 _b_ を引く．最後に，直線 _p_ と _b_
の交点として，軌跡を描く点 _Q_
を作成する．`++LocusEquation(Q,P)++`を用いると，軌跡の正確な方程式を見つけてプロットすることができる．

====

LocusEquation( <論理条件>, <自由点> )::
  論理条件を満たす自由点の軌跡を計算する．

[EXAMPLE]
====

自由点 _A_, _B_, _C_ に対する`++LocusEquation(AreCollinear(A, B, C), A)++` は _A_, _B_, _C_ が同一直線上になる，すなわち
_B_ と _C_ を通る直線上の _A_ の位置の集合を計算する．

====

[NOTE]
====

*Notes:*

* 軌跡は点から作成される必要がある（スライダーからではない）．
* 点，直線，円，円錐曲線などに限定した図形のみ適応可能．（半直線や線分は（無限の）直線として扱われる．）
* 軌跡が複雑すぎる場合は '未定義' を返す．
* 軌跡が存在しない場合，陰関数は空集合であり，その方程式は 0 = 1 となる．
* 軌跡が平面全体であれば，陰関数は方程式0=0となる．
* 計算はhttps://en.wikipedia.org/wiki/ja:%E3%82%B0%E3%83%AC%E3%83%96%E3%83%8A%E3%83%BC%E5%9F%BA%E5%BA%95[グレブナー基底]を用いて行われるため，元の軌跡には存在しなかった曲線の余分な枝が現れることがある．
* 詳しい情報と例は
https://www.geogebra.org/m/KZVzqVEM[geogebra.org]．https://www.geogebra.org/m/mbXQuvUV[陰関数の軌跡の例集（英語）]もある．
* こちらも参照： xref:/commands/Locus.adoc[Locus] コマンドと
https://github.com/kovzol/gg-art-doc/tree/master/pdf/english.pdf[GeoGebra Automated Reasoning Tools: A
Tutorial（英語）].

====
