= PlaySound コマンド
:page-en:commands/PlaySound
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

PlaySound( <URL> )::
  MP3 (.mp3) ファイルを再生する．

[EXAMPLE]
====

* `++PlaySound("http://static.geogebra.org/welcome_to_geogebra.mp3")++`
* `++PlaySound("#J2sQQfwQ")++` http://www.geogebra.org/m/J2sQQfwQ[GeoGebraにアップロードされた.mp3]を再生する．
* `++PlaySound("https://drive.google.com/uc?id=0B7xCmZaU3oU2eXFNUzd6ZlZJS0U&authuser=0&export=download")++`
Googleドライブから.mp3を再生
* `++PlaySound("https://www.dropbox.com/s/27skpv82odjp7ej/material-1264825.mp3?dl=1")++` DropBoxから.mp3を再生

====

[NOTE]
====

iOS上で動作させる場合 (またはすぐに再生したい場合も)，MP3ファイルをインラインの base64 エンコードされた data:URL
としてエンコードできる．詳しくは，https://www.geogebra.org/m/wztkqxuv を参照のこと．GeoGebra Classic 5
で動作させるには，_正確_ に `++data:audio/mp3;base64,++`
という文字列で開始する必要がある．このユーティリティを使用して，MP3 ファイルを GeoGebra で必要な構文に変換できる．
https://test.geogebra.org/~mike/utils/base64Encode.html 

====

PlaySound( <Boolean Play> )::
  再生の一時停止または再開（MP3ファイルは不可）
  `++PlaySound(true)++` = 再生， `++PlaySound(false)++` = 一時停止．
PlaySound( <関数>, <最小値>, <最大値> )::
  範囲が
  -1から1までの時間関数を用いてサウンドを生成し，再生する．時間の単位は秒で，サウンドは最小値から最大値までの区間で再生される．サウンドは，毎秒8000サンプルの8ビットサンプルによって生成される．

これは440Hzの純粋な正弦波トーン（音階 ラ）を1秒間再生する．

[EXAMPLE]
====

`++PlaySound(sin(440 2Pi x), 0, 1)++`

====

PlaySound( <関数>, <最小値>, <最大値>, <サンプルレート>, <サンプル深度> )::
  範囲が
  -1から1までの時間関数を用いてサウンドを生成し，再生する．時間の単位は秒で，サウンドは最小値から最大値までの区間で再生される．
  サンプリング方法は"サンプル深度"と"サンプルレート"によって指定される．
  "サンプルレート"は，1秒間に取得されるサンプル関数の値の数で，許容される値は8000，11025，16000，22050，44100．
  "サンプル深度"は，サンプルのデータサイズをビットで表したもので，許容される値は8と16．

PlaySound( <ノート>, <デュレーション>, <楽器> ) (GeoGebra Classic 5 only)::
  https://en.wikipedia.org/wiki/MIDI[MIDI] ノートを再生する
  _ノート_ は0から127までの整数で，下記の表に基づいた音符を表す，ノートが60の場合，ミドルCが演奏される．
  _デュレーション_ は，音符を演奏する時間を秒で表す．
  _楽器_
  は，ノートを演奏するために使用されるシンセサイザー楽器を表す整数である．使用可能な楽器についてはhttps://web.archive.org/web/20130919034922/http://www.classicalmidiconnection.com/General_Midi.html[技術仕様]を参照のこと．
  ほとんどの楽器に対応しているが，コンピュータのプラットフォームによって違いがある．

*MIDI ノート*

オクターブ

C

C#

D

D#

E

F

F#

G

G#

A

A#

B

*0*

0

1

2

3

4

5

6

7

8

9

10

11

*1*

12

13

14

15

16

17

18

19

20

21

22

23

*2*

24

25

26

27

28

29

30

31

32

33

34

35

*3*

36

37

38

39

40

41

42

43

44

45

46

47

*4*

48

49

50

51

52

53

54

55

56

57

58

59

*5*

60

61

62

63

64

65

66

67

68

69

70

71

*6*

72

73

74

75

76

77

78

79

80

81

82

83

*7*

84

85

86

87

88

89

90

91

92

93

94

95

*8*

96

97

98

99

100

101

102

103

104

105

106

107

*9*

108

109

110

111

112

113

114

115

116

117

118

119

*10*

120

121

122

123

124

125

126

127
