= ProveDetails コマンド
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

ProveDetails( <論理式> )::
  自動証明の結果に関するいくつかの詳細を返す．

通常、GeoGebraは数値計算を用いてxref:/真偽値.adoc[論理式] 論理式が _真_ か _偽_
かを判断する．しかし，ProveDetailsコマンドはhttp://en.wikipedia.org/wiki/Symbolic_computation[記号演算(英文)]を使用して，一般にステートメントが真か偽かを判断する．このコマンドはxref:/commands/Prove.adoc[Prove]
コマンドと同様に機能するが，結果の詳細をxref:/リスト.adoc[リスト]として返す：

* GeoGebraが答えを決定できない場合は，空のリスト *\{}*．
* 一つの要素を持つリスト: *\{false}*．ステートメントが 一般的には真ではない 場合．
* 一つの要素を持つリスト: *\{true}*．ステートメントが 常に真 である場合 (図形が構築可能なすべての場合において)．
* 特定の条件下でステートメントが真である場合， _true_ の論理値といわゆる _非退化条件_
のリストを含む要素がより多いリストを返す．例えば，\{true,
\{"AreCollinear(A,B,C),AreEqual(C,D)"}}のようなリストである．これは，条件のいずれも真でない場合（そして図形が構築できる場合），命題は真となることを意味する．
* リスト**\{true,\{"..."}}**
は，ステートメントが特定の条件下で真であるが，これらの条件が何らかの理由で人間が読める形に変換できない場合．

[EXAMPLE]
====

線分 _AB_ を _a_ とし，`++l=Line(A,B)++`を定義する．_C_ を直線 _l_ 上の任意の点とし，さらに`++b=Segment(B,C)++`,
`++c=Segment(A,C)++` とする．P`++ProveDetails(a==b+c)++` を実行すると \{true,\{"a+b==c", "b==a+c"}}が返される．これは、
stem:[a+b=c]でもstem:[b=a+c]でもない場合，つまりstem:[a+b=c]やstem:[b=a+c]のいずれの条件も満たされない場合には，stem:[a=b+c]となることを意味する．

====

[EXAMPLE]
====

線分ABを __a__とし，`++C=MidPoint(A,B)++`, `++b=PerpendicularBisector(A,B)++`,
`++D=Intersect(a,b)++`と定義する．ここで`++ProveDetails(C==D)++` は \{true,\{"AreEqual(A,B)"}}を返す：点 _A_ と点 _B_
が異なれば，点 _C_ と点 _D_ は一致することを意味する．

====

[EXAMPLE]
====

頂点 _A_, _B_, __C__を持つ三角形を定義し,`++D=MidPoint(B,C)++`, `++E=MidPoint(A,C)++`, `++p=Line(A,B)++`,
`++q=Line(D,E)++`と定義する．`++ProveDetails(p∥q)++` を実行すると \{true}
が返され、これは図が描ける場合、中点をむずぶ線分 _DE_ は辺 _AB_ に平行であることを意味する．

====

非退化条件のリストが最も単純な集合でない可能性がある．上記の例では，最も単純な集合は空集合になる．

[NOTE]
====

こちらも参照： xref:/commands/Prove.adoc[Prove] コマンド， xref:/真偽値.adoc[真偽値],
https://github.com/kovzol/gg-art-doc/tree/master/pdf/english.pdf[GeoGebra Automated Reasoning Tools: A Tutorial]
（英文）， http://dev.geogebra.org/trac/wiki/TheoremProving[technical details of the algorithms]（英文）．

====
