= RandomBetween コマンド
:page-en: commands/RandomBetween
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

RandomBetween( <最小の整数> , <最大の整数> )::
  _最小の整数_ と _最大の整数_ の間のランダムな整数を生成する．
RandomBetween( <最小の整数> , <最大の整数> , <固定の真偽値> )::
  固定の真偽値が “true” の場合，_最小の整数_ と _最大の整数_
  の間のランダムな整数を生成する．この値はファイルがロードされた時，または 取り消し／元に戻す
  が行われた時に一度だけ更新される．

[EXAMPLE]
====

`++RandomBetween(0, 10, true)++` は _0_ 以上 _10_ 以下のランダムな整数を返す．

====

[EXAMPLE]
====

`++RandomBetween(0, 10)++` は _0_ 以上 _10_ 以下のランダムな整数を返す．

====

[NOTE]
====

[.kcode]#F9# キーを押すと，この2つの書式の違いを見ることができる．

====

RandomBetween( <最小の整数> , <最大の整数>, <サンプル数> )::
  _最小の整数_ と _最大の整数_
  の間のランダムな整数のリストを生成する．リストに含まれるランダムな整数の個数は，_サンプル数_ になる．

[EXAMPLE]
====

`++RandomBetween(0, 10, 5)++` 出力例： \{1,3,4,8,2}, \{7,5,6,1,7}, ほか．

====

[NOTE]
====

こちらも参照： xref:/commands/SetSeed.adoc[SetSeed コマンド], xref:/commands/RandomElement.adoc[RandomElement コマンド],
xref:/commands/RandomBinomial.adoc[RandomBinomial コマンド], xref:/commands/RandomNormal.adoc[RandomNormal コマンド],
xref:/commands/RandomPoisson.adoc[RandomPoisson コマンド], xref:/commands/RandomUniform.adoc[RandomUniform コマンド].

====
