= SolveODE コマンド
:page-en: commands/SolveODE
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

SolveODE( <f'(x, y)> )::
  一階常微分方程式（ODE） stem:[\frac{dy}\{dx}(x)=f'(x, y(x))]の厳密解を求める．

[EXAMPLE]
====

`++SolveODE(2x / y)++` 出力： _stem:[\sqrt{2} \sqrt{-c_\{1}+x^\{2}}]_, ここで， stem:[c_\{1}] は定数．

====

[NOTE]
====

stem:[c_\{1}] は，補助オブジェクトとして自動的にスライダーが作成される．

====
SolveODE( <f'(x, y)>, <f上の点> )::
  1 階常微分方程式（ODE） stem:[\frac{dy}\{dx}(x)=f'(x, y(x))]の厳密解から，与えられた点を通る解を求める．

[EXAMPLE]
====

`++SolveODE(y / x, (1, 2))++` 出力： _y = 2x_.

====

SolveODE( <f'(x, y)>, <x開始値>, <　y開始値>, <x終了値>, <間隔> )::
  1 階常微分方程式（ODE） stem:[\frac{dy}\{dx}(x)=f'(x, y)]を与えられた _x_
  の開始値，終了値，間隔を使って数値的に解く．

[EXAMPLE]
====

`++SolveODE(-x*y, x(A), y(A), 5, 0.1)++` は stem:[\frac{dy}\{dx}=-xy] を，あらかじめ定義した _A_
を出発点として解く．

====




[NOTE]
====

* xref:/commands/Length.adoc[Length]( <軌跡> ) を使うと，計算された軌跡に含まれる点の数を知ることができる．
* xref:/commands/First.adoc[First]( <軌跡>, <数値> ) を使うと，点をリストとして取り出すことができる．
* _逆解_ を求めるには，_End x_ に負の値を入力する．例：`++SolveODE(-x*y, x(A), y(A), -5, 0.1)++`

====



SolveODE( <y'>, <x'>, <x開始値>, <y開始値>, <t終了値>, <間隔> )::
  開始点，内部パラメータ _t_ の最大値，及び _t_
  のステップを指定して一階常微分方程式（ODE）stem:[\frac{dy}\{dx}=\frac{f(x, y)}\{g(x, y)}]
  を解く．このコマンドのバージョンは，例えば解の曲線に垂直な点が存在する場合など，最初のバージョンが失敗する可能性がある状況でも機能することがある．

[EXAMPLE]
====

`++SolveODE(-x, y, x(A), y(A), 5, 0.1)++` solves stem:[\frac{dy}\{dx}=- \frac{x}\{y} ] は，あらかじめ定義した _A_
を出発点として解く．

====

[NOTE]
====

_逆解_ を求めるには，_End x_ に負の値を入力する．例： `++SolveODE(-x, y, x(A), y(A), -5, 0.1)++`．

====

SolveODE( <b(x)>, <c(x)>, <f(x)>, <x開始値>, <y開始値>, <y'開始値>, <x終了値>, <間隔> )::
  2階の常微分方程式 stem:[y'' + b(x) y' + c(x) y = f(x)]を解く．

[EXAMPLE]
====

`++SolveODE(x^2, 2x, 2x^2 + x, x(A), y(A), 0, 5, 0.1)++` は，あらかじめ定義した _A_
を出発点として2階の常微分方程式を解く．

====

[NOTE]
====

常に結果を軌跡として返す．アルゴリズムは現在のところ https://en.wikipedia.org/wiki/ja:%E3%83%AB%E3%83%B3%E3%82%B2%EF%BC%9D%E3%82%AF%E3%83%83%E3%82%BF%E6%B3%95[ルンゲ＝クッタ法] に基づく．

====

[NOTE]
====

こちらも参照 xref:/commands/SlopeField.adoc[SlopeField コマンド].

====

== CAS での書式

SolveODE( <等式> )::
  1階または2階の常微分方程式（ODE）の厳密解を求める．_y_ の1次導関数には __y'__を，2次導関数には __y''__を使用できる．

[EXAMPLE]
====

`++SolveODE(y' = y / x)++` 出力： _y = c~1~ x_.

====

SolveODE( <等式>, <f上の点（のリスト）> )::
  与えられた点を通る，1階または2階の常微分方程式（ODE）の厳密解を求める．

[EXAMPLE]
====

`++SolveODE(y' = y / x, (1, 2))++` 出力： _y = 2x_.

====

SolveODE( <等式>, <f上の点（のリスト）>, <f'上の点（のリスト）> )::
  与えられた 1 次または 2 次常微分方程式の厳密解を求め，その解が指定された _f上の点_ を通るようにし，さらに解の微分 _f'_
  も指定された__f'上の点__ を通るようにする．

[EXAMPLE]
====

`++SolveODE(y'' - 3y' + 2 = x, (2, 3), (1, 2))++` 出力： stem:[ y = \frac{-9 x^2 e^3 + 30 x e^3 - 32 \{(e^3)}^2 + 138
e^3 + 32 e^\{3 x} }\{54 e^3} ].

====

SolveODE( <等式>, <従属変数>, <独立変数>, <f上の点（のリスト）> )::
  A与えられた 1 次または 2 次常微分方程式の厳密解を求め，それが指定された点を通るようにする．

[EXAMPLE]
====

`++SolveODE(v' = v / w, v,  w, (1, 2))++` yields _v = 2w_.

====

SolveODE( <等式>, <従属変数>, <独立変数>, <f上の点（のリスト）>, <f'上の点（のリスト）> )::
  与えられた 1 次または 2 次の常微分方程式の厳密解を求め，その解が指定された _f上の点_ を通るようにし，かつ解の微分 _f'_
  も指定された__f'上の点__ を通るようにする

[EXAMPLE]
====

`++SolveODE(v' = v / w, v,  w, (1, 2), (0, 2))++` 出力： _v = 2w_.

====

[NOTE]
====

入力バーとの互換性のため，最初のパラメータが _y'_ や _y''_ を含まない単なる式である場合，それは _y'_
を左辺とする常微分方程式（ODE）の右辺とみなされる．

====
