= Commande AppliquerMatrice
:page-en: commands/ApplyMatrix
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

AppliquerMatrice(<xref:/Matrices.adoc[Matrice] M>,<Objet O>)::
  Transforme l'objet de sorte que le point _P_ de _O_ ait pour image

*si _P_ est un point _2D_ :*

le point _M*P_ si M est une matrice 2stem:[\times]2

[EXAMPLE]
====

Soit `++M={{cos(π/2),-sin(π/2)},{sin(π/2),cos(π/2)}}++` la matrice (en fait stem:[\begin{pmatrix}0&-1\\ 1&0
\end{pmatrix}]) de la transformation et `++u=(2,1)++` un vecteur donné. `++AppliquerMatrice(M,u)++` retourne le vecteur
_u´=(-1,2)_ image de u dans la rotation de 90 degrés dans le sens direct .

====

le point _projeté(M*(x(P), y(P), 1))_ où _projeté_ est le point image de _(x,y,z)_ en _(x/z, y/z)_ si M est une matrice
3stem:[\times]3 ;

[EXAMPLE]
====

Soit `++M={{1,1,0},{0,1,1},{1,0,1}}++`et `++u=(2,1)++` un vecteur donné. `++AppliquerMatrice(M,u)++`
retourne le vecteur _u´=(1,0.67)_. En effet : stem:[\begin{pmatrix}1&1&0\\ 0&1&1\\1&0&1 \end{pmatrix}]
stem:[\begin{pmatrix}2\\ 1\\1 \end{pmatrix}] = stem:[\begin{pmatrix}3\\ 2\\3 \end{pmatrix}], soit (3/3 = 1, 2/3 ≈
0.67) (_Option : 2 décimales_)

====

*si _P_ est un point _3D_ :*

le point _M*P_ si M est une matrice 3stem:[\times]3 ;

le point _N*P_ si M est une matrice 2stem:[\times]2, la matrice _N_ étant une _complétion_ en matrice 3stem:[\times]3
stem:[\begin{pmatrix}a&b&0\\ c&d&0\\0&0&1 \end{pmatrix}] de _M_ = stem:[\begin{pmatrix}a&b\\ c&d \end{pmatrix}]

[NOTE]
====

Cette commande fonctionne aussi pour les images.

====
