= Commande DiagrammeBâtons
:page-en: commands/StickGraph
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

DiagrammeBâtons( <Liste de points> )::
  Dessine un diagramme en bâtons à partir de la liste de points. Pour chaque point est tracé un segment le joignant à
  son projeté sur l'axe des abscisses parallèlement à l'axe des ordonnées.

[EXAMPLE]
====

*Exemple :* `++DiagrammeBâtons({(1, 1), (3, 2), (4, 5), (5, 7)})++`

====

DiagrammeBâtons( <Liste de points>, <Booléen Horizontal> )::
  Si _Horizontal_ = _false_, on est dans la situation précédente ;
  Si _Horizontal_ = _true_, pour chaque point est tracé un segment le joignant à son projeté sur l'axe des ordonnées
  parallèlement à l'axe des abscisses.

[EXAMPLE]
====

*Exemple :* `++DiagrammeBâtons({(1, 1), (3, 2), (4, 5), (5, 7)}, true)++`

====

DiagrammeBâtons( <Liste d'abscisses>, <Liste d'ordonnées> )::
  Dessine un diagramme en bâtons pour la liste de points construits à partir des deux listes de coordonnées.

[EXAMPLE]
====

*Exemple :* `++DiagrammeBâtons({1, 3, 4, 5}, {1, 2, 5, 7})++`

====

DiagrammeBâtons( <Liste d'abscisses>, <Liste d'ordonnées>, <Booléen Horizontal> )::
  même comportement que la deuxième syntaxe

[EXAMPLE]
====

*Exemple :* `++DiagrammeBâtons({1, 3, 4, 5}, {1, 2, 5, 7}, true)++`

====
