= Commande Histogramme
:page-en: commands/Histogram
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

Histogramme( <Liste Bornes Classes>, <Liste Hauteurs> )::
  Histogramme avec les barres de hauteurs données. Les limites de classes déterminent la largeur et la position de
  chacune des barres de l’histogramme.

[EXAMPLE]
====

`++Histogramme({0,1,2,3,4,5},{2,6,8,3,1})++` crée un histogramme à cinq barres de hauteurs données. La
première barre est positionnée sur l’intervalle [_0, 1_], la deuxième sur l’intervalle [_1, 2_], etc.

====

[NOTE]
====

Ne pas oublier que Longueur(<Liste Hauteurs>) = Longueur(<Liste Bornes Classes>) *- 1* !

====

Histogramme( <Liste Bornes Classes>, <Liste Données>, <Densité True|False> , <Echelle> (optionnel) )::
  Les bornes des classes déterminent la largeur et la position de chacune des barres de l’histogramme et sont utilisées
  pour déterminer combien des données appartiennent à chaque classe.

Les hauteurs des barres sont déterminées comme suit :

* Si _Densité = true_, hauteur = (Echelle) * (effectif de la classe) / (largeur de la classe)
* Si _Densité = false_, hauteur= effectif de la classe

Par défaut, Densité = true et Echelle= 1. Ceci crée un histogramme dont l'aire totale vaut _n_, le nombre de données.

[NOTE]
====

Toutes les données doivent appartenir à l'intervalle déterminé par le minimum et le maximum de toutes les
bornes sinon l'histogramme sera “non défini”.

====

[EXAMPLE]
====

(_Histogramme par défaut_ )`++Histogramme({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true)++` crée
un histogramme à 3 barres de hauteurs : 0.5 (1ère barre), 0.2 (2ème), et 0.1 (3ème).L'aire totale de l'histogramme est
0.5*10 + 0.2*10 + 0.1*10 = 8.

====

[EXAMPLE]
====

(_Histogramme de dénombrement_ )`++Histogramme({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, false)++`
crée un histogramme à 3 barres de hauteurs : 5 (1ère barre), 2 (2ème), et 1(3ème). Cet histogramme ne prend pas en
compte la densité, les hauteurs des barres sont les effectifs de chacune des classes.

====

[EXAMPLE]
====

(_Histogramme normalisé_)`++Histogramme({10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true, 1/8)  ++`
crée un histogramme à 3 barres de hauteurs : .0625 (1ère barre), .025 (2ème), et .0125 (3ème) . L'aire totale de
l'histogramme est = .0625*10 + .025*10 + .0125*10 = 1.Si _n_ est le nombre de données, alors Echelle = _1/n_ crée un
histogramme normalisé d'aire totale = 1. C'est utile pour ajuster un histogramme avec une courbe de densité.

====

Histogramme(<Booléen Cumul>,<Liste Bornes Classes>,<Liste Données>,<Densité True|False>,<Echelle>(optionnel) )::
  Si le booléen _cumul_ est _true_ crée un histogramme d'effectifs cumulés.

[EXAMPLE]
====

*Exemple :* :`++Histogramme(true, {10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true)++`crée un histogramme à 3
barres de hauteurs : 0.5 (1ère barre), 0.7 (2ème), et 0.8 (3ème) .

====

[.kcode]#Saisie :# Voir aussi la *commande* : xref:/commands/HistogramDroite.adoc[HistogramDroite].
