= Commande SontAlignés
:page-en: commands/AreCollinear
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

xref:commands/Commandes_Géométrie.adoc[Commandes Géométrie]

SontAlignés( <Point>, <Point>, <Point> )::
  se prononce sur l'alignement des points.

Normalement cette commande détermine le résultat numériquement. Ce comportement peut être changé en utilisant la
commande xref:/commands/Prouver.adoc[Prouver] .

[EXAMPLE]
====

`++SontAlignés((1, 2), (3, 4), (5, 6))++` retourne _true_ car les trois points appartiennent à la même
droite.

Pour les cas dégénérés, la réponse est aussi  _true_

`++SontAlignés((1, 2), (1, 2), (5, 6))++` ou `++SontAlignés((1, 2), (1, 2), (1, 2))++`
====

[.kcode]#Saisie :# Voir aussi les *commandes* : xref:/commands/EstTangente.adoc[EstTangente],
xref:/commands/SontCocycliques.adoc[SontCocycliques], xref:/commands/SontConcourantes.adoc[SontConcourantes],
xref:/commands/SontÉgaux.adoc[SontÉgaux], xref:/commands/SontIsométriques.adoc[SontIsométriques],
xref:/commands/SontParallèles.adoc[SontParallèles], xref:/commands/SontPerpendiculaires.adoc[SontPerpendiculaires].
