= Commande SontIsométriques
:page-en: commands/AreCongruent_Command
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

SontIsométriques( <Objet>, <Objet> )::
  Détermine si les objets sont "isométriques".

Pour des segments, cela se restreint donc à savoir s'ils ont même longueur.

[EXAMPLE]
====

*Exemple :* `++SontIsométriques(Segment((1, 2), (3, 4)), Segment((3, 4), (1, 6)])++` retourne _true_ . Cette commande
équivaut à l'opération booléenne xref:/Valeurs_booléennes.adoc[égal], `++Segment((1,2),(3,4)) ≟ Segment((3,4),(1,6))++`
(les deux segments sont de même longueur).Ne pas confondre avec
`++SontÉgaux(Segment((1, 2), (3, 4)), Segment((3, 4), (1, 6)])++` qui retourne _false_, les deux segments sont de même
longueur mais ne sont pas un même segment.

====

[.kcode]#Saisie :# Voir aussi les *commandes* : xref:/commands/EstTangente.adoc[EstTangente],
xref:/commands/SontÉgaux.adoc[SontÉgaux], xref:/commands/SontAlignés.adoc[SontAlignés],
xref:/commands/SontParallèles.adoc[SontParallèles], xref:/commands/SontConcourantes.adoc[SontConcourantes],
xref:/commands/SontPerpendiculaires.adoc[SontPerpendiculaires], xref:/commands/SontCocycliques.adoc[SontCocycliques].
