= Commande ZEstimationMoyenne
:page-en: commands/ZMeanEstimate
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

xref:commands/Commandes_Statistiques.adoc[Commandes Statistiques]

ZEstimationMoyenne( <Liste Données Échantillon>, <Écart-type Population σ>, <Niveau Confiance α> )::
  Estimation, au _niveau de confiance α_, de l'intervalle de confiance de la moyenne de la population dont on ne connaît
  que l'_écart-type σ_, et la liste des valeurs d'une partie de cette population (_échantillon_).

L'intervalle de confiance est donné sous la forme {limite inférieure de confiance , limite supérieure de confiance}.

ZEstimationMoyenne( <Moyenne Échantillon>,<Écart-type Population σ>,<Taille Échantillon>,<Niveau Confiance α> )::
  Estimation, au _niveau de confiance α_, de l'intervalle de confiance de la moyenne de la population dont on ne connaît
  que l'_écart-type σ_ ainsi que la _moyenne_ et le nombre (_taille_) des valeurs d'une partie de cette population
  (_échantillon_).

L'intervalle de confiance est donné sous la forme {limite inférieure de confiance , limite supérieure de confiance}.
