= Commande ZEstimationMoyenne
:page-en: commands/ZMeanEstimate_Command
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

ZEstimationMoyenne( <Liste Données Échantillon>, <Écart-type Population σ>, <Niveau Confiance α> )::
  Estimation, au niveau de confiance α, de l'intervalle de confiance de la moyenne de la population dont on ne connaît
  que l'écart-type σ, et la liste des valeurs d'une partie de cette population (échantillon).
  L'intervalle de confiance est donné sous la forme \{limite inférieure de confiance , limite supérieure de confiance}.

ZEstimationMoyenne( <Moyenne Échantillon>,<Écart-type Population σ>,<Taille Échantillon>,<Niveau Confiance α> )::
  Estimation, au niveau de confiance α, de l'intervalle de confiance de la moyenne de la population dont on ne connaît
  que l'écart-type σ ainsi que la moyenne et le nombre (taille) des valeurs d'une partie de cette population
  (échantillon).
  L'intervalle de confiance est donné sous la forme \{limite inférieure de confiance , limite supérieure de confiance}.
