= Commande ZTestMoyenne2
:page-en: commands/ZMean2Test_Command
ifdef::env-github[:imagesdir: /fr/modules/ROOT/assets/images]

ZTestMoyenne2( <Liste Données Éch1>, <σ1>, <Liste Données Éch2>, <σ2>, <Queue> ]::
  Réalise un Z-test de la différence des moyennes de deux populations dont on ne connaît que l'écart-type σ, et la liste
  des valeurs d'une partie de ces populations (échantillons).

_Queue_ peut être "<", ">" ou "≠" ce qui définit les hypothèses alternatives suivantes :

"<" = différence des moyennes de populations < 0

">" = différence des moyennes de populations > 0

"≠" = différence des moyennes de populations ≠ 0

Les résultats sont fournis sous forme de liste \{Probabilité, statistique Z-test }.

ZTestMoyenne2( <Moy Éch1>, <σ1>, <Taille Éch1>, <Moy Éch2>, <σ2>, <Taille Éch2>, <Queue> ]::
  Réalise un Z-test de la différence des moyennes de deux populations dont on ne connaît que l'écart-type σ, et la
  moyenne des valeurs d'une partie de ces populations (échantillons). _Queue_ est définie comme ci-dessus.
