= Alati
:page-en: Tools
ifdef::env-github[:imagesdir: /bs/modules/ROOT/assets/images]

Alati omogućavaju konstrukcije novih figura pomoću kursora. Svi alati imaju ekvivalentne xref:/Naredbe.adoc[naredbe]
koje su pogodne za složenije konstrukcije.

Alati za konstrukciju ili moduli mogu biti aktivirani klikom na ikonu xref:/Alatna_traka.adoc[alatne trake]. Također,
možemo kliknuti na malu strelicu u donjem desnom kutu ikone za otvaranje izbornika sličnih alata. Drugi način da
odaberemo alat je da koristimo izbornik [.mw-selflink .selflink]#alati#.

Prema zadanim postavkama, alati su grupisani u dvanaest padajućih izbornika:

* xref:/Pomjeranje_Alat.adoc[Pomjeranje-Alati]
* xref:/Tačka_Alati.adoc[Tačka-Alati]
* xref:/Prava_Alati.adoc[Prava- Alati]
* xref:/tools/Prava_Specijalni_alati.adoc[Prava-Specijalni alati]
* xref:/Mnogougao_Alati.adoc[Mnogougao-Alati]
* xref:/Kružnica_Kružni_luk_Alati.adoc[Kružnica & Kružni luk - Alati]
* xref:/Konike_Alati.adoc[Konike -Alati]
* xref:/Udaljenost_Alati.adoc[Udaljenost-Alati]
* xref:/Transformacije_Alati.adoc[Transformacije -Alati]
* xref:/tools/Specijalni_alati.adoc[Figura-Specijalni alati]
* xref:/Dinamični_Alati.adoc[Dinamični alati]
* xref:/Opći_Alati.adoc[Opći alati]
* xref:/Korisnički_Alati.adoc[Korisnički alati]

Također, možemo promijeniti redoslijed tih padajući izbornika i spremiti postavke u /Reference:File_Format.adoc[GeoGebra
Datoteke (*.ggb)]. Za više detalja pogledajte xref:/Alatna_traka.adoc[Prilagođavanje izgleda alatne trake].

[NOTE]
====

Kod većine konstruktivnih alata, vrlo jednostavno možemo kreirati nove tačke klikom na prazan prostor na radnoj površi.

====

U xref:/CAS_Prikaz.adoc[CAS prikazu] i xref:/Tabelarni_prikaz.adoc[Tabelarnom prikazu] možemo koristiti
xref:/CAS_Alati.adoc[CAS-alate] i xref:/Tabela_Alati.adoc[Tabela-alate] respektivno.
