= Geometrijske Figure
:page-en: Geometric_Objects
ifdef::env-github[:imagesdir: /bs/modules/ROOT/assets/images]

Program GeoGebra radi s mnogo tipova geometrijskih figura

* xref:/Tačke_i_Vektori.adoc[Tačke i Vektori]
* xref:/Prave_i_Ose.adoc[Prave i Ose]
* xref:/Konusni_Presjeci.adoc[Konike i Lukovi]
* xref:/Funkcije.adoc[Funkcije]
* xref:/Krive.adoc[Krive]
* xref:/Nejednakosti.adoc[Nejednakosti]
* xref:/Intervali.adoc[Intervali]
== Putanje

Neke od gore pomenutih figura (prave, konike, lukovi, mnogouglovi, funkcije, nejednačine s jednom promjenljivom,
intervali, liste tačaka) nazivamo i _putanje_. Koristeći naredbu xref:/Tačka_Naredba.adoc[Tačka] možemo definirati
xref:/Tačke_i_Vektori.adoc[tačku] koja pripada putanji. Svakoj tački duž putanje pridružen je parametar putanje, koji je
broj između 0 i 1. Da bismo dobili parametar putanje, možemo koristiti naredbu
xref:/ParametarPutanje_Naredba.adoc[ParametarPutanje].

[NOTE]
====

xref:/Liste.adoc[Liste] drugih putanja također su putanje.

====

== Regioni

Također, možemo ograničiti da tačka pripada regionu (mnogougla, konike, luka, nejednačina s dvije promjenljive)
koristeći naredbu xref:/TačkaU_Naredba.adoc[TačkaU] ili alat xref:/Tačka_na_Figuri_Alat.adoc[Tačka na Figuri].

[NOTE]
====

Vidi također alat xref:/Spoji_Odvoji_Tačku_Alat.adoc[Spoji/Odvoji Tačku].

====
