= Olovka-Alat Alat
:page-en: tools/Pen
ifdef::env-github[:imagesdir: /bs/modules/ROOT/assets/images]

Alat Olovka omogućava korisniku da piše ili crta slobodnom rukom po xref:/Radna_površ.adoc[radnoj površi]. Posebno je
korisna kada se GeoGebra koristi za prezentacije ili na _pametnoj tabli_. Kako bi na radnu površ dodali bilješke pisane
slobodnom rukom stisnemo lijevi klik miša i pišemo ili crtamo. Da završimo samo pustimo klik miša.

GeoGebra sprema bilješkes radne povši kao xref:/IzlomljenaLinija_Naredba.adoc[izlomljene linije] (imenujući ih skicama),
tako da možemo s njima raditi svaku operaciju kao i sa povezanim figurama (pomjerati, rotirati, brisati, itd.).

Zadana boja olovke je crna, no osobinw olovke (boju, stil i debljinu) možemo mijenjati koristeći
xref:/Prikazi.adoc[traku za stil], označivši prvu ikonu u traci radne površi.

== Brisanje

Kako bi obrisali djelove bilješki koje smo napravili na radnoj površi pomoću alata Olovka, pritisnimo i držimo pritisnut
desni klik miša dok ga pomjeramo preko bilješki koje želimo obrisati. Brisanje je gotovo kada otpustite tipku miša. Ako
želimo izbrisati cjelokupnu kreiranu skicu, koristit ćemo padajući izbornik figure ili odgovarajući izraz u Algebarskom
prikazu.
