= DefinertMangekant Kommando
:page-en: commands/RigidPolygon
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

DefinertMangekant[ <Fritt punkt>, ..., <Fritt punkt> ]::
  Lagar ein mangekant som forma ikkje kan endrast på. Mangekanten kan verte flytta ved å dra i det første hjørnet og
  verte rotert ved å dra i det andre hjørnet.
DefinertMangekant[ <Mangekant> ]::
  Lagar ein kopi av ein mangekant. Det er ikkje mogleg å endre forma på kopien, men han kan verte flytta ved å dra i det
  første hjørnet og verte rotert ved å dra i det andre hjørnet.
DefinertMangekant[ <Mangekant>, <Tal x>, <Tal y>]::
  Lagar ein kopi av ein mangekant. Kopien er forskyvd langs x-aksen med _x_ og langs y-aksen med _y_. Det er ikkje
  mogleg å endre forma på kopien, men han kan verte flytta ved å dra i det første hjørnet og verte rotert ved å dra i
  det andre hjørnet.

[NOTE]
====

*Merk:* Kopien vil følgje alle endringar som vert gjort på den opphavlege mangekanten. Dersom du vil endre forma på
kopien må du difor endre originalen.

====
