= Element Kommando
:page-en: commands/Element
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Element[ <Liste>, <Tal n> ]::
  Gjev element _n_ i lista.
Element[ <Matrise>, <Rad>, <Kolonne> ]::
  Gjev elementet i matrisa frå den gjevne rada og kolonna.
Element[ <Liste>, <Indeks1>, <Indeks2>, ... ]::
  Gjeven at lista er _n_-dimensjonal så kan ein gje opp til _n_ indeksar for å få elementet (eller lista av element) for
  dei gjevne koordinatane.

[EXAMPLE]
====

*Døme:*

La _L=\{\{\{1, 2}, \{3, 4}}, \{\{5, 6}, \{7, 8}}}_. Då vil `++Element[L, 1, 2, 1]++` gje _3_ og `++Element[L, 2, 2]++`
gje _\{7, 8}_.

====

[EXAMPLE]
====

*Døme:*

`++Element[{{1, 3, 2}, {0, 3, -2}}, 2, 3]++` gjev _-2_, som er elementet i andre rad og tredje kolonne i
stem:[\begin\{pmatrix}1&3&2\\0&3&-2\end\{pmatrix}].

====

[EXAMPLE]
====

*Døme:*

`++Element[{1, 3, 2}, 2]++` gjev _3_, som er det andre elementet i _\{1, 3, 2}_.

====

[NOTE]
====

*Merk:* For at denne kommandoen skal fungere må lista eller matrisa innehalde berre ein type element (til dømes berre
tal eller berre punkt).

====

== CAS-delen

Element[ <Liste>, <Tal n> ]::
  Gjev element _n_ i lista. Kommandoen kan også verte brukt når lista inneheld udefinerte element.
Element[ <Matrise>, <Rad>, <Kolonne> ]::
  Gjev elementet i matrisa frå den gjevne rada og kolonna. Kommandoen kan også verte brukt når matrisa inneheld
  udefinerte element.

[EXAMPLE]
====

*Døme:*

`++Element[{{a, b, c}, {d, e, f}}, 2, 3]++` gjev _f_, som er elementet i andre rad og tredje kolonne i
stem:[\begin\{pmatrix}a&b&c\\d&e&f\end\{pmatrix}].

====

[EXAMPLE]
====

*Døme:*

`++Element[{a, b, c}, 2]++` gjev _b_, som er det andre elementet i _\{a, b, c}_.

====

[NOTE]
====

*Merk:* Sjå også kommandoane xref:/commands/Første.adoc[Første], xref:/commands/Siste.adoc[Siste] og
xref:/commands/TilfeldigElement.adoc[TilfeldigElement].

====
