= Fyrstikkgraf Kommando
:page-en: commands/StickGraph
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Fyrstikkgraf[ <Liste med punkt> ]::
  Teiknar ein _fyrstikkgraf_ for dei gjevne punkta. For kvart punkt vert ei vertikal linje teikna frå _x_-asksen til
  punktet.
Fyrstikkgraf[ <Liste med punkt>, <Boolsk Horisontal> ]::
  Teiknar ein _fyrstikkgraf_ for dei gjevne punkta.
  * Dersom _Horisontal = false_ vert ei vertikal linje teikna frå _x_-asksen til kvart punkt.
  * Dersom _Horisontal = true_ vert ei horisontal linje teikna frå _y_-asksen til kvart punkt.

Fyrstikkgraf[ <Liste med x-koordinatar>, <Liste med y-koordinatar> ]::
  Teiknar ein _fyrstikkgraf_ for dei to listene med koordinatar. For kvart punkt vert ei vertikal linje teikna frå
  _x_-asksen til punktet.
Fyrstikkgraf[ <Liste med x-koordinatar>, <Liste med y-koordinatar>, <Boolsk Horisontal> ]::
  Teiknar ein _fyrstikkgraf_ for dei to listene med koordinatar.
  * Dersom _Horisontal = false_ vert ei vertikal linje teikna frå _x_-asksen til kvart punkt.
  * Dersom _Horisontal = true_ vert ei horisontal linje teikna frå _y_-asksen til kvart punkt.
