= Følgje Kommando
:page-en: commands/Sequence
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Følgje[ <Sluttverdi b> ]::
  Lagar ei liste av tal frå 1 til _b_.

[EXAMPLE]
====

*Døme:*

* `++Følgje[8]++` lagar lista _\{1, 2, 3, 4, 5, 6, 7, 8}_.
* `++2^Følgje[4]++` lagar lista _\{2, 4, 8, 16}_.

====

Følgje[ <Uttrykk>, <Variabel i>, <Tal a>, <Tal b> ]::
  Gjev ei liste med objekt som vert laga når variabelen _i_ går over tala frå _a_ til _b_ i det gjevne uttrykket.
Følgje[ <Uttrykk>, <Variabel i>, <Tal a>, <Tal b>, <Steglengde s> ]::
  Gjev ei liste med objekt som vert laga når variabelen _i_ går over tala frå _a_ til _b_ med steglengde _s_ i det
  gjevne uttrykket.

[EXAMPLE]
====

*Døme:*

`++Følgje[(2, i), i, 1, 3, 0.5]++` lagar ei liste med punkt som har _x_-koordinat lik 2 og _y_-koordinat som går frå 1
til 3 med steglengde 0.5: _\{(2, 1), (2, 1.5), (2, 2), (2, 2.5), (2, 3)}_.

====

[EXAMPLE]
====

*Døme:*

`++Følgje[(2, i), i, 1, 5]++` lagar ei liste med punkt som har _x_-koordinat lik 2 og _y_-koordinat som går frå 1 til 5:
_\{(2, 1), (2, 2), (2, 3), (2, 4), (2, 5)}_.

====

[NOTE]
====

*Merk:* Sidan parametrane _a_ og _b_ er dynamiske kan xref:/tools/Glidar.adoc[glidare] verte brukt i dei to siste
tilfella ovanfor.

====

[NOTE]
====

*Merk:* Sjå xref:/Lister.adoc[lister] for meir informasjon om listeoperasjonar.

====

== CAS-delen

Følgje[ <Sluttverdi b> ]::
  Lagar ei liste av tal frå 1 til _b_.

[EXAMPLE]
====

*Døme:*

* `++Følgje[8]++` lagar lista _\{1, 2, 3, 4, 5, 6, 7, 8}_.
* `++2^Følgje[4]++` lagar lista _\{2, 4, 8, 16}_.

====

Følgje[ <Uttrykk>, <Variabel i>, <Tal a>, <Tal b> ]::
  Gjev ei liste med objekt som vert laga når variabelen _i_ går over tala frå _a_ til _b_ i det gjevne uttrykket.
Følgje[ <Uttrykk>, <Variabel i>, <Tal a>, <Tal b>, <Steglengde s> ]::
  Gjev ei liste med objekt som vert laga når variabelen _i_ går over tala frå _a_ til _b_ med steglengde _s_ i det
  gjevne uttrykket.

[EXAMPLE]
====

*Døme:*

`++Følgje[x^i, i, 1, 10, 2]++` lagar lista _\{x, x³, x⁵, x⁷, x⁹}_.

====

[EXAMPLE]
====

*Døme:*

`++Følgje[x^i, i, 1, 10]++` lagar lista _\{x, x², x³, x⁴, x⁵, x⁶, x⁷, x⁸, x⁹, x¹⁰}_.

====
