= GrenseUnder Kommando
:page-en: commands/LimitBelow
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

GrenseUnder[ <Funksjon f>, <Verdi t> ]::
  Finn den venstre einsidige grenseverdien til funksjonen _f_ når verdien _t_ vert sett inn for hovedvariabelen i
  funksjonen.

[EXAMPLE]
====

*Døme:*

`++GrenseUnder[1 / x, 0]++` gjev stem:[-\infty] .

====

[NOTE]
====

*Merk:* Ikkje alle grenseverdiar kan verte funne av GeoGebra, så _udefinert_ vil verte returnert både i dei tilfella og
når det korrekte resultatet er udefinert.

====

[NOTE]
====

*Merk:* Sjå også kommandoane xref:/commands/Grenseverdi.adoc[Grenseverdi] og xref:/commands/GrenseOver.adoc[GrenseOver].

====

== CAS-delen

GrenseUnder[ <Uttrykk f>, <Verdi t> ]::
  Finn den venstre einsidige grenseverdien til uttrykket _f_ når verdien _t_ vert sett inn for hovedvariabelen i
  funksjonen.
GrenseUnder[ <Uttrykk f>, <Variabel v>, <Verdi t> ]::
  Finn den venstre einsidige grenseverdien til uttrykket _f_ når verdien _t_ vert sett inn for variabelen _v_ i
  funksjonen.

[EXAMPLE]
====

*Døme:*

`++GrenseUnder[1 / a, a, 0]++` gjev stem:[-\infty] .

====

[EXAMPLE]
====

*Døme:*

`++GrenseUnder[1 / x, 0]++` gjev stem:[-\infty] .

====

[NOTE]
====

*Merk:* Ikkje alle grenseverdiar kan verte funne av GeoGebra, så _?_ vil verte returnert både i dei tilfella og når det
korrekte resultatet er udefinert.

====
