= Kontingenstabell Kommando
:page-en: commands/ContingencyTable
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Kontingenstabell[ <Tekstliste>, <Tekstliste> ]::
  Teiknar ein kontingenstabell som vert laga frå dei to listene. Unike verdiar frå første liste vert bruk som radar i
  tabellen, medan unike verdiar frå den andre lista vert brukt som kolonner i tabellen.
Kontingenstabell[ <Tekstliste>, <Tekstliste>, <Alternativ for ut-data> ]::
  Teiknar ein kontingenstabell som vert laga frå dei to listene på same måte som over. Teksten _Alternativ for ut-data_
  kontrollerar visninga av valfrie berekningar i tabellen.

[NOTE]
====

*Merk:* Moglege verdiar for _Alternativ for ut-data_ er "|", "_", "+", "e", "k", "=".

* "|" = vis kolonneprosentar
* "_" = vis radprosentar
* "+" = vis totale prosentar
* "e" = vis forventa tal
* "k" = vis kjikvadrat bidrag
* "=" = vis resultat av kjikvadrat test

====

Kontingenstabell[ <Liste med radverdiar>, <Liste med kolonneverdiar>, <Frekvenstabell> ]::
  Teiknar ein kontingenstabell som vert laga frå listene med radverdiar, kolonneverdiar og samsvarande frekvenstabell.
Kontingenstabell[ <Liste med radverdiar>, <Liste med kolonneverdiar>, <Frekvenstabell>, <Alternativ for ut-data> ]::
  Teiknar ein kontingenstabell som vert laga frå listene med radverdiar, kolonneverdiar og samsvarande frekvenstabell.
  Teksten _Alternativ for ut-data_ kontrollerar visninga av valfrie berekningar i tabellen på same måte som over.
