= StartAnimasjon Kommando
:page-en: commands/StartAnimation
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

StartAnimasjon[ ]::
  Startar opp att alle animasjonar dersom dei er sett på pause.
StartAnimasjon[ <Boolsk b> ]::
  Avhengig av verdien til _b_ vil animasjonar verte starta eller pausa.
  * Dersom _b = false_ vert alle animasjonar pausa.
  * Dersom _b = true_ vert alle animasjonar starta.

StartAnimasjon[ <Glidar eller punkt>, <Glidar eller punkt>, ... ]::
  Startar animasjon av gjevne punkt og/eller xref:/commands/Glidar.adoc[glidarar]. Punkt må ligge på
  xref:/Geometriske_objekt.adoc[stiar] for å kunne verte animerte.
StartAnimasjon[ <Glidar eller punkt>, <Glidar eller punkt>, ..., <Boolsk b> ]::
  Avhengig av verdien til _b_ vil animasjon av gjevne punkt og/eller xref:/commands/Glidar.adoc[glidarar] starte eller
  stoppe. Punkt må ligge på xref:/Geometriske_objekt.adoc[stiar] for å kunne verte animerte.
  * Dersom _b = false_ vert animasjonane stoppa.
  * Dersom _b = true_ vert animasjonane starta.

[NOTE]
====

*Merk:* Sjå også sida om xref:/Animasjon.adoc[animsjon] i GeoGebra.

====
