= TilfeldigBinomial Kommando
:page-en: commands/RandomBinomial
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

TilfeldigBinomial[ <Tal på forsøk n>, <Sannsyn p> ]::
  Genererer eit tilfeldig tal frå ei binomialfordeling med _n_ forsøk der sannsynet for treff er _p_.

[EXAMPLE]
====

*Døme:*

`++TilfeldigBinomial[100, 0.5]++` gjev eit tal _k_ i intervallet [0, 100] der sannsynet for å få _k_ er sannsynet for at
ei hending med sannsyn 0.5 skjer _k_ gongar på 100 forsøk. _k_ vil altså mest sannsynleg ligge rundt 100*0.5 = 50.

====

[NOTE]
====

*Merk:*

* Du kan bruke _Oppdater alt_ i xref:/Vis_meny.adoc[Vis-menyen] (eller trykke [.kcode]#F9# eller
[.kcode]##Ctrl##+[.kcode]#R#) for å få eit nytt tilfeldig tal.
* Sjå også kommandoen xref:/commands/FordelingBinomial.adoc[FordelingBinomial].
* Sjå også dei andre kommandoane for tilfeldige tal: xref:/commands/SetStartverdi.adoc[SetStartverdi],
xref:/commands/TilfeldigElement.adoc[TilfeldigElement], xref:/commands/TilfeldigMellom.adoc[TilfeldigMellom],
xref:/commands/TilfeldigNormalfordeling.adoc[TilfeldigNormalfordeling],
xref:/commands/TilfeldigPoisson.adoc[TilfeldigPoisson] og xref:/commands/TilfeldigUniform.adoc[TilfeldigUniform].

====

== CAS-delen

TilfeldigBinomial[ <Tal på forsøk n>, <Sannsyn p> ]::
  Genererer eit tilfeldig tal frå ei binomialfordeling med _n_ forsøk der sannsynet for treff er _p_.

[EXAMPLE]
====

*Døme:*

`++TilfeldigBinomial[100, 0.5]++` gjev eit tal _k_ i intervallet [0, 100] der sannsynet for å få _k_ er sannsynet for at
ei hending med sannsyn 0.5 skjer _k_ gongar på 100 forsøk. _k_ vil altså mest sannsynleg ligge rundt 100*0.5 = 50.

====
