= TilfeldigPolynom Kommando
:page-en: commands/RandomPolynomial
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

TilfeldigPolynom[ <Grad d>, <Tal a>, <Tal b> ]::
  Genererer eit tilfeldig polynom med grad _d_ i _x_. Polynomet har heiltalskoeffisientar i intervallet [_a_, _b_]
  (endepunkta er inkludert).

[EXAMPLE]
====

*Døme:*

* `++TilfeldigPolynom[0, 1, 2]++` gjev 1 eller 2.
* `++TilfeldigPolynom[2, 1, 2]++` gjev eit tilfeldig andregradspolynom med koeffisientar lik 1 eller 2, til dømes _2x^2^
+ x + 1_.

====

[NOTE]
====

*Merk:* Dersom tala _a_ og _b_ ikkje er heiltal vil _floor(a)_ og _floor(b)_ verte brukt.

====

== CAS-delen

TilfeldigPolynom[ <Grad d>, <Tal a>, <Tal b> ]::
  Genererer eit tilfeldig polynom med grad _d_ i _x_. Polynomet har heiltalskoeffisientar i intervallet [_a_, _b_]
  (endepunkta er inkludert).

[EXAMPLE]
====

*Døme:*

* `++TilfeldigPolynom[0, 1, 2]++` gjev 1 eller 2.
* `++TilfeldigPolynom[2, 1, 2]++` gjev eit tilfeldig andregradspolynom med koeffisientar lik 1 eller 2, til dømes _2x^2^
+ x + 1_.

====

TilfeldigPolynom[ <Variabel v>, <Grad d>, <Tal a>, <Tal b> ]::
  Genererer eit tilfeldig polynom med grad _d_ i variabelen _v_. Polynomet har heiltalskoeffisientar i intervallet [_a_,
  _b_] (endepunkta er inkludert).

[EXAMPLE]
====

*Døme:*

* `++TilfeldigPolynom[a, 0, 1, 2]++` gjev 1 eller 2.
* `++TilfeldigPolynom[a, 2, 1, 2]++` gjev eit tilfeldig andregradspolynom med koeffisientar lik 1 eller 2, til dømes
_2a^2^ + a + 1_.

====

[NOTE]
====

*Merk:* Dersom tala _a_ og _b_ ikkje er heiltal vil _round(a)_ og _round(b)_ verte brukt.

====
