= TTest2 Kommando
:page-en: commands/TTest2
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

TTest2[ <Liste med utvalsdata 1>, <Liste med utvalsdata 2>, <Hale>, <Boolsk gruppert> ]::
  Gjer ein to-utvals T-test av differansen mellom to populasjonsgjennomsnitt ved å bruke dei gjevne listene med
  utvalsdata.
  Dersom _Boolsk gruppert = true_, vert det lagt til grunn at variansen til populasjonane er lik og standardavvika til
  utvala vert kombinert i berekninga.
  Dersom _Boolsk gruppert =false_, vert det ikkje lagt til grunn at variansen til populasjonane er lik og standardavvika
  til utvala vert ikkje kombinert i berekninga.

_Hale_ kan ha følgjande verdiar

* _<_ betyr: _differanse i populasjonsgjennomsnitt < 0_
* _>_ betyr: _differanse i populasjonsgjennomsnitt > 0_
* _≠_ betyr: _differanse i populasjonsgjennomsnitt ≠ 0_

Resultatet vert gjeve som ei liste på forma _\{sannsynsverdi, T-test statistikkverdi}_.

TTest2[ <Utvalsgjennomsnitt 1>, <Standardavvik 1>, <Uvalsstorleik 1>, <Utvalsgjennomsnitt 2>, <Standardavvik 2>,
<Utvalsstorleik 2>, <Hale>, <Boolsk gruppert> ]

Gjer ein to-utvals T-test av differansen mellom to populasjonsgjennomsnitt ved å bruke dei gjevne utvalsgjennomsnitta,
standardavvika og utvalsstorleikane.

Dersom _Boolsk gruppert = true_, vert det lagt til grunn at variansen til populasjonane er lik og standardavvika til
utvala vert kombinert i berekninga.

Dersom _Boolsk gruppert =false_, vert det ikkje lagt til grunn at variansen til populasjonane er lik og standardavvika
til utvala vert ikkje kombinert i berekninga.

_Hale_ kan ha følgjande verdiar

* _<_ betyr: _differanse i populasjonsgjennomsnitt < 0_
* _>_ betyr: _differanse i populasjonsgjennomsnitt > 0_
* _≠_ betyr: _differanse i populasjonsgjennomsnitt ≠ 0_

Resultatet vert gjeve som ei liste på forma _\{sannsynsverdi, T-test statistikkverdi}_.

[NOTE]
====

*Merk:* Sjå også kommandoane xref:/commands/TTest.adoc[TTest] og xref:/commands/TTestPara.adoc[TTestPara].

====
