= TTest Kommando
:page-en: commands/TTest
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

TTest[ <Liste med utvalsdata>, <Forventa gjennomsnitt>, <Hale> ]::
  Gjer ein eit-utvals T-test av eit populasjonsgjennomsnitt ved å bruke den gjevne lista med utvalsdata og det forventa
  populasjonsgjennomsnittet i nullhypotesa.
  _Hale_ kan ha følgjande verdiar
  * _<_ betyr: _populasjonsgjennomsnitt < forventa gjennomsnitt_
  * _>_ betyr: _populasjonsgjennomsnitt > forventa gjennomsnitt_
  * _≠_ betyr: _populasjonsgjennomsnitt ≠ forventa gjennomsnitt_
  Resultatet vert gjeve som ei liste på forma _\{sannsynsverdi, T-test statistikkverdi}_.
TTest[ <Utvalsgjennomsnitt>, <Standardavvik for utvalet>, <Utvalsstorleik>, <Forventa gjennomsnitt>, <Hale> ]::
  Gjer ein eit-utvals T-test av eit populasjonsgjennomsnitt ved å bruke det gjevne utvalsgjennomsnittet,
  standardavviket, den gjevne utvalsstorleiken og det forventa populasjonsgjennomsnittet i nullhypotesa.
  _Hale_ kan ha følgjande verdiar
  * _<_ betyr: _populasjonsgjennomsnitt < forventa gjennomsnitt_
  * _>_ betyr: _populasjonsgjennomsnitt > forventa gjennomsnitt_
  * _≠_ betyr: _populasjonsgjennomsnitt ≠ forventa gjennomsnitt_
  Resultatet vert gjeve som ei liste på forma _\{sannsynsverdi, T-test statistikkverdi}_.

[NOTE]
====

*Merk:* Sjå også kommandoane xref:/commands/TTest2.adoc[TTest2] og xref:/commands/TTestPara.adoc[TTestPara].

====
