= Varians Kommando
:page-en: commands/Variance
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Varians[ <Liste med tal> ]::
  Finn variansen til elementa i lista.
Varians[ <Liste med tal L>, <Liste med frekvensar D> ]::
  Finn variansen til tala i _L_ når talet på kvart element i _L_ er gjeve av det samsvarande elementet i _F_.

[EXAMPLE]
====

*Døme:* `++Varians[{1, 2, 3, 4, 5}, {5, 1, 1, 3, 9}]++` gjev _2.88_.

====

[EXAMPLE]
====

*Døme:* `++Varians[{1, 2, 3, 4, 5}]++` gjev _2_.

====

[NOTE]
====

*Merk:*

* Jo fleire element det er i lista desto likare vert resultatet med det ein får frå kommandoen
xref:/commands/VariansUtval.adoc[VariansUtval]. Grunnen til dette er at det einaste som skil dei to statistiske
storleikane er at utvalsvariansen har _N - 1_ i nemnaren, medan variansen har _N_, der _N_ er antall element i lista.
* Sjå også kommandoane xref:/commands/Gjennomsnitt.adoc[Gjennomsnitt], xref:/commands/Standardavvik.adoc[Standardavvik]
og xref:/commands/VariansUtval.adoc[VariansUtval].

====

== CAS-delen

Varians[ <Liste med tal> ]::
  Finn variansen til elementa i lista. Kommandoen gjev det eksakte svaret og dersom lista inneheld udefinerte variablar
  vert det gjeve ein formel for svaret.

[EXAMPLE]
====

*Døme:* `++Varians[{2, 3, 5, a}]++` gjev _stem:[\frac\{3a^2-20a+52}\{16}]_.

====
