= ZGjennomsnitt2Test Kommando
:page-en: commands/ZMean2Test
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

ZGjennomsnitt2Test[ <Liste med utvalsdata 1>, <Utvals-standardavvik 1>, <Liste med utvalsdata 2>, <Utvals-standardavvik
2>, <Hale> ]::
  Gjer ein to-utvals Z-test av differansen mellom to populasjonsgjennomsnitt ved å bruke dei gjevne listene med
  utvalsdata og utvalsstorleikane.
  _Hale_ kan ha følgjande verdiar
  * _<_ betyr: _differanse i populasjonsgjennomsnitt < 0_
  * _>_ betyr: _differanse i populasjonsgjennomsnitt > 0_
  * _≠_ betyr: _differanse i populasjonsgjennomsnitt ≠ 0_
  Resultatet vert gjeve som ei liste på forma _\{sannsynsverdi, Z-test}_.

ZGjennomsnitt2Test[ <Utvalsgjennomsnitt 1>, <Utvals-standardavvik 1>, <Utvalsstorleik 1>, <Utvalsgjennomsnitt 2>,
<Utvals-standardavvik 2>, <Utvalsstorleik 2>, <Hale> ]::
  Gjer ein to-utvals Z-test av differansen mellom to populasjonsgjennomsnitt ved å bruke dei gjevne utvalsgjennomsnitta,
  utvals-standardavvika og utvalsstorleikane.
  _Hale_ kan ha følgjande verdiar
  * _<_ betyr: _differanse i populasjonsgjennomsnitt < 0_
  * _>_ betyr: _differanse i populasjonsgjennomsnitt > 0_
  * _≠_ betyr: _differanse i populasjonsgjennomsnitt ≠ 0_
  Resultatet vert gjeve som ei liste på forma _\{sannsynsverdi, Z-test}_.

[NOTE]
====

*Merk:* Sjå også kommandoen xref:/commands/ZGjennomsnittTest.adoc[ZGjennomsnittTest].

====
