= ZGjennomsnitt2Estimat Kommando
:page-en: commands/ZMean2Estimate
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

ZGjennomsnitt2Estimat[ <Liste med utvalsdata 1>, <Liste med utvalsdata 2>, <Utvals-standardavvik 1>,
<Utvals-standardavvik 2>, <Nivå> ]::
  Finn eit Z-konfidensintervallestimat for differansen mellom to populasjonsgjennomsnitt ved å bruke dei to gjevne
  listene med utvalsdata, utvals-standardavvika og det gjevne konfidensnivået.
  Resultatet vert gjeve som ei liste på forma _\{nedre konfidensgrense, øvre konfidensgrense}_.
ZGjennomsnitt2Estimat[ <Utvalsgjennomsnitt 1>, <Utvals-standardavvik 1>, <Utvalsstorleik 1>, <Utvalsgjennomsnitt 2>,
<Utvals-standardavvik 2>, <Utvalsstorleik 2>, <Nivå> ]::
  Finn eit Z-konfidensintervallestimat for differansen mellom to populasjonsgjennomsnitt ved å bruke dei to gjevne
  utvalsgjennomsnitta, utvals-standardavvika, utvalsstorleikane og det gjevne konfidensnivået.
  Resultatet vert gjeve som ei liste på forma _\{nedre konfidensgrense, øvre konfidensgrense}_.

[NOTE]
====

*Merk:* Sjå også kommandoen xref:/commands/ZGjennomsnittEstimat.adoc[ZGjennomsnittEstimat].

====
