= Angle Tool
:page-en: tools/Angle
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

With this tool you can create angles in different ways:

* Click on three points to create an angle between these points. The second point selected is the vertex of the angle.
* Click on two segments to create the angle between them.
* Click on two lines to create the angle between them.
* Click on two vectors to create the angle between them.
* Click on a polygon to create all angles of this polygon.

[NOTE]
====

* If the polygon was created by selecting its vertices in counter clockwise orientation, the _Angle_ tool gives you the
interior angles of the polygon
* Angles are created in _counter clockwise_ orientation. Therefore, the order of selecting these objects is relevant for
the _Angle_ tool. If you want to limit the maximum size of an angle select the desired limits from the drop-down list on
tab _Basic_ of the xref:/Properties_Dialog.adoc[Properties Dialog]
* See also xref:/commands/Angle.adoc[Angle] command.

====
