= Function Inspector Tool
:page-en: tools/Function_Inspector
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

The _Function Inspector_ tool is available only in _GeoGebra Classic_.

Activate the tool, then select the function to explore.

The appearing dialog window displays some meaningful information related to the function (min, max, roots, integral, area, mean, length) in the interval specified at the bottom of the _Interval_ tab.
In the same tab it is possible to set the rounding of the displayed values to the desired number of decimal places or significant figures.

By activating the buttons at the bottom of the _Points_ tab it is possible to:

* View and edit a table of values of the function. The corresponding points are displayed on the graph of the function, but will not be available as variables in the _Algebra View_. In the table of values, for each value of the x-coordinate it is possible to view, besides the y-coordinate displayed by default, also the value of the first derivative, of the second derivative, of the difference, and the curvature of the function at that point. Use the *+* button to select the columns of values to display, and the *x* button to remove a selected column from the table of values. Columns can be ordered by dragging their headers. The x-coordinate at the middle of its column can be edited manually, as well as the steps that specify the distance between two x-values in the table.
* Display in the _Graphics View_ a draggable point belonging to the graph of the function, its projections over the axes and its coordinates in the tab.
* Display in the _Graphics View_ the tangent line to the graph of the function at that point.
* Display in the _Graphics View_ the osculating circle to the graph of the function at that point.
