= Intersect Tool

Intersection points of two objects can be created in two ways:

* Selecting two objects creates all intersection points (if possible).
* Directly clicking on an intersection of the two objects creates only this _single intersection point_.

[NOTE]

====

*Note:* Sometimes it's useful to display only the portions of the intersecating objects near the intersection point. To
do so, open the xref:/Properties_Dialog.adoc[Properties Dialog] of the intersection point, and check the option _Show
trimmed intersection lines_ in the _Basic_ tab of the _Properties_ dialog of the object, then hide the intersecting
objects.

====

== [#Outlying_Intersections]#Outlying Intersections#

For segments, rays, or arcs you may specify whether you want to _Allow outlying intersections_ on tab _Basic_ of the
xref:/Properties_Dialog.adoc[Properties Dialog]. This can be used to get intersection points that lie on the extension
of an object. For example, the extension of a segment or a ray is a straight line.

[NOTE]

====

*Note:* See also xref:/commands/Intersect_Command.adoc[Intersect] command.

====
