= Tetrahedron Tool
:page-en: tools/Regular_Tetrahedron
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Choose one of the following to create a regular tetrahedron:

* Select or create two points in the _xOy plane_ to obtain a regular tetrahedron with one edge defined by the two given points, and lying on the _xOy_ plane.

or

* Select two points having the same _z_-coordinate, _z=c_, to obtain a regular tetrahedron with one edge of the base defined by the two given points, and lying on the plane _z = c_. The tetrahedron can be rotated around the specified edge by dragging the third vertex of the base, created automatically.

or

* Select two points having different z-coordinates to obtain a regular tetrahedron with the edge of one face defined by the two given points and the third vertex of the same face having as _z_-coordinate the average of the _z_-coordinates of the given points. The tetrahedron can be rotated around the specified edge by dragging the third vertex of the base, created automatically.


[NOTE]
====

* See also xref:/commands/Tetrahedron.adoc[Tetrahedron] command.

====
