= Tangents Tool
:page-en: tools/Tangents
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Activate the tool, then:

* Select a point on a conic (or a function) to create all the tangents to the conic (or function) at the selected point.
* Select a point not belonging to a conic to create all the tangents to the conic passing through the selected point.
* Select a point not belonging to a function to create the tangent line to the function at its point with the same _x_-coordinate as the selected one. For example, given _f(x)_ and a point _A_ not on it, the tool creates the tangent line to _f(x)_ at _(x(A), f(x(A))_.
* Select a line and a conic to create the tangent lines to the conic that are parallel to the selected line.
* Select two circles to create their common tangent lines (up to 4).

[NOTE]
====

* Use the form stem:[ y = ... ] (e.g. stem:[ y = x^2+2x+1 ]) instead of using the functional notation stem:[ f(x) = ... ] (e.g. stem:[ f(x) = x^2 + 2x + 1 ]) if you want to work with a *conic* (parabola) rather than a *function*.

* See also the xref:/commands/Tangent.adoc[Tangent] command.
====
