= BinomnaSlučajnaVarijabla naredba
:page-en: commands/RandomBinomial
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

BinomnaSlučajnaVarijabla[ <broj pokušaja n>, <vjerojatnost p> ]::
  Generira slučajni broj iz binomne razdiobe s _n_ pokusa i vjerojatnošću _p_.

[EXAMPLE]
====

`++BinomnaSlučajnaVarijabla[3, 0.1]++` dati će _j ∈ \{0, 1, 2, 3}_, gdje je vjerojatnost postizanja _j_ jednaka
vjerojatnosti događaja čija je vjerojatnost pojavljivanja u jednom pokusu _0.1_ i koji se pojavljuje _j_ puta u tri
pokusa.

====

== CAS prikaz

BinomnaSlučajnaVarijabla[ <broj pokušaja n>, <vjerojatnost p> ]::
  Generira slučajni broj iz binomne razdiobe s _n_ pokusa i vjerojatnošću _p_.

[EXAMPLE]
====

`++BinomnaSlučajnaVarijabla[3, 0.1]++` dati će _j ∈ \{0, 1, 2, 3}_, gdje je vjerojatnost postizanja _j_ jednaka
vjerojatnosti događaja čija je vjerojatnost pojavljivanja u jednom pokusu _0.1_ i koji se pojavljuje _j_ puta u tri
pokusa.

====

[NOTE]
====

Pogledajte još i xref:/commands/NormalnaSlučajnaVarijabla.adoc[NormalnaSlučajnaVarijabla naredba] i
xref:/commands/PoissonovaSlučajnaVarijabla.adoc[PoissonovaSlučajnaVarijabla naredba].

====
