= ErlangovaRazdioba naredba
:page-en: commands/Erlang
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

ErlangovaRazdioba[ <oblik k>, <stupanj λ>, x ]::
  Kreira funkciju gustoće vjerojatnosti (fgv) za https://en.wikipedia.org/wiki/Erlang_distribution[Erlangovu razdiobu] s
  parametrima _k, λ_.
ErlangovaRazdioba[ <oblik k>, <stupnj λ>, x, <kumulacija - logička vrijednost> ]::
  Ako je _kumulacija - logička vrijednost_ jednaka true, izradit će kumulativnu funkciju distribucije za Erlangovu
  razdiobu, u suprotnom će izraditi fgv za Erlangovu razdiobu.
ErlangovaRazdioba[ <oblik k >, <stupanj λ>, <vrijednost varijable v> ]::
  Izračunava vrijednost kumulativne funkcije distribucije Erlangove razdiobe za vrijednost varijable _v_, t.j.
  vjerojatnost _P(X≤v)_ gdje je _X_ Erlangova slučajna varijabla za razdiobu s parametrima _k, λ_.

[NOTE]
====

Daje vjerojatnost za zadanu vrijednost _x_-koordinate (ili površinu ispod krivulje Erlangove razdiobe lijevo od zadane
_x_-koordinate).

====

== CAS prikaz

xref:/CAS_prikaz.adoc[CAS prikaz] podržava samo sljedeću sintaksu:

ErlangovaRazdioba[ <oblik k>, <stupanj λ>, <vrijednost varijable v>]::
  Izračunava vrijednost kumulativne funkcije distribucije Erlangove razdiobe za vrijednost varijable _v_, t.j.
  vjerojatnost _P(X≤v)_ gdje je _X_ Erlangova slučajna varijabla za razdiobu s parametrima _k, λ_.
