= NormalnaSlučajnaVarijabla naredba
:page-en: commands/RandomNormal
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

NormalnaSlučajnaVarijabla[ <aritmetička sredina>, <standardna devijacija> ]::
  Generira slučajni broj iz normalne razdiobe sa zadanom aritmetičkom sredinom i standardnom devijacijom.

[EXAMPLE]
====

`++NormalnaSlučajnaVarijabla[3, 0.1]++` daje slučajnu vrijednost iz normalne razdiobe s aritmetičkom sredinom _3_ i
standardnom devijacijom _0.1_.

====

[NOTE]
====

Pogledajte još xref:/commands/BinomnaSlučajnaVarijabla.adoc[BinomnaSlučajnaVarijabla] i
xref:/commands/PoissonovaSlučajnaVarijabla.adoc[PoissonovaSlučajnaVarijabla].

====

== CAS prikaz

NormalnaSlučajnaVarijabla[ <aritmetička sredina>, <standardna devijacija> ]::
  Generira slučajni broj iz normalne razdiobe sa zadanom aritmetičkom sredinom i standardnom devijacijom.

[EXAMPLE]
====

`++NormalnaSlučajnaVarijabla[3, 0.1]++` daje slučajnu vrijednost iz normalne razdiobe s aritmetičkom sredinom _3_ i
standardnom devijacijom _0.1_.

====

[NOTE]
====

Pogledajte još i naredbe xref:/commands/BinomnaSlučajnaVarijabla.adoc[BinomnaSlučajnaVarijabla] i
xref:/commands/PoissonovaSlučajnaVarijabla.adoc[PoissonovaSlučajnaVarijabla].

====
