= PoissonovaSlučajnaVarijabla naredba
:page-en: commands/RandomPoisson
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

PoissonovaSlučajnaVarijabla[ <očekivanje> ]::
  Generira slučajni broj iz Poissonove razdiobe sa zadanim očekivanjem.

[EXAMPLE]
====

`++PoissonovaSlučajnaVarijabla[3]++` daje slučajnu vrijednost iz Poissonove razdiobe sa očekivanjem _3_.

====

[NOTE]
====

Pogledajte i xref:/commands/BinomnaSlučajnaVarijabla.adoc[BinomnaSlučajnaVarijabla naredba] i
xref:/commands/NormalnaSlučajnaVarijabla.adoc[NormalnaSlučajnaVarijabla naredba].

====

== CAS prikaz

PoissonovaSlučajnaVarijabla[ <aritmetička sredina> ]::
  Generira slučajni broj iz Poissonove razdiobe sa zadanim očekivanjem.

[EXAMPLE]
====

`++PoissonovaSlučajnaVarijabla[3]++` daje slučajnu vrijednost iz Poissonove razdiobe sa očekivanjem _3_.

====

[NOTE]
====

Pogledajte i xref:/commands/BinomnaSlučajnaVarijabla.adoc[BinomnaSlučajnaVarijabla naredba] i
xref:/commands/NormalnaSlučajnaVarijabla.adoc[NormalnaSlučajnaVarijabla naredba].

====
