= PostaviBojuPozadine naredba
:page-en: commands/SetBackgroundColor
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

PostaviBojuPozadine[ <objekt>, <crvena>, <zelena>, <plava> ]

Mijenja boju pozadine zadanog objekta. Koristi se za tekstove i objekte u tabličnom prikazu. Parametri crvena, zelena i
plava predstavljaju količinu odgovoarajuće komponentne boje, 0 je minimum a 1 je maksimum. Ako broj _t_ (za količinu
komponente) prelazi zadani interval, smješta ga se unutar njega korištenjem funkcije stem:[2\left|\frac\{t}2-\mathrm
round\left(\frac\{t}2\right)\right|].

PostaviBojuPozadine[ <objekt>, "<boja>" ]::
  Mijenja boju pozadine zadanog objekta. Koristi se za tekstove i objekte u tabličnom prikazu. Boja se unosi kao
  xref:/Tekstovi.adoc[tekst]. Naredba prihvaća više od stotinu Engleskih naziva boja (vidi link
  http://wiki.geogebra.org/en/Reference:Colors[link]). Neke od njih mogu se koristiti i na hrvatskom jeziku - listu
  pogledajte ispod.

* Crna
* Tamnosiva
* Siva
* Tamnoplava
* Plava
* Tamnozelena
* Zelena
* Kestenjasta
* Grimizna
* Crvena
* Magenta
* Modroljubičasta
* Tamnopurpurna
* Smeđa
* Narančasta
* Zlatna

* Zelenožuta
* Cijan
* Tirkizna
* Svijetloplava
* Akvamarin
* Srebrena
* Svijetlosiva
* Roza
* Ljubičasta
* Žuta
* Svijetložuta
* Svijetlonarančasta
* Svijetloljubičasta
* Svijetlopurpurna
* Svijetlozelena
* Bijela

 
