= PostaviBoju naredba
:page-en: commands/SetColor
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

PostaviBoju[ <objekt>, <crvena>, <zelena>, <plava> ]::
  Mijenja boju zadanog objekta. Parametri crvena, zelena i plava predstavljaju količinu odgovoarajuće komponentne boje,
  0 je minimum a 1 je maksimum. Ako broj _t_ (za količinu komponente) prelazi zadani interval, smješta ga se unutar
  njega korištenjem funkcije stem:[2\left|\frac\{t}2-\mathrm round\left(\frac\{t}2\right)\right|].
PostaviBoju[ <objekt>, "<boja>" ]::
  Mijenja boju zadanog objekta. Boja se unosi kao xref:/Tekstovi.adoc[tekst]. Naredba prihvaća više od stotinu Engleskih
  naziva boja (vidi link http://wiki.geogebra.org/en/Reference:Colors[link]). Neke od njih mogu se koristiti i na
  hrvatskom jeziku - listu pogledajte ispod.

* Crna
* Tamnosiva
* Siva
* Tamnoplava
* Plava
* Tamnozelena
* Zelena
* Kestenjasta
* Grimizna
* Crvena
* Magenta
* Modroljubičasta
* Tamnopurpurna
* Smeđa
* Narančasta
* Zlatna

* Zelenožuta
* Cijan
* Tirkizna
* Svijetloplava
* Akvamarin
* Srebrena
* Svijetlosiva
* Roza
* Ljubičasta
* Žuta
* Svijetložuta
* Svijetlonarančasta
* Svijetloljubičasta
* Svijetlopurpurna
* Svijetlozelena
* Bijela

 
