= TrokutastaRazdioba naredba
:page-en: commands/Triangular
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

TrokutastaRazdioba[ <donja granica>, <gornja granica>, <najčešća vrijednost>, x ]::
  Izradit će funkciju gustoće vjerojatnosti (fgv) za https://en.wikipedia.org/wiki/Triangular_distribution[trokutastu
  razdiobu] koja ima parametre _donja granica, gornja granica, najčešća vrijednost_.
TrokutastaRazdioba[ <donja granica>, <gornja granica>, <najčešća vrijednost>, x, <kumulacija - logička vrijednost> ]::
  Ako je _kumulacija - logička vrijednost_ = true, izradit će kumulativnu funkciju distribucije za trokutastu razdiobu,
  u suprotnom će izraditi fgv za trokutastu razdiobu.
TrokutastaRazdioba[ <donja granica>, <gornja granica>, <najčešća vrijednost>, <vrijednost varijable v> ]::
  Izračunat će vrijednost kumulativne funkcije distribucije trokutaste razdiobe za zadani _v_, t.j. vjerojatnost
  _P(X≤v)_ gdje je _X_ slučajna varijabla trokutaste razdiobe zadane parametrima _donja granica, gornja granica,
  najčešća vrijednost_.

[NOTE]
====

Daje vjerojatnost za zadanu vrijednost _x_-koordinate (ili površinu ispod krivulje trokutaste razdiobe ljivo od zadane
_x_-koordinate).

====

== CAS prikaz

xref:/CAS_prikaz.adoc[CAS prikaz] podržava samo sljedeću sintaksu:

Triangular[ <Lower Bound min>, <Upper Bound max>, <Mode mod>, <Variable Value v>]::
  Izračunat će vrijednost kumulativne funkcije distribucije trokutaste razdiobe za zadani _v_, t.j. vjerojatnost
  _P(X≤v)_ gdje je _X_ slučajna varijabla trokutaste razdiobe zadane parametrima _donja granica, gornja granica,
  najčešća vrijednost_.
