= Zvuk naredba
:page-en: commands/PlaySound
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Zvuk[ <nota>, <trajanje>, <instrument> ]::
  Svira MIDI notu
  _Nota_ je vrijednost između 0 i 127 koja predstavlja glazbenu notu iz tablice ispod. Ako je nota = 60 to predstavlja
  srednji C.
  _trajanje_ prestavlja vrijeme trajanja note u sekundama.
  _instrument_ je cijeli broj koji predstavlja sintetizirani instrument koji izvodi notu. Pogledaj
  http://www.classicalmidiconnection.com/General_Midi.html[tehničke specifikacije] za moguće instrumente.
  Podržana je većina instrumenata, ali postoje neke razlike u računalnim platformama.

*MIDI Notes*

Octave

C

C#

D

D#

E

F

F#

G

G#

A

A#

B

*0*

0

1

2

3

4

5

6

7

8

9

10

11

*1*

12

13

14

15

16

17

18

19

20

21

22

23

*2*

24

25

26

27

28

29

30

31

32

33

34

35

*3*

36

37

38

39

40

41

42

43

44

45

46

47

*4*

48

49

50

51

51

53

54

55

56

57

58

59

*5*

60

61

62

63

64

65

66

67

68

69

70

71

*6*

72

73

74

75

76

77

78

79

80

81

82

83

*7*

84

85

86

87

88

89

90

91

92

93

94

95

*8*

96

97

98

99

100

101

102

103

104

105

106

107

*9*

108

109

110

111

112

113

114

115

116

117

118

119

*10*

120

121

122

123

124

125

126

127

Zvuk[ <niz nota>, <instrument> ]::
  Izvodi niz MIDI nota i naredbi koristeći glazbene oznake http://www.jfugue.org[JFugue]
  "niz nota" su tekstualne oznake koje koristi JFugue kao znak naredbe.
  "instrument" je MIDI instrument koji izvodi note.
  Osnovne naredbe su prikazana ispod. Potpuni skup naredbi je opisan u
  http://www.jfugue.org/jfugue-chapter1.pdf[The Complete Guide to JFugue] (English).

*Osnovne JFugue naredbe*

Znak

Naredba

A-G

Izvodi glazbenu notu danu slovom u 5. oktavi

Za snižene i povišene tonove dodajte b ili #

Za promjenu oktave dodajte broj oktave npr. A4

Trajanje note je četvrtinka, ako nije drugačije naglašeno.

{empty}[number]

Izvodi MIDI notu danu brojem (0-127)

+

Spaja note u harmoniju npr. C+E+G

R

Pauza

w, h, q, i, s

dodano na kraj note ili pauze; određuje trajanje note

w = cijela nota (whole note)

h = polovinka (half note)

q = četvrtinka (quarter note)

i = osminka (eighth note)

s = šesnaestinka (sixteenth note)

/n

Dodano noti ili pauzi; određuje trajanje do n ( decimalni broj)

/1 = cijela nota (whole note)

/.5 = polovinka (half note)

/.25 = četvrtinka (quarter note)

/2 = dvije mjere

I[number]

Određuje instrument

V

V prateći broj od 0 do 15 određuje MIDI kanal. "V9" postavlja MIDI kanal s udaraljkama.

Space

Izvodi prethodnu notu, kombinaciju nota ili pauzu.

[EXAMPLE]
====

`++Zvuk["C+E+G  Rw  Ai Bi Ci  A4i B4i C4i ", 0]++`

Izvodi akord CEG u trajanju četvrtinke; izvodi osminke A, B, C; te ih izvodi opet oktavu niže.

Koristi se piano instrument

====

[EXAMPLE]
====

`++PlaySound["I[56] C5q D5q I[71] G5q F5q", 0]++`

Izvodi note sa različitim instrumentima. (Truba) Trumpet = 56 i (klarinet) Clarinet = 71

====

[EXAMPLE]
====

`++PlaySound["V0 A3q B3q C3q B3q V1 A2h C2h", 0]++`

Izvodi note u harmoniji s različitim glasovima.

====

Zvuk[ <datoteka> ]::
  Izvodi MIDI datoteku (*.mid) ili tekstualni dokument (*.txt) koji sadrži JFigure oznake.
  "dateoteka" je oznaka puta do datoteke npr. Zvuk["path/to/myFile.mid"]

Zvuk[ <funkcija>, <najmanja vrijednost>, <najveća vrijednost> ]::
  Izvodi zvuk generiran funkcijom, zadanom u rasponu [-1,1]. Jedinice vemena su sekunde i zvuk se izvodi od najmanje
  vrijednosti do najveće vrijednosti. Zvuk nastaje 8-bitnim uzorcima uzetim brzinom od 8000 uzoraka u sekundi.

[EXAMPLE]
====

`++Zvuk[sin(440 2Pi x), 0, 1]++`

Izvodi čisti sinusni ton na 440 Hz (glazbena nota A) u trajanju od jedne sekunde.

====

Zvuk[ <funkcija>, <najmanja vrijednost>, <najveća vrijednost>, <frekvencija uzorka>, <dubina uzorka> ]::
  Izvodi zvuk generiran funkcijom, zadanom u rasponu [-1,1]. Jedinice vemena su sekunde i zvuk se izvodi od najmanje
  vrijednosti do najveće vrijednosti. Metoda sempliranja je odeđena "frekvencijom uzorka" i "dubinom uzorka".
  "Frekvencija uzorka" je broj vrijednosti uzorka uzet svake sekunde. Dopuštene vrijednosti su 8000, 11025, 16000,
  22050, or 44100
  "Dubina uzorka" je podatak o semlovima u bitovima. Dopuštene vrijednosti su 8 i 16.

Zvuk[ <sviraj – logička vrijednost> ]::
  Pauza ili nastavi svirati.
  Zvuk[true] = sviraj, Zvuk[false] = pauza.
