= Polecenia
:page-en: Commands
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Za pomocą poleceń możesz tworzyć nowe obiekty oraz modyfikować istniejące. Sprawdź listę wyświetloną po prawej stronie, 
gdzie polecenia zostały pogrupowane według obszaru ich zastosowania, lub zapoznaj się z /Category:Commands.adoc[pełną 
listą poleceń], aby uzyskać więcej informacji.

[NOTE]
====

* Naciśnij klawisz [.kcode]#Enter# po każdym wprowadzeniu danych, aby utworzyć odpowiadający obiekt.
* Wynik polecenia może zostać nazwany poprzez wpisanie etykiety, a następnie znaku równości (=). W poniższym przykładzie nowy punkt zostaje nazwany S.

[EXAMPLE]
====

Aby uzyskać punkt przecięcia dwóch prostych g i h, musisz wpisać polecenie `++S = Przecięcie(g, h)++` (zobacz polecenie
xref:/commands/Przecięcie.adoc[Przecięcie]).

====

* Możesz również używać indeksów w nazwach obiektów: A~1~ zapisuje się jako `++A_1++`, natomiast S~AB~ tworzy się za pomocą
`++S_{AB}++`. Jest to część xref:/LaTeX.adoc[składni LaTeX].

====
