= Intervalli

Un intervallo è un insieme di numeri limitato superiormente e inferiormente. Per definire un intervallo aperto, digitare
ad esempio `2 < x < 3` nella xref:/Barra_di_inserimento.adoc[barra di inserimento], per un intervallo chiuso ad es.
`2 ≤ x ≤ 3`, mentre per un intervallo aperto a destra ad es. `2 ≤ x < 3`.

[NOTE]
====

Vedere anche xref:/Valori_booleani.adoc[valori booleani].

====

Per verificare se un numero _c_ appartiene all'intervallo _r_, digitare `r(c)` nella barra di inserimento: si otterrà un
risultato in forma di valore booleano. La generalizzazione degli intervalli sono le
xref:/Disequazioni.adoc[disequazioni].

== [#Comandi_applicabili_agli_intervalli]#Comandi applicabili agli intervalli#

* I comandi xref:/commands/Comando_Min.adoc[Min], xref:/commands/Comando_Max.adoc[Max] e
xref:/commands/Comando_PuntoMedio.adoc[PuntoMedio], applicati a un intervallo con estremo inferiore _a_ ed estremo
superiore _b_ restituiscono rispettivamente _a_, _b_ e stem:[\frac\{a+b}2]. I risultati non dipendono dalla tipologia di
intervallo (aperto, chiuso, aperto a destra/sinistra).
* Il comando xref:/commands/Comando_Punto.adoc[Punto] restituisce un xref:/Punti_e_vettori.adoc[punto] che può essere
spostato, avente l'ascissa appartiene all'intervallo e ordinata nulla.
* Il comando xref:/commands/Comando_PuntoIn.adoc[PuntoIn] restituisce un punto che può essere spostato, avente l'ascissa
appartenente all'intervallo e l'ordinata definibile arbitrariamente.
