= Rette e assi
:page-en: Lines_and_Axes
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

== Rette

Una retta può essere definita nella _barra di inserimento_ tramite un'equazione lineare in _x_ e _y_, oppure in forma
parametrica. In entrambi i casi è possibile utilizzare all'interno dell'equazione alcuni tipi di oggetti precedentemente
definiti (ad es. numeri, punti, vettori).

[NOTE]
====

Per assegnare un nome alla retta, digitarlo nella _barra di inserimento_ prima dell'equazione, seguito da un simbolo di
due punti `++ : ++`.

====

[EXAMPLE]
====

*Esempi:* 2D

* Equazione lineare: inserire `++g: 3x + 4y = 2++` per definire la retta _g_.
* Forma parametrica: inserire`++g: X = (-5, 5) + t (4, -3)++`.
* Forma esplicita con slider: definire i parametri _m_ = 2 e _q_ = -1. Quindi inserire l'equazione `++h: y = m*x + q++`.

====

[EXAMPLE]
====

*Esempi:* 3D

* Forma parametrica: inserire `++g: X = (1, 6, 3) + λ (7, -4, 4)++`
* Forma con punto e vettore direzione: inserire `++g: Retta((1, 6, 3), Vettore((7, -4, 4)))++`
* Retta come intersezione di due piani: (i seguenti tre inserimenti sono equivalenti):
** `++IntersezioneCammini(4x+7y=46, y+z=9)++`
** `++(4x + 7y = 46, y + z = 9)++`
** `++7y = 46 - 4x = 7(9 - z)++`

====

== Ottenere i coefficienti di una retta

[EXAMPLE]
====

Data la retta `++a: 2.2 x + 3.3 y = 4.4++`:

* `++x(a)++` restituisce il valore 2.2
* `++y(a)++` restituisce il valore 3.3
* `++z(a)++` restituisce il valore -4.4 (perchè GeoGebra lavora internamente sull'equazione in forma implicita).

Per ulteriori informazioni vedere il comando xref:/commands/Coefficienti.adoc[Coefficienti]
====

== Assi

Sono disponibili due assi cartesiani ortogonali, aventi i nomi rispettivamente _asseX_ e _asseY_.

[EXAMPLE]
====

Il comando `++Perpendicolare(A, asseX)++` costruisce la retta passante per il punto A indicato e perpendicolare all'asse
delle ascisse.

====
