= Příkaz Ctyrsten
:page-en: commands/Tetrahedron
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

Ctyrsten( <Rovnostranný trojúhelník> )::
  Vytvoří pravidelný čtyřstěn, jehož základnou je daný rovnostranný trojúhelník.

Ctyrsten( <Bod>, <Bod>, <Směr> )::
  Vytvoří čtyřstěn, jehož jednou hranou je úsečka daná uvedenými dvěma body. 
  Další vrcholy jsou pak jednoznačně určeny daným směrem, který je třeba zadat jako:
  * vektor, úsečku, přímku, či polopřímku, vždy kolmo k uvedené úsečce, nebo
  * mnohoúhelník, či rovinu, rovnoběžně s úsečkou (hranou).
  Výsledný čtyřstěn bude potom mít:
  * stěnu s danou úsečkou jako hranou v rovině kolmé k vektoru/úsečce/přímce/polopřímce, nebo
  * stěnu s danou úsečkou jako hranou v rovině rovnoběžné s mnohoúhelníkem/rovinou.

Ctyrsten( <Bod>, <Bod>, <Bod>)::
  Vytvoří čtyřstěn s uvedenými třemi body jako vrcholy první stěny. Body proto musí tvořit rovnostranný trojúhelník, aby
  jimi byl definován osmistěn.

Ctyrsten( <Bod>, <Bod>)::
  Vytvoří čtyřstěn s danými dvěma body jako vrcholy první stěny, jejíž třetí vrchol je automaticky umístěn na kružnici tak, 
  že je možné čtyřstěnem kolem jeho první hrany otáčet.

[NOTE]
====

Ctyrsten(A, B) je zkrácenou verzí příkazu Ctyrsten(A, B, C), kde 
C = Bod(Kruznice(StredSoumernosti(A, B), Vzdalenost(A, B) sqrt(3) / 2, Usecka(A, B))).

====

[NOTE]
====

Viz též příkazy xref:/commands/Krychle.adoc[Krychle], xref:/commands/Osmisten.adoc[Osmisten],
xref:/commands/Dvacetisten.adoc[Dvacetisten], xref:/commands/Dvanactisten.adoc[Dvanactisten] commands.

====
