= Příkaz Dokazat
:page-en: commands/Prove
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

Dokazat( <Pravdivostní hodnota> )::
  Sdělí, zda je vložený výraz s pravdivostní hodnotou (tzv. booleovský výraz nabývající hodnoty _true_ nebo _false_) obecně pravdivý či nepravdivý.

Normálně GeoGebra rozhoduje o pravdivosti xref:/Pravdivostní_hodnoty.adoc[booleovského výrazu], tj. zda je jeho hodnota _true_ nebo _false_, pomocí numerického výpočtu. Příkaz _Dokazat_ však pro vyhodnocení toho, zda má vložený booleovský výraz hodnotu _true_ nebo _false_, používá https://en.wikipedia.org/wiki/Symbolic_computation[symbolické metody] výpočtu. Jeho závěr má tak obecnou povahu. Pokud GeoGebra nemůže takto o odpovědi rozhodnout, jako výsledek uvede _nedefinovaný_ (_undefined_).

[EXAMPLE]
====

Uvažujme tři body, `++A=(1,2)++`, `++B=(3,4)++`, `++C=(5,6)++`. Příkaz `++JsouKolinearni(A,B,C)++` vrátí hodnotu _true_, protože  provedl numerické ověření kolinearity této konkrétní trojice bodů. Při použití příkazu `++Dokazat(JsouKolinearni(A,B,C))++`
však obdržíme výsledek _false_, protože tři body nejsou obecně kolineární. Konkrétní zadání je tak příkazem _Dokazat_ bráno jako příklad obecného problému kolinearity tří bodů, který posuzuje.

====

[EXAMPLE]
====

Pro trojúhelník daný vrcholy _A_, _B_ a _C_, definujme `++D=StredSoumernosti(B,C)++`, `++E=StredSoumernosti(A,C)++`,
`++p=Primka(A,B)++`, `++q=Primka(D,E)++`. V tomto případě jak příkaz `++p∥q++`, tak i příkaz `++Prove(p∥q)++` uvede výsledek _true_, protože střední příčka trojúhelníku je vždy rovnoběžná s protilehlou stranou. Viz též https://www.geogebra.org/m/vhZETdtd[interaktivní ilustrace tohoto příkladu].

====

[NOTE]
====

See also xref:/commands/ProveDetails.adoc[ProveDetails] command, xref:/Boolean_values.adoc[Boolean values], and
https://github.com/kovzol/gg-art-doc/tree/master/pdf/english.pdf[GeoGebra Automated Reasoning Tools: A Tutorial].

====
