= Příkaz Dvacetisten
:page-en: commands/Icosahedron
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

Dvacetisten( <Rovnostranný trojúhelník> )::
  Vytvoří dvacetistěn, jehož základnou je daný rovnostranný trojúhelník.

Dvacetisten( <Bod>, <Bod>, <Směr> )::
  Vytvoří dvacetistěn, jehož jednou hranou je úsečka daná uvedenými dvěma body.
  Další vrcholy jsou pak jednoznačně určeny daným směrem, který je třeba zadat jako:
  * vektor, úsečku, přímku, či polopřímku, vždy kolmo k uvedené úsečce, nebo
  * mnohoúhelník, či rovinu, rovnoběžně s úsečkou (hranou).
+
Výsledný dvacetistěn bude potom mít:
  * stěnu s danou úsečkou jako hranou v rovině kolmé k vektoru/úsečce/přímce/polopřímce, nebo
  * stěnu s danou úsečkou jako hranou v rovině rovnoběžné s mnohoúhelníkem/rovinou.

Dvacetisten( <Bod>, <Bod>, <Bod>)::
  Vytvoří dvacetistěn s uvedenými třemi body jako vrcholy první stěny. Body proto musí tvořit rovnostranný trojúhelník, aby jimi byl definován dvacetistěn. 

Dvacetisten( <Bod>, <Bod>)::
  Vytvoří dvacetistěn s danými dvěma body jako vrcholy první stěny, jejíž třetí vrchol je automaticky umístěn na kružnici tak, že je možné dvacetistěnem kolem jeho první hrany
  otáčet.

[NOTE]
====

Dvacetisten(A, B) je zkrácenou verzí příkazu Dvacetisten(A, B, C), kde C = Bod(Kruznice(StredSoumernosti(A, B), Vzdalenost(A, B) sqrt(3) /
2, Usecka(A, B))).

====

[NOTE]
====

Viz též příkazy xref:/commands/Krychle.adoc[Krychle], xref:/commands/Ctyrsten.adoc[Ctyrsten],
xref:/commands/Osmisten.adoc[Osmisten], xref:/commands/Dodecahedron.adoc[Dodecahedron] commands.

====
