= Příkaz InverzniHyperGeometricke
:page-en: commands/InverseHyperGeometric_Command
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

InverzniHyperGeometricke( <Velikost populace N>, <Počet úspěchů M>, <Velikost vzorku n>, <Pravděpodobnost p> )::
  Určí hodnotu inverzní funkce k distribuční funkci hypergeometrického rozdělení
  (http://en.wikipedia.org/wiki/Hypergeometric_distribution[Hypergeometric_distribution]) pro pravděpodobnost _p_, tedy
  vypočítá _p_.100% http://en.wikipedia.org/wiki/cs:Kvantil[kvantil]. Jinými slovy, výsledkem je takové _t_ pro něž
  _P(X≤t)=p_, kde X je náhodná veličina s hypergeometrickým rozdělením. Pravděpodobnost _p_ musí být z intervalu [0,1].

[NOTE]
====

Mějme konečný soubor _N_ jednotek, z nichž _M_ má sledovanou vlastnost (úspěch). Z tohoto souboru vybereme náhodně
najednou nebo postupně (bez vracení) _n_ jednotek. Náhodná veličina, představující počet vybraných jednotek se
sledovanou vlastností (úspěchů) má hypergeometrické rozdělení.

====

[NOTE]
====

Anglická verze:
/s_index_php?title=En:Manual:InverseHyperGeometric_Command_action=edit_redlink=1.adoc[InverseHyperGeometric]
====
