= Příkaz InverzniPascal
:page-en: commands/InversePascal
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

InverzniPascal( <Počet úspěchů r>, <Pravděpodobnost úspěchu>, <Pravděpodobnost p> )::
  Určí hodnotu inverzní funkce k distribuční funkci Pascalova rozdělení
  (http://en.wikipedia.org/wiki/Negative_binomial_distribution[Negative binomial distribution]) pro pravděpodobnost _p_,
  tedy vypočítá _p_.100% http://en.wikipedia.org/wiki/cs:Kvantil[kvantil]. Jinými slovy, výsledkem je takové _t_ pro něž
  _P(X≤t)=p_, kde X je náhodná veličina s Pascalovým rozdělením. Pravděpodobnost _p_ musí být z intervalu [0,1].

Pascalovo rozdělení je diskrétní rozdělení definované na Bernoulliho pokusech
(http://en.wikipedia.org/wiki/Bernoulli_process[Bernoulli_process]). Náhodnou veličinou je počet neúspěchů předcházející
sérii _r_ úspěchů.

'Parametry Pascalova rozdělení:

_Počet úspěchů r_: počet po sobě následujícíh úspěchů, jenž zastaví pokus.

_Pravděpodobnost úspěchu_: pravděpodobnost úspěchu v jednom pokusu

[NOTE]
====

Anglická verze: /s_index_php?title=En:Manual:InversePascal_Command_action=edit_redlink=1.adoc[InversePascal]
====
