= Příkaz NahodneNormalni
:page-en: commands/RandomNormal_Command
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

NahodneNormalni [ <Střední Hodnota>, <Směrodatná odchylka> ]::
  Vygeneruje náhodné číslo z normálního rozdělení, jehož střední hodnota a směrodatná odchylka jsou dány.

[EXAMPLE]
====

`++NahodneNormalni[3, 0.1]++` poskytne náhodnou hodnotu z normálního rozdělení, jehož střední hodnota je _3_ a
směrodatná odchylka je _0.1_.

====

[NOTE]
====

Viz též xref:/commands/NahodneBinomicke.adoc[Příkaz_NahodneBinomicke] a
xref:/commands/NahodnePoissonovo.adoc[Příkaz_NahodnePoissonovo].

====

== CAS pohled

NahodneNormalni [ <Střední Hodnota>, <Směrodatná odchylka> ]::
  Vygeneruje náhodné číslo z normálního rozdělení, jehož střední hodnota a směrodatná odchylka jsou dány.

[EXAMPLE]
====

`++NahodneNormalni[3, 0.1]++` poskytne náhodnou hodnotu z normálního rozdělení, jehož střední hodnota je _3_ a
směrodatná odchylka je _0.1_.

====

[NOTE]
====

Viz též xref:/commands/NahodneMezi.adoc[Příkaz_NahodneMezi], xref:/commands/NahodnyPrvek.adoc[Příkaz_NahodnyPrvek],
xref:/commands/NahodneBinomicke.adoc[Příkaz_NahodneBinomicke],
xref:/commands/NahodnePoissonovo.adoc[Příkaz_NahodnePoissonovo],
xref:/commands/NahodneUniformni.adoc[Příkaz_NahodneUniformni].

====
