= Příkaz NahodnyPrvek
:page-en: commands/RandomElement
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

NahodnyPrvek( <Seznam> )::
  Poskytne prvek náhodně vybraný ze zadaného xref:/Seznamy.adoc[seznamu]. Všechny prvky v seznamu musí být stejného
  typu.

[EXAMPLE]
====

`++NahodnyPrvek[{3, 2, -4, 7}]++` poskytne jeden prvek z _\{-4, 2, 3, 7}_.

====

[NOTE]
====

Viz též xref:/commands/Prvek.adoc[Příkaz_Prvek].

====

== CAS Pohled

NahodnyPrvek( <Seznam> )::
  Poskytne prvek náhodně vybraný ze zadaného xref:/Seznamy.adoc[seznamu]. Všechny prvky v seznamu musí být stejného
  typu.

[EXAMPLE]
====

`++NahodnyPrvek[{3, 2, -4, 7}]++` poskytne jeden prvek z _\{-4, 2, 3, 7}_.

====

[NOTE]
====

Viz též xref:/commands/Prvek.adoc[Příkaz_Prvek].

====

[NOTE]
====

Viz též xref:/commands/NahodneMezi.adoc[Příkaz_NahodneMezi],
xref:/commands/NahodneNormalni.adoc[Příkaz_NahodneNormalni],
xref:/commands/NahodneBinomicke.adoc[Příkaz_NahodneBinomicke],
xref:/commands/NahodnePoissonovo.adoc[Příkaz_NahodnePoissonovo],
xref:/commands/NahodneUniformni.adoc[Příkaz_NahodneUniformni]

====
