= Příkaz NahodnePoissonovo
:page-en: commands/RandomPoisson
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

NahodnePoissonovo [ <Střední hodnota> ]::
  Vygeneruje náhodné číslo z Poissonova rozdělení, jehož střední hodnota (intenzita) je dána.

[EXAMPLE]
====

`++NahodnePoissonovo[3]++` poskytne náhodnou hodnotu z Poissonova rozdělení, jehož střední hodnota je _3_.

====

[NOTE]
====

Viz též xref:/commands/NahodneBinomicke.adoc[Příkaz_NahodneBinomicke] a
xref:/commands/NahodneNormalni.adoc[Příkaz_NahodneNormalni].

====

== CAS pohled

NahodnePoissonovo [ <Střední hodnota> ]::
  Vygeneruje náhodné číslo z Poissonova rozdělení, jehož střední hodnota (intenzita) je dána.

[EXAMPLE]
====

`++NahodnePoissonovo[3]++` poskytne náhodnou hodnotu z Poissonova rozdělení, jehož střední hodnota je _3_.

====

[NOTE]
====

Viz též xref:/commands/NahodneMezi.adoc[Příkaz_NahodneMezi], xref:/commands/NahodnyPrvek.adoc[Příkaz_NahodnyPrvek],
xref:/commands/NahodneNormalni.adoc[Příkaz_NahodneNormalni],
xref:/commands/NahodneBinomicke.adoc[Příkaz_NahodneBinomicke],
xref:/commands/NahodneUniformni.adoc[Příkaz_NahodneUniformni].

====
