= Příkaz NahodneBinomicke
:page-en: commands/RandomBinomial
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

NahodneBinomicke [ <Počet pokusů>, <Pravděpodobnost> ]::
  Vygeneruje náhodné číslo z binomického rozdělení s parametry _n_ a _p_, kde _n_ je zadaný počet pokusů a _p_ je zadaná
  pravděpodobnost.

[EXAMPLE]
====

`++NahodneBinomicke[3, 0.1]++` poskytne _j ∈ \{0, 1, 2, 3}_, kde _j_ je počet výskytu nějaké události (jevu) ve 3
nezávislých pokusech, jestliže pravděpodobnost výskytu této události (jevu) je v každém jednotlivém pokusu rovna "0.1".

====

== CAS pohled

NahodneBinomicke [ <Počet pokusů>, <Pravděpodobnost> ]::
  Vygeneruje náhodné číslo z binomického rozdělení s parametry _n_ a _p_, kde _n_ je zadaný počet pokusů a _p_ je zadaná
  pravděpodobnost.

[EXAMPLE]
====

`++NahodneBinomicke[3, 0.1]++` poskytne _j ∈ \{0, 1, 2, 3}_, kde _j_ je počet výskytu nějaké události (jevu) ve 3
nezávislých pokusech, jestliže pravděpodobnost výskytu této události (jevu) je v každém jednotlivém pokusu rovna "0.1".

====

[NOTE]
====

Viz též xref:/commands/NahodneMezi.adoc[Příkaz_NahodneMezi], xref:/commands/NahodnyPrvek.adoc[Příkaz_NahodnyPrvek],
xref:/commands/NahodneNormalne.adoc[Příkaz_NahodneNormalne],
xref:/commands/NahodnePoissonovo.adoc[Příkaz_NahodnePoissonovo],
xref:/commands/NahodneUniformni.adoc[Příkaz_NahodneUniformni].

====
