= Příkaz NastavitDekoraci
:page-en: commands/SetDecoration
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

NastavitDekoraci( <Objekt>, <Číslo> )::
  Nastaví vizuální podobu daného objektu (viz též karta _Styl_ v okně _Nastavení_, u verze GeoGebra Klasik 5 je dostupné volbou _Vlastnosti_). Objektem musí být úhel, úsečka nebo libovolný "vyplnitelný objekt". Druhým parametrem příkazu je číselný kód vzhledu (dekorace) objektu / stylu výplně, dle následující tabulky.

[cols=",,,",options="header",]
|===
|hodnota |vzhled úsečky |vzhled úhlu |styl výplně
|0 |bez dekorace |žádná dekorace |souvislá výplň
|1 |jedno přeškrtnutí |dva obloučky |šrafování
|2 |dvě přeškrtnutí |tři obloučky |dvojité šrafování
|3 |tři přeškrtnutí |jedno přeškrtnutí |šachovnice
|4 |jedna šipka |dvě přeškrtnutí |tečky
|5 |dvě šipky |tři přeškrtnutí |plástev
|6 |tři šipky |šipka proti směru hodin |cihly
|7 |bez dekorace |šipka ve směru hodin |pletivo
|===

NastavitDekoraci(<Úsečka>, <Číslo>, <Číslo>)::
  Nastaví podobu konců úsečky, v pořadí použitém při její definici. Aby bylo zvolené vizuální pojetí konců úsečky vidět, je třeba skrýt její krajní body, tj. body kterými je definovaná. Vzhled úsečky může být nastaven také na kartě _Styl_ v okně _Nastavení_ dostupném v odpovídající kontextové nabídce. První z čísel, která jsou použita jako parametry příkazu, definuje podobu začátku úsečky, druhé z nich pak definuje podobu jejího konce, dosazením příslušné hodnoty dle následující tabulky.

[cols=",",options="header",]
|===
|hodnota |vzhled
|0 |bez dekorace
|1 |kolmá čárka
|2 |prázdný čtvereček
|3 |plný čtvereček
|4 |šipka
|5 |plná šipka
|6 |prázdný kroužek
|7 |plný kroužek
|===
