= Příkaz NastavitDekoraci
:page-en: commands/SetDecoration
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

NastavitDekoraci( <Objekt>, <Číslo> )::
  Nastaví vizuální podobu daného objektu (viz též karta _Styl_ v okně _Nastavení_, u verze GeoGebra Klasik 5 je dostupné volbou _Vlastnosti_). Objektem musí být úhel, úsečka nebo libovolný "vyplnitelný objekt". Druhým parametrem příkazu je číselný kód vzhledu (dekorace) objektu / stylu výplně, dle následující tabulky.

[cols=",,,",options="header",]
|===
|hodnota |vzhled úsečky |vzhled úhlu |styl výplně
|0 |žádná dekorace |žádná dekorace |souvislá výplň
|1 |jedno přeškrtnutí |dva obloučky |šrafování
|2 |dvě přeškrtnutí |tři obloučky |dvojité šrafování
|3 |tři přeškrtnutí |jedno přeškrtnutí |šachovnice
|4 |jedna šipka |dvě přeškrtnutí |tečky
|5 |dvě šipky |tři přeškrtnutí |plástev
|6 |tři šipky |šipka proti směru hodin |cihly
|7 |bez dekorace |šipka ve směru hodin |pletivo
|===

SetDecoration(<Segment>, <Number>, <Number>)::
  Sets the aspect of the line start and end of a segment. In order to view the decoration, it's necessary to hide the
  two points that define the vertices of the segment. The segment decoration can also be set in the _Style_ tab of the
  _Properties_ window of the segment. The first number used as command parameter defines the style of the line segment
  start, and the second number sets the style of the line segment end, as described in the following table.

[cols=",",options="header",]
|===
|Value |Decoration
|0 |No decoration
|1 |vertical bar
|2 |empty square
|3 |filled square
|4 |arrow
|5 |filled arrow
|6 |empty dot
|7 |filled dot
|===
