= Příkaz NastavitBarvuPozadi
:page-en: commands/SetBackgroundColor_Command
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

NastavitBarvuPozadi( <Objekt>, "<barva>")::
  Změní barvu pozadí daného objektu. Funguje pro texty a pro tabulky. Název barvy je zadán jako xref:/Texty.adoc[text].
  Příkaz akceptuje více než sto anglických výrazů pro barvy (viz
  /s_index_php?title=En:Reference:Colors_action=edit_redlink=1.adoc[Seznam barev]). Barvy, které jsou zapsány do seznamu
  níže, mohou být zadány česky.
NastavitBarvuPozadi( <Objekt>, <Červená>, <Zelená>, <Modrá> )::
  Změní barvu pozadí daného objektu. Funguje pro texty a pro tabulky. První, druhé a třetí číslo, ležící v intervalu od
  0 do 1, popisuje množství odpovídající barevné složky požadované ve výsledku. Číslu _t_, které přesahuje daný
  interval, je přiřazeno číslo stem:[2\left|\frac\{t}2-\mathrm round\left(\frac\{t}2\right)\right|].

* černá
* tmavě šedá
* šedá
* tmavě modrá
* modrá
* tmavě zelená
* zelená
* hnědočerná
* rudá
* červená
* purpurová
* indigo
* nachová
* hnědá
* oranžová
* zlatá

* limetková
* azurová
* tyrkysová
* světle modrá
* akvamarínová
* stříbrná
* světle šedá
* růžová
* fialová
* žlutá
* světle žlutá
* světle oranžová
* světle fialová
* světle nachová
* světle zelená
* bílá

 
