= Příkaz NejkratsiVzdalenost
:page-en: commands/ShortestDistance
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

NejkratsiVzdalenost( <Seznam hran>, <Počáteční bod>, <Koncový bod>, <Ohodnocený (true/false)> )::
  Nalezne (http://en.wikipedia.org/wiki/cs:_Dijkstr%C5%AFv_algoritmus[nejkratší cestu]) v neorientovaném
  http://en.wikipedia.org/wiki/cs:graf[grafu], zadaném seznamem hran. Hrany grafu jsou zadané úsečkami. Logická hodnota
  pro parametr _Ohodnocený_ určuje, zda jsou uvažovány délky úseček. Pokud zadáme hodnotu _false_, je uvažovaná délka
  všech hran 1, jinak jsou jako hodnoty hran grafu uvažovány skutečné délky úseček. Výsledný objekt je
  xref:/commands/MnozinaBodu.adoc[množina bodů] dané vlastnosti, tedy je to
  xref:/Volné_závislé_a_pomocné_objekty.adoc[pomocný objekt].

[NOTE]
====

Podívejte se na ostatní příkazy z teorie grafů:
xref:/commands/Diskrétní_matematika_(Příkazy).adoc[Diskrétní_matematika_(Příkazy)]

====

[NOTE]
====

/s_index_php?title=En:ShortestDistance_Command_action=edit_redlink=1.adoc[ShortestDistance]
====
