= Příkaz Obal
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

Obal( <Seznam bodů>, <Procento p> )::
  Vytvoří zobecněný obal (https://en.wikipedia.org/wiki/convex_hull[convex hull]) dané množiny bodů. Definice a
  konstrukce zobecněné obálky množiny bodů je popsána v http://www.geosensor.net/papers/duckham08.PR.pdf[Efficient
  generation of simple polygons for characterizing the shape of a set of points in the plane]. Pro _p=1_, je výsledkem
  konvexní obal množiny bodů (xref:/commands/KonvexniObal.adoc[Příkaz_KonvexniObal]). Hodnota procenta _p_ z intervalu
  [0,1] určuje obsah výsledné obálky. Obvykle platí, že pro menší _p_ je menší i obsah obálky, ale pro _p=0_ nemusí být
  nutně výsledkem obraz s minimálním obsahem.

Výsledný objekt je xref:/commands/MnozinaBodu.adoc[množina bodů] dané vlastnosti, tedy je to
xref:/Volné_závislé_a_pomocné_objekty.adoc[pomocný objekt].

[NOTE]
====

Hodnoty _p_ větší než 1 dávají výsledek identický s __p__=1, se zápornými čísly je zacházeno jako s __p__=0.

====

[NOTE]
====

Anglická verze příkazu: /s_index_php?title=En:Hull_Command_action=edit_redlink=1.adoc[Hull command]

====
