= Příkaz Osmisten
:page-en: commands/Octahedron
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

Osmisten( <Rovnostranný trojúhelník> )::
  Vytvoří osmistěn, jehož podstavou je daný rovnostranný trojúhelník.

Osmisten( <Bod>, <Bod>, <Směr> )::
  Vytvoří osmistěn, jehož jednou hranou je úsečka daná uvedenými dvěma body.
  Další vrcholy jsou pak jednoznačně určeny daným směrem, který je třeba zadat jako:
  * vektor, úsečku, přímku, či polopřímku, vždy *kolmo* k uvedené úsečce, nebo
  * mnohoúhelník, či rovinu, *rovnoběžně* s úsečkou (hranou).
+ 
Výsledný osmistěn bude potom mít:
  * stěnu s danou úsečkou jako hranou v rovině kolmé k vektoru/úsečce/přímce/polopřímce, nebo
  * stěnu s danou úsečkou jako hranou v rovině rovnoběžné s mnohoúhelníkem/rovinou.

Osmisten( <Bod>, <Bod>, <Bod>)::
  Vytvoří osmistěn s uvedenými třemi body jako vrcholy první stěny. Body proto musí tvořit rovnostranný trojúhelník, aby jimi byl definován osmistěn.

Octahedron( <Bod>, <Bod>)::
  Creates an octahedron with the two points of the first face, and the third point automatically created on a circle, so
  that the octahedron can rotate around its first edge.

[NOTE]
====

Octahedron(A, B) is a shortcut for Octahedron(A, B, C) with C = Point(Circle(Midpoint(A, B), Distance(A, B) sqrt(3) / 2,
Segment(A, B))).

====

[NOTE]
====

See also xref:/commands/Cube.adoc[Cube], xref:/commands/Tetrahedron.adoc[Tetrahedron],
xref:/commands/Icosahedron.adoc[Icosahedron], xref:/commands/Dodecahedron.adoc[Dodecahedron] commands.

====
