= Příkaz PodrobnostiDukazu
:page-en: commands/ProveDetails
ifdef::env-github[:imagesdir: /cs/modules/ROOT/assets/images]

PodrobnostiDukazu( <Booleovský výraz> )::
  Poskytne detailnější informace o výsledku automatického důkazu obecné pravdivosti tvrzení vloženého ve formě booleovského výrazu, tj. výrazu nabývajícího hodnoty _true_ nebo _false_.

Normálně GeoGebra rozhoduje o pravdivosti xref:/Pravdivostní_hodnoty.adoc[booleovského výrazu], tj. zda je jeho hodnota _true_ nebo _false_, pomocí numerického výpočtu. Příkaz _PodrobnostiDukazu_ však pro vyhodnocení toho, zda má vložený booleovský výraz hodnotu _true_ nebo _false_, používá https://en.wikipedia.org/wiki/Symbolic_computation[symbolické metody] výpočtu. Zabývá se tak obecnou platností vlastnosti, které se výraz týká. Příkaz funguje stejně jako příkaz xref:/commands/Dokazat.adoc[Dokazat], akorát navíc vypíše nějaké detailnější informace o svém výsledku formou xref:/Seznamy.adoc[seznamu] takto:

* Prázdný seznam *{}*, pokud GeoGebra nemůže určit odpověď.
* Seznam s jedním prvkem: *{false}*, pokud tvrzení není obecně pravdivé.
* Seznam s jedním prvkem: *{true}*, pokud je předmětné tvrzení vždy pravdivé (ve všech případech, na které může být daný obrázek modifikován).
* Seznam s více prvky, konkrétně obsahující booleovskou hodnotu _true_ spolu s dalším seznamem pro tzv. _nedegenerativní podmínky_ (_non-degeneracy
conditions_), pokud je tvrzení pravdivé za určitých podmínek. Příkladem takového výstupu je seznam {true, {"JsouKolinearni(A,B,C),JsouTotozne(C,D)"}}, jehož význam je takový, že pokud není splněna žádná z uvedených podmínek "JsouKolinearni(A,B,C),JsouTotozne(C,D)" (a příslušná geometrická konfigurace může být zobrazena), předmětné tvrzení je pravdivé.
* Seznam ve tvaru *{true,{"..."}}*, pokud je tvrzení pravdivé za určitých podmínek, které však nelze z nějakých důvodů vyjádřit člověku srozumitelnou formou.

[EXAMPLE]
====

Nechť jsou pro trojúhelník s vrcholy _A_, _B_, _C_ definovány body `++D=StredSoumernosti(B,C)++`, `++E=StredSoumernosti(A,C)++` a přímky
`++p=Primka(A,B)++`, `++q=Primka(D,E)++`. Potom příkaz `++PodrobnostiDukazu(p∥q)++` vrátí {true}, což znamená, že pokud lze sestrojit obrázek, střední příčka _DE_ uvažovaného trojúhelníku je rovnoběžná se stranou _AB_.

====

[EXAMPLE]
====

Pro úsečku _AB_ označenou _a_ definujme `++C=StredSoumernosti(A,B)++`, `++b=OsaUsecky(A,B)++`,
`++D=Prusecik(a,b)++`. Nyní příkaz `++PodrobnostiDukazu(C==D)++` vrátí {true,{"JsouTotozne(A,B)"}}, což znamená, že pokud jsou body _A_
a _B_ různé, potom body _C_ a _D_ splývají, tj. jsou totožné.

====

[EXAMPLE]
====

Spolu s úsečkou _AB_ označenou _a_ je definována přímka `++l=Line(A,B)++`. Nechť _C_ je libovolný bod na přímce _l_, pro který jsou definovány úsečky `++b=Segment(B,C)++`, `++c=Segment(A,C)++`. Potom příkaz `++ProveDetails(a==b+c)++` vrátí {true,{"a+b==c", "b==a+c"}}, což znamená, že pokud neplatí stem:[a+b=c], ani stem:[b=a+c], potom je pravda, že stem:[a=b+c].

====

Může se stát, že uvedený seznam nedegenerativních podmínek není nejjednodušší možný.

[NOTE]
====

Viz též příkaz xref:/commands/Dokazat.adoc[Dokazat], xref:/Pravdivostní_hodnoty.adoc[Pravdivostní hodnoty] a článek
https://github.com/kovzol/gg-art-doc/tree/master/pdf/english.pdf[GeoGebra Automated Reasoning Tools: A Tutorial] a
http://dev.geogebra.org/trac/wiki/TheoremProving[technical details of the algorithms].

====
