= Comando Arco
:page-en: commands/Arc
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Arco(Circonferenza, Punto A, Punto B)::
  Restituisce l'arco di circonferenza compreso tra i punti _A_ e _B_, orientato in senso antiorario.

Arco(Ellisse, Punto A, Punto B)::
  Restituisce l'arco di ellisse compreso tra i punti _A_ e _B_, orientato in senso antiorario.

Arco(Circonferenza, Numero t1, Numero t2)::
  Restituisce l'arco di circonferenza compreso tra i valori _t1_ e _t2_ del parametro.

[NOTE]
====

Internamente viene utilizzata la forma parametrica:

* Circonferenza: _(r cos(t), r sin(t))_, dove _r_ è il raggio della circonferenza.

====

Arco(Ellisse, Numero t1, Numero t2)::
  Restituisce l'arco di ellisse compreso tra i valori _t1_ e _t2_ del parametro.

[NOTE]
====

Internamente viene utilizzata la forma parametrica:

* Ellisse: (_a_ cos(_t_), _b_ sin(_t_)) dove _a_, _b_ sono le lunghezze dei semiassi, rispettivamente maggiore e minore.

====

[NOTE]
====

Vedere anche il comando xref:/commands/ArcoTrePunti.adoc[ArcoTrePunti].

====
