= Comando Binomiale
:page-en: commands/BinomialDist
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Binomiale(Numero di prove, Probabilità di successo)::
  Restituisce un diagramma a barre di una http://en.wikipedia.org/wiki/it:Distribuzione_binomiale[distribuzione
  binomiale].
  _Parametri:_
  * _Numero di prove_: numero di prove di Bernoulli indipendenti
  * _Probabilità di successo_: probabilità di successo di una prova


Binomiale(Numero di prove, Probabilità di successo, Booleano _Cumulata_)::
  Restituisce un diagramma a barre di una distribuzione binomiale quando _Cumulata_ = false.
  Restituisce il grafico della distribuzione binomiale cumulata quando _Cumulata_ = true.
  I primi due parametri hanno le caratteristiche indicate nella sintassi precedente.

Binomiale(Numero di prove, Probabilità di successo, Valore variabile _v_ , Booleano _Cumulata_)::
  Sia X una variabile casuale binomiale.
  Restituisce P( X = _v_) quando _Cumulata_ = false.
  Restituisce P( X ≤ _v_) quando _Cumulata_ = true.
  I primi due parametri hanno le caratteristiche indicate nelle sintassi precedenti.

Binomiale(Numero di prove, Probabilità di successo, Lista di valori)::
 Calcola P(_u_ ≤ X ≤ _v_) applicando la sintassi precedente (con _Cumulata_ = false) e sommando i valori ottenuti utilizzando a turno gli elementi della _Lista di valori_ come _valori variabile_.

[EXAMPLE]
====

`++Binomiale(10, 0.2, {1,2,3})++` restituisce _0.77175_, ed è equivalente a `++Binomiale(10, 0.2, 1, false)++` + `++Binomiale(10, 0.2, 2, false)++` + `++Binomiale(10, 0.2, 3, false)++`

====

[NOTE]
====

Le sintassi `++Binomiale(10, 0.2, {1,2,3})++` e `Binomiale(10, 0.2, 1..3)` sono equivalenti
====

== Sintassi CAS


Binomiale(Numero di prove, Probabilità di successo, Valore variabile _v_, Booleano _Cumulata_)::
  Sia X una variabile casuale binomiale.
  Restituisce P(X = _v_) quando _Cumulata_ = false.
  Restituisce P(X <= _v_) quando _Cumulata_ = true.

[EXAMPLE]
====

Supponiamo di trasferire tre pacchetti di dati su una linea difettosa. La probabilità che un pacchetto trasferito lungo
tale linea risulti corrotto è stem:[\frac{1}{10}], e quindi la probabilità di trasferire un pacchetto con successo è
stem:[\frac{9}{10}].

* `++Binomiale(3, 0.9, 0, false)++` restituisce _stem:[\frac{1}{1000}]_, la probabilità che nessuno dei tre pacchetti
sia trasferito con successo,
* `++Binomiale(3, 0.9, 1, false)++` restituisce _stem:[\frac{27}{1000}]_, la probabilità che esattamente uno dei tre
pacchetti sia trasferito con successo,
* `++Binomiale(3, 0.9, 2, false)++` restituisce _stem:[\frac{243}{1000}]_, la probabilità che esattamente due dei tre
pacchetti siano trasferiti con successo,
* `++Binomiale(3, 0.9, 3, false)++` restituisce _stem:[\frac{729}{1000}]_, la probabilità che tutti i tre pacchetti
siano trasferiti con successo.
* `++Binomiale(3, 0.9, 0, true)++` restituisce _stem:[\frac{1}{1000}]_, la probabilità che nessuno dei tre pacchetti
sia trasferito con successo,
* `++Binomiale(3, 0.9, 1, true)++` restituisce _stem:[\frac{7}{250}]_, la probabilità che al più uno dei tre pacchetti
sia trasferito con successo,
* `++Binomiale(3, 0.9, 2, true)++` restituisce _stem:[\frac{271}{1000}]_, la probabilità che al più due dei tre
pacchetti siano trasferiti con successo,
* `++Binomiale(3, 0.9, 3, true)++` restituisce _1_, la probabilità che al più tre dei tre pacchetti siano trasferiti con
successo.
* `++Binomiale(3, 0.9, 4, false)++` restituisce _0_, la probabilità che esattamente quattro dei tre pacchetti siano
trasferiti con successo,
* `++Binomiale(3, 0.9, 4, true)++` restituisce _1_, la probabilità che al più quattro dei tre pacchetti siano trasferiti
con successo.

====

Binomiale(Numero di prove, Probabilità di successo, Lista di valori)::
 Calcola P(_u_ ≤ X ≤ _v_) applicando la sintassi precedente (con _Cumulata_ = false) e sommando i valori ottenuti utilizzando a turno gli elementi della _Lista di valori_ come _valori variabile_.

[EXAMPLE]
====

`++Binomiale(10, 0.2, {1,2,3})++` restituisce stem:[\frac{1507328}{1953125}], ed è equivalente a `++Binomiale(10, 0.2, 1, false)++` + `++Binomiale(10, 0.2, 2, false)++` + `++Binomiale(10, 0.2, 3, false)++`

====
