= Comando CasualeUniforme
:page-en: commands/RandomUniform
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

CasualeUniforme(Min, Max)::
  Restituisce un numero reale casuale con https://it.wikipedia.org/_Distribuzione_continua_uniforme[distribuzione
  uniforme] nell'intervallo [min,max].

[EXAMPLE]
====

`++CasualeUniforme(0,1)++` restituisce un numero casuale compreso tra 0 e 1

====

CasualeUniforme(Min, Max, Numero di campioni n)::
  Restituisce una lista di _n_ numeri reali casuali con
  https://it.wikipedia.org/_Distribuzione_continua_uniforme[distribuzione uniforme] nell'intervallo [_min_,
  _max_].

[EXAMPLE]
====

`++CasualeUniforme(0, 1, 3)++` restituisce una lista contenente tre numeri casuali compresi tra 0 e 1.

====

[NOTE]
====

* `++CasualeUniforme(0,1)++` è equivalente a `++random()++` (vedere xref:/Funzioni_e_operatori_predefiniti.adoc[Funzioni
e operatori predefiniti]).
* Vedere anche i comandi xref:/commands/ImpSeme.adoc[ImpSeme], xref:/commands/CasualeTra.adoc[CasualeTra],
xref:/commands/CasualeBinomiale.adoc[CasualeBinomiale], xref:/commands/CasualeNormale.adoc[CasualeNormale],
xref:/commands/CasualePoisson.adoc[CasualePoisson], xref:/commands/ElementoCasuale.adoc[ElementoCasuale].

====
