= Comando Cauchy
:page-en: commands/Cauchy
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Cauchy(Mediana, Scala, Valore variabile)::
  Calcola il valore della funzione di distribuzione cumulata di una http://en.wikipedia.org/wiki/it:Distribuzione_di_Cauchy[distribuzione di Cauchy] in corrispondenza del _valore variabile v_, cioè la probabilità _P(X ≤ v)_ dove _X_ è una variabile casuale di Cauchy avente per parametri la _mediana_ e la _scala_ indicate.

[EXAMPLE]
====

`++Cauchy(1, 2, 3)++` restituisce _0.75_ nella _vista Algebra_ e _stem:[\frac{3}{4}]_ nella _vista CAS_.

====

[NOTE]
====

Questa sintassi restituisce la probabilità relativa a un determinato valore diella variabile, che è l'area sottesa dalla curva della
distribuzione di Cauchy alla sinistra dell'ascissa indicata.

====

Cauchy(Mediana, Scala, Valore variabile, Booleano Cumulata)::
Se _Cumulata_ è _true_, calcola il valore della funzione di distribuzione cumulata in corrispondenza del _valore variabile_ della distribuzione di Cauchy; in caso
  contrario calcola la funzione di densità di probabilità in corrispondenza del _valore variabile_ della distribuzione di Cauchy avente per parametri la _mediana_ e la _scala_ indicate.

Cauchy(Mediana, Scala, x, Booleano Cumulata)::
  Se _Cumulata_ è _true_, genera la funzione di distribuzione cumulata della distribuzione di Cauchy; in caso
  contrario genera la funzione di densità di probabilità della distribuzione di Cauchy avente per parametri la _mediana_ e la _scala_ indicate.





