= Comando CerchioOsculatore
:page-en: commands/OsculatingCircle
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

CerchioOsculatore(Punto, Funzione)::
  Genera il cerchio osculatore della funzione nel punto indicato.

[EXAMPLE]
====

`++CerchioOsculatore((0,0), x^2)++` restituisce _x² + y² - y = 0_.

====

CerchioOsculatore(Punto, Curva)::
  Genera il cerchio osculatore della curva nel punto indicato.

[EXAMPLE]
====

`++CerchioOsculatore((1, 0), Curva(cos(t), sin(2t), t, 0, 2π))++` restituisce _x² + y² + 6x = 7_.

====

CerchioOsculatore(Punto, Oggetto)::
  Genera il cerchio osculatore dell'oggetto (funzione, curva, conica), nel punto indicato.

[EXAMPLE]
====

*Esempi:*

* `++CerchioOsculatore((0 ,0), x^2)++` restituisce _x² + y² - y = 0_
* `++CerchioOsculatore((1, 0), Curva(cos(t), sin(2t), t, 0, 2π))++` restituisce _x² + y² + 6x = 7_
* `++CerchioOsculatore((-1, 0), Conica({1, 1, 1, 2, 2, 3}))++` restituisce _x² + y² + 2x +1y = -1_

====

[NOTE]
====

Questo comando è applicabile solo a oggetti bidimensionali. Per oggetti 3D è possibile creare uno strumento
personalizzato, come ad esempio qui: https://www.geogebra.org/m/tan7dxjt

====
