= Comando Cubo

Cubo(Punto, Punto, Oggetto)::
  Genera un cubo avente per spigolo il segmento individuato dai due punti indicati.
  +
  Gli altri vertici sono determinati univocamente da un _Oggetto_, che indica la _direzione_ di creazione, che può
  essere:
  +
  * un vettore, un segmento, una retta o una semiretta perpendicolari perpendicolari al segmento, oppure
  * un poligono o un piano paralleli al segmento.
  +
  Il cubo così creato avrà:
  +
  * una faccia avente per spigolo il segmento, in un piano perpendicolare al vettore/segmento/retta/semiretta indicati,
  oppure
  * una faccia avente per spigolo il segmento, in un piano parallelo a quello del poligono/piano indicato.

Cubo(Punto, Punto, Punto)::
  Genera il cubo avente i tre punti indicati come vertici adiacenti della prima faccia. I punti devono formare un
  quadrato, per fare in modo che il cubo risulti definito.

Cubo(Punto, Punto)::
  Genera il cubo avente per spigolo della prima faccia il segmento il segmento individuato dai punti indicati, mentre il
  terzo vertice della faccia è individuato su una circonferenza, in modo che il cubo possa ruotare attorno allo spigolo.
  +

[NOTE]

====

`Cubo(A, B)` è una sintassi abbreviata di `Cubo(A, B, C)`, con
`C = C = Punto(Circonferenza(B, Distanza(A, B), Segmento(A, B)))`.

====

[NOTE]

====

Vedere anche i comandi xref:/commands/Comando_Tetraedro.adoc[Tetraedro], xref:/commands/Comando_Ottaedro.adoc[Ottaedro],
xref:/commands/Comando_Icosaedro.adoc[Icosaedro], xref:/commands/Comando_Dodecaedro.adoc[Dodecaedro].

====
