= Comando Curva

Curva(Espressione, Espressione, Parametro, Valore iniziale, Valore finale)::
  Traccia il grafico cartesiano della xref:/Curve.adoc[curva parametrica] indicata, in cui _x_ e _y_ sono definite
  rispettivamente dalle due _espressioni_, dipendenti dal parametro indicato, variabile nell'intervallo [_Valore
  iniziale_, _Valore finale_] indicato.

[EXAMPLE]
====

`++Curva(2 cos(t), 2 sin(t), t, 0, 2 pi)++` traccia la circonferenza di raggio 2 con centro nell'origine del sistema di
coordinate.

====

Curva( Espressione, Espressione , Espressione, Parametro , Valore iniziale, Valore finale )::
  Traccia il grafico cartesiano della curva parametrica 3d indicata, in cui _x_, _y_ e _z_ sono definite rispettivamente
  dalle tre _espressioni_, dipendenti dal parametro indicato, variabile nell'intervallo [_Valore iniziale_, _Valore
  finale_].

[EXAMPLE]
====

`++Curva(cos(t), sin(t), t, t, 0, 10π)++` genera una spirale 3d.

====

[NOTE]
====

* Il _Valore finale_ assunto dal parametro deve essere maggiore o uguale del _Valore iniziale_, ed entrambi devono
essere finiti.
* Non è possibile utilizzare _x_, _y_ e _z_ come parametri
* Per ulteriori dettagli vedere la pagina xref:/Curve.adoc[Curve], il comando
xref:/commands/Comando_Derivata.adoc[Derivata] e il comando
xref:/commands/Comando_DerivataParametrica.adoc[DerivataParametrica].

====
