= Comando Se

Se(Condizione, Oggetto)::
  Restituisce una copia dell'oggetto se la condizione è soddisfatta (_true_), e un oggetto _non definito_ se la
  condizione non è soddisfatta (_false_).

[EXAMPLE]
====

*Esempi:*

* Sia _n_ = 3. Il comando `++Se(n==3, x + y = 4)++` genera e traccia la retta di equazione _x + y = 4_
* Sia _n_ = 4. Il comando `++Se(n==3, x + y = 4)++` crea un oggetto _non definito_ perché la condizione sul numero _n_
non è soddisfatta.

====

Se(Condizione, Oggetto a, Oggetto b)::
  Restituisce una copia dell'oggetto _a_ se la condizione è soddisfatta (_true_), e una copia dell'oggetto _b_ se la
  condizione non è soddisfatta (_false_). *Entrambi gli oggetti devono essere dello stesso tipo*.

[EXAMPLE]
====

Sia _n_ un numero qualsiasi. Allora `++Se(n==3, x + y = 4, x - y = 4)++` genera e traccia la retta x + y = 4 quando _n_
= 3, mentre genera e traccia la retta x - y = 4 quando _n_ assume qualsiasi valore diverso da 3

====

Se(Condizione1, Allora 1, Condizione 2, Allora 2, ... , Altrimenti (facoltativo))::
  Restituisce una copia dell'oggetto _Allora 1_ quando la prima condizione è soddisfatta, una di _Allora 2_ quando la
  seconda condizione è soddisfatta, e così via. Se non è soddisfatta alcuna condizione ed è stato indicato un
  _Altrimenti_, allora il comando restituisce una copia di _Altrimenti_. In tutti gli altri casi viene restituito un
  _non definito_.

[EXAMPLE]
====

Il comando `++Se(a ≟ 1, "Teo", a ≟ 2, "Mattia", a ≟ 3, "Chiara", "Roberto")++` restituisce il testo _Teo_ quando _a_ =
1, il testo _Mattia_ quando _a_ = 2, il testo _Chiara_ quando _a_ = 3 e il testo _Roberto_ per tutti gli altri valori di
_a_.

====

== [#Funzioni_condizionate]#Funzioni condizionate#

Il comando _Se_ può essere utilizzato per creare funzioni definite a tratti. Tali funzioni possono essere richiamate da
qualsiasi comando che accetti come argomento una funzione, come xref:/commands/Comando_Derivata.adoc[Derivata],
xref:/commands/Comando_Integrale.adoc[Integrale], e xref:/commands/Comando_Intersezione.adoc[Intersezione].

[EXAMPLE]
====

*Esempi:*

* `++f(x) = Se(x < 3, sin(x), x^2)++` restituisce la funzione a tratti stem:[f(x) = \left\\{\begin\{matrix}\{} sin(x)& :
&x < 3\\ x^\{2}& : &\text\{altrove} \end\{matrix}\right ]
* `++f(x) = Se(0<=x<=3, sin(x))++` restituisce la funzione sin(x) per le _x_ tra 0 e 3 e non è definita altrove. In
questo caso è possibile utilizzare anche una versione più compatta del comando: `++f(x) = sin(x), 0 <= x <= 3++`
* `++f(x) =Se(x<-1,x²,-1<=x<=1,1,-x²+2)++` restituisce la funzione a tratti stem:[f(x) = \left\\{\begin\{matrix}\{}
x^\{2}& : &x < -1\\ 1& :& -1 ≤ x ≤ 1\\ -x^\{2} + 2& : &\text\{altrove} \end\{matrix}\right ].

====

== [#Funzioni_condizionate_in_pi.C3.B9_variabili]#Funzioni condizionate in più variabili#

Il comando *Se* può essere utilizzato anche per definire funzioni in più variabili che dipendono da una condizione. In
questo caso, le definizioni delle componenti della funzione da creare devono contenere tutte le variabili della
funzione.

[EXAMPLE]
====

Sia `++sliderVal = 1++` uno slider a valori nell'intervallo [1,3]. Il comando
`++f(x,y,a,b,c) = Se(sliderVal==1, x + 0y +a + 0b + c, sliderVal==2, 0x+ y^2 + 0a +2b +0c, x + y + 0a + b +0c)++`
restituisce una funzione in più variabili che sarà uguale a _x+a+c_ quando il valore dello slider è 1, _y^2^ + 2b_
quando il valore dello slider è 2, e _x + y + b_ quando il valore dello slider è 3.

====

[NOTE]
====

* Vedere la sezione xref:/Valori_booleani.adoc[Valori booleani] per i simboli utilizzati nelle espressioni condizionali.
* La derivata di una funzione definita a tratti, del tipo _Se(condizione, f(x), g(x))_ sarà nella forma _Se(condizione,
f'(x), g'(x))_, senza valutazione dei limiti nei punti critici.

====

== [#Comando_Se_in_uno_script]#Comando _Se_ in uno script#

Il comando _Se_ può essere utilizzato negli script per eseguire determinate azioni sotto certe condizioni. Gli argomenti
del comando _Se_ non devono essere assegnazioni, ma _oggetti_ o xref:/commands/Comandi_Scripting.adoc[Comandi
Scripting]. Un'istruzione del tipo `++b = Se(a > 1, 2, 3)++` è sintatticamente corretta, ma b=2 o b=3 non verranno
accettati come parametri di _Se_.

[EXAMPLE]
====

Siano _n_ un numero e A un punto: il comando `++Se(Resto(n, 7)==0, ImpCoordinate(A, n, 0), ImpCoordinate(A, n, 1))++`
modifica le coordinate del punto A secondo la condizione indicata. La stringa di comandi più efficiente relativamente a
questa azione rimane comunque `++ ImpCoordinate(A, n, Se(Resto(n, 7) == 0, 0, 1))++`.

====
