= Comando AnalizzaNumero

AnalizzaNumero(Numero, Testo)::
  Analizza il testo e memorizza il corrispondente valore in un link:/it/Numeri_e_angoli[numero] _a_. Il numero _a_ deve
  essere già definito e impostato come oggetto link:/it/Oggetti_liberi,_dipendenti_e_ausiliari[libero] prima di
  utilizzare il comando.
  +
  +

[EXAMPLE]

====

*Esempio:* Definire ` a = 3` e ` testo1 = "6"`. Allora ` AnalizzaNumero(a, testo1)` restituisce _a = 6_.

====

[NOTE]

====

*Note:* Questo è un link:/it/Comandi_Scripting[comando di tipo scripting] che imposta il valore del numero una volta
sola. Per convertire un testo _testo1_ in un numero che possa essere aggiornato dinamicamente, utilizzare il comando
link:/it/Comando_DaBase[DaBase](testo1,10).

====

AnalizzaNumero(Testo)::
  Analizza il testo e memorizza il risultato in un link:/it/Numeri_e_angoli[numero].
  +

[EXAMPLE]

====

*Esempio:* `AnalizzaNumero("1+2+5-pi")` crea il numero _a = 4.86_.

====

[NOTE]

====

*Note:* Vedere anche il comando link:/it/Comando_AnalizzaFunzione[AnalizzaFunzione].

====
