= Comando CasualeTra

CasualeTra(Minimo intero, Massimo intero)::
  Genera un intero casuale compreso tra i valori _minimo_ e _massimo_ indicati (inclusi).

[EXAMPLE]
====

`++CasualeTra(0, 10)++` restituisce un numero compreso tra 0 e 10 (inclusi)

====

CasualeTra(Minimo intero, Massimo intero, Booleano _fissato_)::
  Se il valore booleano _fissato_ = "true", genera un intero casuale compreso tra i valori _minimo_ e _massimo_ indicati
  (inclusi), che viene aggiornato una sola volta (all'apertura del file o in caso di annulla/ripristina).
  +

[EXAMPLE]
====

`++CasualeTra(0, 10, true)++` genera un intero compreso tra _0_ e _10_ (inclusi).

====

[NOTE]
====

Premere [.kcode]#F9# per visualizzare la differenza tra le due sintassi.

====

CasualeTra(Minimo intero, Massimo intero, Numero di campioni)::
  Genera una lista di interi casuali compresi tra i valori _minimo_ e _massimo_ indicati (inclusi). Il numero di interi
  casuali generati è definito dal parametro _Numero di campioni_.

[EXAMPLE]
====

`++CasualeTra(0, 10, 5)++` restituisce ad esempio \{1,3,4,8,2}, oppure \{7,5,6,1,7}, etc.

====

[NOTE]
====

Vedere anche i comandi xref:/commands/Comando_ImpSeme.adoc[ImpSeme],
xref:/commands/Comando_ElementoCasuale.adoc[ElementoCasuale],
xref:/commands/Comando_CasualeBinomiale.adoc[CasualeBinomiale],
xref:/commands/Comando_CasualeNormale.adoc[CasualeNormale], xref:/commands/Comando_CasualePoisson.adoc[CasualePoisson],
xref:/commands/Comando_CasualeUniforme.adoc[CasualeUniforme].

====
