= Comando Compatta

Compatta(Espressione, Variabile1, Lista1, Variabile2, Lista2, ...)::
  Genera una xref:/Liste.adoc[lista] di oggetti, ottenuti sostituendo alle variabili dell'espressione gli elementi
  contenuti nelle liste corrispondenti. Se il numero delle variabili è uguale al numero delle liste, ciascuna variabile
  è estratta dalla lista successiva, mentre se il numero delle variabili supera di 1 il numero delle liste, l'ultima
  variabile assumerà i valori 1, 2, 3, ..., _k_ dove _k_ è la lunghezza della lista più corta. La lunghezza della lista
  risultante è uguale al minimo tra le lunghezze delle liste indicate.
  +
  +

[EXAMPLE]
====

Sia _lista1=\{1, 2, 5}_ una lista di numeri. `Compatta(Semplifica(a*x^(b-1)), a, lista1,b)` restituisce la lista _\{1,
2x, 5x²}_.

====

[EXAMPLE]
====

Sia _lista1=\{x^2, x^3, x^6}_ una lista di polinomi. `Compatta(Grado(a), a, lista1)` restituisce la lista _\{2, 3, 6}_.

====

[EXAMPLE]
====

Siano _P_, _Q_, _R_, _S_ dei punti. `Compatta(PuntoMedio(A, B), A, {P, Q}, B, {R, S})` restituisce una lista contenente
i xref:/commands/Comando_PuntoMedio.adoc[punti medi] dei segmenti _PR_ e _QS_.

====

A partire dalla versione 5.0.258, possono essere utilizzate anche le funzioni come variabili:

[EXAMPLE]
====

`Compatta(f(2), f, {x+1,x+3})` restituisce la lista _\{3, 5}_.

====

[NOTE]
====

Gli elementi di ciascuna lista devono essere dello stesso tipo.

====
