= Comando CasualeUniforme

CasualeUniforme(Min, Max)::
  Restituisce un numero reale casuale con http://en.wikipedia.org/wiki/it:_Distribuzione_continua_uniforme[distribuzione
  uniforme] nell'intervallo [min,max].
  +

[EXAMPLE]

====

`CasualeUniforme(0,1)` restituisce un numero casuale compreso tra 0 e 1

====

CasualeUniforme(Min, Max, Numero di campioni n)::
  Restituisce una lista di _n_ numeri reali casuali con
  http://en.wikipedia.org/wiki/it:_Distribuzione_continua_uniforme[distribuzione uniforme] nell'intervallo [_min_,
  _max_].
  +

[EXAMPLE]

====

`CasualeUniforme(0, 1, 3)` restituisce una lista contenente tre numeri casuali compresi tra 0 e 1.

====

[NOTE]

====

* `CasualeUniforme(0,1)` è equivalente a `random()` (vedere xref:/Funzioni_e_operatori_predefiniti.adoc[Funzioni e
operatori predefiniti]).
* Vedere anche i comandi xref:/commands/Comando_ImpSeme.adoc[ImpSeme],
xref:/commands/Comando_CasualeTra.adoc[CasualeTra], xref:/commands/Comando_CasualeBinomiale.adoc[CasualeBinomiale],
xref:/commands/Comando_CasualeNormale.adoc[CasualeNormale], xref:/commands/Comando_CasualePoisson.adoc[CasualePoisson],
xref:/commands/Comando_ElementoCasuale.adoc[ElementoCasuale].

====
