= Comando PosizioneDi

PosizioneDi(Oggetto, Lista)::
  Restituisce la posizione della prima occorrenza dell'_oggetto_ nella lista.
  +

[EXAMPLE]
====

`PosizioneDi(5, {1, 3, 5, 2, 5, 4})` restituisce 3.

====

[NOTE]
====

Quando l'oggetto non è presente nella lista, restituisce _non definito_.

====

PosizioneDi(Oggetto, Lista, Numero)::
  Restituisce la posizione della prima occorrenza dell'_oggetto_ nella lista, maggiore o uguale alla posizione indicata
  dal _numero_ inserito.

[EXAMPLE]
====

* `PosizioneDi(5, {1, 3, 5, 2, 5, 4}, 3)` restituisce 3.
* `PosizioneDi(5, {1, 3, 5, 2, 5, 4}, 4)` restituisce 5.
* `PosizioneDi(5, {1, 3, 5, 2, 5, 4}, 6)` restituisce _non definito_.

====

PosizioneDi(Testo, Testo)::
  Restituisce la posizione della prima occorrenza del primo _testo_ indicato, all'interno del secondo testo indicato.

[EXAMPLE]
====

`PosizioneDi("Ge", "GeoGebra")` restituisce 1.

====

PosizioneDi(Testo, Testo, Numero)::
  Restituisce la posizione della prima occorrenza del primo _testo_ indicato all'interno del secondo testo indicato,
  maggiore o uguale alla posizione indicata dal _numero_ inserito.

[EXAMPLE]
====

`PosizioneDi("Ge", "GeoGebra", 2)` restituisce 4.

====
