= Comando ApplicaMatrice

ApplicaMatrice(xref:/Matrici.adoc[Matrice], xref:/Oggetti_geometrici.adoc[Oggetto])::
  Applica la matrice di trasformazione all'oggetto, in modo tale che ogni punto _P_ appartenente all'oggetto abbia come
  immagine:

* il punto _M*P_, se _M_ è una matrice 2 x 2 e _P_ è un punto _2D_

* il punto _proiez(M*(x(P), y(P), 1))_ se _P_ è un punto _2D_ e _M_ è una matrice 3 x 3: _proiez_ è una proiezione, che
manda il punto _(x, y, z)_ nel punto _(x/z, y/z)_.

* il punto _M*P_, se _P_ è un punto _3D_ e _M_ una matrice 3 x 3
* il punto _N*P_, se _P_ è un punto _3D_ e _M_ è una matrice 2 x 2: la matrice _N_ è il _completamento di ordine 3_ di
_M_: data _M_ = stem:[\begin\{pmatrix}a&b\\ c&d \end\{pmatrix}] allora _N_ = stem:[\begin\{pmatrix}a&b&0\\ c&d&0\\0&0&1
\end\{pmatrix}]

[EXAMPLE]
====

Siano `M={{1,1,0},{0,1,1},{1,0,1}}` la matrice della trasformazione e `u=(2,1)` un vettore assegnato.
`ApplicaMatrice(M,u)` restituisce il vettore _u'=(1,0.67)_. Infatti stem:[\begin\{pmatrix}1&1&0\\ 0&1&1\\1&0&1
\end\{pmatrix}] stem:[\begin\{pmatrix}2\\ 1\\1 \end\{pmatrix}] = stem:[\begin\{pmatrix}3\\ 2\\3 \end\{pmatrix}], e (3/3
= 1, 2/3 ≈ 0.67) (con un arrotondamento a 2 cifre decimali)

====

[EXAMPLE]
====

Siano `M={{cos(π/2),-sin(π/2)}, {sin(π/2), cos(π/2)}}` la matrice della trasformazione e `u=(2,1)` un vettore assegnato.
`ApplicaMatrice(M,u)` restituisce il vettore _u'=(-1,2)_, che è l'immagine di _u_ nella rotazione in senso antiorario di
90°.

====

[NOTE]
====

Questo comando è applicabile anche alle quadriche e alle xref:/tools/Strumento_Immagine.adoc[immagini]: se il
determinante della matrice della trasformazione è 0, il comando restituisce "non definito".

====
