= Comando ValoreFuturo

ValoreFuturo(Tasso, Numero periodi, Pagamento, Valore attuale (facoltativo), Tipo (facoltativo))::
  Restituisce il valore futuro di un investimento basato su pagamenti periodici costanti e tasso di interesse costante.

* *Tasso*: tasso di interesse per periodo.
* *Numero periodi*: numero totale di periodi di pagamento annuali.
* *Pagamento*: ammontare pagato in ciascun periodo.
* *Valore attuale (facoltativo)*: valore attuale di una serie di pagamenti futuri. Se non viene inserito alcun valore,
tale variabile sarà posta uguale a 0.
* *Tipo (facoltativo)*: indica le scadenze dei pagamenti. Se non viene inserito un valore o si inserisce 0, il pagamento
si intende effettuato al termine del periodo; se si inserisce 1 il pagamento si intende effettuato all'inizio del
periodo.

[EXAMPLE]
====

`++ValoreFuturo(10%/12, 15, -200, 0, 1)++` restituisce un valore futuro di 3207.99.

====

[NOTE]
====

Assicurarsi di utilizzare lo stesso tipo di unità per i parametri _Tasso_ e _Numero periodi_. Se si pianificano
pagamenti mensili per un prestito della durata di quattro anni a un interesse annuo del 10%, è necessario indicare quale
_Tasso_ il valore 10%/12 e quale _Numero periodi_ il valore 4*12.

====

[NOTE]
====

* In generale gli esborsi sono sempre indicati da numeri negativi, mentre gli introiti sono indicati da numeri positivi.
* Vedere anche i comandi xref:/commands/Comando_Rata.adoc[Rata], xref:/commands/Comando_Tasso.adoc[Tasso],
xref:/commands/Comando_ValoreAttuale.adoc[ValoreAttuale] e xref:/commands/Comando_NumeroRate.adoc[NumeroRate].

====
