= Comando FrazioneContinua

FrazioneContinua(Numero)::
  Genera la http://en.wikipedia.org/wiki/it:Frazione_continua[frazione continua] approssimante il numero indicato. Il
  risultato è un xref:/Testi.adoc[oggetto testo] LaTeX. La frazione viene calcolata tramite un algoritmo numerico, con
  precisione 10^-8^.
  +

[EXAMPLE]

====

`FrazioneContinua(5.45)` restituisce _stem:[5 + \frac\{1}\{ 2+ \frac\{1}\{4+ \frac\{1}\{ 1+ \frac\{1}\{ 1 } } } }]_
</math>

====

FrazioneContinua(Numero, Livello)::
  Genera la frazione continua approssimante il numero indicato. Il numero dei quozienti è minore o uguale a _Livello_,
  ma non supera mai il numero di quozienti necessari per raggiungere la precisione precedentemente indicata.
  +

[EXAMPLE]

====

`FrazioneContinua(5.45, 3)` restituisce _stem:[5 + \frac\{1}\{ 2+ \frac\{1}\{4+ ... } }]_

====

FrazioneContinua(Numero, Livello (facoltativo), Abbreviata true|false)::
  I primi due parametri utilizzano le precedenti sintassi. Quando _Abbreviata_ è _true_, il risultato sarà espresso in
  forma abbreviata: il testo LaTeX conterrà l'elenco delle parti intere della frazione continua.
  +

[EXAMPLE]

====

*Esempi:*

* `FrazioneContinua(5.45, true)` restituisce [5; 2, 4, 1, 1]
* `FrazioneContinua(5.45, 3, true)` restituisce [5; 2, 4, ...]

====
