= Comando ValoreAttuale

ValoreAttuale(Tasso, Numero periodi, Pagamento, Valore futuro (facoltativo), Tipo (facoltativo))::
  Restituisce il valore attuale di un investimento basato su pagamenti periodici costanti e tasso di interesse costante.

* *Tasso*: tasso di interesse per periodo.
* *Numero periodi*: numero totale di periodi di pagamento annuali.
* *Pagamento*: ammontare pagato in ciascun periodo.
* *Valore futuro (facoltativo)*: saldo che si desidera ottenere dopo l'ultimo pagamento. Se non viene inserito alcun
valore, tale variabile sarà posta uguale a 0.
* *Tipo (facoltativo)*: indica le scadenze dei pagamenti. Se non viene inserito un valore o si inserisce 0, il pagamento
si intende effettuato al termine del periodo; se si inserisce 1 il pagamento si intende effettuato all'inizio del
periodo.

[EXAMPLE]
====

`++ValoreAttuale(12%/12, 4*12, -100, 5000, 0)++` restituisce un valore attuale di 696.06.
`++ValoreAttuale(12%/12, 4*12, -100, 5000, 1)++` restituisce un valore attuale di 734.07.

====

[NOTE]
====

Assicurarsi di utilizzare lo stesso tipo di unità per i parametri _Tasso_ e _Numero periodi_. Se si pianificano
pagamenti mensili per un prestito della durata di quattro anni a un interesse annuo del 12%, è necessario indicare quale
_Tasso_ il valore 12%/12 e quale _Numero periodi_ il valore 4*12.

====

[NOTE]
====

* In generale gli esborsi sono sempre indicati da numeri negativi, mentre gli introiti sono indicati da numeri positivi.
* Vedere anche i comandi xref:/commands/Comando_Rata.adoc[Rata], xref:/commands/Comando_Tasso.adoc[Tasso],
xref:/commands/Comando_ValoreFuturo.adoc[ValoreFuturo] e xref:/commands/Comando_NumeroRate.adoc[NumeroRate].

====
