= Comando RisolviNEDO

RisolviNEDO(Lista derivate, Ascissa iniziale, Lista ordinate iniziali, Ascissa finale)::
  Risolve numericamente il sistema di equazioni differenziali indicato.

[EXAMPLE]
====

Siano _f'(t, f, g, h) = g_,     _g'(t, f, g, h) = h_    e    _h'(t, f, g, h) = -t h + 3t g + 2f + t_

`++RisolviNEDO({f', g', h'}, 0, {1,2,-2}, 10)++`

`++RisolviNEDO({f', g', h'}, 0, {1,2,-2}, -5)++`.

====

[EXAMPLE]
====

Siano _x1'(t, x1, x2, x3, x4) = x2_,    _x2'(t, x1, x2, x3, x4) = x3_,    _x3'(t, x1, x2, x3, x4) = x4_,     e   
_x4'(t, x1, x2, x3, x4) = -8x1 + sin(t) x2 - 3x3 + t^2_.

Siano inoltre _x10 = -0.4_,    _x20 = -0.3_,    _x30 = 1.8_    e    _x40 = -1.5_

`++RisolviNEDO({x1', x2', x3', x4'}, 0, {x10, x20, x30, x40}, 20)++`

====

[EXAMPLE]
====

Simulazione di un pendolo:

Siano _g = 9.8_,   _l = 2_,   _a = 5_ la posizione iniziale   e   _b = 3_ la forza iniziale.

Siano inoltre _y1'(t, y1, y2) = y2_   e   _y2'(t, y1, y2) = (-g) / l sin(y1)_

`++RisolviNEDO({y1', y2'}, 0, {a, b}, 20) ++`

`++lun = Lunghezza(IntegraleNumerico1) ++`

`++c = Slider(0, 1, 1 / lun, 1, 100, false, true, true, false) ++`

`++x1 = l sin(y(Punto(IntegraleNumerico1, c))) ++`

`++y1 = -l cos(y(Punto(IntegraleNumerico1, c))) ++`

`++A = (x1, y1) ++`

`++Segmento((0, 0), A)++`

`++AvviaAnimazione()++`

====

[NOTE]
====

Vedere anche i comandi xref:/commands/Comando_CampoDirezioni.adoc[CampoDirezioni] e
xref:/commands/Comando_RisolviEDO.adoc[RisolviEDO].

====
