= Comando SoluzioniC

== [#Sintassi_CAS]#Sintassi CAS#

SoluzioniC(Equazione)::
  Risolve l'equazione indicata rispetto alla variabile principale e restituisce la lista di tutte le soluzioni nel campo
  complesso.

[EXAMPLE]
====

`SoluzioniC(x^2=-1)` restituisce _\{ί, -ί}_.

====

SoluzioniC(Equazione, Variabile)::
  Risolve l'equazione rispetto alla variabile indicata e restituisce la lista di tutte le soluzioni nel campo complesso.

[EXAMPLE]
====

`SoluzioniC(a^2=-1, a)` restituisce _\{ί, -ί}_.

====

SoluzioniC(Lista di equazioni, Lista di variabili)::
  Risolve un sistema di equazioni rispetto alle variabili indicate e restituisce la lista di tutte le soluzioni nel
  campo complesso.

[EXAMPLE]
====

`SoluzioniC({y^2 = x- 1, x = 2 * y - 1}, {x, y})` restituisce stem:[\begin\{pmatrix}1 + 2 ί&1 + ί\\1 - 2 ί&1 -
ί\end\{pmatrix}].

====

[NOTE]
====

* Per ottenere l'unità immaginaria ί premere [.kcode]#ALT # + [.kcode]# i#.
* Vedere anche il xref:/commands/Comando_RisolviC.adoc[comando RisolviC] e il
xref:/commands/Comando_Soluzioni.adoc[comando Soluzioni].

====
