= Comando Triangolare

Triangolare(Limite inferiore, Limite superiore, Moda, x)::
  Genera la funzione di distribuzione cumulativa di una
  http://en.wikipedia.org/wiki/it:Distribuzione_triangolare[distribuzione triangolare] avente i parametri di limite
  inferiore, superiore e moda indicati.

Triangolare(Limite inferiore, Limite superiore, Moda, x, Booleano Cumulativa)::
  Se _Cumulativa_ è _true_, genera la funzione di distribuzione cumulativa della distribuzione triangolare, altrimenti
  genera la funzione di densità di probabilità della distribuzione triangolare.

Triangolare(Limite inferiore, Limite superiore, Moda, Valore variabile)::
  Calcola il valore della funzione di distribuzione cumulativa della distribuzione triangolare in corrispondenza del
  valore della variabile _v_ indicato, cioè la probabilità _P(X ≤ v)_ dove _X_ è una variabile casuale con distribuzione
  triangolare avente parametri di limite inferiore, superiore e moda indicati.
  +

[EXAMPLE]
====

`Triangolare(0, 5, 2, 2)` restituisce _0.4_.

====

[NOTE]
====

Restituisce la probabilità relativa a un determinato valore di _x_ (cioè l'area sottesa dalla curva della distribuzione
triangolare alla sinistra dell'ascissa _x_ indicata).

====
