= Comando Semplifica

Semplifica(Funzione)::
  Semplifica, se possibile, i termini della funzione.
  +

[EXAMPLE]

====

`Semplifica(x+x+x)` restituisce la funzione _f(x) = 3x_.

====

Semplifica(Testo)::
  Semplifica, se possibile, espressioni di testo, rimuovendo ad esempio i termini negativi ridondanti
  +

[EXAMPLE]

====

Se _a = b = c = -1_ `Semplifica("f(x) = "+a+"x²+"+b+"x+"+c)` restituisce il testo _f(x)= -x^2^ - x - 1_.

====

[NOTE]

====

* Il xref:/commands/Comando_LaTeX.adoc[comando LaTeX] in genere produce risultati migliori ed è più intuitivo.
* Questo comando necessita del caricamento del CAS (Computer Algebra System), quindi potrebbe causare rallentamenti su
alcuni computer. In alternativa, conviene provare a utilizzare il comando
xref:/commands/Comando_Polinomio.adoc[Polinomio].

====

== [#Sintassi_CAS]#Sintassi CAS#

Semplifica(Funzione)::
  Semplifica, se possibile, i termini della funzione, che possono comprendere anche variabili non definite.
  +

[EXAMPLE]

====

*Esempi:*

* `Semplifica(3 * x + 4 * x + a * x)` restituisce ` a x + 7x`.
* `Assumi(x<2, Semplifica(sqrt(x-2sqrt(x-1))))` restituisce `-sqrt(abs(x - 1)) + 1`
* `Assumi(x>2, Semplifica(sqrt(x-2sqrt(x-1))))` restituisce `sqrt(x - 1) + 1`

====

[NOTE]

====

Vedere anche i comandi xref:/commands/Comando_Fattorizza.adoc[Fattorizza], xref:/commands/Comando_Assumi.adoc[Assumi],
xref:/commands/Comando_FrazioniParziali.adoc[FrazioniParziali], xref:/commands/Comando_Sviluppa.adoc[Sviluppa],
xref:/commands/Comando_Polinomio.adoc[Polinomio].

====
