= Comando AnalizzaFunzione

AnalizzaFunzione(Testo)::
  Analizza il testo contenente la definizione della funzione e crea la corrispondente link:/it/Funzioni[funzione].
  +

[EXAMPLE]

====

*Esempi:*

* ` AnalizzaFunzione("x^2")` crea la funzione _f_(_x_) = __x__^2^_._
* ` AnalizzaFunzione("t+2/t"})` crea la funzione _f_(_t_) = _t_ + 2/_t_.

====

AnalizzaFunzione(Funzione, Testo)::
  Analizza la stringa di testo e memorizza il risultato in una link:/it/Funzioni[funzione] _f_, che deve essere un
  oggetto link:/it/Oggetti_liberi,_dipendenti_e_ausiliari[libero] già definito prima di utilizzare il comando.
  +

[EXAMPLE]

====

*Esempio:* Definire ` f(x) = 3x² + 2` e ` testo1 = "f(x) = 3x + 1"`. Allora ` AnalizzaFunzione(f, testo1)` restituisce
_f(x) = 3x + 1_.

====

AnalizzaFunzione(Testo, Lista di variabili)::
  Analizza il testo contenente la definizione della funzione e crea la corrispondente link:/it/Funzioni[funzione] nelle
  variabili definite nella lista.
  +

[EXAMPLE]

====

*Esempio:* ` AnalizzaFunzione("2u+3v",{"u", "v"})` crea la funzione _a(u,v) = 2u + 3v_.

====

[NOTE]

====

*Note:* Vedere anche il comando link:/it/Comando_AnalizzaNumero[AnalizzaNumero].

====
