= Comando Min

Min(Numero, Numero)::
  Restituisce il minimo tra i due numeri indicati.
  +

[EXAMPLE]

====

`Min(12, 15)` restituisce _12_.

====

Min(Lista di numeri)::
  Restituisce il minimo tra i numeri della lista.
  +
  +

[EXAMPLE]

====

`Min({-2, 12, -23, 17, 15})` restituisce _-23_.

====

[NOTE]

====

Se gli argomenti sono oggetti non numerici, allora _Min_ considera i numeri associati a tali oggetti. Per esempio, se
_Lista1_ è una lista di segmenti, _Min_(_Lista1_) restituisce il segmento di minima lunghezza.

====

Min(Funzione, x iniziale, x finale)::
  Calcola (numericamente) il punto di minimo *locale* della funzione nell'intervallo dato. La funzione deve essere
  continua e avere un solo punto di minimo locale nell'intervallo (e nessun massimo locale).
  +

[EXAMPLE]

====

`Min(x^3+2x^2-1, -2, 0)` genera il punto (0, -1).

====

Min(Intervallo)::
  Restituisce l'estremo inferiore dell'intervallo.
  +
  +

[EXAMPLE]

====

`Min(2<x<3)` restituisce 2.

====

[NOTE]

====

Gli intervalli aperti vengono comunque considerati chiusi.

====

Min(Lista dati, Lista frequenze)::
  Restituisce il minimo della lista di dati rispetto alle corrispondenti frequenze.
  +

[EXAMPLE]

====

`Min({1, 2, 3, 4, 5}, {0, 3, 4, 2, 3})` restituisce 2, il minimo tra gli elementi della lista avente frequenza maggiore
di 0.

====

== [#Sintassi_CAS]#Sintassi CAS#

Min(Funzione, x iniziale, x finale)::
  A differenza della _Vista Algebra_, questa sintassi restituisce il minimo della funzione nell'intervallo indicato,
  inclusi gli estremi.
  +

[EXAMPLE]

====

* `Min(x^2,-1,2)` restituisce il punto _(0,0)_
* `Min(-x^2,-1,2)` restituisce il punto _(2,-4)_

====

[NOTE]

====

* Per determinare il minimo di due funzioni `f(x)` e `g(x)` utilizzare `(f(x) + g(x) - abs(f(x) - g(x)))/2`
* Vedere anche i comandi xref:/commands/Comando_Max.adoc[Max], xref:/commands/Comando_Estremo.adoc[Estremo] e lo
strumento xref:/tools/Strumento_Assistente_Funzioni.adoc[Assistente Funzioni].

====
