= Comando Limite

Limite(Funzione, Valore)::
  Calcola il http://en.wikipedia.org/wiki/it:Limite_di_una_funzione[limite] della funzione al tendere della variabile al
  valore indicato (anche infinito).
  +
  +

[EXAMPLE]

====

`Limite((x^2+x)/x^2, +∞)` restituisce _1_ .

====

[NOTE]

====

Non tutti i limiti possono essere calcolati da GeoGebra: in tali casi sarà visualizzato _"non definito"_ (come
pure nei casi in cui la funzione non ammette limite).

====

== [#Sintassi_CAS]#Sintassi CAS#

Limite(Espressione, Valore)::
  Calcola il limite dell'espressione, al tendere della variabile indipendente della funzione al valore indicato.
  +

[EXAMPLE]

====

`Limite(a sin(x)/x, 0)` restituisce _a_ .

====

Limite(Espressione, Variabile, Valore)::
  Calcola il limite dell'espressione, al tendere della variabile indicata al valore indicato.
  +

[EXAMPLE]

====

`Limite(a sin(v)/v, v, 0)` restituisce _a_ .

====

[NOTE]

====

* Non tutti i limiti possono essere calcolati da GeoGebra: in tali casi sarà visualizzato _?_ (come pure nei casi in cui
la funzione non ammette limite).
* Per calcolare i limiti di una xref:/commands/Comando_Se.adoc[funzione definita a tratti] è necessario utilizzare i
comandi xref:/commands/Comando_LimiteDestro.adoc[LimiteDestro] o
xref:/commands/Comando_LimiteSinistro.adoc[LimiteSinistro], ad esempio `LimiteDestro(Se(x>1, x^2, -2x), 1)`
* Vedere anche il xref:/commands/Comando_Asintoto.adoc[comando Asintoto], il
xref:/commands/Comando_LimiteDestro.adoc[comando LimiteDestro] e il xref:/commands/Comando_LimiteSinistro.adoc[comando
LimiteSinistro].

====
