= Comando DiagrammaTorta
:page-en: commands/PieChart
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

DiagrammaTorta(Lista di frequenze)::
  Crea un diagramma a torta utilizzando la lista di frequenze indicata. L'intera torta rappresenta il 100%, e i dati
  indicati saranno rappresentati come fette della torta.

[EXAMPLE]
====

`++DiagrammaTorta({20, 15, 40, 5, 10, 20})++` crea un diagramma a torta con centro nel punto (0,0) predefinito e raggio
3.

====

DiagrammaTorta(Lista di frequenze, Centro, Raggio)::
  Crea un diagramma a torta con centro e raggio specificati, utilizzando la lista di frequenze indicata. L'intera torta
  rappresenta il 100%, e i dati indicati saranno rappresentati come fette della torta.

[EXAMPLE]
====

`++DiagrammaTorta({20, 15, 40, 5, 10, 20},(3,3),5)++` crea un diagramma a torta con centro nel punto (3,3) e raggio 5.

====

[NOTE]
====

Utilizzare la scheda _Colore_ nella finestra di dialogo delle _Proprietà_ del diagramma a torta per personalizzare il
colore di ogni spicchio, e la scheda _Stile_ per scegliere uno stile di riempimento.

====
