= Comando DistribuzioneBeta
:page-en: commands/BetaDist
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

DistribuzioneBeta( Numero α, Numero β, Valore variabile v )::
  Calcola il valore della funzione di distribuzione cumulata (cdf) di una distribuzione beta con parametri _α, β_ in corrispondenza del valore della variabile _v_, che è la probabilità _P(X≤v)_ dove _X_ è una variabile casuale di una distribuzione beta di parametri _α_ e _β_

DistribuzioneBeta( Numero α, Numero β, Valore variabile v, Booleano Cumulata )::
  Se _Cumulata_ è _true_, calcola il valore della funzione di distribuzione cumulata di una distribuzione beta di parametri _α_ e _β_ in corrispondenza del valore della variabile _v_. Se _Cumulata_ è _false_, calcola il valore della funzione di densità di probabilità (pdf) della distribuzione beta corrispondente in _v_.


DistribuzioneBeta( Numero α, Numero β, x, Booleano Cumulata )::
  Se _Cumulata_ è _true_, crea la funzione di distribuzione cumulata di una distribuzione beta di parametri _α_ e _β_, altrimenti crea la funzione di densità di probabilità (pdf) della distribuzione beta corrispondente.

[NOTE]
====
Vedere anche il comando xref:/commands/BetaInversa.adoc[BetaInversa].
====
