= Comando Dodecaedro
:page-en: commands/Dodecahedron
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Dodecaedro(Punto, Punto, Oggetto)::
  Genera un dodecaedro avente per spigolo il segmento individuato dai due punti indicati.
  Gli altri vertici sono determinati univocamente da un _Oggetto_, che indica la _direzione_ di creazione, che può
  essere:
  * un vettore, un segmento, una retta o una semiretta, perpendicolari rispetto al segmento, oppure
  * un poligono o un piano, paralleli al segmento.
  Il dodecaedro così creato avrà:
  * una faccia avente come spigolo il segmento, in un piano perpendicolare al vettore/segmento/retta/semiretta indicato,
  oppure
  * una faccia avente come spigolo il segmento, in un piano parallelo a quello del poligono/piano indicato.

Dodecaedro(Punto, Punto, Punto)::
  Genera il dodecaedro avente i tre punti indicati come vertici della prima faccia. I punti devono formare un pentagono
  regolare, per fare in modo che il dodecaedro risulti definito.

Dodecaedro(Punto, Punto)::
  Genera il dodecaedro avente per spigolo della prima faccia il segmento il segmento individuato dai punti indicati,
  mentre il terzo vertice della faccia è individuato su una circonferenza, in modo che il dodecaedro possa ruotare
  attorno allo spigolo.

[NOTE]
====

`++Dodecaedro(A, B)++` è una sintassi abbreviata di `++Dodecaedro(A, B, C)++`, con
`++C = Punto(Circonferenza(((1 - sqrt(5)) A + (3 + sqrt(5)) B) / 4, Distanza(A, B) sqrt(10 + 2sqrt(5)) / 4, Segmento(A, B))).}}++`.

====

[NOTE]
====

Vedere anche i comandi xref:/commands/Cubo.adoc[Cubo], xref:/commands/Tetraedro.adoc[Tetraedro],
xref:/commands/Ottaedro.adoc[Ottaedro], xref:/commands/Icosaedro.adoc[Icosaedro].

====
