= Comando DS
:page-en: commands/SD
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

DS(Lista dati grezzi)::
  Calcola la https://it.wikipedia.org/Deviazione_standard[deviazione standard] dei valori della lista.

[NOTE]
====

Questo comando ha la sintassi equivalente `devstp(Lista dati grezzi)`.

====

[EXAMPLE]
====

* `++DS({1, 2, 3, 4, 5})++` restituisce _1.41_
* `++devstp({1, 2, 3, 4, 5})++` restituisce _1.41_


====

DS(Lista dati grezzi, Lista frequenze)::
  Calcola la deviazione standard pesata dei valori indicati.

[NOTE]
====

Questo comando ha la sintassi equivalente `devstp(Lista dati grezzi, Lista frequenze)`.

====

[EXAMPLE]
====

* `++DS({1, 2, 3, 4, 5}, {5, 4, 3, 2, 1})++` restituisce _1.25_
* `++devstp({1, 2, 3, 4, 5}, {5, 4, 3, 2, 1})++` restituisce _1.25_

====

== Sintassi CAS

DS(Lista dati grezzi)::
  Calcola la deviazione standard dei valori indicati.

[NOTE]
====

Questo comando ha la sintassi equivalente `devstp(Lista dati grezzi)`.

====

[EXAMPLE]
====

* `++DS({1, 2, 3, 4, 5})++` restituisce stem:[\sqrt{2}].
* `++devstp({1, 2, 3, 4, 5})++` restituisce stem:[\sqrt{2}].
* `++DS({-3 + 2 x, -1- 4 x, -2 + 5 x^2})++` restituisce il xref:/tools/Calcola.adoc[risultato simbolico] stem:[
\sqrt{2} \frac{\sqrt{25x⁴ + 10x³ + 28x² - 18x + 3} }{ 3 } ]

====

DS(Lista dati grezzi, Lista frequenze)::
  Calcola la deviazione standard pesata dei valori indicati.

[NOTE]
====

Questo comando ha la sintassi equivalente `devstp(Lista dati grezzi, Lista frequenze)`.

====

[EXAMPLE]
====

* `++DS({1, 2, 3, 4, 5}, {5, 4, 3, 2, 1})++` restituisce stem:[\frac{\sqrt{14}}{3}]
* `++devstp({1, 2, 3, 4, 5}, {5, 4, 3, 2, 1})++` restituisce stem:[\frac{\sqrt{14}}{3}]

====

[NOTE]
====

Vedere anche il xref:/commands/Media.adoc[comando Media].

====
