= Comando Esegui
:page-en: commands/Execute
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

[NOTE]
====

I nomi dei comandi elencati nella lista da eseguire devono essere sempre *in Inglese (US)*, anche se l'interfaccia di GeoGebra è in una lingua diversa.

====

Esegui(Lista di testi)::
  Esegue la lista di comandi, elencati in una lista di testi.

[EXAMPLE]
====

*Esempi:*

* `++Esegui({"A=(1,1)","B=(3,3)","C=MidPoint(A,B)"})++` genera i punti _A, B_ e il loro punto medio _C_.
* `++Esegui(Join({"f_{1}=1","f_{2}=1"}, Sequence("f_{"+(i+2)+"}=f_{"+(i+1)+"}+f_{"+i+"}",i,1,10)))++` genera i primi 10
elementi della http://en.wikipedia.org/wiki/it:_Successione_di_Fibonacci[successione di Fibonacci].

====

Esegui(Lista di testi, Parametro,...., Parametro)::
  Utilizzare i segnaposto %1, %2 e così via come argomenti dei comandi elencati nella lista. Tali segnaposto verranno sostituiti con i parametri elencati nel comando, seguendo l'ordine di elencazione. È possibile specificare fino a 9 parametri. Dopo le sostituzioni, verranno eseguiti gli script risultanti.
 

[EXAMPLE]
====

`++Esegui({"Segment(%1,%2)","Midpoint(%1,%2)"}, A, B)++` genera il segmento _AB_ e il suo punto medio.

====

[NOTE]
====

Se la tastiera in uso non ha il tasto delle virgolette (`++"++`), utilizzare la tastiera virtuale di GeoGebra o il comando  `++UnicodeInLettera(34)++`.

====
