= Comando Esponenziale
:page-en: commands/Exponential
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Esponenziale(Parametro, x)::
  Genera la funzione di distribuzione cumulativa di una
  http://en.wikipedia.org/wiki/it:Distribuzione_esponenziale[distribuzione esponenziale] di parametro λ indicato.

Esponenziale(Parametro, x, Booleano Cumulativa)::
  Se _Cumulativa_ è _true_, genera la funzione di distribuzione cumulativa della distribuzione esponenziale, altrimenti
  genera la funzione di densità di probabilità della distribuzione esponenziale.

Esponenziale(Parametro, Valore variabile)::
  Calcola il valore della funzione di distribuzione cumulativa della distribuzione esponenziale in corrispondenza del
  valore della variabile _v_, cioè la probabilità _P(X ≤ v)_ dove _X_ è una variabile casuale con distribuzione
  esponenziale di parametro indicato λ.

[NOTE]
====

Restituisce la probabilità relativa a un determinato valore di _x_ (ovvero l'area sottesa dalla curva della
distribuzione esponenziale alla sinistra dell'ascissa _x_ indicata).

====

== Sintassi CAS

Esponenziale(Parametro, Valore variabile)::
  Calcola il valore della funzione di distribuzione cumulativa della distribuzione esponenziale in corrispondenza del
  valore della variabile _v_, cioè la probabilità _P(X ≤ v)_ dove _X_ è una variabile casuale con distribuzione
  esponenziale di parametro indicato λ.

[EXAMPLE]
====

`++Esponenziale(2, 1)++` restituisce _stem:[1 - \frac\{1}\{e^\{2} } ]_, che vale circa _0.86_.

====
