= Comando FattorizzaI
:page-en: commands/IFactor
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

FattorizzaI(Polinomio)::
  Fattorizza il polinomio in termini con coefficienti irrazionali reali.

[EXAMPLE]
====

`++FattorizzaI(x^2 + x - 1)++` restituisce stem:[ \left( x + \frac{-\sqrt{5} + 1}\{2} \right) \left( x +
\frac{\sqrt{5} + 1}\{2} \right)]

====

== Sintassi CAS

FattorizzaI(Polinomio)::
  Fattorizza il polinomio in termini con coefficienti irrazionali reali.

[EXAMPLE]
====

`++FattorizzaI(x^2 + x - 1)++` restituisce stem:[ \left( x + \frac{-\sqrt{5} + 1}\{2} \right) \left( x +
\frac{\sqrt{5} + 1}\{2} \right)]

====

FattorizzaI(Polinomio, Variabile)::
  Fattorizza il polinomio in termini con coefficienti irrazionali reali, rispetto alla variabile indicata.

[EXAMPLE]
====

`++FattorizzaI(a^2 + a - 1, a)++` restituisce stem:[ \left( a + \frac{-\sqrt{5} + 1}\{2} \right) \left( a +
\frac{\sqrt{5} + 1}\{2} \right)]

====

[NOTE]
====

Vedere anche il comando xref:/commands/FattorizzaCI.adoc[FattorizzaCI].

====
