= Comando Gamma
:page-en: commands/Gamma
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Gamma(Alfa, Beta, Valore variabile)::
  Calcola il valore della funzione di distribuzione cumulata di una https://it.wikipedia.org/Distribuzione_Gamma[distribuzione Gamma] in corrispondenza del _valore variabile v_ specificato, cioè calcola la probabilità _P(X≤v)_ dove _X_ è una variabile casuale con distribuzione Gamma con parametri _alfa_ e _beta_ indicati.

[NOTE]
====

Questa sintassi restituisce la probabilità relativa al valore indicato della variabile, che è l'area sottesa dalla curva della distribuzione Gamma alla sinistra dell'ascissa indicata.

====

Gamma(Alfa, Beta, Valore variabile, Booleano Cumulata)::
 Se _Cumulata_ è _true_, calcola il valore della funzione di distribuzione cumulata di una distribuzione Gamma con parametri _alfa_ e _beta_ in corrispondenza del _valore variabile_, altrimenti calcola il valore della funzione densità di probabilità di una distribuzione Gamma con parametri _alfa_ e _beta_ indicati in corrispondenza del _valore variabile_.

Gamma(Alfa, Beta, x, Booleano Cumulata)::
 Se _Cumulata_ è _true_, genera la funzione di distribuzione cumulata di una distribuzione Gamma, altrimenti genera la funzione densità di probabilità di una distribuzione Gamma di parametri _alfa_ e _beta_ indicati.
