= Comando Inviluppo
:page-en: commands/Envelope
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Inviluppo(Cammino, Punto)::

Genera l'equazione dell'https://it.wikipedia.org/wiki/Inviluppo_%28matematica%29[inviluppo] di un insieme di cammini, al
variare della posizione di un punto su un vincolo. L'inviluppo di una famiglia di curve è un insieme di curve, tangenti
a ciascun elemento della famiglia in un punto.

[EXAMPLE]
====

http://www.geogebra.org/student/m67909[Una scala è appoggiata a un muro e scivola verso il basso]. La famiglia di curve
tangenti in ogni punto alla scala durante il suo movimento è l'inviluppo della scala. In pratica, GeoGebra calcola
l'inviluppo di tutta la retta contenente il segmento che identifica la scala. In generale GeoGebra riesce a calcolare
solo inviluppi la cui costruzione genera un sistema di equazioni algebriche.

====

[NOTE]
====

Vedere anche i comandi xref:/commands/Luogo.adoc[Luogo], xref:/commands/EquazioneLuogo.adoc[EquazioneLuogo] e https://github.com/kovzol/gg-art-doc/tree/master/pdf/english.pdf[GeoGebra Automated Reasoning Tools: A Tutorial].

====
