= Comando IterazioneLista

IterazioneLista(Funzione, Valore iniziale, Numero di iterazioni)::
  Genera una lista di lunghezza _n+1_ (con _n_ = numero di iterazioni) i cui elementi sono le iterazioni della funzione
  a partire dal valore iniziale indicato.
  +
  +
  È inoltre possibile utilizzare questo comando per definire una successione, in cui _a~k+1~_ dipende da _a~k~_ e _k_.
  Se la funzione _f_ inserita è in due variabili e il valore iniziale è una lista di due numeri _\{s, a~s~}_, allora la
  lista restituita contiene i numeri _a~s~_,_a~s+1~_,....,_a~s+n~_ in cui, per _k > s_ si ha _a~k+1~=f(k, a~k~)_.

[EXAMPLE]
====

Sia `++f(k,a)=(k+1)*a++`, che è la definizione ricorsiva del fattoriale. Il comando `++IterazioneLista(f, {3, 6}, 4)++`
restituisce la lista _\{6, 24, 120, 720, 5040}_.

====

[EXAMPLE]
====

Sia `++f(x) = x^2++`: il comando `++IterazioneLista(f, 3, 2)++` genera la lista _L = \{3, 9, 81}_.

====

IterazioneLista(Espressione, Nome variabile, ..., Valori iniziali, Numero di iterazioni)::
  Genera una lista di lunghezza _n+1_ (con _n_ = numero di iterazioni) i cui elementi sono le iterazioni
  dell'espressione a partire dai valori iniziali indicati. In ogni iterazione le variabili dell'espressione vengono
  sostituite con gli ultimi elementi della lista. Per ottenere un risultato definito, il numero dei _valori iniziali_
  deve essere almeno uguale al numero delle variabili.

[EXAMPLE]
====

Siano _A_, _B_ due punti. Il comando `++IterazioneLista(PuntoMedio(A, C), C, {B}, 3)++` calcola internamente i valori
__C__~0~ = _B_,   __C__~1~ = _PuntoMedio_(_A_, __C__~0~),   __C__~2~ = _PuntoMedio_(_A_, __C__~1~),   __C__~3~ =
_PuntoMedio_(_A_, __C__~2~) e restituisce \{__C__~0~, __C__~1~, __C__~2~, __C__~3~}. Se quindi _A_ = (0,0) e _B_ = (8,0)
il risultato sarà \{(8,0), (4,0), (2,0), (1,0)}.

====

[EXAMPLE]
====

Siano _f__0, _f__1 due numeri. Il comando `++IterazioneLista(a + b, a, b, {f_0,f_1}, 5)++` calcola i primi 2 valori
della lista risultante a partire dai valori iniziali indicati. I valori successivi vengono calcolati come segue:
__f__~2~ = __f__~0~ + __f__~1~   __f__~3~ = __f__~1~ + __f__~2~,   __f__~4~ = __f__~2~ + __f__~3~,   __f__~5~ = __f__~3~
+ __f__~4~. Se quindi _f__0 = _f__1 = 1 il risultato sarà \{1, 1, 2, 3, 5, 8}.

====

[NOTE]
====

* Solo la prima sintassi è al momento supportata nella vista CAS
* Vedere anche il comando xref:/commands/Iterazione.adoc[Iterazione].

====
