= Comando LaTeX
:page-en: commands/FormulaText
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

LaTeX(Oggetto)::
  Restituisce la formula relativa all'oggetto in formato testo LaTeX.

[EXAMPLE]
====

*Esempi:*

* Se _a = 2_ e _f(x) = a x^2^_, allora `++LaTeX(f)++` restituisce _2 x^2^_ (in formato testo LaTeX).
* `++LaTeX($1)++` restituisce il contenuto della riga 1 della xref:/Vista_CAS.adoc[vista CAS] in formato testo LaTeX.

====

[NOTE]
====

Per impostazione predefinita, le variabili sono sostituite con i rispettivi valori.

====

LaTeX(Oggetto, Booleano)::
  Restituisce la formula relativa all'oggetto in formato testo LaTeX. Il valore booleano indica se le variabili devono
  essere sostituite con i rispettivi valori (_true_) o se devono essere visualizzate nel testo (_false_).

[EXAMPLE]
====

Se _a = 2_ e _f(x) = a x^2^_, allora `++LaTeX(f, true)++` restituisce _2 x^2^_ (come testo LaTeX), mentre
`++LaTeX(f, false)++` restituisce _a x^2^_ (come testo LaTeX).

====

LaTeX(Oggetto, Booleano per la sostituzione delle variabili, Booleano Mostra nome)::
  Restituisce la formula relativa all'oggetto in formato testo LaTeX. Il primo valore booleano indica se le variabili
  devono essere sostituite con i rispettivi valori (_true_) o se devono essere visualizzate nel testo (_false_), il
  secondo indica se il nome dell'oggetto deve essere visualizzato nel testo (_true_) oppure no (_false_).

[EXAMPLE]
====

Se _a = 2_ e _f(x) = a x^2^_, allora `++LaTeX(f, true, true)++` restituisce _f(x)=2 x^2^_ (come testo LaTeX), mentre
`++LaTeX(f, false, false)++` restituisce _a x^2^_ (come testo _LaTeX_).

====
