= Comando LimiteDestro
:page-en: commands/LimitAbove
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

LimiteDestro(Funzione, Valore)::
  Calcola il
  http://en.wikipedia.org/wiki/it:_Limite_di_una_funzione#Limite_destro.2C_sinistro.2C_per_eccesso.2C_per_difetto[limite
  destro] della _funzione_ quando la variabile tende al _valore_ indicato.

[EXAMPLE]
====

`++LimiteDestro(1/x, 0)++` restituisce stem:[\infty] .

====

[NOTE]
====

Non tutti i limiti possono essere calcolati da GeoGebra: in tali casi sarà visualizzato _"non definito"_ (come pure nei
casi in cui il calcolo è corretto e la funzione non ammette limite).

====

== Sintassi CAS

LimiteDestro(Espressione, Valore)::
  Calcola il limite destro della funzione, al tendere della variabile indipendente della funzione al valore indicato.

[EXAMPLE]
====

`++LimiteDestro(1/x, 0)++` restituisce stem:[\infty] .

====

LimiteDestro(Espressione, Variabile, Valore)::
  Calcola il limite destro della funzione in più variabili, al tendere della _variabile_ al _valore_ indicato.

[EXAMPLE]
====

`++LimiteDestro(1/a, a, 0)++` restituisce stem:[\infty] .

====


[NOTE]
====

* Non tutti i limiti possono essere calcolati da GeoGebra: in tali casi sarà visualizzato _?_ (come pure nei casi in cui
il calcolo è corretto e la funzione non ammette limite).
* Vedere anche il xref:/commands/Limite.adoc[comando Limite] e il xref:/commands/LimiteSinistro.adoc[comando
LimiteSinistro].

====
