= Comando Logistica
:page-en: commands/Logistic
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Logistica(Media, Scala, x)::
  Genera la funzione di distribuzione cumulativa di una
  http://en.wikipedia.org/wiki/it:Distribuzione_logistica[distribuzione logistica] di media e scala indicate.
Logistica(Media, Scala, x, Booleano Cumulativa)::
  Se _Cumulativa_ è _true_, genera la funzione di distribuzione cumulativa della distribuzione logistica; in caso
  contrario genera la funzione di densità di probabilità della distribuzione logistica.
Logistica(Media, Scala, Valore variabile)::
  Calcola il valore della funzione di distribuzione cumulativa della distribuzione logistica in corrispondenza del
  valore _v_ indicato della variabile, cioè la probabilità _P(X ≤ v)_ dove _X_ è una variabile casuale logistica avente
  le date media e scala.

[NOTE]
====

Restituisce la probabilità relativa a un determinato valore di _x_ (ovvero l'area sottesa dalla curva della
distribuzione logistica alla sinistra dell'ascissa _x_ indicata).

====
