= Comando Logistica
:page-en: commands/Logistic
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Logistica(Media, Scala, Valore variabile)::
  Calcola il valore della funzione di distribuzione cumulata di una distribuzione logistica in corrispondenza del _valore variabile v_ specificato, cioè calcola la probabilità _P(X≤v)_ dove _X_ è una variabile casuale con distribuzione logistica con parametri _media_ e _scala_ indicati.

[NOTE]
====

Questa sintassi restituisce la probabilità relativa al valore indicato della variabile, che è l'area sottesa dalla curva della distribuzione logistica alla sinistra dell'ascissa indicata.
====
Logistica(Media, Scala, Valore variabile, Booleano Cumulata)::
  Se _Cumulata_ è _true_, calcola il valore della funzione di distribuzione cumulata di una distribuzione logistica con _media_ e _scala_ indicate in corrispondenza del _valore variabile_, altrimenti calcola il valore della funzione densità di probabilità di una distribuzione logistica di parametri _media_ e _scala_ indicati in corrispondenza del _valore variabile_.

Logistica(Media, Scala, x, Booleano Cumulata)::
  Se _Cumulata_ è _true_, genera la funzione di distribuzione cumulata di una distribuzione logistica, altrimenti genera la funzione densità di probabilità di una distribuzione logistica avente i parametri _media_ e _scala_ indicati.
