= Comando NumeroRate

NumeroRate(Tasso, Pagamento, Valore attuale (facoltativo), Valore futuro (facoltativo), Tipo (facoltativo))::
  Restituisce il numero di rate di un investimento a pagamenti periodici e costanti e tasso di interesse costante.

* *Tasso*: tasso di interesse per periodo.
* *Pagamento*: ammontare pagato in ciascun periodo.
* *Valore attuale (facoltativo)*: valore attuale o ammontare del valore attuale di una serie di pagamenti futuri.
* *Valore futuro (facoltativo)*: saldo che si desidera ottenere dopo l'ultimo pagamento. Se non viene inserito alcun
valore, tale variabile sarà posta uguale a 0.
* *Tipo (facoltativo)*: indica le scadenze dei pagamenti. Se non viene inserito un valore o si inserisce 0, il pagamento
si intende effettuato al termine del periodo; se si inserisce 1 il pagamento si intende effettuato all'inizio del
periodo.

[EXAMPLE]
====

`++NumeroRate(10%/12, -200, -400, 10000)++` restituisce 39.98 pagamenti. `++NumeroRate(10%/12, -200, -400, 10000, 1)++`
restituisce 39.7 pagamenti.

====

[NOTE]
====

Assicurarsi di suddividere il _Tasso_ su base annua. Se si pianificano pagamenti mensili a un interesse annuo del 10%, è
necessario indicare quale _Tasso_ il valore 10%/12.

====

[NOTE]
====

* In generale gli esborsi sono sempre indicati da numeri negativi, mentre gli introiti sono indicati da numeri positivi.
* Vedere anche i comandi xref:/commands/Rata.adoc[Rata], xref:/commands/Tasso.adoc[Tasso],
xref:/commands/ValoreFuturo.adoc[ValoreFuturo] e xref:/commands/ValoreAttuale.adoc[ValoreAttuale].

====
