= Comando Prodotto
:page-en: commands/Product
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Prodotto(Lista di numeri)::
  Calcola il prodotto di tutti i numeri della lista.
Prodotto(Lista di numeri, Numero di elementi)::
  Calcola il prodotto dei primi _n_ numeri della lista.
Prodotto(Lista di numeri,Lista di frequenze)::
  Calcola il prodotto di tutti gli elementi della lista, rispettivamente elevati ai valori indicati nella _lista di
  frequenze_ .

[EXAMPLE]
====

*Esempi:* `++Prodotto({20, 40, 50, 60}, {4, 3, 2, 1})++` restituisce
__1536000000000000__`++Prodotto({sqrt(2), cbrt(3), sqrt(5), cbrt(-7)}, {4, 3, 2, 3})++` restituisce _-420_

====

[EXAMPLE]
====

`++Prodotto({1, 2, 3, 4}, 3)++` restituisce _6_.

====

[EXAMPLE]
====

`++Prodotto({2, 5, 8})++` restituisce _80_.

====

[NOTE]
====

Le due liste devono avere la stessa lunghezza.

====

== Sintassi CAS

La seguente sintassi è utilizzabile esclusivamente nella xref:/Vista_CAS.adoc[Vista CAS]:

Prodotto(Lista di espressioni)::
  Calcola il prodotto di tutti gli elementi della lista.
Prodotto(Espressione, Variabile, Da, A)::
  Calcola il prodotto delle espressioni ottenute sostituendo la variabile con tutti gli interi compresi tra _Da_ e _A_.

[EXAMPLE]
====

`++Prodotto(x + 1,  x,  2, 3)++` restituisce _12_.

====

[EXAMPLE]
====

`++Prodotto({1, 2, x})++` restituisce _2x_.

====
