= Comando Relazione

Relazione(Lista)::
  Visualizza un messaggio che fornisce informazioni relative alla relazione tra due o più oggetti (massimo 4).
Relazione(Oggetto, Oggetto)::
  Visualizza un messaggio che fornisce informazioni relative alla relazione tra i due oggetti indicati.

Questo comando consente di verificare se:

* due rette sono perpendicolari
* due rette sono parallele
* due (o più) oggetti sono uguali
* un punto giace su una retta o su una conica
* una retta è tangente o secante a una conica
* tre punti sono allineati
* tre rette sono incidenti (o parallele)
* quattro punti sono conciclici (o allineati).

Alcune di queste relazioni possono essere verificate anche simbolicamente. Se GeoGebra consente un confronto di tipo
simbolico, viene visualizzato il pulsante "Altro": facendo clic su di esso GeoGebra può inoltre fornire ulteriori
informazioni relative alla validità della relazione in generale (eventualmente secondo determinate condizioni).

[NOTE]
====

Vedere anche lo strumento xref:/tools/Relazione.adoc[Relazione].

====
