= Comando TestChiQuadro
:page-en: commands/ChiSquaredTest
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

TestChiQuadro(Matrice dei valori osservati)::
  Applica un http://en.wikipedia.org/wiki/it:_Test_chi_quadrato[Test Chi Quadro] che confronta la matrice indicata dei
  valori osservati e la matrice dei valori (teorici) attesi, sotto un'ipotesi di indipendenza.
  La matrice dei valori attesi viene calcolata internamente: ciascun valore atteso è calcolato a partire dai totali di
  riga e colonna della matrice indicata, applicando la regola:
  stem:[ \text\{valore atteso} = \frac{\text\{totale riga} × \text\{totale colonna}}\{\text\{totale valori osservati}}
  ]

I risultati sono restituiti in una lista del tipo \{http://en.wikipedia.org/wiki/it:_Valore_p[Probabilità], statistica
test Chi Quadro}.

[EXAMPLE]
====

`++TestChiQuadro({{1, 2, 1}, {3, 2, 3}})++` restituisce _\{0.69, 0.75}_.

====

TestChiQuadro(Lista dei valori osservati, Lista dei valori attesi)::
  Applica un test di verifica della bontà del modello che confronta la lista dei valori osservati e quella dei valori
  attesi. I risultati sono restituiti in una lista del tipo \{Probabilità, statistica test Chi Quadro}.

[EXAMPLE]
====

`++TestChiQuadro({1, 2, 3, 4}, {3, 2, 4, 2})++` restituisce _\{0.31, 3.58}_.

====

TestChiQuadro(Matrice dei valori osservati, Matrice dei valori attesi)::
  Applica un http://en.wikipedia.org/wiki/it:_Test_chi_quadrato[Test Chi Quadro] che confronta la matrice dei valori
  osservati e la matrice dei valori (teorici) attesi indicate. I risultati sono restituiti in una lista del tipo
  \{Probabilità, statistica test Chi Quadro}.

[EXAMPLE]
====

`++TestChiQuadro({{1, 2, 1}, {3, 2, 3}}, {{2, 3, 2}, {4, 2, 3}})++` restituisce _\{0.45, 1.58}_.

====
