= Comando TestCongruenza
:page-en: commands/AreCongruent
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

TestCongruenza(Oggetto, Oggetto)::
  Decide se i due oggetti sono congruenti.

In generale questo comando determina il risultato numericamente. Tale comportamento può essere modificato utilizzando il
comando xref:/commands/Verifica.adoc[Verifica].

[EXAMPLE]
====

I comandi `++TestCongruenza(Circonferenza((0, 0),1),x^2+y^2=1)++` e
`++TestCongruenza(Circonferenza((1, 1),1), x^2+y^2=1)++` restituiscono _true_, in quanto le due circonferenze hanno lo
stesso raggio.

====

[NOTE]
====

Vedere anche i comandi xref:/commands/TestUguaglianza.adoc[TestUguaglianza],
xref:/commands/TestAllineamento.adoc[TestAllineamento], xref:/commands/TestConciclici.adoc[TestConciclici],
xref:/commands/TestIncidenza.adoc[TestIncidenza], xref:/commands/TestPerpendicolarità.adoc[TestPerpendicolarità],
xref:/commands/TestParallelismo.adoc[TestParallelismo], xref:/commands/TestTangenza.adoc[TestTangenza].

====
