= Comando TestIncidenza
:page-en: commands/AreConcurrent
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

TestIncidenza(Retta, Retta, Retta)::
  Decide se le tre rette sono incidenti. Se le rette sono parallele tra loro, si assume che abbiano un punto di
  intersezione all'infinito, quindi anche in questo caso il comando restituisce _true_.

Questo comando calcola il risultato mediante tecniche numeriche, ma tale procedura può essere modificata utilizzando il
comando xref:/commands/Verifica.adoc[Verifica].

[EXAMPLE]
====

`++TestIncidenza(Retta((1, 2), (3, 4)), Retta((1, 2), (3, 5)), Retta((1, 2), (3, 6)))++` restituisce _true_, in quanto
le tre rette indicate contengono il punto (1,2).

====

[NOTE]
====

Vedere anche i comandi xref:/commands/TestAllineamento.adoc[TestAllineamento],
xref:/commands/TestConciclici.adoc[TestConciclici], xref:/commands/TestUguaglianza.adoc[TestUguaglianza],
xref:/commands/TestPerpendicolarità.adoc[TestPerpendicolarità], xref:/commands/TestParallelismo.adoc[TestParallelismo],
xref:/commands/TestTangenza.adoc[TestTangenza].

====
