= Comando TestChiQuadro
:page-en: commands/ChiSquaredTest
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

TestChiQuadro(Matrice)::
  Applica un https://it.wikipedia.org/_Test_chi_quadrato[Test Chi Quadro] che confronta la matrice indicata dei
  valori osservati e la matrice dei valori (teorici) attesi definita dall'ipotesi di indipendenza.
  La matrice dei valori attesi viene calcolata internamente: ciascun valore atteso è calcolato a partire dai totali di
  riga e colonna della matrice indicata, applicando la regola:
  stem:[ \text{valore atteso} = \frac{\text{totale riga} × \text{totale colonna}}{\text{totale valori osservati}}
  ]

I risultati sono restituiti in una lista del tipo { https://it.wikipedia.org/wiki/Valore_p[Probabilità], statistica
test Chi Quadro}.

[EXAMPLE]
====

`++TestChiQuadro({{1, 2, 1}, {3, 2, 3}})++` restituisce _{0.69, 0.75}_.

====

TestChiQuadro(Lista dei valori osservati, Lista dei valori attesi)::
  Applica un test di verifica della bontà del modello che confronta la lista dei valori osservati e quella dei valori
  attesi. La probabilità viene calcolata con _n_-1 gradi di libertà, dove _n_ è il numero di elementi di ciascuna lista. Liste di lunghezza diversa rendono i risultati del comando non definiti. I risultati del comando sono restituiti in una lista del tipo {Probabilità, statistica test Chi Quadro}. 

[EXAMPLE]
====

`++TestChiQuadro({1, 2, 3, 4}, {3, 2, 4, 2})++` restituisce _{0.31, 3.58}_.

====

TestChiQuadro(Matrice dei valori osservati, Matrice dei valori attesi)::
  Applica un https://it.wikipedia.org/_Test_chi_quadrato[Test Chi Quadro] che confronta la matrice dei valori
  osservati e la matrice dei valori (teorici) attesi indicate. La probabilità viene calcolata con stem:[(r-1)\cdot(c-1)] gradi di libertà, dove _r_ e _c_ sono rispettivamente il numero di righe e di colonne di ciascuna matrice. Matrici di dimensioni diverse rendono i risultati del comando non definiti. I risultati sono restituiti in una lista del tipo
  {Probabilità, statistica test Chi Quadro}.

[EXAMPLE]
====

`++TestChiQuadro({{1, 2, 1}, {3, 2, 3}}, {{2, 3, 2}, {4, 2, 3}})++` restituisce _{0.45, 1.58}_.

====

TestChiQuadro(Lista dei valori osservati, Lista dei valori attesi, Gradi di libertà)::
  Applica un test di verifica della bontà del modello che confronta la lista dei valori osservati e quella dei valori
  attesi, utilizzando il numero indicato di gradi di libertà. I risultati del comando sono restituiti in una lista del tipo {Probabilità, statistica test Chi Quadro}. 

[EXAMPLE]
====

`++TestChiQuadro({1, 2, 3, 4}, {3, 2, 4, 2}, 2)++` restituisce _{0.17, 3.58}_.
