= Comando Uniforme
:page-en: commands/Uniform
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]



Uniforme(Limite inferiore, Limite superiore, Moda, Valore variabile)::
  Calcola il valore della funzione di distribuzione cumulata di una http://en.wikipedia.org/wiki/it:Distribuzione_continua_uniforme[distribuzione uniforme] in corrispondenza del _valore variabile v_ specificato, cioè calcola la probabilità _P(X≤v)_ dove _X_ è una variabile casuale con distribuzione uniforme in [_limite inferiore_, _limite superiore_] con _moda_ indicata.

Uniforme(Limite inferiore, Limite superiore, Moda, Valore variabile, Booleano Cumulata)::
Se _Cumulata_ è _true_, calcola il valore della funzione di distribuzione cumulata di una distribuzione uniforme in [_limite inferiore_, _limite superiore_] con _moda_ indicata, in corrispondenza del _valore variabile_, altrimenti calcola il valore della funzione densità di probabilità di una distribuzione uniforme con i parametri indicati, in corrispondenza del _valore variabile_.

Uniforme(Limite inferiore, Limite superiore, Moda, x, Booleano Cumulata)::
 Se _Cumulata_ è _true_, genera la funzione di distribuzione cumulata di una distribuzione uniforme, altrimenti genera la funzione densità di probabilità di una distribuzione uniforme in [_limite inferiore_, _limite superiore_] con _moda_ indicata.

