= Comando Vertice
:page-en: commands/Vertex
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Vertice(Conica)::
  Determina tutti i vertici della conica indicata.

Vertice(Poligono)::
  Determina tutti i vertici del poligono indicato.

Vertice(Poligono, Numero n)::
  Determina l'_n-esimo_ vertice del poligono indicato.

Vertice(Disequazione)::
  Restituisce i punti di intersezione delle frontiere della disequazione indicata.

[EXAMPLE]
====

*Esempi:*

`++ Vertice((x + y < 3) && (x - y > 1))++` restituisce il punto (2,1)

`++ {Vertice((x + y < 3) ∧ (x - y > 1) && (y>-2))}++` restituisce la lista \{(2, 1), (5, -2), (-1, -2)}

`++ Vertice((y > x²) ∧ (y < x))}++` restituisce i punti (0, 0), (1, 1)

`++{Vertice((y > x²) ∧ (y < x))}++` restituisce la lista \{(0, 0), (1, 1)}.

====

[NOTE]
====

Per ottenere i vertici di un poligono, conica o disequazione in una xref:/Liste.adoc[lista], utilizzare il comando
`++{Vertice(Oggetto)}++`.

====

Vertice(Segmento,Indice)::
  Restituisce il punto iniziale (Indice = 1) o il punto finale (Indice = 2) del segmento.
