= Polecenie BazaGroebneraLeks
:page-en: commands/GroebnerLex
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

== Specyficzna składnia CAS

BazaGroebneraLeks( <Lista Wielomianów> )::
  Oblicza bazę Gröbnera dla listy wielomianów względem uporządkowania leksykograficznego zmiennych
  (w języku angielskim to uporządkowanie określane jest _lex_, _plex_ lub _pure lexical_).

[EXAMPLE]
====

`++BazaGroebneraLeks({x^3-y-2,x^2+y+1})++` daje w wyniku {stem:[ y^{3} + 4 y^{2} + 7 y + 5, x - y^{2} - 3 y - 3 ]}.

====

BazaGroebneraLeks( <Lista Wielomianów>, <Lista Zmiennych> )::
  Oblicza bazę Gröbnera dla listy wielomianów względem uporządkowania leksykograficznego dla podanej listy zmiennych
(w języku angielskim to uporządkowanie określane jest _lex_, _plex_ lub _pure lexical_).

[EXAMPLE]
====

`++BazaGroebneraLeks({x^3-y-2,x^2+y+1},{y,x})++` daje w wyniku {stem:[ -x^{3} - x^{2} + 1, -y - x^{2} - 1 ]}.

====

[NOTE]
====

Zobacz także polecenia xref:/commands/BazaGroebneraStopniowoOdwrotnieLeks.adoc[BazaGroebneraStopniowoOdwrotnieLeks] i xref:/commands/BazaGroebneraStopniowoLeks.adoc[BazaGroebneraStopniowoLeks].

====
