= Polecenie GranicaPrawostronna
:page-en: commands/LimitAbove
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

GranicaPrawostronna( <Funkcja>, <Wartość> )::
  Oblicza https://pl.wikipedia.org/wiki/Granica_jednostronna[granicę prawostronną] funkcji 
dla podanej wartości głównej zmiennej funkcji.

[EXAMPLE]
====

`++GranicaPrawostronna(1 / x, 0)++` daje w wyniku _stem:[\infty]_ .

====

[NOTE]
====

Nie wszystkie granice mogą zostać obliczone przez GeoGebrę, więc w takich przypadkach (jak również wtedy,
gdy poprawny wynik jest nieokreślony) zostanie zwrócone _niezdefiniowane_.

====

== Specyficzna składnia CAS

GranicaPrawostronna( <Wyrażenie>, <Wartość> )::
  Oblicza granicę prawostronną wyrażenia dla podanej wartości głównej zmiennej wyrażenia.

[EXAMPLE]
====

`++GranicaPrawostronna(1 / x, 0)++` daje w wyniku stem:[\infty] .

====

GranicaPrawostronna( <Wyrażenie>, <Zmienna>, <Wartość> )::
  Oblicza granicę prawostronną wyrażenia dla podanej wartości danej zmiennej wyrażenia.

[EXAMPLE]
====

`++GranicaPrawostronna(1 / a, a, 0)++` daje w wyniku stem:[\infty] .

====

[NOTE]
====

Nie wszystkie granice mogą zostać obliczone przez GeoGebrę, więc w takich przypadkach (jak również wtedy, 
gdy poprawny wynik jest niezdefiniowany) zostanie zwrócone _?_.

====

[NOTE]
====

Zobacz także polecenia xref:/commands/Granica.adoc[Granica] i xref:/commands/GranicaLewostronna.adoc[GranicaLewostronna].

====
