= Polecenie LosowaJednostajny
:page-en: commands/RandomUniform
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

LosowaJednostajny( <Min>, <Max> )::
  Zwraca losową liczbę rzeczywistą z https://pl.wikipedia.org/wiki/Rozk%C5%82ad_jednostajny_ci%C4%85g%C5%82y[rozkładu jednostajnego]
  w przedziale [_min_, _max_].

[EXAMPLE]
====

`++LosowaJednostajny(0, 1)++` zwraca losową liczbę z przedziału od _0_ do _1_.

====

LosowaJednostajny( <Min>, <Max>, <Ilość próbek> )::
  Zwraca listę zawierającą _n_ losowych liczb rzeczywistych (n - ilość próbek) z 
https://pl.wikipedia.org/wiki/Rozk%C5%82ad_jednostajny_ci%C4%85g%C5%82y[rozkładu jednostajnego] w przedziale [_min_, _max_].

[EXAMPLE]
====

`++LosowaJednostajny(0, 1, 3)++` zwraca listę trzech losowych liczb z przedziału od _0_ do _1_.

====

[NOTE]
====

* Zapis`++LosowaJednostajny(0,1)++` jest równoważny `++random()++` (Zobacz xref:/Predefiniowane_Funkcje_i_Operatory.adoc[Predefiniowane
funkcje i operatory]).
* Zobacz także polecenia xref:/commands/UstawPunktStartowyGeneratoraLosowego.adoc[UstawPunktStartowyGeneratoraLosowego], 
xref:/commands/LosowaCałkowita.adoc[LosowaCałkowita], xref:/commands/ElementLosowy.adoc[ElementLosowy],
xref:/commands/LosowaDwumianowy.adoc[LosowaDwumianowy], xref:/commands/LosowaNormalny.adoc[LosowaNormalny],
xref:/commands/LosowaPoisson.adoc[LosowaPoisson].

====
