= Polecenie Regresja
:page-en: commands/Fit
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Regresja( <Lista Punktów>, <Lista Funkcji> )::
  Zwraca kombinację liniową _funkcji_, która najlepiej dopasowuje się do _punktów_ z listy.

[EXAMPLE]
====

* `++Regresja({(-2, 3), (0, 1), (2, 1), (2, 3)}, {x^2, x})++` daje w wyniku _0.625 x^2 - 0.25x_.
* Niech  _L = {A, B, C, ...}_, _f(x) = 1_, _g(x) = x_, _h(x) = e^x_, _F = {f, g, h}_. `++Regresja(L, F)++` blicza funkcję 
postaci _a + b x + c e^x_, która dopasowuje się do punktów z listy.

====

Regresja( <Lista Punktów>, <Funkcja> )::
  Zwraca funkcję, która dopasowuje się do _punktów_  z listy z minimalnym błędem średniokwadratowym względem określonego modelu. 
Podana _funkcja_ modelu musi zależeć od jednego lub więcej suwaków, które są traktowane jako wartości początkowe parametrów do optymalizacji. 
Iteracja nieliniowa może się nie zbiegać, ale dostosowanie suwaków do lepszego punktu początkowego może pomóc.

[EXAMPLE]
====

Niech _a_ będzie suwakiem w przedziale od _-5_ do _5_ z krokiem 1. `++Regresja({(-2, 3), (0, 1), (2, 1), (2, 3)}, a + x^2)++`
daje w wyniku _-1 + x^2_.

====

[NOTE]
====

* Zobacz także polecenia  xref:/commands/RegresjaWykładnicza.adoc[RegresjaWykładnicza], xref:/commands/RegresjaWzrostuWykładniczego.adoc[RegresjaWzrostuWykładniczego],
xref:/commands/RegresjaY.adoc[RegresjaY], xref:/commands/RegresjaX.adoc[RegresjaX], xref:/commands/RegresjaLogarytmiczna.adoc[RegresjaLogarytmiczna],
xref:/commands/RegresjaLogistyczna.adoc[RegresjaLogistyczna], xref:/commands/RegresjaWielomianowa.adoc[RegresjaWielomianowa], xref:/commands/RegresjaPotęgowa.adoc[RegresjaPotęgowa]
and xref:/commands/RegresjaSinusoidalna.adoc[RegresjaSinusoidalna]
* Jeśli pracujesz z bardzo dużymi lub bardzo małymi liczbami, warto je znormalizować dla uzyskania dokładniejszych wyników — zobacz polecenie
xref:/commands/Normalizuj.adoc[Normalizuj].

====
