= Polecenie Relacja
:page-en: commands/Relation
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Relacja( <Lista> )::
  Wyświetla okno z komunikatem, które podaje informacje o relacji między dwoma lub więcej (maksymalnie czterema) obiektami.
Relacja( <Obiekt>, <Obiekt> )::
  Wyświetla okno z komunikatem, które podaje informacje o relacji między dwoma obiektami.

To polecenie pozwala sprawdzić, czy:

* dwie proste są prostopadłe,
* dwie proste są równoległe,
* dwa (lub więcej) obiekty są równe,
* punkt leży na prostej lub krzywej stożkowej,
*prosta jest styczna lub przecinająca krzywą stożkową,
* trzy punkty są współliniowe,
* trzy proste są współbieżne (lub równoległe),
* cztery punkty leżą na jednym okręgu (lub są współliniowe).

Niektóre z tych sprawdzeń mogą być wykonywane symbolicznie. 
Jeśli GeoGebra obsługuje symboliczne sprawdzenie danej własności, pojawia się przycisk „Sprawdź symbolicznie”. 
Po jego kliknięciu GeoGebra może dostarczyć więcej informacji na temat tego, czy dana własność jest ogólnie prawdziwa (ewentualnie pod jakimi warunkami).

[NOTE]
====

Zobacz także narzędzie xref:/tools/Relacja.adoc[Relacja].

====
