= Polecenie RozkładDwumianowy
:page-en: commands/BinomialDist
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

RozkładDwumianowy( <Liczba Prób>, <Prawdopodobieństwo Sukcesu> )::
  Zwraca wykres słupkowy https://pl.wikipedia.org/wiki/Rozk%C5%82ad_dwumianowy[rozkładu dwumianowego].
  Parametr _Liczba Prób_ określa liczbę niezależnych prób Bernoulliego, a parametr _Prawdopodobieństwo 
Sukcesu_ określa prawdopodobieństwo sukcesu w jednej próbie.

RozkładDwumianowy( <Liczba Prób>, <Prawdopodobieństwo Sukcesu>, <Czy Skumulowany> )::
  Zwraca wykres słupkowy rozkładu dwumianowego, gdy parametr _Czy Skumulowany_ = false.
  Zwraca wykres rozkładu dwumianowego skumulowanego, gdy parametr _Czy Skumulowany_ = true.
  Pierwsze dwa parametry są takie same jak powyżej.

RozkładDwumianowy( <Liczba Prób>, <Prawdopodobieństwo Sukcesu>, <Liczba sukcesów>, <Czy Skumulowany> )::
  Niech _X_ będzie zmienną losową o rozkładzie dwumianowym, a _v_ liczbą sukcesów.
  Polecenie zwraca P( X = _v_), gdy _Czy Skumulowany_ = false.
  Polecenie zwraca P( X ≤ _v_), gdy _Czy Skumulowany_ = true.
  Pierwsze dwa parametry są takie same jak powyżej.

RozkładDwumianowy( <Liczba Prób>, <Prawdopodobieństwo Sukcesu>, <Lista wartości>)::
  Oblicza P(_u_ ≤ X ≤ _v_), stosując wcześniejszą składnię (z _Czy Skumulowany_ = false)  i sumując wartości uzyskane, gdy elementy z _Listy wartości_ są używane jako _Liczba sukcesów_.

[EXAMPLE]
====

`++RozkładDwumianowy(10, 0.2, {1,2,3})++` daje w wyniku _0.77175_ i jest równoważne: `++RozkładDwumianowy(10, 0.2, 1, false)++` + `++RozkładDwumianowy(10, 0.2, 2, false)++` + `++RozkładDwumianowy(10, 0.2, 3, false)++`

====


[NOTE]
====

Składnie `++RozkładDwumianowy(10, 0.2, {1,2,3})++` i  `++RozkładDwumianowy(10, 0.2, 1..3)++` są równoważne.

====



== Specyficzna składnia CAS


RozkładDwumianowy( <Liczba Prób>, <Prawdopodobieństwo Sukcesu>, <Liczb sukcesów>, <Czy Skumulowany> )::
  Niech _X_ będzie zmienną losową o rozkładzie dwumianowym, a _v_ liczbą sukcesów.
  Polecenie zwraca P( X = _v_), gdy _Czy Skumulowany_ = false.
  Polecenie zwraca P( X ≤ _v_), gdy _Czy Skumulowany_ = true.

[EXAMPLE]
====

Możesz narysować wykres, używając na przykład `++f(x):=RozkładDwumianowy(100,x,36,true)-RozkładDwumianowy(100,x,23,true)++`

====

[EXAMPLE]
====

Załóżmy, że przesyłane są trzy pakiety danych przez wadliwą linię. Szansa, że dowolny pakiet przesłany przez tę linię 
ulegnie uszkodzeniu, wynosi stem:[\frac{1}{10}], więc prawdopodobieństwo przesłania dowolnego pakietu bez uszkodzeń wynosi
stem:[\frac{9}{10}].

* `++RozkładDwumianowy(3, 0.9, 0, false)++` daje w wyniku _stem:[\frac{1}{1000}]_, prawdopodobieństwo, że żaden z trzech pakietów 
nie zostanie przesłany poprawnie.
* `++RozkładDwumianowy(3, 0.9, 1, false)++` daje w wyniku _stem:[\frac{27}{1000}]_, prawdopodobieństwo, że dokładnie jeden z trzech 
pakietów zostanie przesłany poprawnie.
* `++RozkładDwumianowy(3, 0.9, 2, false)++` daje w wyniku _stem:[\frac{243}{1000}]_, prawdopodobieństwo, że dokładnie dwa z 
trzech pakietów zostaną przesłane poprawnie.
* `++RozkładDwumianowy(3, 0.9, 3, false)++` daje w wyniku _stem:[\frac{729}{1000}]_, prawdopodobieństwo, że wszystkie trzy 
pakiety zostaną przesłane poprawnie.
* `++RozkładDwumianowy(3, 0.9, 0, true)++` daje w wyniku _stem:[\frac{1}{1000}]_, prawdopodobieństwo, że żaden z trzech pakietów 
nie zostanie przesłany poprawnie.
* `++RozkładDwumianowy(3, 0.9, 1, true)++` daje w wyniku _stem:[\frac{7}{250}]_, prawdopodobieństwo, że co najwyżej jeden z trzech 
pakietów zostanie przesłany poprawnie.
* `++RozkładDwumianowy(3, 0.9, 2, true)++` yields _stem:[\frac{271}{1000}]_, prawdopodobieństwo, że co najwyżej dwa z trzech 
pakietów zostaną przesłane poprawnie.
* `++RozkładDwumianowy(3, 0.9, 3, true)++` daje w wyniku _1_, prawdopodobieństwo, że co najwyżej trzy z trzech pakietów zostaną 
przesłane poprawnie.
* `++RozkładDwumianowy(3, 0.9, 4, false)++` daje w wyniku _0_, prawdopodobieństwo, że dokładnie cztery z trzech pakietów zostaną 
przesłane poprawnie.
* `++RozkładDwumianowy(3, 0.9, 4, true)++` daje w wyniku _1_, prawdopodobieństwo, że co najwyżej cztery z trzech pakietów zostaną 
przesłane poprawnie.

====

RozkładDwumianowy( <Liczba Prób>, <Prawdopodobieństwo Sukcesu>, <Lista wartości>)::
  Oblicza P(_u_ ≤ X ≤ _v_), stosując wcześniejszą składnię (z _Czy Skumulowany_ = false)  i sumując wartości uzyskane, gdy elementy z _Listy wartości_ są używane jako _Liczba sukcesów_.

[EXAMPLE]
====

`++RozkładDwumianowy(10, 0.2, {1,2,3})++` daje w wyniku stem:[\frac{1507328}{1953125}] i jest równoważne: `++RozkładDwumianowy(10, 0.2, 1, false)++` + `++RozkładDwumianowy(10, 0.2, 2, false)++` + `++RozkładDwumianowy(10, 0.2, 3, false)++`

====
