= Polecenie TestChiKwadrat
:page-en: commands/ChiSquaredTest
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

TestChiKwadrat( <Macierz> )::
  Przeprowadza https://pl.wikipedia.org/wiki/Test_chi-kwadrat[test chi-kwadrat], który porównuje daną macierz - zaobserwowanych wartości z macierzą
  wartości oczekiwanych wyznaczoną na podstawie hipotezy niezależności. Macierz wartości oczekiwanych obliczana jest wewnętrznie. Każda wartość 
oczekiwana wyznaczana jest na podstawie sum wierszy i kolumn podanej macierzy obserwowanej według wzoru:
  stem:[ \text{wartość oczekiwana} = \frac{\text{suma wiersza} × \text{ suma kolumny}}{\text{suma wszystkich zaobserwowanych wartości}} ]

Wyniki zwracane są w formie listy: _{wartość prawdopodobieństwa, statystyka testu chi-kwadrat}_.

[EXAMPLE]
====

`++TestChiKwadrat({{1, 2, 1}, {3, 2, 3}})++` daje w wyniku _{0.69, 0.75}_.

====

TestChiKwadrat( <Lista>, <Lista> )::
  Przeprowadza https://en.wikipedia.org/wiki/Goodness_of_fit[test dopasowania (Goodness of Fit)], który porównuje pierwszą podaną listę - wartości zaobserwowanych
  z drugą listą - wartości oczekiwanych. Do obliczenia prawdopodobieństwa zakłada się _n_-1 stopni swobody, gdzie _n_ 
to liczba elementów w każdej z list. Dla list o różnych rozmiarach wynik jest niezdefiniowany.
  Wyniki zwracane są w formie listy: _{wartość prawdopodobieństwa, statystyka testu chi-kwadrat}_.

[EXAMPLE]
====

`++TestChiKwadrat({1, 2, 3, 4}, {3, 2, 4, 2})++` daje w wyniku _{0.31, 3.58}_.

====

TestChiKwadrat( <Macierz>, <Macierz> )::
  https://pl.wikipedia.org/wiki/Test_chi-kwadrat[test chi-kwadrat], który porównuje pierwszą podaną macierz - - wartości zaobserwowanych
  z drugą macierzą - wartości oczekiwanych.Do obliczenia prawdopodobieństwa zakłada się stem:[(r-1)\cdot(c-1)] stopni swobody, gdzie
  _r_ i _c_ ato liczba wierszy i kolumn w każdej macierzy. Dla macierzy o różnych rozmiarach wynik jest niezdefiniowany.
  Wyniki zwracane są w formie listy: _{wartość prawdopodobieństwa, statystyka testu chi-kwadrat}_.

[EXAMPLE]
====

`++TestChiKwadrat({{1, 2, 1}, {3, 2, 3}}, {{2, 3, 2}, {4, 2, 3}})++` daje w wyniku _{0.45, 1.58}_.

====

TestChiKwadrat( <Lista>, <Lista>, <Liczba Stopni Swobody> )::
  Przeprowadza https://en.wikipedia.org/wiki/Goodness_of_fit[test dopasowania (Goodness of Fit)], który porównuje pierwszą podaną listę - wartości zaobserwowanych
  z drugą listą - wartości oczekiwanych, wykorzystując określoną liczbę stopni swobody.
  Wyniki zwracane są w formie listy: _{wartość prawdopodobieństwa, statystyka testu chi-kwadrat}_.
   Dla list o różnych rozmiarach wynik jest niezdefiniowany.

[EXAMPLE]
====

`++ChiSquaredTest({1, 2, 3, 4}, {3, 2, 4, 2}, 2)++` daje w wyniku _{0.17, 3.58}_.

====
