= Polecenie UstawWspółrzędne
:page-en: commands/SetCoords
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

UstawWspółrzędne( <Obiekt>, <x>, <y> )::
  Ustawia współrzędne kartezjańskie xref:/Obiekty_Swobodne_Zależne_i_Pomocnicze.adoc[obiektów swobodnych] w widoku 2D 
  na podane współrzędne. Polecenie korzysta z wartości współrzędnych, a nie ich definicji, dzięki czemu obiekt pozostaje swobodny.

UstawWspółrzędne( <Obiekt>, <x>, <y>, <z> )::
  Ustawia współrzędne kartezjańskie xref:/Obiekty_Swobodne_Zależne_i_Pomocnicze.adoc[obiektów swobodnych] w widoku 3D 
  na podane współrzędne. Polecenie korzysta z wartości współrzędnych, a nie ich definicji, dzięki czemu obiekt pozostaje swobodny.

[NOTE]
====

* Polecenie działa również dla punktów na ścieżkach oraz w obszarach – punkt zostanie przesunięty do najbliższej możliwej pozycji.

* To polecenie działa także dla suwaków, przycisków, pól wyboru, pól tekstowych oraz obrazów. 

* Jeżeli włączona jest opcja "Położenie bezwzględne na ekranie", współrzedne _x_, _y_ i _z_ są podawane w pikselach.

====
