= Polecenie WielokątUstalonegoKształtu
:page-en: commands/RigidPolygon
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

WielokątUstalonegoKształtu( <wielokąt> )::
  Tworzy kopię dowolnego wielokąta, którą można przesuwać zmieniając położenie jej pierwszego wierzchołka, a obracać zmieniając położenie jej drugiego wierzchołka.

WielokątUstalonegoKształtu( <wielokąt>, <Przesunięcie x>, <Przesunięcie y> )::
  Tworzy kopię danego wielokąta z podanym przesunięciem, którą można przesuwać zmieniając położenie jej pierwszego wierzchołka, 
a obracać zmieniając położenie jej drugiego wierzchołka.

WielokątUstalonegoKształtu( <Punkt Swobodny>, ..., <Punkt Swobodny> )::
 Tworzy wielokąt, którego kształt nie może zostać zmieniony. Ten wielokąt można przesuwać położenie jego pierwszego wierzchołka, 
a obracać zmieniając położenie jego drugiego wierzchołka.

[NOTE]
====

Kopia będzie się zmieniać przy każdej zmianie oryginalnego wielokąta. Jeśli chcesz zmienić kształt kopii, musisz zmienić oryginał.

====
