= Polecenie WykresKołowy
:page-en: commands/PieChart
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

WykresKołowy(< Lista Częstości >)::
  Tworzy wykres kołowy na podstawie listy częstotliwości. Całe koło reprezentuje 100%, a dostarczone dane są przedstawione jako wycinki koła.

[EXAMPLE]
====

`++WykresKołowy({20, 15, 40, 5, 10, 20})++` tworzy wykres kołowy z domyślnym środkiem (0,0) i promieniem 3.

====

WykresKołowy(< Lista Częstości >, < Centrum >, < Promień >)::
  Tworzy wykres kołowy z danynym środkiem (centrum) i promieniem na podstawie listy częstotliwości. Całe koło reprezentuje 100%, a dostarczone dane są przedstawione jako wycinki koła.

[EXAMPLE]
====

`++WykresKołowy({20, 15, 40, 5, 10, 20},(3,3),5)++` tworzy wykres kołowy z środkiem (3,3) i promieniem 5.

====

[NOTE]
====

Wybierz zakładkę _Kolor_ tw oknie dialogowym _Ustawienia_  wykresu kołowego, aby wybrać spośród szerokiej gamy kolorów i dostosować każdy wycinek, 
a zakładkę _Styl_, aby ustawić wypełnienie każdego wycinka.

====
