= Polecenie ZagrajDźwięk
:page-en: commands/PlaySound
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

ZagrajDźwięk( <Plik> )::
  Odtwarza plik MP3 MP3 (.mp3).

[EXAMPLE]
====

* `++ZagrajDźwięk("https://test.geogebra.org/~mike/welcome-to-geogebra-markus.mp3")++`
* `++ZagrajDźwięk("#J2sQQfwQ")++` odtwarza http://www.geogebra.org/m/J2sQQfwQ[plik .mp3 przesłany do GeoGebry]
* `++ZagrajDźwięk("https://drive.google.com/uc?id=0B7xCmZaU3oU2eXFNUzd6ZlZJS0U&authuser=0&export=download")++` plik .mp3 przesłany do Google Drive'a
* `++ZagrajDźwięk("https://www.dropbox.com/s/27skpv82odjp7ej/material-1264825.mp3?dl=1")++`plik .mp3 przesłany do DropBox'a

====

[NOTE]
====

Aby działało na iOS (a także jeśli chcesz natychmiastowego odtwarzania), możesz zakodować .mp3 jako
inline base64-encoded data: URL, zobacz przykład: https://www.geogebra.org/m/wztkqxuv . Adres musi się zaczynać od _dokładnego_ ciągu:
`++data:audio/mp3;base64,++`, aby działał w GeoGebrze Classic 5. Możesz użyć tego narzędzia do konwersji plików .MP3 
do odpowiedniej składni dla GeoGebry: https://test.geogebra.org/~mike/utils/base64Encode.html

====

ZagrajDźwięk( <Czy grać> )::
  Wstrzymuje lub wznawia odtwarzanie (nie dotyczy plików MP3).
  `++ZagrajDźwięk(true)++` = odtwarzanie, `++ZagrajDźwięk(false)++` = pauza.

ZagrajDźwięk( <Funkcja>, <Min>, <Max> )::
  Odtwarza dźwięk wygenerowany przez funkcję czasu, której wartości mieszczą się w zakresie [-1,1].
Jednostką czasu są sekundy, a dźwięk odtwarzany jest od czasu Min do Max.
Dźwięk generowany jest przez próbki 8-bitowe w tempie 8000 próbek na sekundę.

Czysta fala sinusoidalna o częstotliwości 440 Hz (dźwięk A) przez 1 sekundę:

[EXAMPLE]
====

`++ZagrajDźwięk(sin(440 2Pi x), 0, 1)++`

====

ZagrajDźwięk( <Funkcja>, <Min>, <Max>, <Wartość próbki>, <Głębokość próbki> )::
  Odtwarza dźwięk wygenerowany przez funkcję czasu, której wartości mieszczą się w zakresie [-1,1].
Jednostką czasu są sekundy, a dźwięk odtwarzany jest od czasu Min od Max. Metoda próbkowania jest określona 
przez parametry "Wartość próbki" i "Głębokość próbki".
  "Wartość próbki" - liczba próbek pobieranych w ciągu sekundy. Dozwolone wartości to 8000, 11025, 16000,
  22050, or 44100
  "Głębokość próbki" – rozmiar próbki w bitach. Dozwolone wartości: 8 i 16.

ZagrajDźwięk( <Dźwięk>, <Czas trwania>, <Instrument> ) (tylko GeoGebra Classic 5)::
  Odtwarza dźwięk https://pl.wikipedia.org/wiki/MIDI[MIDI].
  _Dźwięk_ - liczba całkowita od 0 do 127 oznaczająca nutę wg tabeli. Gdy Dźwięk = 60 odgrywane jest środkowe C.
  _Czas trwania_ - czas odtwarzania nuty w sekundach.
  _Instrument_ – liczba całkowita oznaczająca instrument syntezatora użyty do odtworzenia nuty. 
  Lista w możliwych do stosowania instrumentów zawarta jest w 
  https://en.wikipedia.org/wiki/General_MIDI#Program_change_events[specyfikacji technicznej].
 Większość instrumentów jest obsługiwana, ale mogą występować różnice między platformami.

*Dzwięki MIDI*

[width=100 %, cols=",,,,,,,,,,,,",options= "header"]

|===
| Oktawe | C=Do |Do#|D = Re|Re#|E = Mi|F = Fa|Fa#|G = Sol|Sol#|A = La|La#|B = Si
|**0**| 0|1|2|3|4|5|6|7|8|9|10|11
|**1**|12|13|14|15|16|17|18|19|20|21|22|23
|**2**|24|25|26|27|28|29|30|31|32|33|34|35
|**3**|36|37|38|39|40|41|42|43|44|45|46|47
|**4**|48|49|50|51|52|53|54|55|56|57|58|59
|**5**|60|61|62|63|64|65|66|67|68|69|70|71
|**6**|72|73|74|75|76|77|78|79|80|81|82|83
|**7**|84|85|86|87|88|89|90|91|92|93|94|95
|**8**|96|97|98|99|100|101|102|103|104|105|106|107
|**9**|108|109|110|111|112|113|114|115|116|117|118|119
|**10**|120|121|122|123|124|125|126|127||||
|===
