= Açı Araç
:page-en: tools/Angle
ifdef::env-github[:imagesdir: /tr/modules/ROOT/assets/images]

Bu araç ile açıları farklı yollarla oluşturabilirsiniz:

* Üç noktaya bu noktalar arasındaki açıyı oluşturmak için tıklayın. Seçilen ikinci nokta açının köşesidir.
* İki doğru parçasına bunlar arasındaki açıyı oluşturmak için tıklayın.
* İki doğruya bunlar arasındaki açıyı oluşturmak için tıklayın.
* İki vektöre bunlar arasındaki açıyı oluşturmak için tıklayın.
* Bir çokgene, bu çokgenin tüm açılarını oluşturmak için tıklayın.

[NOTE]
====

*Notlar:*

* Eğer bu çokgen köşeleri saatin ters yönünde seçilerek oluşturulmuşsa _Açı_ aracı size çokgenin iç açılarını verir
* Açılar _saatin ters_ yönünde oluşturulur. Bu yüzden nesneleri seçme sırası _Açı_ aracı için belirleyicidir. Eğer bir
açının en büyük değerini sınırlandırmak isterseniz xref:/Özellikler_Diyaloğu.adoc[Özellikler Diyaloğunun] _Temel_
sekmesindeki aşağı açılır listeden arzu ettiğiniz sınırları seçin.
* xref:/commands/Açı.adoc[Açı] komutuna da bakın.

====
