= Kesiştir Araç
ifdef::env-github[:imagesdir: /tr/modules/ROOT/assets/images]

İki nesnenin kesişim noktaları iki şekilde oluşturulabilir:

* İki nesneyi seçmek (eğer mümkünse) tüm kesişim noktalarını oluşturur.
* İki nesnenin kesişimine doğrudan tıklamak sadece bu _bir tek kesişim noktasını_ oluşturur.

[NOTE]
====

Bazen kesişen nesnelerin sadece kesişme noktaları civarındaki kısımlarını göstermek kullanışlıdır. Bunu yapmak için
kesişme noktasının xref:/Özellikler_Diyaloğu.adoc[Özelliklerini] açın ve _Temel_ sekmesinde _Kırpılmış kesişim
çizgilerini göster_ seçeneğini işaretleyin. Ardından kesişen nesneleri gösterip gizleyebilirsiniz.

====

== Dış Kesişimler

Doğru parçaları, ışınlar ve yaylar için xref:/Özellikler_Diyaloğu.adoc[Özellikler] diyaloğunun _Temel_ sekmesinde __Dış
Kesişimlere İzin Ver__meyi isteyip istemediğinizi belirleyebilirsiniz. Bu bir nesnenin uzantısının üzerinde kalan
kesişim noktalarını elde etmek için kullanılabilir. Örneğin, bir doğru parçası veya ışının uzantısı bir doğrudur.

[NOTE]
====

xref:/commands/Kesiştir.adoc[Kesiştir] komutuna da bakın.

====
