= Freihandskizze (Werkzeug)
:page-en: tools/Freehand_Shape
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Mit dem Werkzeug "Freihandskizze erkennen" können Sie entweder eine xref:/Funktionen.adoc[Funktion] skizzieren oder
freihändig einen Kreis, eine Strecke oder ein Vieleck zeichnen, welcher/welche/welches automatisch erkannt und in die
exakte Form umgewandelt wird. Wird eine Funktion _f_ erzeugt, so können Sie deren Wert an einem bestimmten Punkt
berechnet, einen Punkt darauf setzen oder Transformationen durchführen. Tangenten und Ableitungen sind für diese
Funktionen allerdings nicht möglich.

[NOTE]
====

Auf Funktionen, die mit diesem Werkzeug erstellt wurden, können alle Trend-Befehle angewendet werden, z.B. der Befehl
xref:/commands/TrendSin.adoc[TrendSin].

====

[NOTE]
====

Auf Funktionen, die mit diesem Werkzeug erstellt wurden, kann der Befehl xref:/commands/Integral.adoc[Integral]
angewendet werden, z.B. `++Integral[f, 1, 5]++`, um die Fläche unterhalb der Funktion zu berechnen und zu schattieren.

====
