= Schnittpunkt (Werkzeug)
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Die Schnittpunkte zweier Objekte können auf zwei verschiedene Arten erzeugt werden:

* Klicken Sie nacheinander auf die beiden Objekte, um (falls möglich) alle Schnittpunkte zu erzeugen.
* Klicken Sie direkt auf den Schnittpunkt zweier Objekte, um nur diesen einen Schnittpunkt zu erzeugen.

[NOTE]
====

Manchmal ist es von Vorteil sich nur Teile der sich schneidenden Objekte nahe des jeweiligen Schnittpunkts anzeigen zu
lassen. Wählen Sie dazu im xref:/Eigenschaften_Dialog.adoc[Eigenschaften-Dialog] des Schnittpunktes die Option _Gekürzte
Schnittgeraden anzeigen_ im Tab _Grundeinstellungen_ aus und verbergen Sie dann die sich schneidenden Objekte.

====

== Außerhalb liegende Schnittpunkte

Beim Schneiden von Strecken, Strahlen oder Bögen können Sie im xref:/Eigenschaften_Dialog.adoc[Eigenschaften-Dialog] im
Tab _Grundeinstellungen_ angeben, ob Sie _außerhalb liegende Schnittpunkte zulassen_ möchten. Dadurch können auch
Schnittpunkte angezeigt werden, welche auf der Verlängerung der betroffenen Objekte liegen (z. B. die Verlängerung einer
Strecke ist eine Gerade).

[NOTE]
====

Siehe auch Befehl xref:/commands/Schnittpunkt.adoc[Schnittpunkt].

====
