= Winkel (Werkzeug)
:page-en: tools/Angle_Tool
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Mit diesem Werkzeug können Sie auf verschiedene Arten Winkel erzeugen:

* Markieren Sie drei Punkte A, B und C um den eingeschlossenen Winkel zu erzeugen. Dabei ist der zweite ausgewählte
Punkt der Scheitelpunkt des Winkels.
* Markieren Sie zwei Strecken um den Schnittwinkel zu erzeugen. Dieser Winkel wird gegebenenfalls auf der Verlängerung
der beiden Strecken eingezeichnet.
* Markieren Sie zwei Geraden um den Schnittwinkel der beiden Geraden zu erzeugen.
* Markieren Sie zwei Vektoren um den eingeschlossenen Winkel zu erzeugen.
* Markieren Sie ein Vieleck um alle Winkel dieses Vielecks gleichzeitig zu erzeugen.

[NOTE]
====

* Bei einem Dreieck werden standardmäßig stets die Innenwinkel des Dreiecks eingezeichnet. Für Vielecke mit mehr als
drei Ecken, die gegen den Uhrzeigersinn erzeugt wurden, werden ebenfalls die Innenwinkel angezeigt.
* Winkel werden in GeoGebra stets in _mathematisch positiver Richtung_ (also gegen den Uhrzeigersinn) erzeugt. Daher ist
die Reihenfolge der markierten Objekte hier für die Orientierung des Winkels ausschlaggebend. Sie können jedoch die
Größe eines Winkels auf maximal 180° einschränken, indem Sie im xref:/Eigenschaften_Dialog.adoc[Eigenschaften-Dialog]
auf der Karte Grundeinstellungen die Option _Überstumpfer Winkel möglich_ ausschalten.
* Siehe auch den Befehl xref:/commands/Winkel.adoc[Winkel].

====
