= Gje namn til objekt
:page-en: Naming_Objects
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Du kan gje namn til eit objekt når du lagar det ved bruk av xref:/Inntastingsfelt.adoc[inntastingsfeltet]:

* xref:/Punkt_og_vektorar.adoc[Punkt]: I GeoGebra vil punkt alltid få namn med store bokstavar. Berre skriv inn namnet
(t.d. _A_ eller _P_), eit likskapsteikn og koordinatane (eller kommandoar som avgjer koordinatane) til punktet.

[EXAMPLE]
====

*Døme:* `++C = (2, 4)++`, `++ P = (1; 180°)++`

====

* xref:/Punkt_og_vektorar.adoc[Vektorar]: For å skilje mellom punkt og vektorar får vektorar små bokstavar som namn i
GeoGebra. Skriv inn namnet (t.d. _u_ eller _v_), eit likskapsteikn og koordinatane (eller kommandoar som avgjer
koordinatane) til vektoren.

[EXAMPLE]
====

*Døme:* `++v = (1, 3)++`, `++ u = (3; 90°)++`

====

* xref:/Linjer_og_aksar.adoc[Linjer], sirklar, og xref:/Kjeglesnitt.adoc[kjeglesnitt]: Desse objekta kan du gje namn ved
å skrive inn namnet, eit kolon og likninga eller kommandoane for objektet.

[EXAMPLE]
====

*Døme:* `++g: y = x + 3++`, `++c: (x-1)^2 + (y – 2)^2 = 4++`, `++hyp: x^2 – y^2 = 2++`

====

* xref:/Funksjonar.adoc[Funksjonar]: Du kan gje namn til funksjonar ved å skrive til dømes `++f(x) =++` or `++g(x)=++`
framfor likninga eller kommandoane for funksjonen.

[EXAMPLE]
====

*Døme:* `++h(x) = 2 x + 4++`, `++q(x) = x^2, trig(x) = sin(x)++`

====

[NOTE]
====

*Merk:*

* Dersom du ikkje gjev eit objekt namn manuelt vil GeoGebra gje namn i alfabetisk rekkefølgje.
* Du kan lage indeksar i namna ved å bruke understrek. Til dømes A~1~ vert skrive inn som `++A_1++` og s~AB~ vert skrive
inn som `++s_{AB}++`.

====

== Reserverte namn

Dette er dei namna du ikkje kan bruke på objekt du lagar: x, y, xAxis, yAxis, zAxis, abs, sgn, sqrt, exp, log, ln, ld,
lg, cos, sin, tan, acos, arcos, arccos, asin, arcsin, atan, arctan, cosh, sinh, tanh, acosh, arcosh, arccosh, asinh,
arcsinh, atanh, arctanh, atan2, erf, floor, ceil, round, random, conjugate, arg, gamma, gammaRegularized, beta,
betaRegularized, sec, csc, cosec, cot, sech, csch, coth

I symbollista til inntastingsfeltet finn du spesielle teikn for dei følgjande konstantane:

* π - sirkelkonstanten pi, som du også kan skrive som [.kcode]#Alt # + [.kcode]# p#
* ℯ - Eulertalet, t.d. brukt i eksponentialfunksjonen ℯ^x. Du kan også skrive den som [.kcode]#Alt # + [.kcode]# e#
* ί - den imaginære eininga, t.d. for komplekse tal som z = 3 + ί. Du kan også skrive den som [.kcode]#Alt # + [.kcode]#
i#

Når variabelnamna _e_ og _i_ ikkje er tatt i bruk vil dei automatisk verte lese som høvesvis ℯ og ί.

[NOTE]
====

*Merk:* Sjå også sida om xref:/Namn_og_objekttekstar.adoc[Namn og objekttekstar].

====
