= Innstillingar for utskrift
:page-en: Printing_Options
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

== Utskrift av grafikkfeltet

GeoGebra let deg skrive ut eit bilde av konstruksjonane i xref:/Grafikkfelt.adoc[grafikkfeltet]. Du finn eit menyvalet
_Førehandsvis utskrift_ i xref:/Filmeny.adoc[Fil-menyen] eller du kan trykke [.kcode]#Ctrl# + [.kcode]#P#. I
dialogboksen som vert opna kan du skrive inn tittel, forfatter og dato for konstruksjonen. I tillegg kan du velje
skalering, orientering (liggande eller ståande) og kva for felt som skal verte skrive ut (algebrafelt eller
grafikkfelt).

[NOTE]
====

*Merk:* For å oppdatere førehandsvisninga etter at du har gjort ei endring i teksten må du trykke [.kcode]#Enter#.

====

== Utskrift av framgangsmåte

Dersom du vil skrive ut xref:/s_index_php?title=Framgangsmåte_action=edit_redlink=1.adoc[framgangsmåten] må du først
opne den frå xref:/Vis_meny.adoc[Vis-menyen] eller ved å trykke [.kcode]#Ctrl# + [.kcode]#Shift# + [.kcode]#L# og så
velje _Skriv ut_.

I utskriftsdialogboksen som vert opna kan du skrive inn forfattar, velje margstorleik og orientering før du skriv ut.

[NOTE]
====

*Merk:* For å skjule kolonnar i utskrifta, må du velje kva for kolonner som skal verte vist i framgangsmåten før du
opnar utskriftsdialogen.

====
