= Intervall
:page-en: Intervals
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Eit intervall er eit sett med tal mellom ei øvre og ei nedre grense. For å opprette eit intervall, skriv du til dømes
`++2 < x < 3++` i xref:/Inntastingsfelt.adoc[inntastingsfeltet]. Dette er eit opent intervall. For å lage eit lukka
intervall skriv du `++2 ≤ x ≤ 3++`, medan eit delvis lukka intervall kan vere `++2 ≤ x < 3++`.

[NOTE]
====

*Merk:* Sjå også xref:/Boolske_verdiar.adoc[Boolske verdiar].

====

For å avgjere om eit tal _c_ høyrer til eit intervall _r_ skriv inn `++r(c)++` i _inntastingsfeltet_, resultatet vil
vere ein boolsk verdi. Ei generalisering av intervall er xref:/Ulikskapar.adoc[ulikskapar].

[NOTE]
====

*Merk:*

* Kommandoane xref:/commands/Min.adoc[Min[ <Intervall> ]], xref:/commands/Maks.adoc[Maks[ <Intervall> ]] - Dei
returnerer henhaldsvis nedre og øvre grense til eit intervall uavhengig av om det er ope, lukka eller delvis lukka.
* Kommandoen xref:/commands/Midtpunkt.adoc[Midtpunkt[ <Intervall> ]] - Returnerer midtpunktet til intervallet:
stem:[\frac\{a+b}2]. Resultatet er uavhengig av om intervallet er ope, lukka eller delvis lukka.
* Kommandoen xref:/commands/Punkt.adoc[Punkt[ <Intervall> ]] - Returnerer eit flyttbart
xref:/Punkt_og_vektorar.adoc[punkt], der x-koordinaten høyrer til intervallet og y-koordinaten er 0.
* Kommandoen xref:/commands/PunktI.adoc[PunktI[ <Intervall> ]] - Returnerer eit flyttbart
xref:/Punkt_og_vektorar.adoc[punkt], der x-koordinaten høyrer til intervallet og y-koordinaten kan verte endra
vilkårleg.

====
