= Kjeglesnitt
:page-en: Conic_sections
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Du kan skrive inn kjeglesnitt som kvadratiske likningar i _x_ og _y_ i xref:/Inntastingsfelt.adoc[inntastingsfeltet].
Tidlegare definerte variablar (t.d. tal, punkt og vektorar) kan verte brukt i likninga for kjeglesnittet.

[NOTE]
====

*Merk:* Namnet til kjeglesnittet kan du skrive inn etterfulgt av eit kolon før du skriv inn likninga.

====

Du kan også lage kjeglesnitt ved bruk av xref:/commands/Kjeglesnitt_Kommandoar.adoc[kommandoar for kjeglesnitt] eller
verktøy for xref:/Verktøy_for_kjeglesnitt.adoc[kjeglesnitt] og xref:/Verktøy_for_sirklar_og_bogar.adoc[sirklar].

== Døme

[cols=",",options="header",]
|===
|Kjeglesnitt |Inndata
|Ellipse ell1 |ell1: 9 x^2 + 16 y^2 = 144
|Ellipse ell2 |ell2: b^2 x^2 + a^2 y^2 = a^2 b^2, der _a_ og _b_ er definerte på førehand
|Hyperbel hyp |hyp: 9 x^2 – 16 y^2 = 144
|Parabel par |par: y^2 = 4 x
|Sirkel c1 |c1: x^2 + y^2 = 25
|Sirkel c2 |c2: (x – 5)^2 + (y + 2)^2 = 25
|===
