= Konstruksjonsforklaring
:page-en: Construction_Protocol
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Du kan opne den interaktive konstruksjonsforklaringa ved å gå til _Konstruksjonsforklaring_ i
xref:/Vis_meny.adoc[Vis-menyen]. Konstruksjonsforklaringa er ein tabell som visar alle konstruksjonsstega. Den let deg
gjere om ein konstruksjon steg for steg ved å bruke xref:/Navigasjonslinje.adoc[navigasjonslinja] nederst i
xref:/Grafikkfelt.adoc[grafikkfeltet].

[NOTE]
====

*Merk:* Navigasjonslinja opnar du ved å høgreklikke på ein ledig plass i grafikkfeltet og ved å velje _Verktøylinje for
navigasjon_.

====

== Navigasjon og endring i konstruksjonsforklaringa

Du kan bruke tastaturet for å navigere i konstruksjonsforklaringa:

* Bruk [.kcode]#↑# for å gå til forrige konstruksjonssteg.
* Bruk [.kcode]#↓# for å gå til neste konstruksjonssteg.
* Bruk [.kcode]#Home# for å gå til starten på konstruksjonsforklaringa.
* Bruk [.kcode]#End# for å gå til slutten på konstruksjonsforklaringa.
* Bruk [.kcode]#Delete# for å slette eit konstruksjonssteg.

[NOTE]
====

*Merk:* Dersom du slettar eit konstruksjonssteg kan det påverke steg som er avhengige av det sletta steget.

====

Du kan også bruke musa for å navigere i konstruksjonsforklaringa:

* Dobbeltklikk på ei rad for å velje eit konstruksjonssteg.
* Dobbeltklikk på ei overskrift for å gå til starten av konstruksjonsforklaringa.
* Dra og slipp ei rad for å flytte eit konstruksjonssteg til ein annan posisjon.

[NOTE]
====

*Merk:* Dette er ikkje alltid mogleg sidan objekt kan vere avhengige av andre objekt.

====

* Høgreklikk på ei rad for å opne xref:/Kontekstmeny.adoc[kontekstmenyen] for objektet på dette konstruksjonssteget.

[NOTE]
====

*Merk:* Du kan setje inn eit konstruksjonssteg på kva som helst posisjon. Dobbeltklikk på det steget som du vil setje
inn eit nytt steg under. Lag det nye objektet. Dette objektet vert då plassert på den ønska posisjonen i
konstruksjonsforklaringa.

====

Frå menyvalet _Kolonner_ i konstruksjonsforklaringa kan du setje inn ei kolonne for å definere etappepunkt. Det let deg
gruppere fleire objekt. Vel _Vis berre etappepunkt_ frå menyvalet _Innstillingar_ for å skjule dei andre punkta i
forklaringa. Når du navigerer gjennom forklaringa vil då grupperte objekt verte vist samtidig.

[NOTE]
====

*Merk:* Frå menyvalet _Kolonner_ kan du også velje kva for andre kolonner som skal verte vist i
konstruksjonsforklaringa.

====

== Eksportere konstruksjonsforklaringa som ei webside

GeoGebra let deg eksportere konstruksjonsforklaringa som ei webside. Vel _Eksporter som webside_ frå menyen i
konstruksjonsforklaringa. I vinduet som vert opna kan du skrive inn tittel, forfattar, dato for konstruksjonen og velje
om du vil inkludere eit bilde av xref:/Grafikkfelt.adoc[grafikkfeltet] og xref:/Algebrafelt.adoc[algebrafeltet]. I
tillegg kan du velje om du vil eksportere med fargar. Då vil objekta i konstruksjonsforklaringa få same farge som dei
samsvarande objekta i konstruksjonen.

[NOTE]
====

*Merk:* Den eksporterte HTML-fila kan verte vist med alle internettlesarar (til dømes Firefox, Opera, Chrome og Internet
Explorer), og den kan verte endra med mange tekstbehandlarar (til dømes OpenOffice Writer og Microsoft Office Word).

====
