= Lag
:page-en: Layers
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

[NOTE]
====

*Merk:* I GeoGebra vert lag brukt til å avgjere kva for objekt som vert markert/flytta når brukaren trykkjer på fleire
objekt samtidig (t.d. dersom fleire objekt ligg over/under kvarandre).

====

Som standard vert alle objekt teikna på lag 0 som er bakgrunnslaget i xref:/Grafikkfelt.adoc[grafikkfeltet]. Det er
totalt 10 lag tilgjengeleg (frå 0 til og med 9), og lag med høgare nummer vert teikna over dei med lågare nummer.

Ved å gå til fana xref:/Avanserte_eigenskapar.adoc[_Avansert_] i xref:/Eigenskapar.adoc[eigenskapar], kan du endre kva
for eit lag eit objekt skal tilhøyre. Når du har endra lagnummeret til minst eit objekt vekk frå 0, vil alle nye objekt
verte teikna i det laget med høgast nummer som har eit objekt i seg.

[NOTE]
====

*Merk:* Etter å ha markert eit objekt, kan du markere alle objekt i det same laget ved menypunktet _Vel dette laget_ i
xref:/Redigeringsmeny.adoc[Rediger-menyen] (tastatursnarveg: [.kcode]#Ctrl# + [.kcode]#L#). Dette menypunktet er berre
tilgjengeleg dersom alle markerte objekt ligg i same lag.

====

== Vidare bruk av lag

* For eksport av SVG-filer vert objekt gruppert i lag.
* Lag kan verte kontrollert ved å bruke brukergrensesnittet for JavaScript for
xref:/Eksporter_dialogboks_for_arbeidsark.adoc[GeoGebra applets].
