= Legg inn i CMS, VLE (Moodle) og Wiki
:page-en: Embedding_to_CMS_VLE_(Moodle)_and_Wiki
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Dersom https://en.wikipedia.org/wiki/no:Publiseringssystemet[publiseringssystemet] (Content Mangagement System, CMS)
eller https://en.wikipedia.org/wiki/no:L%C3%A6ringsplattform[læringsplattformen] (Virtual Learning Environment, VLE) din
er i stand til å setje inne ubehandla HTML, vil den enklaste måten å eksportere ein interaktiv GeoGebra konstruksjon
vere ved bruk av tastatursnarvegen [.kcode]#Ctrl# + [.kcode]#Shift# + [.kcode]#M#. HTML-koden vert sendt til
utklippstavla og du kan setje din CMS eller VLE til å godta HTML redigering og lime koden inn der. Dersom du vil endre
nokon parametrar i teksten som vert kopiert bruk xref:/Eksporter_dialogboks_for_arbeidsark.adoc[dialogboksen for å
eksportere arbeidsark] og vel _Utklippstavle: html_ under fana _Avansert_.

== GeoGebra

Eit anna val er å laste opp arbeidsarket til http://www.geogebra.org/[*GeoGebra*], som du no enkelt kan gjere gjennom
GeoGebra ved å gå til xref:/Filmeny.adoc[Ful -> Del...]. http://www.geogebra.org/[*GeoGebra*] vil då gi deg ein kode som
du kan bruke.

== MediaWiki og Google Nettsteder

For http://www.mediawiki.org[MediaWiki] eller http://sites.google.com[Google Nettsteder] kan du bruke _Fil -> Eksporter
-> Dynamisk ark som webside (html)..._ og under fana avansert i dialogboksen for å
xref:/Eksporter_dialogboks_for_arbeidsark.adoc[eksportere arbeidsark] vel du henhaldsvis__Utklippstavle: MediaWiki__
eller _Utklippstavle: Google Gadget_. For MediaWiki er det nok å lime inn koden frå utklippstavla til sida du redigerer.
For Google Nettsteder må du først lagre koden som ein gadget og så bruk sett inn gadget funksjonen.

[NOTE]
====

*Merk:* For MediaWiki, DokuWiki og nokre andre system er det nødvendig med ein plugin for å setje inn GeoGebra appletar.
Sjå /s_index_php?title=En:Tutorial:Main_Page_action=edit_redlink=1.adoc[en:Tutorial:Main Page] for detaljar.

====
