= Tilgang
:page-en: Accessibility
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

== Styring med mus

For å bruke GeoGebra kun med musa, er det mogleg å vise eit xref:/Virtuelt_tastatur.adoc[virtuelt tastatur]. Vel
menypunktet '_Tastatur_ frå xref:/Vis_meny.adoc[Vis-menyen]. Du kan bruke dette tastaturet ved å trykke på _tastane_ med
musa.

[NOTE]
====

*Merk:* Det er fleire symbol tilgjengeleg enn på eit vanleg tastatur (t.d. _pi_, _integral_, _alfa_ med fleire). Dersom
du trykkar på knappen [.kcode]#AltG# på det virtuelle tastaturet får du opp fleire teikn.

====

== Styring med tastaturet

For å opne ein meny ved kun å bruke tastaturet trykkar du [.kcode]#Alt# og piltastar (på Windows). På Mac må du først
aktivere _full tastaturtilgang_; trykk [.kcode]#Ctrl# + [.kcode]#F1#. Du kan då velje menyar ved å bruke [.kcode]#Ctrl#
+ [.kcode]#F2# eller på nokre tastatur [.kcode]#Fn# + [.kcode]#Ctrl# + [.kcode]#F2#.

For meir, sjå sida xref:/Tastatursnarvegar.adoc[Tastatursnarvegar]. I tillegg er alle vala i
xref:/Eigenskapar.adoc[eigenskapar] tilgjengeleg ved bruk av xref:/commands/Scripting_Kommandoar.adoc[kommandoar for
scripting].

== GeoGebra Basis

For å gjere GeoGebra enklare å bruke for yngre elevar er det laga ein enklare versjon,
xref:/GeoGebraBasis.adoc[GeoGebraBasis], som har større fontar og færre GUI-funksjonar.
