= Verktøytips
:page-en: Tooltips
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Verktøytips er tekstar som vert vist ved sida av musepekaren når du held han over eit objekt i
xref:/Grafikkfelt.adoc[grafikkfeltet]. Under fana _Avansert_ i xref:/Eigenskapar.adoc[eigenskapar] kan du velje dei
følgjande modusane for verktøytips:

Automatisk::
  Verktøytips vert vist dersom xref:/Algebrafelt.adoc[algebrafeltet] er aktivt. Tipset inneheld type objekt og namn. Ved
  xref:/Frie_objekt_avhengige_objekt_og_hjelpeobjekt.adoc[avhengige objekt] viser verktøytipset også ei
  objektbeskriving.
På::
  Verktøytips vert vist uavhengig av om algebrafeltet er aktivt eller ikkje. Innhaldet er det same som for _Automatisk_.
Av::
  Verktøytips vert ikkje vist.
Objekttekst::
  xref:/Namn_og_objekttekstar.adoc[Objektteksten] til eit objekt vert brukt som verktøytips. Du kan setje objektteksten
  under fana _Basis_ i xref:/Eigenskapar.adoc[eigenskapar].
Neste celle::
  Dersom objektet er ei celle i xref:/Rekneark.adoc[reknearket] vil innhaldet i cella til høgre for cella verte brukt
  som verktøytips.

Under menypunktet *Avansert* i xref:/Innstillingar.adoc[Innstillingar-menyen] kan du velje språk og varigheit på
verktøytipsa.
