= Verktøy
:page-en: Tools
ifdef::env-github[:imagesdir: /nn/modules/ROOT/assets/images]

Verktøy let deg enkelt lage nye objekt ved å bruke musa. Alle verktøya har samsvarande xref:/Kommandoar.adoc[kommandoar]
som kan verte brukt for meir kompliserte konstruksjonar.

Konstruksjonsverktøya kan verte aktivert frå xref:/Verktøylinje.adoc[verktøylinja]. Du kan trykkje på den lille pila i
nedre høgre hjørne av eit ikon for å opne ei verktøykasse med liknande verktøy. Du kan også velje frå
xref:/Verktøymeny.adoc[Verktøymenyen].

Som standard er verktøya ordna i tolv verktøybokser:

* xref:/Verktøy_for_flytting.adoc[Verktøy for flytting]
* xref:/Punktverktøy.adoc[Punktverktøy]
* xref:/Linjeverktøy.adoc[Linjeverktøy]
* xref:/Verktøy_for_spesielle_linjer.adoc[Verktøy for spesielle linjer]
* xref:/Verktøy_for_mangekantar.adoc[Verktøy for mangekantar]
* xref:/Verktøy_for_sirklar_og_bogar.adoc[Verktøy for sirklar og bogar]
* xref:/Verktøy_for_kjeglesnitt.adoc[Verktøy for kjeglesnitt]
* xref:/Verktøy_for_måling.adoc[Verktøy for måling]
* xref:/Verktøy_for_omformingar.adoc[Verktøy for omformingar]
* xref:/Verktøy_for_spesielle_objekt.adoc[Verktøy for spesielle objekt]
* xref:/Verktøy_for_objekthandlingar.adoc[Verktøy for objekthandlingar]
* xref:/Generelle_verktøy.adoc[Generelle verktøy]

Du kan endre på desse verktøyboksane og lagre innstillingane. Sjå xref:/Verktøylinje.adoc[Tilpass verktøylinje] for
detaljar.

Du kan lage eigne verktøy i GeoGebra. Sjå sida xref:/Eigne_verktøy.adoc[Eigne verktøy] for detaljar.

I xref:/CAS_delen.adoc[CAS-delen] og xref:/Rekneark.adoc[reknearket] kan du bruke henholdsvis
xref:/CAS_verktøy.adoc[CAS-verktøy] og xref:/Verktøy_for_rekneark.adoc[verktøy for rekneark].
