= Strumento Intersezione

I punti di intersezione di due oggetti possono essere creati in due modi:

* Selezionando due oggetti vengono creati tutti i punti di intersezione (se possibile).
* Facendo clic direttamente sul punto di intersezione di due oggetti viene creato esclusivamente questo _singolo punto
di intersezione_.

[NOTE]
====

Nelle costruzioni geometriche spesso è utile visualizzare solo i tratti delle curve che generano il punto di
intersezione nell'intorno del punto stesso, invece dei grafici globali di tali curve. Per ottenere la visualizzazione
"ristretta" all'intorno del punto di intersezione, selezionare l'opzione _Mostra le linee intersezione troncate_ nella
scheda _Generali_ della xref:/Finestra_di_dialogo_Propriet%C3%A0.adoc[finestra di dialogo Proprietà] del punto, quindi
nascondere le curve che generano l'intersezione.

====

== Intersezioni sui prolungamenti

Per i segmenti, le semirette e gli archi è possibile selezionare l'opzione _Consenti intersezioni sul prolungamento_
nella scheda _Generali_ della xref:/Finestra_di_dialogo_Propriet%C3%A0.adoc[finestra di dialogo Proprietà]. In questo
modo si otterranno anche le intersezioni che appartengono al prolungamento dell'oggetto considerato: ad esempio per
estensione di un segmento o di una semiretta si intende la retta su cui giacciono questi oggetti.

[NOTE]
====

Vedere anche il comando xref:/commands/Intersezione.adoc[Intersezione].

====
