= Strumento Tangenti
:page-en: tools/Tangents
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Attivare lo strumento, quindi:

* Selezionare un punto appartenente a una conica (o a una funzione) per creare le rette tangenti alla conica (o alla funzione), passanti per il punto selezionato.
* Selezionare un punto non appartenente a una conica per creare le rette tangenti alla conica uscenti dal punto selezionato.
* Selezionare un punto non appartenente a una funzione per creare la retta tangente alla funzione nel suo punto di ascissa uguale a quella del
punto selezionato (ad es. data una funzione _f(x)_ e un punto _A_, si ottiene la tangente a _f(x)_ nel punto (x(A),f(x(A))_.
* Selezionare una retta e una conica per creare le rette tangenti alla conica e parallele alla retta selezionata.
* Selezionare due circonferenze per ottenere le loro tangenti comuni (fino a 4)

[NOTE]
====

* Inserire l'equazione esplicita di una conica nella forma stem:[ y = ... ] (ad es. stem:[ y = x^2+2x+1 ]) invece di utilizzare la notazione funzionale stem:[ f(x) = ... ] (ad es. stem:[ f(x) = x^2 + 2x + 1 ]) se si desidera lavorare con una *conica* (parabola) invece che con una *funzione*.

* Vedere anche il comando xref:/commands/Tangenti.adoc[Tangenti].

====
