= Strumento Tetraedro
:page-en: tools/Regular_Tetrahedron
ifdef::env-github[:imagesdir: /it/modules/ROOT/assets/images]

Attivare lo strumento, quindi:

* Selezionare o creare due punti nel piano _xOy_ per generare il tetraedro regolare con spigolo definito dai due punti e una base che giace su tale piano 

oppure

* Selezionare due punti aventi entrambi la stessa coordinata _z = c_ per generare un tetraedro regolare appoggiato sul piano _z = c_, che può essere ruotato attorno allo spigolo definito dai due punti indicati trascinando il terzo vertice della base, creato automaticamente.

oppure

* Selezionare due punti aventi coordinata _z_ diversa per generare un tetraedro regolare avente come spigolo di base i due punti selezionati e come terzo vertice di base un punto avente come coordinata _z_ la media delle coordinate _z_ dei due punti selezionati in precedenza, che può essere ruotato attorno a tale spigolo trascinando il terzo vertice della base, creato automaticamente.

[NOTE]
====

* Vedere anche il comando xref:/commands/Tetraedro.adoc[Tetraedro].

====
