= ChiQuadratTest (Befehl)
:page-en: commands/ChiSquaredTest
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

ChiQuadratTest( <Matrix> )::
  Führt einen http://en.wikipedia.org/wiki/de:Chi-Quadrat-Test[Chi-Quadrat-Test] durch, der die gegebene Matrix der
  beobachteten Häufigkeiten mit der Matrix der erwarteten Häufigkeiten, welche durch die Unabhängigkeitshypothese
  bestimmt wird, vergleicht.
  Die Matrix der erwarteten Häufigkeiten wird intern berechnet. Die erwartete Anzahl von Beobachtungen wird wie folgt
  berechnet:
  stem:[ \text\{erwartete Anzahl von Beobachtungen} = \frac\{\text\{beobachtete Zeilenhäufigkeiten} × \text\{beobachtete
  Spaltenhäufigkeiten}}\{\text\{Totale Häufigkeit}} ]

Die Ergebnisse werden in Form einer Liste als _\{Wahrscheinlichkeitswert, Chi-Quadrat-Test Statistik}_ zurückgegeben.

ChiQuadratTest( <Liste>, <Liste> )

Führt einen http://en.wikipedia.org/wiki/de:Anpassungstest[Anpassungstest] durch, welcher die Liste der beobachteten
Häufigkeiten mit der Liste der erwarteten Häufigkeiten vergleicht.

Die Ergebnisse werden in Form einer Liste als _\{Wahrscheinlichkeitswert, Chi-Quadrat-Test Statistik}_ zurückgegeben.

ChiQuadratTest( <Matrix>, <Matrix> )

Führt einen http://en.wikipedia.org/wiki/de:Chi-Quadrat-Test[Chi-Quadrat-Test] durch, der die gegebene Matrix der
beobachteten Häufigkeiten mit der gegebenen Matrix der erwarteten Häufigkeiten vergleicht.

Die Ergebnisse werden in Form einer Liste als _\{Wahrscheinlichkeitswert, Chi-Quadrat-Test Statistik}_ zurückgegeben.

[EXAMPLE]
====

`++ChiQuadratTest[{{1, 2, 1}, {3, 2, 3}}, {{2, 3, 2}, {4, 2, 3}}]++` liefert _\{0.45, 1.58}_.

====

[EXAMPLE]
====

`++ChiQuadratTest[{1, 2, 3, 4}, {3, 2, 4, 2}]++` liefert _\{0.31, 3.58}_.

====

[EXAMPLE]
====

`++ChiQuadratTest[{{1, 2, 1}, {3, 2, 3}}]++` liefert _\{0.69, 0.75}_.

====
