= Dodekaeder (Befehl)
:page-en: commands/Dodecahedron
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Dodekaeder( <Punkt>, <Punkt>, <Richtung> )::
  Erstellt ein Dodekaeder, welches die (automatisch erstellte) Strecke zwischen den zwei gegebenen Punkten als eine
  Kante hat.
  Die Eckpunkte werden von der gegebenen Richtung eindeutig bestimmt. Die Richtung kann definiert sein durch:
  * einen Vektor, eine Strecke, eine Gerade, einen Strahl *normal* auf die Strecke, oder
  * ein Vieleck, eine Ebene *parallel* zu der Strecke.
  Das erstellte Dodekaeder wird Folgendes aufweisen:
  * eine Fläche, die in der zum/zur gegebenen Vektor/Strecke/Gerade/Strahl normalenstehenden Ebene enthalten ist, mit
  der Strecke als Kante, oder
  * eine Fläche, die in der zum/zur Vieleck/Ebene parallelen Ebene enthalten ist, mit der Strecke als Kante.

Dodekaeder(<Punkt>, <Punkt>, <Punkt>)::
  Erstellt ein Ikosaeder, bei dem die drei eingegebenen Punkte eine Seitenfläche bilden. Die Punkte müssen dabei ein
  gleichseitiges Fünfeck definieren.

Dodekaeder( <Punkt>, <Punkt>)::
  Erstellt ein Dodekaeder mit zwei Punkten einer Seitenfläche, wobei ein dritter Punkt automatisch auf einem Kreis
  erstellt wird, sodass das Dodekaeder um die Strecke zwischen den zwei eingegebenen Punkten rotiert werden kann.

[NOTE]
====

Dodekaeder[A, B] ist eine Kurzschreibweise für Dodekaeder[A, B, C] mit C = Punkt[Kreis[((1-sqrt(5)) A + (3+sqrt(5)) B) /
4, Abstand[A, B] sqrt(10+2 sqrt(5)) / 4, Strecke[A, B]]].

====

[NOTE]
====

Siehe auch die Befehle xref:/commands/Würfel.adoc[Würfel], xref:/commands/Tetraeder.adoc[Tetraeder],
xref:/commands/Ikosaeder.adoc[Ikosaeder], xref:/commands/Oktaeder.adoc[Oktaeder].

====
