= Häufigkeit (Befehl)
:page-en: commands/Frequency_Command
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Häufigkeit( <Liste von Rohdaten> )::
  Erzeugt eine Liste mit der Erscheinungshäufigkeit der einzelnen Elemente (Zahlen oder Texte) der angegebenen Liste.
  Die Liste wird in aufsteigender Reihenfolge der einzelnen Elemente sortiert. Um die Liste der einzelnen, voneinander
  verschiedenen Elemente zu erhalten, können Sie den Befehl xref:/commands/Einzigartig.adoc[Einzigartig] verwenden.

[EXAMPLE]
====

Geben Sie `++Liste1 = { "a", "a", "x", "x", "x", "b" }++` ein. `++Häufigkeit[Liste1]++` erzeugt die Liste _\{ 2, 1, 3
}_. `++Einzigartig[Liste1]++` erzeugt die Liste _\{ "a", "b", "x" }_.

====

Häufigkeit( <Wahrheitswert kumulativ>, <Liste von Rohdaten> )::
  Ist der _Wahrheitswert_ = _false_, so wird dieselbe Liste wie beim Befehl Häufigkeit[<Liste von Rohdaten>] erzeugt.
  Ist der _Wahrheitswert_ = _true_, so wird eine Liste mit kumulativen Häufigkeiten erzeugt.

[EXAMPLE]
====

Geben Sie `++Liste1 = { 0, 0, 0, 1 , 1, 2 }++` ein. `++Häufigkeit[true, Liste1]++` erzeugt die Liste _\{ 3, 5, 6 }_.
`++Häufigkeit[false, Liste1]++` erzeugt die Liste _\{ 3, 2, 1}_. `++Einzigartig[Liste1]++` erzeugt die Liste _\{ 0, 1, 2
}_.

====

Häufigkeit( <Liste von Klassenbereichen>, <Liste von Rohdaten> )::
  Erzeugt eine Liste, die die Erscheinungshäufigkeit der Rohdaten in den angegebenen Listen innerhalb der
  Klassenbereiche angibt. Alle Intervalle haben die Form [a, b), außer das höchste Intervall, dieses hat die Form [a,
  b].

[EXAMPLE]
====

Die Eingabe `++Häufigkeit[{1,2,3},  {1,1,2,3}]++` erzeugt die Liste _\{ 2, 2 }_.

====

Häufigkeit( <Liste von Texten>, <Liste von Texten> )::
  Erzeugt eine Kontingenzmatrix, welche die Anzahl der zusammengefügten Paare der Elemente beider Listen enthält. Die
  Reihen der Matrix entsprechen den Elementen der ersten Liste, und die Spalten entsprechen den Elementen der zweiten
  Liste. Um die Liste der den Häufigkeiten entsprechenden Elemente einer Liste zu erhalten, verwenden Sie den Befehl
  xref:/commands/Einzigartig.adoc[Einzigartig].

[EXAMPLE]
====

Die Eingabe `++Liste1 = {"a", "b", "b", "c", "c", "c", "c"}++` und `++Liste2 =  {"a", "b", "a", "a", "c", "c", "d"}++`.
Der Befehl `++Häufigkeit[ Liste1, Liste2 ]++` erzeugt die Matrix stem:[\begin\{pmatrix} 1 & 0 & 0 & 0\\ 1 &1 & 0 &0 \\ 1
& 0 & 2 & 1 \\ \end\{pmatrix}]

====

[NOTE]
====

Siehe auch den Befehl xref:/commands/Kontingenztafel.adoc[Kontingenztafel].

====

Häufigkeit( <Wahrheitswert kumulativ>, <Liste von Klassenbereichen>, <Liste von Rohdaten> )::
  Ist der _Wahrheitswert_ = _false_, so wird dieselbe Liste wie beim Befehl Häufigkeit[ <Liste von Klassenbereichen>,
  <Liste von Rohdaten>] erzeugt.
  Ist der _Wahrheitswert_ = _true_, so wird eine Liste mit kumulativen Häufigkeiten erzeugt.

Häufigkeit( <Liste von Klassenbereichen>, <Liste von Rohdaten>, <Wahrheitswert Dichte>, <Skalierungsfaktor>
(optional))::
  Erzeugt eine Häufigkeitsliste für den entsprechenden xref:/commands/Histogramm.adoc[Histogramm-Befehl].
  Ist _Wahrheitswert Dichte_ = _false_, so wird dieselbe Liste wie beim Befehl Häufigkeit[ <Liste von Klassenbereichen>,
  <Liste von Rohdaten>] erzeugt.
  Ist _Wahrheitswert Dichte_ = _true_, so wird die Liste mit Häufigkeiten von jeder Klasse erzeugt.

[EXAMPLE]
====

Die Eingabe `++Daten = {1, 2, 2, 2, 3, 3, 4, 4, 4, 4}++` erzeugt die Liste der Rohdaten und die Eingabe
`++Klassen={0, 2, 5}++` die Liste von Klassenbereichen. Die Befehle `++Häufigkeit[Klassen, Daten, false]++` und
`++Häufigkeit[Klassen, Daten]++` erzeugen beide die Liste _\{1, 9}_, aber `++Häufigkeit[Klassen, Daten, true]++` erzeugt
die Liste _\{0.5, 3}_.

====

Häufigkeit( <Wahrheitswert kumulativ>, <Liste von Klassenbereichen>, <Liste von Rohdaten>, <Wahrheitswert Dichte> ,
<Skalierungsfaktor> (optional) )::
  Erzeugt eine Häufigkeitsliste für den entsprechenden xref:/commands/Histogramm.adoc[Histogramm-Befehl].
