= Iterationsliste (Befehl)
:page-en: commands/IterationList
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Iterationsliste( <Funktion>, <Startwert>, <Anzahl der Iterationen n> )::
  Erzeugt eine Liste der Länge _n+1_, deren Elemente Iterationen der Funktion sind, beginnend mit dem Startwert.

[EXAMPLE]
====

Nach der Definition der Funktion `++f(x) = x^2++` liefert der Befehl `++Iterationsliste[f, 3, 2]++` die Liste _{3, 9,
81}_.

====

Iterationsliste( <Ausdruck>, <Variablen>, <Startwert>, <Anzahl n>)::
  Erzeugt eine Liste der Länge _n+1_, deren Elemente Iterationen des Ausdrucks sind, beginnend mit dem Startwert. Bei
  jeder Iteration werden die Variablen im Ausdruck durch die letzten Elemente der Liste ersetzt. Deshalb sollten
  mindestens soviele Startwerte wie Variablen angegeben werden, ansonsten ist das Ergebnis _undefiniert_.

[EXAMPLE]
====

Seien _f~0~_, _f~1~_ Zahlen. `++Iterationsliste[a + b, a, b, {f_0, f_1},5]++` weist den ersten zwei Werten der
resultierenden Liste die Startwerte zu. Danach werden die Werte als _f~2~_ = _f~0~_ + _f~1~_,   _f~3~_ =
_f~1~_ + _f~2~_,   _f~4~_ = _f~2~_ + _f~3~_,   _f~5~_ = _f~3~_ + _f~4~_ berechnet. D.h. für _f~0~_ =
_f~1~_ = 1 wird das Ergebnis _{1, 1, 2, 3, 5, 8}_ sein.

====

[EXAMPLE]
====

Seien _A_ und _B_ Punkte. Der Befehl `++Iterationsliste[Mittelpunkt[A, C], C, {B}, 3]++` berechnet intern die Werte
_C~0~_ = _B_,   _C~1~_ = _Mittelpunkt_[_A_, _C~0~_],   _C~2~_ = _Mittelpunkt_[_A_, _C~1~_],   _C~3~_ =
_Mittelpunkt_[_A_, _C~2~_] und liefert {_C~0~_, _C~1~_, _C~2~_, _C~3~_}. D.h. für _A_ = (0,0) und _B_ = (8,0)
wird das Ergebnis _{(8,0), (4,0), (2,0), (1,0)}_ sein.

====

[NOTE]
====

Siehe auch den Befehl xref:/commands/Iteration.adoc[Iteration].

====
