= LinksseitigerGrenzwert (Befehl)
:page-en: commands/LimitBelow
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

LinksseitigerGrenzwert( <Funktion>, <Wert> )::
  Berechnet den https://de.wikipedia.org/wiki/Grenzwert_(Funktion)#Einseitige_Grenzwerte[linksseitigen Grenzwert] der
  Funktion beim gegebenen Wert.

[EXAMPLE]
====

`++LinksseitigerGrenzwert[1 / x, 0]++` berechnet _stem:[-\infty]_ .

====

[NOTE]
====

Nicht alle Grenzwerte können mit GeoGebra berechnet werden und in diesen Fällen wird _undefiniert_ ausgegeben (ebenso,
wenn das richtige Ergebnis undefiniert ist).

====

== CAS-Ansicht

LinksseitigerGrenzwert( <Ausdruck>, <Wert> )::
  Berechnet den https://de.wikipedia.org/wiki/Grenzwert_(Funktion)#Einseitige_Grenzwerte[linksseitigen Grenzwert] der
  Funktion beim gegebenen Wert.
LinksseitigerGrenzwert( <Ausdruck>, <Variable>, <Wert> )::
  Berechnet den linksseitigen Grenzwert der Funktion in mehreren Variablen für die angegebene Variable beim gegebenen
  Wert.

[EXAMPLE]
====

`++LinksseitigerGrenzwert[ 1/a, a, 0 ]++` berechnet _stem:[-\infty]_ .

====

[EXAMPLE]
====

`++LinksseitigerGrenzwert[1 / x, 0]++` berechnet _stem:[-\infty]_ .

====

[NOTE]
====

Nicht alle Grenzwerte können mit GeoGebra berechnet werden und in diesen Fällen wird _?_ ausgegeben (ebenso, wenn das
richtige Ergebnis undefiniert ist).

====

[NOTE]
====

Siehe auch die Befehle xref:/commands/Grenzwert.adoc[Grenzwert] und
xref:/commands/RechtsseitigerGrenzwert.adoc[RechtsseitigerGrenzwert].

====
