= Lösungen (Befehl)
:page-en: commands/Solutions
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

== CAS-Ansicht

Lösungen[ <Gleichung> ]::
  Löst die angegebene Gleichung für die Variable _x_ und erzeugt eine Liste mit allen Lösungen.
Lösungen[ <Gleichung>, <Variable> ]::
  Löst die angegebene Gleichung für die angegebene, unbekannte Variable und erzeugt eine Liste mit allen Lösungen.
Lösungen[ <Liste von Gleichungen>, <Liste von Variablen> ]::
  Löst das angegebene Gleichungssystem für die Liste von Variablen und erzeugt eine Liste mit allen Lösungen.

[EXAMPLE]
====

* `++Lösungen[{x = 4 x + y , y + x = 2}, {x, y}]++` berechnet _\{\{-1, 3}}_, die einzige Lösung von _x = 4x + y_ und _y
+ x = 2_ und zeigt die Lösung als _stem:[\begin{pmatrix}-1&3\end{pmatrix}]_ an.
* `++Lösungen[{2a^2 + 5a + 3 = b, a + b = 3}, {a, b}]++` berechnet _\{\{-3, 6}, \{0, 3}}_ und zeigt die Lösung als
stem:[\begin{pmatrix}-3&6\\0&3\end{pmatrix}] an.

====

[EXAMPLE]
====

`++Lösungen[x * a^2 = 4a, a]++` liefert \{stem:[\frac\{4}\{x}, 0]}.

====

[EXAMPLE]
====

`++Lösungen[x^2 = 4x]++` liefert _\{0, 4}_.

====

[NOTE]
====

Siehe auch den Befehl xref:/commands/Löse.adoc[Löse].

====
