= Max (Befehl)
:page-en: commands/Max
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Max( <Liste> )::
  Gibt das Maximum der Zahlen in einer Liste an.

[EXAMPLE]
====

`++Max[{-2, 12, -23, 17, 15}]++` berechnet _17_.

====

[NOTE]
====

Handelt es sich bei den Elementen in der Liste nicht um Zahlen, so werden die mit den Objekten verbundenen Zahlen
betrachtet. Zum Beispiel berechnet bei einer Liste von Strecken der Befehl _Max[ <Liste> ]_ jene Strecke mit maximaler
Länge.

====

Max( <Intervall> )::
  Gibt die obere Grenze des Intervalls an.

[EXAMPLE]
====

`++Max[2<x<3]++` ergibt _3_.

====

[NOTE]
====

Es macht keinen Unterschied, ob das Intervall offen oder geschlossen ist.

====

Max( <Zahl>, <Zahl> )::
  Gibt das Maximum zweier Zahlen an.

[EXAMPLE]
====

`++Max[12, 15]++` berechnet _15_.

====

Max( <Funktion>, <Startwert>, <Endwert> )::
  Sei _a_ der Startwert und _b_ der Endwert. Dann berechnet dieser Befehl den höchsten Punkt einer Funktion im Intervall
  [_a, b_]. Dabei sollte die Funktion stetig sein und nur einen Hochpunkt in diesem Intervall haben.

[EXAMPLE]
====

`++Max[ x^3 + 2x^2 - 1, -2, 0 ]++` berechnet den Punkt (-1.33, 0.19).

====

Max( <Liste von Daten>, <Liste von Häufigkeiten> )::
  Gibt das Maximum der Zahlen in der Liste mit zugehörigen Häufigkeiten an.

[EXAMPLE]
====

`++Max[{1, 2, 3, 4, 5}, {5, 3, 4, 2, 0}]++` ergibt 4, die höchste Zahl der ersten Liste, deren Häufigkeit größer als 0
ist.

====

[NOTE]
====

Siehe auch die Befehle xref:/commands/Extremum.adoc[Extremum], xref:/commands/Min.adoc[Min] und Werkzeug
xref:/tools/Funktionsinspektor.adoc[Funktionsinspektor].

====
