= Perioden (Befehl)
:page-en: commands/Periods
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Perioden( <Zinssatz>, <Zahlung>, <Barwert>, <Endwert (optional)>, <Fälligkeit (optional)> )::
  Liefert die Anzahl der Zahlungsperioden einer Investition. Ein konstanter Zinssatz und regelmäßige, konstante
  Zahlungen werden vorausgesetzt.

* *<Zinssatz>* Zinssatz pro Zahlungsperiode.
* *<Zahlung>* Wert der regelmäßigen Zahlung (pro Periode).
* *<Barwert>* Gesamtbetrag, den eine Reihe von zukünftigen Zahlungen zum gegenwärtigen Zeitraum wert ist.
* *<Endwert (optional)>* Zukünftiger Betrag, den Sie nach der letzten Zahlung erreicht haben möchten. Wird kein Endwert
eingegeben, wird dieser mit 0 festgelegt.
* *<Fälligkeit (optional)>* Legt fest, wann die Zahlungen zu tätigen sind. Wird kein Wert oder der Wert 0 eingegeben,
ist die Zahlung am Ende der jeweiligen Periode zu tätigen (nachschüssig). Wird 1 eingegeben, sind die Zahlungen am
Beginn einer Periode zu tätigen (vorschüssig).

[EXAMPLE]
====

`++Perioden[10%/12, -200, -400, 10000]++` liefert eine Anzahl von 39.98 Zahlungen.

`++Perioden[10%/12, -200, -400, 10000, 1]++` liefert eine Anzahl von 39.7 Zahlungen.

[NOTE]
====

Verwenden Sie 10%/12 für den `++<Zinssatz>++` , falIs monatliche Zahlungen bei einem Jahreszinssatz von 10% getätigt
werden sollen.

====

====

[NOTE]
====

Für alle Argumente gilt: Ausgaben werden mit negativen und Einnahmen mit positiven Zahlen angegeben.

====

[NOTE]
====

Siehe auch die Befehle xref:/commands/Zinssatz.adoc[Zinssatz], xref:/commands/Zahlung.adoc[Zahlung],
xref:/commands/Barwert.adoc[Barwert] und xref:/commands/Endwert.adoc[Endwert].

====
