= Schieberegler (Befehl)
:page-en: commands/Slider
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

Schieberegler( <Min>, <Max>, <Schrittweite>, <Geschwindigkeit>, <Breite>, <IstWinkel>, <Horizontal>, <Animiert>,
<Zufällig>)::
  Erzeugt einen xref:/tools/Schieberegler.adoc[Schieberegler]. Die Parametereinstellungen können wie folgt sein:
  * _Min, Max_: Legt das Intervall des Schiebereglers fest. Diese Parameter müssen angegeben werden.
  * _Schrittweite_: Legt die Schrittweite der Werte des Schiebereglers fest - Standardwert: 0.1
  * _Geschwindigkeit_: Legt die Geschwindigkeit des Schiebereglers während einer Animation fest - Standardwert: 1
  * _Breite_: Legt die Breite des Schiebereglers in Pixel fest - Standardwert: 100
  * _IstWinkel_: Legt fest, ob der Schieberegler in Beziehung zu einem Winkel steht. Dieser Parameter kann _true_ oder
  _false_ sein - _false_
  * _Horizontal_: Legt fest, ob der Schieberegler horizontal (_true_) oder vertikal (_false_) angezeigt wird -
  Standardwert: _true_
  * _Animiert_: Legt die automatische Animation des Schiebereglers fest - Standardwert: _false_
  * _Zufällig_: Legt fest, ob der Schieberegler aufeinanderfolgende Werte innerhalb von [Min, Max] annehmen soll
  (_false_) oder ob er zwischen zufälligen Werten innerhalb dieses Intervalls hin und her springen soll (_true_) -
  Standardwert: _false_
