= SetzeHintergrundfarbe (Befehl)
:page-en: commands/SetBackgroundColor_Command
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

SetzeHintergrundfarbe( <Objekt>, <Rot>, <Grün>, <Blau> )::
  Verändert die Hintergrundfarbe des gegebenen Objekts. Das Objekt kann ein Text oder ein Tabellenobjekt sein. Rot, Grün
  und Blau repräsentiert den Anteil der jeweiligen Farbkomponente, von 0 (minimal) bis 1 (maximal). Falls ein Parameter
  _t_ dieses Intervall überschreitet, wird er nach folgender Formel neu berechnet: stem:[2\left|\frac\{t}2-\mathrm
  round\left(\frac\{t}2\right)\right|].
SetzeHintergrundfarbe( <Objekt>, <"Farbe"> )::
  Verändert die Hintergrundfarbe des gegebenen Objekts. Das Objekt kann ein Text oder ein Tabellenobjekt sein. Die Farbe
  wird als xref:/Texte.adoc[Text] eingefügt. Der Befehl akzepiert mehr als hundert englische Farbnamen (siehe
  http://wiki.geogebra.org/en/Reference:Colors[Colors]), und folgende deutsche Farbnamen:

[NOTE]
====

Falls Sie diesen Befehl in einem GeoGebraScript verwenden möchten, müssen Sie die englischen Farbnamen benutzen.

====

* Schwarz
* Dunkelgrau
* Grau
* Dunkelblau
* Blau
* Dunkelgrün
* Grün
* Kastanienbraun
* Scharlachrot
* Rot
* Magenta
* Indigo
* Purpur
* Braun
* Orange
* Gold

* Limone
* Zyan
* Türkis
* Hellblau
* Wasser
* Silber
* Hellgrau
* Pink
* Violett
* Gelb
* Hellgelb
* Hellorange
* Hellviolett
* Helles Purpur
* Hellgrün
* Weiß

 
