= StarresVieleck (Befehl)
:page-en: commands/RigidPolygon_Command
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

StarresVieleck( <Vieleck> )::
  Erzeugt eine Kopie eines beliebigen Vielecks, welche nur verschoben und gedreht werden kann. Das Vieleck kann durch
  Ziehen des ersten Eckpunktes verschoben und durch Ziehen des zweiten Eckpunktes gedreht werden.

StarresVieleck( <Vieleck>, <x-Verschiebung>, <y-Verschiebung> )::
  Erzeugt eine Kopie eines beliebigen Vielecks im angegebenen Abstand, welche nur verschoben und gedreht werden kann
  (wiederum durch Ziehen des ersten bzw. des zweiten Eckpunktes).

StarresVieleck( <Freier Punkt>, ..., <Freier Punkt> )::
  Erzeugt ein Vieleck, dessen Form nicht verändert, sondern nur verschoben und gedreht werden kann (wiederum durch
  Ziehen des ersten bzw. des zweiten Eckpunktes).

[NOTE]
====

Die Kopie macht jede Veränderung des ursprünglichen Vielecks mit. Wenn Sie die Form des Vielecks ändern wollen, muss das
ursprüngliche Vieleck geändert werden.

====
