= TTest2 (Befehl)
:page-en: commands/TTest2_Command
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

TTest2( <Stichprobenliste 1>, <Stichprobenliste 2>, <Seite>, <Boolean GemeinsameVarianz> )::
  Führt einen Zweistichproben-t-Test durch. Dieser testet ob die Mittelwerte der Grundgesamtheiten, aus denen die
  Stichproben stammen, sich unterscheiden. _Seite_ hat als mögliche Werte "<", ">" , "≠". Diese bestimmen die
  Alternative Hypothese wie folgt:
  "<" = Differenz der Mittelwerte < 0
  ">" = Differenz der Mittelwerte > 0
  "≠" = Differenz der Mittelwerte ≠ 0

Wenn _GemeinsameVarianz_ = true, wird angenommen, dass die Varianzen der beiden Grundgesamtheiten gleich sind und die
Stichprobenvarianzen werden in der Berechnung kombiniert ("gepooled").

Wenn _GemeinsameVarianz_ = false, werden die Stichprobenvarianzen nicht kombiniert.

Das Ergebnis wird als Liste in der Form _\{Wert der Wahrscheinlichkeit, t-Teststatistik}_ zurückgegeben.

TTest2( <Stichprobenmittelwert 1>, <Stichprobenstandardabweichung 1>, <Stichprobengröße 1>, <Stichprobenmittelwert 2>,
<Stichprobenstandardabweichung 2>, <Stichprobengröße 2>, <Seite>, <Boolean GemeinsameVarianz> )::
  Führt einen Zweistichproben-t-Test durch. Dieser testet ob die Mittelwerte der Grundgesamtheiten, aus denen die
  Stichproben stammen, sich unterscheiden. _Seite_ und _GemeinsameVarianz_ sind definiert wie oben. Das Ergebnis wird
  als Liste in der Form _\{Wert der Wahrscheinlichkeit, t-Teststatistik}_ zurückgegeben.
