= ZufallszahlBinomialverteilt (Befehl)
:page-en: commands/RandomBinomial_Command
ifdef::env-github[:imagesdir: /de/modules/ROOT/assets/images]

ZufallszahlBinomialverteilt( <Anzahl der Versuche>, <Wahrscheinlichkeit> )::
  Erzeugt eine Zufallszahl von einer Binomialverteilung mit _n_ Versuchen und Wahrscheinlichkeit _p_.

[EXAMPLE]
====

`++ZufallszahlBinomialverteilt[3, 0.1]++` liefert _j ∈ \{0, 1, 2, 3}_, wobei die Wahrscheinlichkeit, _j_ zu erhalten,
gleich der Wahrscheinlichkeit eines Ereignisses ist, welches mit der Wahrscheinlichkeit _0.1_ _j_-mal in drei Versuchen
eintritt.

====

[NOTE]
====

Siehe auch die Befehle xref:/commands/SetzeSeed.adoc[SetzeSeed], xref:/commands/Zufallszahl.adoc[Zufallszahl],
xref:/commands/ZufälligesElement.adoc[ZufälligesElement],
xref:/commands/ZufallszahlNormalverteilt.adoc[ZufallszahlNormalverteilt] und
xref:/commands/ZufallszahlPoissonverteilt.adoc[ZufallszahlPoissonverteilt],
xref:/commands/ZufallszahlGleichverteilt.adoc[ZufallszahlGleichverteilt].

====
