= Alatna traka
:page-en: Toolbar
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Alatna traka se nalazi odmah ispod xref:/Traka_sa_izbornicima.adoc[trake sa izbornicima]. Svaki
xref:/Prikazi.adoc[prikaz] koji je aktivan ima svoju vlastitu alatnu traku u gornjem dijelu. Svaka je alatna traka
podijeljena na grupe, a svaka od njih sadrži jedan ili više xref:/Alati.adoc[alata]. Alatna traka glavnog prozora može
se premjestiti dolje tako da isključite _Pokaži na vrhu_ u podizborniku _Alatna traka_ izbornika
xref:/Izbornik_Pogled.adoc[Pogled].

== Pomoć u alatnoj traci

Pomoć u alatnoj traci nalazi se desno iza alatne trake i sadrži informaciju o načinu upotrebe trenutno označenog alata.
Ako ju ne vidite, morate promijeniti dimenzije prozora. Kada kliknete na pomoć, možete otvoriti web-stranicu za odabrani
alat (gumb Pokaži pomoć na Mreži) .

== Alatne trake za različite prikaze

GeoGebra ima tri alatne trake: jednu za xref:/Grafički_prikaz.adoc[Grafički prikaz], jednu za
xref:/Tablični_prikaz.adoc[Tablični prikaz] i jednu za xref:/CAS_prikaz.adoc[CAS prikaz]. Čim počnete koristiti drugi
xref:/Prikazi.adoc[prikaz] unutar GeoGebra prozora, alatna traka se promijeni. Ako otvorite tablični prikaz ili Cas
prikaz u posebnom prozoru, alatne trake će im biti pridružene.

== Prilagodba alatne trake

Sa sve tri alatne trake možete upravljati koristeći podizbornik _Prilagodba alatne trake…_ izbornika
xref:/Izbornik_Alati.adoc[Alati]. S padajuće liste odaberite alatnu traku koju želite urediti. Kako biste uklonili alat
ili grupu alata iz alatne trake, označite ikonu iz ponuđene liste na lijevoj strani dijaloškog prozora i kliknite na
gumb _Ukloni_. Kako biste dodali alat, odaberite mu ikonu na desnoj listi. Ako ga želite dodati u novu grupu alata,
odaberite na lijevoj listi grupu koja će u alatnoj traci biti lijevo od željene pozicije i kliknite na gumb _Umetni_.
Ako ga želite dodati u postojeću grupu alata, otvorite grupu na lijevoj listi i odaberite alat iznad željene pozicije.
Kako biste premjestili alat iz jedne grupe u drugu, morate ga ukloniti i umetnuti.

[NOTE]
====

Možete vratiti izvornu alatnu traku klikom na gumb _Vrati izvornu alatnu traku_ u lijevom donjem uglu dijaloškog
prozora.

====

Alatna traka u xref:/Dijaloški_okvir_Izvoz_dinamičkog_uratka.adoc[dinamičkom uratku] može se postaviti korištenjem
slijedećih http://wiki.geogebra.org/en/Reference:Applet_Parameters[parametara]].
