= Alati
:page-en: Tools
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Alati omogućavaju stvaranje novih objekata korištenjem miša. Svi oni imaju svoju ekvivalentne
xref:/Naredbe.adoc[naredbe] koje su prikladne kod kompliciranijih konstrukcija.

Alati se aktiviraju pritiskom desne tipke miša na gumb iz xref:/Alatna_traka.adoc[alatne trake]. Možete pritisnuti i
malu strelicu u desnom donjem uglu ikone čime se otvara grupa svih srodnih alata. Drugi način biranja alata je
korištenjem xref:/Izbornik_Alati.adoc[izbornika Alati].

Prema dogovoru, alati su složeni u dvanaest grupa:

* xref:/Alati_za_pomicanje.adoc[Alati za pomicanje]
* xref:/Alati_za_točku.adoc[Alati za točku]
* xref:/Alati_za_crte.adoc[Alati za crte]
* xref:/Posebni_alati_za_pravac.adoc[Posebni alati za pravac]
* xref:/Alati_za_mnogokut.adoc[Alati za mnogokut]
* xref:/Alati_za_kružnicu_i_luk.adoc[Alati za kružnicu i luk]
* xref:/Alati_za_konike.adoc[Alati za konike]
* xref:/Alati_za_mjerenje.adoc[Alati za mjerenje]
* xref:/tools/Transformacijski_alati.adoc[Transformacijski alati]
* xref:/Posebni_alati_za_objekt.adoc[Posebni alati za objekt]
* xref:/tools/Akcijski_alati.adoc[Akcijski alati]
* xref:/tools/Opći_alati.adoc[Opći alati]
* xref:/tools/Korisnički_alati.adoc[Korisnički alati]

Možete izmijeniti redoslijed ovih grupa i spremiti postavke u
http://wiki.geogebra.org/en/Reference:File_Format#.ggb_-_GeoGebra_Worksheet[GeoGebra Worksheet (*.ggb)]. Pogledajte
xref:/Alatna_traka.adoc[prilagodbu alatne trake] za detalje.

[NOTE]
====

Kod većine konstrukcijskih alata lako ćete napraviti novu točku klikom miša na prazni dio grafičkog prikaza.

====

U xref:/CAS_prikaz.adoc[CAS prikazu] i xref:/Tablični_prikaz.adoc[tabličnom prikazu] možete korisititi
xref:/tools/CAS_alati.adoc[CAS alate] i xref:/Alati_tabličnog_prikaza.adoc[alate tabličnog prikaza].
