= Geometrijski objekti
:page-en: Geometric_Objects
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

GeoGebra operira s mnogim tipovima geometrijskih objekata

* xref:/Točke_i_vektori.adoc[Točke i vektori]
* xref:/Pravci_i_osi.adoc[Pravci i osi]
* xref:/Konike.adoc[Konike i lukovi]
* xref:/Funkcije.adoc[Funkcije]
* xref:/Krivulje.adoc[Krivulje]
* xref:/Nejednakosti.adoc[Nejednakosti]
* xref:/Intervali.adoc[Intervali]
== Putanje

Neki od gore spomenutih objekata (pravci, konike, lukovi, mnogokuti, funkcije, nejednakosti jedne varijable, intervali,
liste točaka) označeni su kao _putanje_. Koristeći naredbu xref:/commands/Točka.adoc[Točka] može se definirati
xref:/Točke_i_vektori.adoc[točka] tako da pripada putanji. Svakoj točki na putanji pridružen je parametar putanje, kao
broj između 0 i 1. Kako biste dobili taj parametar možete koristiti naredbu
xref:/commands/ParametarPutanje.adoc[ParametarPutanje].

[NOTE]
====

xref:/Liste.adoc[Liste] drugih putanja također su putanje.

====

== Područja

Također možete ograničiti točku da pripada _području_ (mnogokut, konika, luk, nejednakost dviju varijabli) koristeći
naredbu xref:/commands/TočkaUPodručju.adoc[TočkaUPodručju] ili alat xref:/tools/Točka_na_objektu.adoc[Točka na objektu].

[NOTE]
====

Pogledajte alat xref:/tools/Priveži_Odvoji_točku.adoc[Priveži / Odvoji točku].

====
