= Imenovanje objekata
:page-en: Naming_Objects
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Nekom objektu možete pridružiti određeno ime kada ga kreirate koristeći xref:/Traka_za_unos.adoc[traku za unos]:

* xref:/Točke_i_vektori.adoc[Točke]: U GeoGebri, za naziv točaka rezervirana su velika slova. Jednostavno upišite naziv
(npr., A, P) i zatim znak jednakosti iza kojeg slijede koordinate ili naredbe.

[EXAMPLE]
====

`++A = (2, 4)++`, `++ P = (1; 180°)++`, `++T = Točka[c]++` (pri čemu je c prije zadana krivulja, konika, ili funkcija).

====

* xref:/Točke_i_vektori.adoc[Vektori]: Kako bismo razikovali točke i vektore, vektorima se u GeoGebri pridjeljuju nazivi
s malim slovima. Opet, utipkajte naziv (npr., v, u) i zatim znak jednakosti iza kojeg slijede koordinate ili naredbe.

[EXAMPLE]
====

`++v = (1, 3)++`, `++ u = (3; 90°)++`, `++w = Vektor[A,B]++`

====

* xref:/Pravci_i_osi.adoc[Pravci], kružnice, i xref:/Konike.adoc[konike]: Ovim objektima pridružit ćemo naziv tako da
ukucamo naziv i dvotočku ispred njihove jednadžbe ili naredbi.

[EXAMPLE]
====

`++g: y = x + 3++`, `++c: (x-1)^2 + (y – 2)^2 = 4++`, `++hip: x^2 – y^2 = 2++`, `++el: Elipsa[A,B,3]++`

====

* xref:/Funkcije.adoc[Funkcije]: Možete ih nazvati tako da, na primjer, utipkate, `++f(x) =++` or `++g(x)=++` ispred
jednadžbe funcije ili naredbe.

[EXAMPLE]
====

`++h(x) = 2 x + 4++`, `++q(x) = x^2, trig(x) = sin(x)++`

====

[NOTE]
====

* Ako ručno ne pridjelite naziv objektu, GeoGebra pridjeljuje nazive abecednim redom.
* Možete stavljati znakove za indekse unutar naziva. Na primjer, A~1~ se upisuje kao `++A_1++` i s~AB~ se upisuje kao
`++s_{AB}++`.

====

== Rezervirane oznake

Ovo su oznake koje ne možete koristiti za nazive objekata: x, y, xOs, yOs, zOs, abs, sgn, sqrt, exp, log, ln, ld, lg,
cos, sin, tan, acos, arcos, arccos, asin, arcsin, atan, arctan, cosh, sinh, tanh, acosh, arcosh, arccosh, asinh,
arcsinh, atanh, arctanh, atan2, erf, floor, ceil, round, random, conjugate, arg, gamma, gammaRegularized, beta,
betaRegularized, sec, csc, cosec, cot, sech, csch, coth

U listi simbola trake za unos, naći ćete oznake za slijedeće konstante:

* π - broj pi, kojeg također možete unijeti pomoću tipki [.kcode]#Alt-p#
* ℯ - Eulerov broj, tj. baza eksponencijalne funkcije ℯ^x, kojeg također možete unijeti pomoću tipki [.kcode]#Alt-e#
* ί - imaginarna jedinica, npr. za kompleksni broj z = 3 + ί, koju također možete unijeti pomoću tipki [.kcode]#Alt-i#

Ako varijable e, i nisu još iskorištene, one se automatski čitaju kao ℯ, ί.

Pogledajte još i xref:/Oznake_i_natpisi.adoc[Oznake i natpisi].
