= Info oblačići
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Info oblačići su tekstovi koji nastaju kod kursora kada prevlačite kursor preko objekta u
xref:/Grafički_prikaz.adoc[grafičkom prikazu]. U kartici Dodatno xref:/Dijaloški_okvir_Svojstva.adoc[dijaloškog okvira
Svojstva] možete specificirati način info oblačića:

Automatski::
  Info oblačić se pokazuje samo kada je xref:/Algebarski_prikaz.adoc[algebarski prikaz] aktivan. Info oblačić sadrži tip
  i naziv objekta; kod xref:/Nezavisni_Zavisni_i_Pomoćni_objekti.adoc[zavisnih objekata] info oblačić sadrži opis
  objekta.
Uključeno::
  Info oblačić se pokazuje bilo da je algebarski prikaz aktivan ili ne. Sadržaj info oblačića je jednak kao i kod opcije
  _Automatski_.
Isključeno::
  Info oblačić se ne pokazuje.
Natpis::
  xref:/Oznake_i_natpisi.adoc[Natpis] objekta se koristi kao info oblačić. Natpis možete zadati u kartici Osnovno
  dijaloškog okvira Svojstva.
Slijedeća ćelija::
  Ako je objekt ćelija xref:/Tablični_prikaz.adoc[tablice], sadržaj ćelije se koristi kao info oblačić (tip i naziv
  objekta).

U kartici Dodatno dijaloškog okvira xref:/Dijaloški_okvir_Postavke.adoc[Postavke] možete također specificirati jezik i
trajanje info oblačića (u sekundama).
