= Intervali
:page-en: Intervals
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Interval je skup svih brojeva omeđenih donjom i gornjom granicom. Interval možemo napraviti tako da u
xref:/Traka_za_unos.adoc[traku za unos] upišemo npr. `++2 < x < 3++`. Interval u ovom primjeru je otvoreni interval.
Možete definirati i zatvoreni interval (`++2 ≤ x ≤ 3++`) ili poluotvoreni interval (`++2 ≤ x < 3++`).

[NOTE]
====

Vidi još i xref:/Boolean_vrijednosti.adoc[Boolean vrijednosti].

====

Kako biste odredili pripada li broj _c_ intervalu _r_ upišite `++r(c)++` u traku za unos, rezultat će biti logička
vrijednost. Poopćenje intervala su xref:/Nejednakosti.adoc[Nejednakosti].

== Naredbe za intervale

* Naredbe xref:/commands/Minimum.adoc[Minimum], xref:/commands/Maksimum.adoc[Maksimum],
xref:/commands/Polovište.adoc[Polovište] za interval omeđen brojevima _a_ i _b_ daju redom brojeve _a_, _b_ i
stem:[\frac\{a+b}2]. Rezultat ne ovisi o tome je li interval otovren, zatvoren ili poluotvoren.
* Naredba xref:/commands/Točka.adoc[Točka] daje pomičnu xref:/Točke_i_vektori.adoc[točku] čija x-koordinata pripada
intervalu, a y-koordinata je 0.
* Naredba xref:/commands/TočkaUPodručju.adoc[TočkaUPodručju] daje pomičnu točku čija x-koordinata pripada intervalu, a
y-koordinata se može mijenjati po volji.
