= Nejednakosti
:page-en: Inequalities
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

GeoGebra podržava nejednakosti jedne ili dviju varijabli. Nema ograničenja na broj nejednakosti koje se vide u
xref:/Algebarski_prikaz.adoc[algebarskom prikazu], ali samo specijalne nejednakosti mogu biti ucrtane u
xref:/Grafički_prikaz.adoc[grafičkom prikazu]:

* polinomne nejednakosti jedne varijable, npr. _x^3 > x + 1_ or _y^2>y_,
* kvadratne nejednakosti dviju varijabli, npr. _x^2 + y^2 + x*y ≤ 4_,
* nejednadžbe linearne po jednoj varijabli, npr. _2x > sin(y)_ ili _y < sqrt(x)_.

Za smisao (oznaku) nejednakosti može se koristiti <, >, ≤, ≥. Simboli <= i => također su valjani.

Unija i presjek također su podržani pa će, npr. biti nacrtan presjek__(x>y)&&(x+y<3)__.

Ako želimo da se prikaže rješenje nejednakosti kao jedan ili više intervala na x osi, treba označiti _Pokaži na x-osi_ u
kartici _Stil_ dijaloškog okvira xref:/Dijaloški_okvir_Svojstva.adoc[Svojstva] dane nejednakosti.

Nejednakosti su nalik funkcijama, pa možete testirati zadovoljavaju li _x_ i _y_ nejednakost _a_ tako da ukucate
_a(x,y)_ u xref:/Traka_za_unos.adoc[traku za unos]. Također je valjana i sintaksa _a(A)_ za točku _A_ . Točka A može
biti ograničena na područje zadane nejednakosti korištenjem xref:/commands/TočkaUPodručju.adoc[TočkaUPodručju]. Za
nejednakost jedne varijable _b_, npr. po _x_, Točka[b] dat će točku ograničenu na onaj dio x-osi koji zadovoljava
nejednakost _b_.
