= Opis konstrukcije
:page-en: Construction_Protocol
ifdef::env-github[:imagesdir: /hr/modules/ROOT/assets/images]

Možete pristupiti interaktivnom opisu konstrukcije odabirom podizbornika Opis konstrukcije iz izbornika Pogled. Radi se
o tablici koja prikazuje sve korake konstrukcije. Opis konstrukcije omogućava da ponovite gotovu konstrukciju korak po
korak koristeći xref:/Traka_za_korake.adoc[Traku za korake konstrukcije] na dnu grafičkog prikaza.

== Upravljanje i mijenjanje opisa konstrukcije

Možete koristiti tipkovnicu kako biste prolazili kroz opis konstrukcije::

* Upotrijebite ↑ ‘strelica gore’ na vašoj tipkovnici kako biste se vratili na prethodan korak konstrukcije.
* Upotrijebite ↓ ‘strelica dolje’ na vašoj tipkovnici kako biste išli na slijedeći korak konstrukcije.
* Upotrijebite tipku Home da biste se vratili na početak konstrukcije.
* Upotrijebite tipku End kako biste skočili na kraj konstrukcije.
* Upotrijebite tipku Delete kako biste izbrisali izabrani korak konstrukcije.

[NOTE]
====

Ovo može utjecati na objekte koji ovise o odabranom objektu/koraku konstrukcije.

====

Možete koristiti miš za pomicanje kroz opis konstrukcije:

* Dvostruki klik na redak odabire korak konstrukcije.
* Dvostruki klik na zaglavlje bilo kojeg stupca vraća na početak opisa konstrukcije.
* Povucite mišem i pustite redak kako biste promijenili redoslijed koraka konstrukcije u opisu konstrukcije.

[NOTE]
====

Ovo nije uvijek moguće zbog zavisnosti među objektima.

====

* Kliknite desnom tipkom miša na redak kako biste otvorili _skočni izbornik_ pripadnog objekta.

[NOTE]
====

Možete umetnuti korak konstrukcije bilo gdje: Odaberite redak opisa konstrukcije ispod kojeg želite umetnuti novi korak
konstrukcije. Ostavite dijaloški okvir Opis konstrukcije otvoren dok kreirate novi objekt. Novi korak konstrukcije se
odmah umeće na odabrano mjesto u opisu konstrukcije.

====

Koristeći stupac *_Kontrolna točka_* u izborniku Pogled dijaloškog okvira Opis konstrukcije, možete definirati neke
korake konstrukcije kao kontrolne točke. Ovo vam omogućava da grupirate nekoliko objekata zajedno. Kad se pomičete kroz
konstrukciju koristeći xref:/Traka_za_korake.adoc[Traku za korake konstrukcije], ta grupa objekata se prikazuje
istodobno.

[NOTE]
====

Možete uključiti ili isključiti i druge stupce Opisa konstrukcije koristeći padajući izbornik _Stupci_ dijaloškog okvira
Opis konstrukcije.

====

== Izvoz opisa konstrukcije kao web-stranice

GeoGebra omogućava izvoz opisa konstrukcije u obliku web-stranice. Najprije morate otvoriti Opis konstrukcije koristeći
izbornik Pogled. Zatim kliknite na gumb _Izvoz kao web-stranica_.

U dijaloškom okviru izvoza opisa konstrukcije možete unijeti naslov, autora i nadnevak konstrukcije i izabrati želite li
umetnuti crtež konstrukcije (izvozi crtež xref:/Grafički_prikaz.adoc[grafičkog prikaza] i
xref:/Algebarski_prikaz.adoc[algebarskog prikaza] ukoliko je ovaj drugi otvoren. Možete izabrati i umetanje crteža svih
otvorenih prikaza. Također možete odabrati izvoz opisa konstrukcije u boji. To znači da će retci u opisu konstrukcije
imati boju odgovarajućeg objekta u odgovarajućem koraku konstrukcije. Možete odabrati i pokazivanje ikona alatne trake.

[NOTE]
====

Stvorena HTML datoteka može se otvoriti bilo kojim web-preglednikom (npr. Firefox, Internet Explorer) i mijenjati pomoću
raznih programa za uređivanje teksta (npr. OpenOffice Writer).

====
