= Narzędzie Czworościan
:page-en: tools/Regular_Tetrahedron
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Używając narzędzia:

* Wybierz lub utwórz dwa punkty w płaszczyźnie _xOy plane_, aby utworzyć czworościan foremny, którego jedna krawędź jest zdefiniowana przez podane punkty i leży w płaszczyźnie _xOy_.

lub

* Wybierz dwa punkty o takiej samej współrzędnej _z=c_, aby utworzyć czworościan foremny, którego jedna krawędź jest zdefiniowana przez podane punkty i leży w płaszczyźnie _z = c_. 
Czworościan można obracać wokół tej krawędzi zmieniając położenie trzeciego wierzchołka podstawy, który jest tworzony automatycznie.

lub

* Wybierz dwa punkty o różnych współrzędnych _z_ , aby utworzyć czworościan foremny, którego jedna krawędź jest zdefiniowana przez podane punkty, a trzeci wierzchołek tej samej ściany 
ma współrzędną _z_ równą średniej arytmetycznej współrzędnych _z_ wybranych punktów. Czworościan można obracać wokół tej krawędzi zmieniając położenie trzeciego wierzchołka podstawy, który jest tworzony automatycznie.


[NOTE]
====

* Zobacz także polecenie xref:/commands/Czworościan.adoc[Czworościan].

====
