= Narzędzie Kąt
:page-en: tools/Angle
ifdef::env-github[:imagesdir: /pl/modules/ROOT/assets/images]

Używając narzędzia, utworzysz kąt w następujący sposób:

* Wybierając trzy istniejące punkty lub klikając trzy pozycje w _Widoku Grafiki_. Utworzy kąt, którego wierzchołkiem będzie drugi z punktów, a jego ramiona będą przechodzić przez pozostałe dwa punkty.
* Wybierając dwa odcinki, by utworzyć kąt między nimi.
* Wybierając dwie proste, by utworzyć kąt między nimi.
* Wybierając dwa wektory, by utworzyć kąt między nimi.
* Wybierając wielokąt, by utworzyć wszystkie jego kąty wewnętrzne.

[NOTE]
====

* Kąty tworzone są w kierunku _przeciwnym do ruchu wskazówek zegara_. Dlatego, kolejność wybierania obiektów podczas używania narzędzia _Kąt_ ma znaczenie.
Możesz użyć listy rozwijalnej _Kąt pomiędzy_ w zakładce _Podstawowe_ tab w the xref:/Okno_Ustawień_Obiektu.adoc[okna Ustawień Obiektu] dla kąta, aby ograniczyć jego miarę do określonego przedziału.
* Zobacz także polecenie xref:/commands/Kąt.adoc[Kąt].

====
