= Narzędzie Odległość lub długość
:page-en: tools/Distance_or_Length
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Używając tego narzędzia:

* Klijnij dwa punkty, aby zmierzyć odległość między nimi i wyświetlić ją w _Widoku Algebry_, a także utworzyć w ich środku w _Widoku Grafiki_ dynamiczny tekst zawierający tę samą wartość. 
* Klijnij dwie proste, aby zmierzyć odległość między nimi i wyświetlić ją w _Widoku Algebry_. 
* Klijnij punkt i prostą, aby zmierzyć odległość między nimi i wyświetlić ją w _Widoku Algebry_, a także utworzyć dynamiczny tekst w _Widoku Grafiki_ zawierający tę samą wartość. 
* Klijnij odcinek, aby zmierzyć jego długość i wyświetlić ją jako dynamiczny tekst w _Widoku Grafiki_. 
* Klijnij okrąg lub elipsę, aby zmierzyć ich obwód i wyświetlić go w _Widoku Algebry_, a także utworzyć dynamiczny tekst w _Widoku Grafiki_ zawierający tę samą wartość. 
* Klijnij wielokąt, aby zmierzyć jego obwód i wyświetlić go w _Widoku Algebry_, a także utworzyć dynamiczny tekst w _Widoku Grafiki_ zawierający tę samą wartość.

[NOTE]
====

Zobacz także polecenia xref:/commands/Odległość.adoc[Odległość] i xref:/commands/Długość.adoc[Długość].

====
