= Narzędzie Przecięcie dwóch obiektów
:page-en: tools/Intersect
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Punkty przecięcia dwóch obiektów można tworzyć na dwa sposoby:

* Wybranie dwóch obiektów tworzy wszystkie punkty przecięcia (jeśli to możliwe).
* Bezpośrednie kliknięcie w punkt przecięcia dwóch obiektów tworzy tylko ten _pojedynczy punkt przecięcia_.

[NOTE]
====

Czasami przydatne jest wyświetlanie tylko fragmentów przecinających się obiektów w pobliżu punktu przecięcia. Aby to zrobić, otwórz 
xref:/Okno_Ustawień_Obiektu.adoc[okno dialogowe Ustawienia] punktu przecięcia i zaznacz opcję _Pokaż przecinające się
proste_ w zakładce _Podstawowe_ okna _Ustawienia_ obiektu,a następnie ukryj przecinające się obiekty.

====

== Przecięcia poza obiektami

Dla odcinków, półprostych lub łuków możesz określić, czy chcesz włączyć _Przecięcia oddalonych obiektów_ w zakładce _Podstawowe_ 
xref:/Okno_Ustawień_Obiektu.adoc[okna Ustawienia]. Może to być użyteczne do uzyskania punktów przecięcia leżących na przedłużeniu obiektu. 
Na przykład przedłużeniem odcinka lub półprostej jest prosta, a przedłużeniem łuku jest okrąg.

[NOTE]
====

Zobacz także polecenie xref:/commands/Przecięcie.adoc[Przecięcie].

====
