= Narzędzie Styczne
:page-en: tools/Tangents
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Używając narzędzia:

* Wybierz punkt leżący na krzywej stożkowej (lub na wykresie funkcji), aby utworzyć styczna do krzywej (lub wykresu funkcji) przechodzącą przez dany punkt.
* Wybierz punkt nienależący do krzywej stożkowej, aby utworzyć wszystkie styczne do stożkowej przechodzące przez wybrany punkt.
* Wybierz punkt nienależący do funkcji, aby utworzyć styczną do funkcji w jej punkcie o tej samej współrzędnej _x_ co wybrany punkt. Na przykład, dla danej funkcji _f(x)_ i punktu _A_  nienależącego do niej, narzędzie tworzy styczną do _f(x)_ w punkcie _(x(A), f(x(A))_.
* Wybierz prostą i krzywą stożkową, aby utworzyć styczne do krzywej stożkowej równoległe do wybranej prostej.
* Wybierz dwa okręgi, aby utworzyć ich wspólne styczne (maksymalnie 4).

[NOTE]
====

* Użyj fromy stem:[ y = ... ] (e.g. stem:[ y = x^2+2x+1 ]) zamiast zapisu stem:[ f(x) = ... ] (e.g. stem:[ f(x) = x^2 + 2x + 1 ]) jeśli chcesz pracować z *krzywą stożkową* (parabolą) a nie z *funkcją*.

* Zobacz także polecenie xref:/commands/Styczna.adoc[Styczna].
====
