= Narzędzie 
:page-en: tools/Cube
ifdef::env-github[:imagesdir: /en/modules/ROOT/assets/images]

Używając narzędzia:

* Wybierz lub utwórz dwa punkty na płaszczyźnie  _xOy_, aby utworzyć sześcian, którego jedna krawędź jest zdefiniowana przez dwa podane punkty i leży na płaszczyźnie _xOy_.

lub

* Wybierz dwa punkty o takiej samej współrzędnej _ _z=c_,  aby utworzyć sześcian, którego jedna krawędź jest zdefiniowana przez dwa podane punkty i leży na płaszczyźnie _z = c_. 
Sześcian można obracać wokół tej krawędzi, zmieniając położenie swobodnego wierzchołka podstawy, który jest tworzony automatycznie.

lub

* Wybierz dwa punkty o różnych współrzędnych _z_  aby utworzyć sześcian, którego krawędź jednej z ścian jest zdefiniowana przez podane punkty, a niektóre krawędzie są równoległe do płaszczyzny _xOy_. 
Sześcian można obracać wokół tej krawędzi, zmieniając położenie swobodnego wierzchołka podstawy, który jest tworzony automatycznie.


[NOTE]
====

* Zobacz także polecenie xref:/commands/Sześcian.adoc[Sześcian].

====
