= БиномнаРаспределба Наредба
:page-en: commands/BinomialDist
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

БиномнаРаспределба[ <Број на обиди>, <Веројатност на Поволни настани> ]::
  Го враќа графикот на биномната распрелба https://en.wikipedia.org/wiki/Binomial_distribution[БиномнаРаспределба].
  _Параметри:_
  _Број на испитувања_: Го определува бројот на независни Бернулиеви испитувања
  _Веројатноста за успех_: Се определува веројатноста за успех во еден пробен

БиномнаРаспределба[ <Број на обиди>, <Веројатност на Поволни настани>, <Булова Константа> ]::
  Го враќа графикот на биномна распределба кога _Кумулативни_ = неточни.
  Го враќа графикот на кумулативна биномна распределба кога _Кумулативни_ = точно.
  Првите два параметри се еднакви со претходниот пример за Биномна распределба.
БиномнаРаспределба[ <Број на обиди>, <Веројатност на Поволни настани>, <Вредност на променлива>, <Булова Константа> ]::
  Нека X биде биномна случајна променлива.
  Го враќа P( X = _v_) кога _Кумулативни_ = неточни.
  Го враќа P( X ≤ _v_) кога _Кумулативни_ = точно.
  Првите два параметри се еднакви со претходниот пример за Биномна распределба.

== CAS Специфицна синтакса

Во xref:/s_index_php?title=CAS_View_action=edit_redlink=1.adoc[CAS View] е дозволена само една синтакса:

БиномнаРаспределба[ <Број на обиди>, <Веројатност на Поволни настани>, <Вредност на променлива>, <Булова Константа> ]::
  Нека X биде биномна случајна променлива.
  Го враќа P( X = _v_) кога _Кумулативни_ = неточни.
  Го враќа P( X ≤ _v_) кога _Кумулативни_ = точно.

[EXAMPLE]
====

Да се претпостави пренесување на три пакети на податоци на една дефектна линија. Шансата на произволен пакет пренесен
преку оваа линија ќе биде корумпиран е stem:[ \frac\{1}\{10}], па од тука можност за пренесување на еден пакет е
stem:[\frac\{9}\{10} ].

* `++БиномнаРаспределба[3, 0.9, 0, false]++` дава stem:[ \frac\{1}\{1000} ], веројатноста за ниту еден од трите пакети
се пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 1, false]++` дава stem:[\frac\{27}\{1000}], веројатноста за ниту еден од трите пакети се
пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 2, false]++` дава stem:[\frac\{243}\{1000}], веројатноста за ниту еден од трите пакети
се пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 3, false]++` дава stem:[\frac\{729}\{1000}], веројатноста за ниту еден од трите пакети
се пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 0, true]++` дава stem:[\frac\{1}\{1000}], веројатноста за ниту еден од трите пакети се
пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 1, true]++` дава stem:[\frac\{7}\{250}], веројатноста за ниту еден од трите пакети се
пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 2, true]++` дава stem:[\frac\{271}\{1000}], веројатноста за најмногу две од три пакети
се пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 3, true]++` дава _1_, веројатноста за ниту еден од трите пакети се пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 4, false]++` дава _0_, веројатноста за точно четири на три пакети се пренесува успешно,
* `++БиномнаРаспределба[3, 0.9, 4, true]++` дава _1_, веројатноста за најмногу четири од три пакети се пренесува
успешно.

====
