= ВеибуловаРаспределба Наредба
:page-en: commands/Weibull
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ВеибуловаРаспределба[ <Форма k>, <Обем λ>, x]::
  Создава густина на веројатност со функцијата (pdf) of
  [https://en.wikipedia.org/wiki/Weibull_distribution[Weibull_distribution]] со параметри _k, λ_.
ВеибуловаРаспределба[ <Форма>, <обем>, <Вредност на променливата> ]::
  Ако _Константата_ е точно, создава константна распределба - функција на Веибулова Распределба, инаку создава PDF на
  Веибулова Распределба.
ВеибуловаРаспределба[ <Форма k>, <Обем λ>, <Променлива v> ]::
  Пресметува вредноста на кумулативна распеделба функција на Веибулова Распределба на _V_, односно _веројатноста P (x ≤
  V)_ каде што _x_ е случајна променлива со Веибулова Распределба дадена од страна на параметри _k, λ_.

[NOTE]
====

Ја враќа веројатност за дадена _x_-координата како вредност (или област под Веибулова Распределба - крива лево од
дадената _x_-координата).

====

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е подржана само следната синтакса:

ВеибуловаРаспределба[ <Форма k>, <Обем λ>, <Променлива v> ]: Пресметува вредноста на кумулативна распеделба како
функција на Веибулова Распределба на _V_, односно _веројатноста P (x ≤ V)_ каде што _x_ е случајна променлива со
Веибулова Распределба дадена од страна на параметри _k, λ_.
