= Вметни Наредба
:page-en: commands/Insert
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Вметни[ <објект>, <листа>, <позиција> ]::
  Креира нова листа при што се вметнува објектот во листата на дадената позиција.

[EXAMPLE]
====

`++Вметни[x^2, {1, 2, 3, 4, 5}, -1]++`места _x^2^_ на крајот се добива листата _\{1, 2, 3, 4, 5, x^2^}_.

====

[EXAMPLE]
====

`++Вметни[x^2, {1, 2, 3, 4, 5}, 3]++` места _x^2^_ на третата позиција ја дава листата _\{1, 2, x^2^, 3, 4, 5}_.

====

[NOTE]
====

Ако позицијата е негативен број, позицијата на објектот се број од десно.

====

Вметни[ <листа>, <листа>, <позиција> ]::
  Креира нова листа при што се внесуваат сите елементи на _Листа 1_ во _Листа2_ од дадената позиција.

[EXAMPLE]
====

`++Вметни[{11, 12}, {1, 2, 3, 4, 5}, -2]++` ги вметнува елементите на _Листа 1_ пред последниот елемент на _Листа 2_ ,
односно новата листа е: _\{1, 2, 3, 4, 11, 12, 5}_.

====

[EXAMPLE]
====

`++Вметни[{11, 12}, {1, 2, 3, 4, 5}, 3]++` ги става од елементите на _Листа 1_ од третата позиција (3) преминува со
ставање на елементите од _Листа 2_, а потоа продолжува со елементите од _Листа 1_ и се добива следната нова листа _\{1,
2, 11, 12, 3, 4, 5}_.

====

[NOTE]
====

Ако позицијата е негативен број, позицијата на објектот се број од десно.

====
