= Гама Наредба
:page-en: commands/Gamma
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Гама[ <алфа α>, <бета β>, x ]::
  Ја дава густината на веројатност (PDF) на [https://en.wikipedia.org/wiki/Gamma_distribution%7CГама[распределба]] со
  параметри _α_ и _β_.
Гама[ <алфа>, <бета>, х, <Булова константа> ]::
  Ако константата е _точно_, креира кумулативната функција на гама распределбата (CDF), инаку креира PDF на гама
  распределба.
Гама[ <алфа>, <бета>, <Вредност на променлива> ]::
  Ја пресметува вредноста на кумулативна распределба на гама распределбата на вредноста _v_, т.е. кумулативната
  веројатност _P(X≤v)_ каде _X_ е случајна променлива со гама распределбата дадена од страна на параметри _α_ и _β'_.

[NOTE]
====

Дава веројатноста за вредноста на дадено _x_-координата (односно површината под кривата на гама распределбата која е
лево од дадената _x_-координата).

====

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е подржана само следната синтакса:

Гама[ <алфа>, <бета>, <Вредност на променлива> ]::
  Ја пресметува вредноста на кумулативна распределба на гама распределбата на вредноста _v_, т.е. на кумулативната
  веројатност _P(X≤v)_ каде _X_ е случајна променлива со гама распределбата дадена од страна на параметри _α_ и _β'_.
