= ЕдинеченНормаленВектор Наредба
:page-en: commands/UnitPerpendicularVector
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ЕдинеченНормаленВектор[ <права> ]::
  Дава единечен нормален вектор со должина 1 на дадена линија.
ЕдинеченНормаленВектор[ <отсечка> ]::
  Дава единечен нормален вектор со должина 1 на дадена отсечка.
ЕдинеченНормаленВектор[ <вектор> ]::
  Дава единечен нормален вектор со должина 1 на даден вектор.

[EXAMPLE]
====

Let _v=stem:[\begin\{pmatrix}3\\4\end\{pmatrix}]. `++ЕдинеченНормаленВектор[v]++` дава_
stem:[\begin\{pmatrix}-0.8\\0.6\end\{pmatrix}]__.__

====

[EXAMPLE]
====

`++ЕдинеченНормаленВектор[3x + 4y = 5]++` дава _stem:[\begin\{pmatrix}0.6\\0.8\end\{pmatrix}]_.

====

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е дозволена само една синтакса:

ЕдинеченНормаленВектор[ <вектор> ]::
  Дава единечен нормален вектор со должина 1 на даден вектор.

[EXAMPLE]
====

`++ЕдинеченНормаленВектор[{a, b}]++` дава _\{stem:[\frac\{-b}\{\sqrt\{a^\{2} + b^\{2}}}], stem:[\frac\{a}\{\sqrt\{a^\{2}
+ b^\{2}}}]}_.

====
