= ЕдинеченВектор Наредба
:page-en: commands/UnitVector
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ЕдинеченВектор[ <вектор> ]::
  Го дава векторот со должина 1, која има иста насока и ориентација како на даден вектор.
ЕдинеченВектор[ <права> ]::
  Ја дава насоката на векторот на дадена линија, со должина 1.
ЕдинеченВектор[ <отсечка> ]::
  Ја дава насоката на векторот на даден сегмент, со должина 1.

[EXAMPLE]
====

`++ЕдинеченВектор[3x + 4y = 5]++` дава _stem:[\begin\{pmatrix}0.8\\-0.6\end\{pmatrix}]_.

====

[EXAMPLE]
====

Let _v=stem:[\begin\{pmatrix}3\\4\end\{pmatrix}]. `++ЕдинеченВектор[v]++` дава_
stem:[\begin\{pmatrix}0.6\\0.8\end\{pmatrix}]__.__

====

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е дозволена само една синтакса:

ЕдинеченВектор[ <вектор> ]::
  Го дава векторот со должина 1, која има иста насока и ориентација како на даден вектор.

[EXAMPLE]
====

`++ЕдинеченВектор[{2, 4, 4}]++` дава _\{stem:[\frac\{1}\{3}], stem:[\frac\{2}\{3}], stem:[\frac\{2}\{3}]}_.

====

[EXAMPLE]
====

`++ЕдинеченВектор[{a, b}]++` дава _\{stem:[\frac\{a}\{\sqrt\{a^\{2} + b^\{2}}}], stem:[\frac\{b}\{\sqrt\{a^\{2} +
b^\{2}}}]}_.

====
