= ЕрланговаРаспределба Наредба
:page-en: commands/Erlang
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ЕрланговаРаспределба[ <Форма k>, <Брзина λ>, x ]::
  Ја дава густината на веројатноста со параметри _k, λ_.
ЕрланговаРаспределба[ <Форма k>, <Брзина λ>, x, <Булова кумулативна> ]::
  Ако _Константата_ е точна, создава кумулативна распределба на Ерлангова распределба, инаку создава PDF на Ерлангова
  распределба.
ЕрланговаРаспределба[ <Форма k>, <Брзина λ>, <Вредност на променлива> ]::
  Пресметува вредноста на кумулативна распределба како функција на Ерлангова распределба на _V_, односно веројатноста _P
  (x ≤ V)_ каде што _x_ е случајна променлива со Ерлангова распределба дадена од страна на параметри _k, λ_.

[NOTE]
====

Ја дава веројатноста за _x_- кординатата како вредност (или област под Ерлангова распределбаа како крива лево од
дадената _x_-координата).

====

== CASСинтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е подржана само следната синтакса:

ЕрланговаРаспределба[ <Форма k>, <Брзина λ>, <Вредност на променлива> ]::
  Ја дава вредноста на кумулативна распределба како функција на Ерлангова распределба на _V_, односно веројатноста _P (x
  ≤ V)_ каде што _x_ е случајна променлива со Ерлангова распределба дадена од страна на параметри _k, λ_.
