= Зумирај Наредба
:page-en: commands/ZoomIn
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Зумирај[ <Константа на пропорционалност> ]::
  Зумирање од страна на даден фактор во однос на тековниот зум, центарот на екранот се користи како централна точка за
  зум.

[EXAMPLE]
====

`++ Зумитај[1]++` не прави ништо, `++ZoomIn[2]++` зумира поглед во, `++ Зумирај[0.5]++` е еквивалентно на
`++ОдЗумирај Наредба[2]++`,односно зумира на изглед.

====

Зумирај[ <Константа на пропорционалност>, <Центар> ]::
  Зумира од страна дадени фактор во однос на тековниот зум, вториот параметар одредува центар точка за зумот.
Зумирај[ <минимална-x>, <минимална-y>, <максимална-x>, <максимална-y> ]::
  Го зумира графика на правоаголник дадена од страна на темиња (Min-x, Min-y), (Max-x,Max y). Ако било кој од овие
  параметри се зависни, границата на погледот станува динамична (на пример, `++ Зумитај[-a,-a,a,a]++` прави зум на
  погледот во зависност од лизгачот. За да се избегне ова однесување, се користи
  xref:/commands/КопирајСлободенОбјект.adoc[КопирајСлободенОбјект Наредба].

[NOTE]
====

Ако има повеќе xref:/commands/График_Наредби.adoc[График Наредби] кој се присутни, активно се користи.

====
