= Коефициенти Наредба
:page-en: commands/Coefficients
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Коефициенти[ <Полином> ]::
  Дава листа со сите коефициенти stem:[\\{a_k,a_\{k-1},\ldots,a_1, a_0\}] на полиномот
  stem:[a_kx^k+a_\{k-1}x^\{k-1}+\cdots+a_1x+a_0].

[EXAMPLE]
====

`++Коефициенти[x^3 - 3 x^2 + 3 x]++` дава _\{1, -3, 3, 0}_, односно список на сите коефициенти на stem:[x^3 - 3 x^2 + 3
x].

====

Коефициенти[ <Конусен> ]::
  Дава листа со коефициентите stem:[\\{a, b, c, d, e, f\}] на конусен пресек во општ облик: stem:[a\cdot x^2 + b\cdot
  y^2 + c + d\cdot x\cdot y + e\cdot x + f\cdot y = 0]

[NOTE]
====

За права во имплицитен облик stem:[l: ax + by + c = 0] се добива коефициентите користејќи го синтаксот stem:[x(l), y(l),
z(l)].

[EXAMPLE]
====

Ако е дефинирана правата `++l: 3x + 2y - 2 = 0++`: `++x(l)++` дава 3, `++y(l)++` дава 2, and `++z(l)++` дава -2

====

====

== CAS Поглед

Коефициенти[ <Полином> ]::
  Дава листа на сите коефициенти на полиномот за главната променлива.
Коефициенти[ <Полином>,<Променлива> ]::
  Дава листа на сите коефициенти на полиномот за зададената променлива.

[EXAMPLE]
====

* `++Коефициенти[a^3 - 3 a^2 + 3 a, a]++` дава _\{1, -3, 3, 0}_, односно список на коефициентите на stem:[a^3 - 3 a^2 +
3 a]
* `++Коефициенти[a^3 - 3 a^2 + 3 a, x]++` дава stem:[\\{a^3 - 3 a^2 + 3 a\}]
* `++Коефициенти[a^3 - 3 a^2 x + 3 a x^2,x]++` дава stem:[\\{3a,-3a^2,a^3\}]
* `++Коефициенти[a^3 - 3 a^2 x + 3 a x^2,a]++` дава stem:[\\{1, -3 x, 3x², 0\}]

====

[EXAMPLE]
====

`++Коефициенти[x^3 - 3 x^2 + 3 x]++` дава _\{1, -3, 3, 0}_, односно листа на коефициентите на stem:[x^3 - 3 x^2 + 3 x].

====
