= ЛогаритамскаНормалнаРаспределба Наредба
:page-en: commands/LogNormal
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ЛогаритамскаНормалнаРаспределба[ <аритметичка средина μ>, <стандардна девијација σ>, x ]::
  Ја дава густината на веројатност со параметри _μ, σ_.
ЛогаритамскаНормалнаРаспределба[ <аритметичка средина μ>, <стандардна девијација σ>, x, <булова константа> ]::
  Ако _Константата_ е точна, создава константна густина, инаку создава PDF на нормална распределба.
ЛогаритамскаНормалнаРаспределба[ <аритметичка средина μ>, <стандардна девијација σ>, <вредност на променлива v> ]::
  Ја дава вредноста на константната распределба со веројатноста _P (x ≤ V)_ така што _x_ е случајна променлива со
  нормална распределба дадена од страна на параметри _μ, σ_.

[NOTE]
====

Ја дава вредноста од _x_-кординатата.

====

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е подржана само следната синтакса:

ЛогаритамскаНормалнаРаспределба[ <аритметичка средина μ>, <стандардна девијација σ>, <вредност на променлива v> ]

Ја дава вредноста на константната распределба со веројатноста _P (x ≤ V)_ така што _x_ е случајна променлива со нормална
распределба дадена од страна на параметри _μ, σ_.
