= Низа Наредба
:page-en: commands/Sequence
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Низа[ <израз>, <променлива>, <од број>, <до број> ]::
  Дава листа на објекти креирани со користење на даден израз на индексот _i_ кој се движи од бројот _а_ до број _b_.
Низа[ <израз>, <променлива i>, <од број a>, <до број b>, <чекор>]::
  Дава листа на објекти креирани со користење од даден израз и на индексот _j_ кој се движи од бројот _a_ на бројот _b_.
Низа[ <до број b> ]::
  Дава листа на броеви од 1 до _b_, т.е. \{1, 2, ..., b}.

[EXAMPLE]
====

`++L = 2^Низа[4]++` дава низа со вредности _\{2, 4, 8, 16}_.

====

[EXAMPLE]
====

`++L = Низа[(2, j), j, 1, 3, 0.5]++` дава листа на точки чија _y_-координата е во опсег од 1 до 3 со пораст од 0,5:
`++L = {(2, 1), (2, 1.5), (2, 2), (2, 2.5), (2, 3)}++`.

====

[EXAMPLE]
====

`++L = Низа[(2, i), i, 1, 5]++` дава листа на вредности чија _y_-координати имаат опсег од 1 до 5:
`++L = {(2, 1), (2, 2), (2, 3), (2, 4), (2, 5)}++`.

====

[NOTE]
====

Види и xref:/commands/Листа_Наредби.adoc[Листа Наредби] за повеќе информации.

====

== CAS Syntax

Низа[ <израз>, <променлива j>, <од број a>, <до број b>, <чекор>]::
  Дава листа на објекти креирани со користење од даден израз и на индексот _j_ кој се движи од број _a_ на бројот _б_ се
  врши зголемување.
Низа[ <израз>, <променлива ј>, <од број a>, <до број b>, <чекор>]::
  Дава листа на објекти креирани со користење од даден израз и на индексот _ј_ кој се движи од број _a_ на бројот _б_ се
  врши зголемување.
Низа[ <до број b> ]::
  Дава листа на броеви од 1 до _b_, т.е. \{1, 2, ..., b}.

[EXAMPLE]
====

`++L = 2^Низа[4]++` дава низа со вредности _\{2, 4, 8, 16}_.

====

[EXAMPLE]
====

`++Низа[x^j, j, 1, 10, 2]++` генерира низа _\{x, x³, x⁵, x⁷, x⁹}_.

====

[EXAMPLE]
====

`++Низа[x^j, j, 1, 10]++` генерира низа _\{x, x², x³, x⁴, x⁵, x⁶, x⁷, x⁸, x⁹, x¹⁰}_.

====
