= Паскал Наредба
:page-en: commands/Pascal
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Паскал[ <Број на поволни настани r>, <веројатност на поволниот настан p> ]::
  _Параметри_
  _Број на успеси_: број на независни Бернулиеви испитувања кои мора да бидат успешни
  _Веројатноста за успех_: веројатноста за успех во една проба.

Паскал[ <Број на поволни настани r>, <веројатност на поволниот настан p> ,<булова константа> ]::
  Го дава графикот на Паскаловата распределба кога _Константата_ = неточна.
  Го дава графикот на Паскаловата распределба кога _Константата_ = точна.
  Првите два параметри се исти како погоре.
Паскал[ <Број на поволни настани r>, <веројатност на поволниот настан p>, <вредност на променливата>, <булова константа>
]::
  Ако X е случајна Паскалова променлива.
  Го дава P( X = _v_) кога _Константата_ =неточна.
  Го дава P( X ≤ _v_) кога _Константата_ = точна.
  Првите два параметри се исти како погоре.

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е поддржана само следната синтакса:

Паскал[ <Број на поволни настани r>, <веројатност на поволниот настан p>, <вредност на променливата>, <булова константа>
]::
  Ако X е случајна Паскалова променлива.
  Го дава P( X = _v_) кога _Константата_ =неточна.
  Го дава P( X ≤ _v_) кога _Константата_ = точна.
