= ПоасоноваРаспределба Наредба
:page-en: commands/Poisson
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ПоасоноваРаспределба[ <аритметичка средина> ]::
  Го дава графикот на ПоасоноваРаспределба со вредност λ.
ПоасоноваРаспределба[ <аритметичка средина>, <булова константа> ]::
  Го дава графикот на Поасонова распределба кога _Константата = неточна_.
  Го дава графикот на константната Поасонова распределба кога _Константата = точна_.
  Првиот параметар е еднаков како погоре.
ПоасоноваРаспределба[ <аритметичка средина>, <вредност на променлива>, <Булова кумулатива> ]::
  Ако X е случајна Поасонова променлива.
  Дава P( X = _v_) кога _Константата_ = неточна.
  Дава P( X ≤ _v_) кога _Константата_ = точна.
  Првиот параметар е еднаков како погоре.

== CAS Специфична синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е поддржана само следната синтакса: ПоасоноваРаспределба[ <аритметичка средина>,
<вредност на променлива>, <Булова кумулатива> ]

Ако X е случајна Поасонова променлива.

Дава P( X = _v_) кога _Константата_ = неточна.

Дава P( X ≤ _v_) кога _Константата_ = точна.

Првиот параметар е еднаков како погоре.
