= ПоставиБоја Наредба
:page-en: commands/SetColor
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ПоставиБоја[ <Објект>, <Црвена>, <Зелена>, <Сина> ]::
  Ја менува бојата на даден објект. Црвена, зелена и сина го претставува износот на соодветните компоненти на бојата, 0
  е минималната и 1 максимaлната. Број _t_ го надминува овој интервал и е одбележан со функцијата
  stem:[2\left|\frac\{t}2-\mathrm round\left(\frac\{t}2\right)\right|].
ПоставиБоја[ <Објект>, "<боја>" ]::
  Ја менува бојата на даден објект. Бојата е внесена како xref:/commands/Текст.adoc[Текст Наредба]. Командата прифаќа
  повеќе од сто англиски имиња на бои. Некои од нив може да се користат и на национални јазици кои се наведени подолу.

* Црна
* ТемноСива
* Сива
* ТемноСина
* Сина
* ТемноЗелена
* Зелена
* Костенлива
* Пурпурна
* Црвена
* СветлоРозова
* Индиго
* Виолетова
* Кафеава
* Портокалова
* Златна

* СветлоЖолта
* СветлоТиркизна
* Тиркизна
* Light Blue
* ЗеленоПлава
* Сребрена
* СветлоСива
* Розова
* СветлоВиолетова
* Жолта
* СветлоЖолта
* СветлоПортокалова
* ПосветлоВиолетова
* СветлоВиолетова
* СветлоЗелена
* Бела

 
