= Прост Наредба
:page-en: commands/Sample
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Примерок[ <листа>, <големина> ]::
  враќа листа од _n_ случајно избрани елементиод _L_; елементиме можат да бидат избрани неколку пати.
Примерок[ <листа L>, <обем n>, <булеан за замена> ]::
  враќа листа од _n_ случајно избрани елементи од__L__; елементиме можат да бидат избрани неколку пати ако и само ако
  последниот параметар е точен.

[EXAMPLE]
====

`++Примерок[{1, 2, 3, 4, 5}, 5, true]++` дава примерок _\{2, 3, 3, 4, 5}_.

====

[EXAMPLE]
====

`++Примерок[{1, 2, 3, 4, 5}, 5]++`дава примерок _\{1, 2, 1, 5, 4}_.

====

== CAS Syntax

Примерок[<листа>, <големина>]::
  враќа листа од _n_ случајно избрани елементиод__L__; елементиме можат да бидат избрани неколку пати.
Примерок[ <листа L>, <обем n>, <булеан за замена> ]::
  враќа листа од _n_ случајно избрани елементиод__L__; елементиме можат да бидат избрани неколку пати ако и само ако
  последниот параметар е точен.

[EXAMPLE]
====

Листата може да содржи и листи: Нека _листа1_ е _\{1, 2, 3}_.`++Примерок [{листа1, 4, 5, 6, 7, 8}, 3, false]++` дава
примерок _\{6, \{1, 2, 3}, 4}_.

====

[EXAMPLE]
====

`++Примерок[{-5, 2, a, 7, c}, 3]++` дава примерок__\{a, 7, -5}__.

====
