= СлучаенБрој Наредба
:page-en: commands/RandomUniform
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

СлучаенПомеѓу[ <најмал цел број>, <најголем цел број> ]::
  Генерира случаен цел број помеѓу _најмалиот_ и _најголемиот_ број (вклучувајќи ги и нив).
СлучаенПомеѓу[ <најмал цел број>, <најголем цел број, Булова > ]::
  Ако __Булова__=_true_, генерира случаен цел број помеѓу _најмалиот_ и _најголемиот_ (вклучувајќи ги и нив), кој се
  обновува само еднаш (при отворање на датотеката и на поништи/повтори).

[EXAMPLE]
====

`++СлучаенПомеѓу[0, 10]++` Генерира случаен цел број помеѓу _0_ и _10_ (вклучувајќи ги и _0_ и _10_)

====

[NOTE]
====

Притискај [.kcode]#F9# за да се види разликата помеѓу овие две синтакси.

====

== CAS Syntax

СлучаенПомеѓу[ <најмал цел број>, <најголем цел број> ]::
  Генерира случаен цел број помеѓу _најмалиот_ и _најголемиот_ број (вклучувајќи ги и нив).

[EXAMPLE]
====

`++СлучаенПомеѓу[0, 10]++` Генерира случаен цел број помеѓу _0_ и _10_ (вклучувајќи ги и _0_ и _10_)

====

[NOTE]
====

Види и xref:/ПоставиСеме_Наредба.adoc[ПоставиСеме наредба],
xref:/commands/СлучаенЕлемент.adoc[СлучаенЕлемент наредба],
xref:/СлучајнаБиномна_Наредба.adoc[СлучајнаБиномна наредба],
xref:/СлучајнаНормална_Наредба.adoc[СлучајнаНормала наредба],
xref:/СлучајнаПоасонова_Наредба.adoc[СлучајнаПоасонова наредба],
xref:/СлучајнаРамномерна_Наредба.adoc[СлучајнаРамномерна наредба].

====
