= СлучајнаПоасоноваПроменлива Наредба
:page-en: commands/RandomPoisson
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

СлучајнаПоасоноваПроменлива[ <аритметичка средина> ]::
  Генерира случаен број од Поасоновата распределба во дадена аритметичка средина.

[EXAMPLE]
====

`++СлучајнаПоасоноваПроменлива[3]++` дава случајна вредност од Поасоновата распределба со средната вредност на _3_.

====

[NOTE]
====

Види и xref:/commands/СлучајнаБиномнаПроменлива.adoc[СлучајнаБиномнаПроменлива Наредба] и
xref:/commands/СлучајнаНормалнаПроменлива.adoc[СлучајнаНормалнаПроменлива Наредба].

====

== CAS Синтакса

СлучајнаПоасоноваПроменлива[ <аритметичка средина> ]::
  Генерира случаен број од Поасоновата распределба во дадена аритметичка средина.

[EXAMPLE]
====

`++СлучајнаПоасоноваПроменлива[3]++` дава случајна вредност од Поасоновата распределба со средната вредност на _3_.

====

[NOTE]
====

Види и xref:/commands/СлучајнаБиномнаПроменлива.adoc[СлучајнаБиномнаПроменлива Наредба] и
xref:/commands/СлучајнаНормалнаПроменлива.adoc[СлучајнаНормалнаПроменлива Наредба].

====
