= СлучајнаНормалнаПроменлива Наредба
:page-en: commands/RandomNormal
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

СлучајнаНормалнаПроменлива[ <аритметичка средина>, <стандардно отстапување> ]::
  Генерира случаен број од нормална распределба со средна вредност и стандардна девијација.

[EXAMPLE]
====

`++СлучајнаНормалнаПроменлива[3, 0.1]++` дава случајна вредност од нормална распределба со средната вредност на _3_ и
стандардната девијација на _0,1_.

====

[NOTE]
====

Види и xref:/commands/СлучајнаБиномнаПроменлива.adoc[СлучајнаБиномнаПроменлива Наредба] и
xref:/commands/СлучајнаПоасоноваПроменлива.adoc[СлучајнаПоасоноваПроменлива Наредба].

====

== CAS Синтакса

СлучајнаНормалнаПроменлива[ <аритметичка средина>, <стандардно отстапување> ]::
  Генерира случаен број од нормална распределба со средна вредност и стандардна девијација.

[EXAMPLE]
====

`++СлучајнаНормалнаПроменлива[3, 0.1]++` дава случајна вредност од нормална распределба со средната вредност на _3_ и
стандардната девијација на _0,1_.

====

[NOTE]
====

Види и xref:/commands/СлучајнаБиномнаПроменлива.adoc[СлучајнаБиномнаПроменлива Наредба] и
xref:/commands/СлучајнаПоасоноваПроменлива.adoc[СлучајнаПоасоноваПроменлива Наредба].

====
