= ТИнтервалнаДоверба2 Наредба
:page-en: commands/TMean2Estimate
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ТИнтервалнаДоверба2[ <листа на примерок податоци 1>, <листа на примерок податоци 2>, <ниво>, <булова> ]::
  Калкулира Т Интервал на Доверба проценувајќи од разликите на две популациони аритметичките средини користејќи ги
  дадените податоци на примероците и нивото на сигурност.
  Ако _Pooled_ = true, тогаш варијансите на популацијата се претпоставува дека се еднакви и простите стандардни
  девијации се комбинираат во пресметката.
  Ако _Pooled_ = false, тогаш варијансите на популацијата не се претпоставува дека се еднакви и простите стандардни
  девијации не се комбинираат.
  Резултатите се добиваат во форма на листа како \{долна граница на сигурност, горна граница на сигурност}.

ТИнтервалнаДоверба2[ <аритметичка средина на примерок 1>, <стандардна девијација на примерок 1>, <големина на примерок
1>, <аритметичка средина на примерок 2>, <стандардна девијација на примерок 2>, <големина на примерок 2>, <ниво>,
<булова> ]::
  Пресметува Т Интервал на Доверба проценувајќи од разликите на две популациони аритметичките средини користејќи ги
  дадените податоци на примероците и нивото на сигурност. __Pooled__е дефиниран како погоре.
  Резултатите се добиваат во форма на листа како \{долна граница на сигурност, горна граница на сигурност}.
