= ТРаспределба Наредба
:page-en: commands/TDistribution
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ТРаспределба[ <степен на слобода d>, x ]::
  Дава густина на веројатноста со _d_ степени на слобода.
ТРаспределба[ <степен на слобода d>, x ,<Булова константа>]::
  Ако _Константата_ е точна, креира константна распределба како функција на t-распределбата, инаку создава PDF на
  t-распределбата.
ТРаспределба[ <степен на слобода d>, <вредност на променлива v> ]::
  Ја дава вредноста на константната распределба како функција на t-распределбата на _V_, односно веројатноста _P (x ≤
  V)_ каде што _x_ е случајна променлива со t-распределба и со _d_ степени на слобода .

[NOTE]
====

Ја дава вредноста од _x_ - координатата.

====

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е поддржана следната синтакса:

ТРаспределба[ <степен на слобода d>, <вредност на променлива v> ]::
  Ја дава вредноста на константната распределба како функција на t-распределбата на _V_, односно веројатноста _P (x ≤
  V)_ каде што _x_ е случајна променлива со t-распределба и со _d_ степени на слобода .
