= Триаголен Наредба
:page-en: commands/Triangular
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Триаголен[ <долна граница>, <горна граница>, <начин>, x ]::
  Ја дава густината на веројатност со параметри _мин, макс, мод_.
Триаголен[ <долна граница>, <горна граница>, <начин>, x, <булова константа> ]::
  Ако _Константата_ е точна, создава константна распределба како функција на триаголни распределби, инаку ја создава
  густината на веројатност како функција на триаголна распределба. '.
Триаголен[ <долна граница>, <горна граница>, <начин>, <вредност на променлива> ]::
  Ја дава вредноста на константната распределба како функција на триаголна распределба на _V_, односно веројатноста _P
  (x ≤ V)_ каде што _x_ е случајна променлива со триаголена распределба дадена од страна на параметрите _мин, макс,
  мод_.

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е поддржана само следната синтакса:

Триаголен[ <долна граница>, <горна граница>, <начин>, <вредност на променлива> ]::
  Ја дава вредноста на константната распределба како функција на триаголна распределба на _V_, односно веројатноста _P
  (x ≤ V)_ каде што _x_ е случајна променлива со триаголена распределба дадена од страна на параметрите _мин, макс,
  мод_.
