= ТТест2 Наредба
:page-en: commands/TTest2
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ТТест2[ <листа на примерок податоци 1>, <листа на примерок податоци 2>, <дно>, <булова> ]::
  Изведува еден T тест за разликите на две Аритметички Средини на популацијата користејќи ја дадената листа на податоци
  од примерокот. _Крајот_ има три можности "<", ">" , "≠"кои ја определуваат Алтернативната Хипотеза како што следи:
  "<" = разликите на Аритметичките Средини < 0
  ">" =разликите на Аритметичките Средини > 0
  "≠" = разликите на Аритметичките Средини ≠ 0
  Ако Pooled = true, тогаш варијансите на популацијата се претпоставува дека се еднакви и простите стандардни девијации
  се комбинираат во пресметката.
  Ако Pooled = false, тогаш варијансите на популацијата не се претпоставува дека се еднакви и простите стандардни
  девијации не се комбинираат.
  Резултатите се даваат во форма на листа \{P вредност, T статистички тест}.

ТТест2[ <аритметичка средина на примерок 1>, <стандардна девијација на примерок 1>, <големина на примерок 1>,
<аритметичка средина на примерок 2>, <стандардна девијација на примерок 2>, <големина на примерок 2>, <дно>, <булова> ]

Изведува еден T тест за разликите на две Аритметички Средини на популацијата користејќи ја дадената статистика на
примерокот. _Pooled_ и _Крајот_ се дефинирани како погоре.
