= ФРаспределба Наредба
:page-en: commands/FDistribution
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ФРаспределба[ <Броител на Степени на слобода>, <Именител на степени на слобода>, х ]::
  Ја дава густината на веројатност со параметри__n, d__.
ФРаспределба[ <Броител на Степени на слобода>, <Именител на степени на слобода>, х, <Булова кумулатива> ]::
  Ако _Константата_ е точна, креира константна распределба на F-распределбата, инаку создава PDF на F-распределбата.
ФРаспределба[ <Броител на Степени на слобода>, <Именител на степени на слобода>, <Вредност на променлива> ]::
  Ја дава вредноста на константната распределба на F-распределбата на _V_, односно веројатноста _P (x ≤ V)_ каде што _x_
  е случајна променлива со F-распределба дадена од страна на параметри на 'N, d__.__

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е поддржана само следната синтакса:

ФРаспределба[ <Броител на Степени на слобода>, <Именител на степени на слобода>, <Вредност на променлива> ]::
  Ја дава вредноста на константната распределба на F-распределбата на _V_, односно веројатноста _P (x ≤ V)_ каде што _x_
  е случајна променлива со F-распределба дадена од страна на параметри на 'N, d__.__
