= Фреквенција Наредба
:page-en: commands/Frequency
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Фреквенција[ <листа на податоци> ]::
  Враќа листа со бројот на појавување на секоја уникатна вредност, во дадената листа од податоци. Овој влезна листа може
  да биде нумеричка или текстуална. Листата е подредена по растечки редослед на уникатните вредности. За да добиете
  листа на соодветните уникатни вредности користете ја командата ЛистанаЕдинствени[ <листа од податоци >]

[EXAMPLE]
====

Внесете `++листа1 =  {"а", "а" "Х", "Х", "Х", "б"}++`. `++Фреквенција [листа1]++` враќа листа \{ 2, 1, 3 }.
`++ЛистанаЕдинствени [листа1]++` враќа листа \{"А", "б", "x",}.

====

Фреквенција[ <кумулативна>, <листа на податоци> ]::
  Ако кумулативна = false, враќа иста листа како Фреквенција[ <листа на податоци> ]
  Ако кумулативна = true, враќа листа на кумулативни фреквенции за Фреквенција[ <листа на податоци> ]

[EXAMPLE]
====

Внесете `++листа1 = { 0, 0, 0, 1 , 1, 2 }++`.`++Фреквенција[ true, листа1 ]++` враќа листа\{ 3, 5, 6 }.
`++Фреквенција[ false, листа1]++` враќа листа \{ 3, 2, 1}. `++ ЛистанаЕдинствени[листа1]++` враќа листа \{ 0, 1, 2 }

====

Фреквенција[ <листа на класните граници>, <листа на податоци> ]::
  Враќа листа со бројот на појавување на вредност од дадена листа со податоци кои припаѓаат на интервалите формирани од
  дадената класа на граници. Сите интервали освен највисокиот се во форма[a, b). Највисокиот интервал има форма [a, b].

[EXAMPLE]
====

`++Фреквенција[{1,2,3},  {1,1,2,3}]++` враќа листа\{ 2, 2 }.

====

Фреквенција[ <кумулативна>, <листа на класните граници>, <листа на податоци> ]::
  Ако кумулативна = false, враќа иста листа како Фреквенција[ <листа на класните граници>, <листа на податоци> ]
  Ако кумулативна = true, враќа листа на кумулативни фреквенции за Фреквенција[ <листа на класните граници> , <листа на
  податоци> ]

Фреквенција[[<листа на класните граници>, <листа на податоци>, <густина> , <степен на густина> (optional) ]::
  Враќа листа со фреквенции како иxref:/commands/Хистограм.adoc[Хистограм Наредба].

Фреквенција[ <Булова кумулативна>, <листа на класните граници>, <листа на податоци>, <густина>, <степен на густина> ]::
  Враќа листа со фреквенции како иxref:/commands/Хистограм.adoc[Хистограм Наредба].
