= ФреквентнаТабела Наредба
:page-en: commands/FrequencyTable
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ФреквентнаТабела[ <листа на податоци> ]::
  Враќа табела (како текст), чија прва колона е составена од подредена листа на уникатни елементи _L_, а втората колона
  ги содржи фреквенциите на вредностите од првата колона. Листата _L_ може да биде составена или од броеви или од текст.

ФреквентнаТабела[ <Булова кумулативна C>, <листа на класните граници>]::
  Ако _Кумулативна = false_, враќа иста табела како Фреквенција [<L>]
  Ако _Кумулативна = true_, враќа табела чија прва колона е иста како и во ФреквентнаТабела [<L>], а втората ги содржи
  кумулативните фреквенции на вредностите од првата колона.

ФреквентнаТабела[ <листа на класните граници>, <листа на висини> ]::
  Враќа табела (како текст), чија прва колона ги содржи интервалите (класите) ,а втората колона ги содржи фреквенциите
  на броевите од _L_ кои припаѓаат на интервалите од првата колона. Сите интервали освен највисокиот се во форма [a, b).
  Највисокиот интервал е во форма [a, b].

ФреквентнаТабела[ <Булова кумулативна>,<листа на класните граници C>,<листа на класните граници L>]::
  Ако _Кумулативна = false_, враќа иста табела како ФреквентнаТабела[ <листа на класните граници>, <листа на висини> ]
  Ако _Кумулативна = true_,враќа табела чија прва колона е иста како и во ФреквентнаТабела [<L>], а втората ги содржи
  кумулативните фреквенции на вредностите од првата колона.

ФреквентнаТабела[ <листа на класните граници>, <листа на податоци>, <Булова густина>, <степен на густина> ];::
  Враќа табела (како текст), чија прва колона ги содржи интервалите (класите), а втората ги содржи фреквенции за
  соодветната xref:/commands/Хистограм.adoc[Хистограм Наредба].

ФреквентнаТабела[ <Булова кумулативна>, <листа на класните граници>, <листа на податоци>, <Булова густина>, <степен на
густина> ]::
  Враќа табела (како текст), чија прва колона ги содржи интервалите (класите), а втората ги содржи фреквенции за
  соодветната xref:/commands/Хистограм.adoc[Хистограм Наредба].

[NOTE]
====

Оваа команда е слична на xref:/commands/Фреквенција.adoc[Фреквенција Наредба] и xref:/commands/Хистограм.adoc[Хистограм
Наредба]. Статиите за овие команди содржат некои поврзани примери.

====
