= Хистограм Наредба
:page-en: commands/Histogram
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Хистограм[ <листа од гранични вредности>, <листа на висини> ]::
  Дава хистограм со решетки на дадените вредности. Граничната вредност ја одредува ширината и позицијата на секоја лента
  на хистограмот.

[EXAMPLE]
====

`++Хистограм[{0, 1, 2, 3, 4, 5}, {2, 6, 8, 3, 1}]++` креира хистограм со 5 парови на дадените вредности. Првиот пар е
позициониран на интервалот [ _0, 1_], во втората лента е позициониран интервалот [ _1, 2_], и така натаму.

====

Хистограм[ <листа од гранични вредности>, <листа на необработени податоци> ,<Булова густина>, <фактор на скаларна
густина>]::
  Дава хистограм со користење на необработени податоци. Граничната вредност ја одредува ширината и позицијата на секоја
  лента на хистограмот и се користи за да се утврди колку податоци од елементите лежат во секоја класа.

* Ако__Густина = точна__, висината = (фактор на скаларна густина) * (класа фреквенција) / (класа ширина)
* Ако__Густина = лажни__, висината = класа фреквенција

Стандардно, користење Густина = вистински и скаларниот фактор на густина = 1. Ова создава хистограм со вкупна површина =
n, податочни вредности.

[EXAMPLE]
====

(_Дифолтен Хистограм_)

`++Хистограм[{10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true]++` креира хистограм со 3 бари, со висина 0.5
(првиот бар), 0.2 (втор бар), и 0.1 (трета лента).

Овај хистограм има вкупна површина = 0,5 * 0,2 * 10 + 10 + 0,1 * 10 = 8.

====

[EXAMPLE]
====

(_Графот хисограм_)

`++Хистограм[{10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, false]++`креира хистограм со 3 бари, со висина 5
(првиот бар), 2 (втор бар), и 1 (третата лента). Овој хистограм не користи скаларна густина и дава бар височини со
изедначен бројот на вредности во секоја класа.

====

[EXAMPLE]
====

(_Хистограм на релативна фрекфенција_)

`++Хистограм[{10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true, 10/ 8] ++` креира хистограм со 3 бари, со
височина 0,625 (прв бар), 0,25 (втор бар), и 0,125 (трета лента). Овој хистограм користи скаларна густина која е
изедначена со процентот на вредности во секоја класа.

Ако n е бројот на податочни вредности, и класите имаат постојана ширина W, а потоа фактор на скаларната густина = w / N
создава релативен хистограм.

====

[EXAMPLE]
====

(_Нормализиран Хистограм_)

`++Хистограм[{10, 20, 30, 40}, {10, 11, 11, 12, 18, 20, 25, 40}, true, 1/8]  ++` креира хистограм со 3 бари, со височина
0,0625 (прв бар), 0,025 (втор бар), и 0,0125 (трета лента).

Овој хистограм има вкупна површина = 0,0625 * 10 + 0,025 * 10 + 0,0125 * 10 = 1.

Ако n е бројот на податочни вредности, тогаш скаларниот фактор на густина = 1 / n , создава нормализиран хистограм со
вкупна површина = 1. Ова е корисно за монтирање на хистограм со крива густина.

====
