= ХиКвадратна Наредба
:page-en: commands/ChiSquared
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ХиКвадратна[ <степени на слобода>, x]::
  Ја дава густината на веројатност со _r_ степени на слобода.
ХиКвадратна[ <степени на слобода>, x, <булова константа> ]::
  Ако _Константата_ е точна, создава константни распределба на ХиКвадратна распределба, инаку создава PDF на ХиКвадратна
  распределба.
ХиКвадратна[ <степени на слобода>, <вредност на променлива> ]::
  Ја дава вредноста на константната распределба на ХиКвадратна распределба на _V_, односно веројатноста _P (x ≤ V)_ каде
  што _x_ е случајна променлива со ХиКвадратна распределба со _г_ степени на слобода.

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е поддржана само следната синтакса:

ХиКвадратна[ <степени на слобода>, <вредност на променлива> ]::
  Ја дава вредноста на константната распределба на ХиКвадратна распределба на _V_, односно веројатноста _P (x ≤ V)_ каде
  што _x_ е случајна променлива со ХиКвадратна распределба со _г_ степени на слобода.

[EXAMPLE]
====

`++ХиКвадратна[4, 3]++` дава stem:[\gamma(2, \frac\{3}\{2})], што е приближно _0.44_.

====
