= ХиперГеометриски Наредба
:page-en: commands/HyperGeometric
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

ХиперГеометриски[ <големина на популација>, <број на поволни настани>, <големина на примерокот>, <Вредност на
променливата> ]::
  Го дава графикот на распределба.
  _Параметри:_
  _Големината на популацијата_: број на топки во урната.
  _Број на успеси_: број на бели топки во урната.
  _Големина на примерокот_: број на топки составен од урната.

Графикот ја покажува веројатноста на бројот на бели топки во примерокот.

ХиперГеометриски[ <големина на популација>, <број на поволни настани>, <големина на примерокот>, <Булова кумулатива> ]::
  Го дава графикот на ХиперГеометриска распределба кога _Константата_ = неточна.
  Го дава графикот на константна ХиперГеометриска распределба кога _Константата_ = точна.
  Првите три параметри се исти како погоре.

ХиперГеометриски[ <големина на популација>, <број на поволни настани>, <големина на примерокот>, <Вредност на
променливата, <Булова кумулатива> ]::
  Ако X е ХиперГеометриска случајна променлива.
  Дава P( X = _v_) каде _Константата_ = неточна.
  Дава P( X ≤ _v_) каде _Константата_ = точна.
  Првите три параметри се исти како погоре.

== CAS Синтакса

Во xref:/CAS_Поглед.adoc[CAS Поглед] е поддржана следната синтакса:

ХиперГеометриски[ <големина на популација>, <број на поволни настани>, <големина на примерокот>, <Вредност на
променливата, <Булова кумулатива> ]::
  Ако X е ХиперГеометриска случајна променлива.
  Дава P( X = _v_) каде _Константата_ = неточна.
  Дава P( X ≤ _v_) каде _Константата_ = точна.
  Првите три параметри се исти како погоре.

[EXAMPLE]
====

Да се претпостави дека се избрани две топки од вкупно десет топки, од кои две се бели, без враќање на топките.

* `++ХиперГеометриски[10, 2, 2, 0, false]++` дава stem:[\frac\{28}\{45}], веројатноста за избирање на нула бело топки,
* `++ХиперГеометриски[10, 2, 2, 1, false]++` дава stem:[\frac\{16}\{45}], веројатноста за избирање на една бела топка,
* `++ХиперГеометриски[10, 2, 2, 2, false]++` дава stem:[\frac\{1}\{45}], веројатноста за изборање на бели топки,
* `++ХиперГеометриски[10, 2, 2, 3, false]++` дава _0_, веројатноста за избирање на три бели топчиња.
* `++ХиперГеометриски[10, 2, 2, 0, true]++` дава stem:[\frac\{28}\{45}], веројатноста за избирање на нула (или помалку)
Бела топки,
* `++ХиперГеометриски[10, 2, 2, 1, true]++` дава stem:[\frac\{44}\{45}], веројатноста за избирање на еден или помалку
бели топки,
* `++ХиперГеометриски[10, 2, 2, 2, true]++` дава _1_, веројатноста на изборот се намалува или помалку бели топки се
останати
* `++ХиперГеометриски[10, 2, 2, 3, true]++` дава _1_, тој веројатноста за изборот на три или помалку бели топки.

====
