= Características Avanzadas
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Estas son las xref:/Cuadro_de_Propiedades.adoc[propiedades] de los xref:/Objetos.adoc[objetos] a las que se accede a
partir de la pestaña [.kcode]#Avanzado#:

* xref:/Capas.adoc[Capas]
* xref:/Visibilidad_condicional.adoc[Visibilidad Condicional]
* xref:/Colores_Dinámicos.adoc[Colores Dinámicos]
* xref:/Indicaciones.adoc[Indicaciones]

* Seleccionable o no
* xref:/Posición_del_Objeto.adoc[Posición del Objeto]

'''''

* Casillas de xref:/Vistas.adoc[Vista Gráfica 1 y/o Vista Gráfica 2] y/o xref:/Vista_3D.adoc[Vista 3D] para decidir
dónde van a mostrarse el xref:/Objetos.adoc[objeto] en juego

Se pueden indicar aquí, en cuáles de las diferentes vistas se puede mostrar un objeto

¤Gráfica ¤Gráfica 2 ¤Gráfica 3D

y también se puede crear una nueva vista a partir de la alternativa _Crear una nueva vista 2D de ..._ del menú
contextual de un objeto 3D, una nueva opción se propone: ¤Otras vistas

'''''

* xref:/LaTeX.adoc[LaTeX]

Para los xref:/Textos.adoc[textos] se cuenta con una potente alternativa: xref:/LaTeX.adoc[LaTeX]. Permite crear, con
agilidad, fórmulas matemáticas de aspecto claro, adecuado y prolijo.
