= Comandos
:page-revisar:
:page-en: Commands
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

Con la ayuda de los comandos se pueden crear nuevos objetos o modificar los existentes. Se puede consultar la lista que
se ofrece a la derecha, con una selección de comandos habituales según su área de aplicación. También está disponible la
/Categoría:Comandos.adoc[lista completa categorizada] con todos los comandos de GeoGebra para mayores detalles.

[NOTE]
====

*Notas:*

* Presione [.kcode]#Enter# luego de ingresar el comando para crear el objeto correspondiente.
* El resultado de un comando puede nominarse ingresando un nombre sucedido por un signo igual “=”. En el ejemplo que
aparece a continuación, un nuevo punto se llamará S.

[EXAMPLE]
====

La intersección de dos rectas _g_ y _h_ produce un nuevo punto, que puede ingresarse como `++S = Interseca(g, h)++` (ver
xref:/commands/Interseca.adoc[Comando Interseca]).

====

* También se pueden usar subíndices en los nombres de los objetos: A~1~ o s~AB~ se anotan como `++A_1++` y `++s_{AB}++`
respectivamente. Esto es parte de la xref:/LaTeX.adoc[sintaxis de LaTeX].

====
