= GeoGebra
:page-en: GeoGebra
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

== GeoGebra: Ayuda

*http://www.geogebra.org/[Volver a GeoGebra]* &#0151; *xref:/Envío_a_GeoGebra.adoc[Volver a Ayuda de Página Inicial]*

GeoGebra es el nombre de la plataforma para http://www.geogebra.org%7Ccompartir[materiales de GeoGebra]. Se pueden subir
archivos http://www.geogebra.org%7Cdirectamente[desde aquí] sea para compartirlos con docentes y estudiantes o para
conservarlos exclusivamente para acceder desde cualquier vía de conexión propia.

== Búsqueda de Materiales

Basta con anotar en el campo de entrada de la página principal las palabras adecuadas de búsqueda para ir a la búsqueda
de los materiales, A medida que se avanza, filtros sucesivos aparecerán para facilitar el encuentro de lo apropiado
para:

* cierta edad de destinatarios
* idioma y
* tipo de materiales (Libro GeoGebra, Hojas de Trabajo, Herramientas, etc.)

Por omisión, se desplegarán los accesibles para todos los idiomas encabezados por los del señalado como preferido (se
puede modificar en la esquina superior derecha de la página). Se pueden, además, incluir algunas especificaciones de
sintaxis.

id:42::
  para buscar material con id 42
tags:Thales::
  para dar con los que incluyen a "Thales" como etiqueta (_tag_)
Thales -teorema::
  encontrará lo que contenga "Thales" pero no "teorema"
Thales NOT teorema::
  ídem el anterior
Thales AND Taylor::
  buscará materiales con sendos términos
