= Intervalos
:page-en: Intervals
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

== Intervalo

Un intervalo es un conjunto de números entre un límite superior y uno inferior. Para crear, por ejemplo, el intervalo
abierto `++2 <  x <  3++`, basta escribirlo en la xref:/Barra_de_Entrada.adoc[Barra de Entrada].También se puede
establecer abierto (`++2 ≤ x ≤ 3++`) o semi-abierto (`++2 ≤ x < 3++`).

[NOTE]
====

Ver también la sección destinada a xref:/Valores_Lógicos.adoc[Valores Lógicos o _Booleanos_].

====

Para determinar si un número _c_ pertenece a un intervalo _r_ se escribe `++r(c)++` en ña Barra de Entrada para obtener
el valor _booleano_ resultante. La generalización de los intervalos no son sino las
xref:/Inecuaciones.adoc[Inecuaciones].

=== Comandos para Intervalos

* Los comandos xref:/commands/Mínimo.adoc[Mínimo], xref:/commands/Máximo.adoc[Máximo],
xref:/commands/PuntoMedio.adoc[PuntoMedio] para un intervalo con límite inferior _a_ y superior, _b_ ofrece los números
_a_, _b_ y stem:[\frac{a+b}2] respectivamente. El resultado [.underline]#no# depende de la condición de abierto o
cerrado o semi-abierto del intervalo.
* El comando xref:/commands/Punto.adoc[Punto] establece un xref:/Puntos_y_Vectores.adoc[punto] móvil cuya coordenada *x*
pertenece al intervalo y su ordenada es 0.
* El comando xref:/commands/PuntoEn.adoc[PuntoEn] establece un punto móvil cuya abscisa pertenece al intervalo y su
coordenada *y* puede modificarse arbitraria y libremente.
