= Tutoriales
ifdef::env-github[:imagesdir: /es/modules/ROOT/assets/images]

== Aplicaciones Matemáticas GeoGebra

Prueba nuestras https://www.geogebra.org[Aplicaciones GeoGebra] y aprende a graficar funciones, visualizar derviadas e
integrales, transformar objetos con deslizadores, y mucho más. Nuestros tutoriales:

* https://www.geogebra.org/m/u3sxv87w[Aprende Suite Calculadora GeoGebra]
* https://www.geogebra.org/m/vmqxhqxj[Aprende GeoGebra Calculadora Gráfica]
* https://www.geogebra.org/m/cb3u6vtb[Aprende GeoGebra Calculadora CAS]
* https://www.geogebra.org/m/be8nd8zx[Aprende GeoGebra Calculadora Científica]
* https://www.geogebra.org/m/m6rgmhvq[Aprende GeoGebra Geometría]
* https://www.geogebra.org/m/fuznheva[Aprende GeoGebra 3D]
* https://www.geogebra.org/m/MqVqGRux[Aprende GeoGebra Clásico]

El _Modo Examen_ transforma tu teléfono o tableta en una calculadora de mano y te permite usar nuestras aplicaciones en
pruebas y exámenes:

* https://www.geogebra.org/m/zbkpuyg9[GeoGebra en Exámenes]

== Notas GeoGebra

https://www.geogebra.org/notes[GeoGebra Notas] es una aplicación GeoGebra en línea que te permite crear presentaciones
que contengan texto manuscrito, elementos de audio y video, las aplicaciones gráficas de GeoGebra y Graspable Math y
mucho más. Descubre la potencia de GeoGebra Notas en nuestro https://www.geogebra.org/m/evcxeqne[tutorial].

== Geogebra Classroom, Grupos GeoGebra y Recursos

https://www.geogebra.org/classroom[GeoGebra Classroom] es nuestro nuevo entorno, especialmente diseñado para educación
remota. Con GeoGebra Classroom puede asignar tareas interactivas a tus estudiantes y monitorear su progreso en tiempo
real. Echa un vistazo al tutorial: https://www.geogebra.org/m/fstbrmvt[Aprende GeoGebra Classroom].

Comparte https://www.geogebra.org/materials[recursos didácticos], existentes o creados por ti, con tus estudiantes en
https://www.geogebra.org/groups[Grupos GeoGebra].

* https://www.geogebra.org/m/Ucar7PHU[Grupos GeoGebra (tutorial)]
* https://www.geogebra.org/m/XjCeBFS3[Creación de recursos (tutorial)]

== Más ayuda

En nuestro http://help.geogebra.org[Centro de ayuda] se pueden obtener rápidas respuestas a cualquier duda. Además,
nuestro xref:/Manual.adoc[Manual] explica el uso de todos los xref:/Comandos.adoc[comandos] y
xref:/Herramientas.adoc[herramientas] de GeoGebra.
