= Helling Macro
:page-en: tools/Slope
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Met deze knop bereken je d ehelling van een rechte. In het xref:/Tekenvenster.adoc[Tekenvenster] wordt ook een
driehoekje getoond dat deze helling illustreert. De afmeting van dit driehoekje kan je aanpassen in het
xref:/Eigenschappen_dialoogvenster.adoc[Eigenschappenvenster].

(zie ook het commando xref:/commands/Helling.adoc[Helling]).

== Positie van het hellingsdriehoekje

Bij een rechte door twee gegeven punten _A_ en _B_ (in deze volgorde), gecreëerd met de knop
xref:/tools/Rechte_door_twee_punten.adoc[Rechte door twee punten] of het commando xref:/commands/Rechte.adoc[Rechte],
wordt de driehoek op het punt _A_ geplaatst. Bij een rechte _l_ waarvan je de vergelijking ingeeft in het
xref:/Invoerveld.adoc[Invoerveld] (b.v. `++l:x+2y=3++`), wordt de driehoek op het snijpunt met de y-as geplaatst (= het
punt op de rechte _l_ waarvan de x-coördinaat gelijk is aan 0). Je kunt de driehoek op een andere plaats tonen met
volgende instructies. /Sjabloon:Step.adoc[Sjabloon:Stepselecteer] de knop
xref:/tools/Rechte_door_twee_punten.adoc[Rechte door twee punten], klik op de rechte _l_ in twee punten om de punten _C_
en _D_ te creëren; tegelijk wordt een nieuwe rechte gecreëerd /Sjabloon:Step.adoc[Sjabloon:Step]Gebruik de _Hellingknop_
voor de nieuw gecreëerde rechte /Sjabloon:Step.adoc[Sjabloon:Stepverberg] punt _D_
/Sjabloon:Step.adoc[Sjabloon:Stepverplaats] punt _C_ naar de gewenste positie
