= Invulvak invoegen Macro
:page-en: tools/Input_Box
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Je kunt de waarde van een bestaand object (parameter, functievoorschirft, coördinaten van een punt...) wijzigen door -
te dubbelklikken in het algebra venster en het object een nieuwe waarde te geven - het object te herdefiniëren in de
invoerbalk. Je kunt ook in het tekenvenster een _invulvak_ creëren. Dit is een tekstveld waarin je kunt typen om de
waarde van een reeds bestaand object wijzigen. Je creëert een _Invulvak_ door in de _knoppenbalk_ te klikken op de knop
_Invulvak invoegen_. Klik vervolgens in het _tekenvenster_. Typ in het dialoogvenster een
xref:/Labels_en_titels.adoc[titel] voor het invulvak en selecteer in de lijst reeds gedefinieerde objecten, voor welk
object je een invulvak wil creëren.

[NOTE]
====

Zie ook het commando xref:/commands/Invulvak.adoc[Invulvak].

====

[NOTE]
====

Een invulvak is beveiligd tegen onbedoeld wijzigen van de eigenschappen. Je kunt de verwijzing niet zomaar wijzigen en
evenmin het invulvak verwijderen. Je kunt dit enkel na rechtsklikken en uitvinken van _Object fixeren_.

====
