= Tekst invoegen Macro
:page-en: tools/Text
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

Met deze knop kan je zowel statische teksten, dynamische teksten als LaTeX formules in het
xref:/Tekenvenster.adoc[Tekenvenster] tonen.

De plaats van de tekst bepaal je op volgende manieren:

* Klik ergens in het Tekenvenster om op die plaats een tekst te creëren.
* Klik op een punt om een tekst te creëren die aan dit put vastgehecht is.

[NOTE]
====

In het xref:/Eigenschappen_dialoogvenster.adoc[Eigenschappenvenster] kan je de positie van de tekst als _absoluut_ op
het scherm bepalen of _relatief_ t.o.v. het coödinatensysteem.

====

In het dialoogvenster typ je je tekst, die statisch, dynamisch of gemengd kan zijn. Tekst die je rechtstreeks in het
veld _Bewerken_ typt, wordt beschouwd al statisch, d.w.z. hij word niet beïnvloed door wijzigingen van een object. Om
een dynamische tekst te creëren, die de veranderende waarden van een object weergeeft, selecteer je het overeenkomende
object in de drop-down lijst _Objecten_ . De overeenkomende naam wordt getoond in een klein tekstveldje binnen het veld
_Bewerken_. De waarde van het object wordt getoond in het _Voorbeeldscherm_ er onder. Wanneer je rechtsklikt in het
kleine veldje kan je voor elk object "Definitie" of "Waarde" selecteren.

Je kunt ook algebrai¨sche berekeningen en specifieke commando's toepassen op deze objecten. Klik in het kleine veldje
van een object en typ de bewerking of het commando. Het resultaat wordt dynamisch getoond in het Tekenvenster.

Bij het typen van wiskundige formules maak je best gebruik van LaTex. Selecteer hiervoor het aanvinkvakje _LaTeX
Formule_ en selecteer de gewenste formule uit de drop-down lijst. Naast de formules uit deze lijst kan je zelf nog
andere formules gebruiken. Lijsten van LaTeX-formules vind je op tal van websites. Je kunt ook een reeks van wiskundige
symbolen en operatoren selecteren uit de drop-down lijst in de tab _Symbolen_ .

== Zie ook

* xref:/Teksten.adoc[Teksten]
* xref:/LaTeX.adoc[LaTeX]
* xref:/commands/Tekst_Commando_s.adoc[Tekst Commando's]
