= Verplaatsen Macro
:page-en: tools/Move_Tool
ifdef::env-github[:imagesdir: /nl/modules/ROOT/assets/images]

== De knop _Verplaatsen_ in het Tekenvenster

Om xref:/Vrije_afhankelijke_en_hulpobjecten.adoc[Vrije objecten] te verplaatsen, hoef je enkel de de knop _Verplaatsen_
te selecteren. Je kunt hierbij ook

* … het object verwijderen door op /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode] te klikken
* … het object verplaatsen met de pijltoetsen (zie xref:/Animatie.adoc[Animatie])

[NOTE]
====

* Je kunt de knop _Verplaatsen_ ook selecteren met de toetsen /Sjabloon:KeyCode.adoc[Sjabloon:KeyCode].
* Een xref:/tools/Schuifknop.adoc[Schuifknop] verslepen kan je met de rechtermuisknop.

====

== De knop _Verplaatsen_ in het 3D tekenvenster

Met de knop _Verplaatsen_ in het _xref:/3D_tekenvenster.adoc[3D tekenvenster]_ kan je
xref:/Vrije_afhankelijke_en_hulpobjecten.adoc[Vrije punten] verslepen. Om een punt te verslepen in het driedimensionaal
coördinatensysteem kan je kiezen tussen twee modi door te klikken op het punt:

* *Modus _x_-_y_-vlak*: Je kunt het punt verplaatsen evenwijdig met het _x_-_y_-vlak zonder de z-coördinaat te
veranderen.
* *Modus _z_-as*: Je kunt het punt verplaatsen evenwijdig met de _z_-as zonder de _x_- en _y_-coördinaten te veranderen.
