= Агол Алатка
:page-en: tools/Angle
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

/s_index_php?title=Предлошка:ManualPage_action=edit_redlink=1.adoc[Предлошка:ManualPage]

Со оваа алатка можете да креирате агли на различни начини (исто така види команда [.mw-selflink .selflink]#Агол#):

* Кликнете три точки за да се создаде аголот помеѓу овие точки. Втората точка е избрана за теме на аголот.
* Кликнете два сегменти да се создаде аголот помеѓу нив.
* Кликнете две линии да се создаде аголот помеѓу нив.
* Кликнете два вектори да се создаде аголот помеѓу нив.
* Кликнете полигон да се создадат сите агли на овој полигон.

[NOTE]
====

Ако многуаголникот е создаден со избирање на неговите темиња во спротивен правец од движењето на стрелките на
часовникот,_Агол_ алатката ви дава внатрешни агли на многуаголникот.

====

[NOTE]
====

Агол се создава во спротивна насока од движењето на стрелките на часовникот. Затоа, за таа цел изборот на овие објекти е
важен за _Агол_ алатката. Ако сакате да се ограничи максималната големина на агол 180 °, провери _Дозволи рефлекс агол_
на табот _Основни_ на xref:/Дијалог_прозорец_за_карактеристики.adoc[Дијалог прозорец за карактеристики].

====
