= Вметнување текст Алатка
:page-en: tools/Text
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Со оваа алатка можете да креирате статички и динамички текст или LaTeX формули во xref:/Графички_поглед.adoc[Графички
поглед].

Најпрво, треба да ja наведете локацијата на текстот на еден од следниве начини:

* Кликнете во графички поглед за да создадетe нов текст на оваа локација
* Кликнете на точка да се создаде нов текст кој е прикачен на оваа точка.

[NOTE]
====

Можете да ја прецизирате позицијата на еден текст како апсолутна на екранот или во однос на координатниот систем на
основниот таб xref:/Дијалог_прозорец_за_карактеристики.adoc[Дијалог прозорец за карактеристики].

====

Потоа, ќе се појави дијалог каде што може да го внесете вашиот текст, коj можe да бидат статични, динамичен, или мешан.

Текстот кој го пишувате директно во _Уреди_ полето се смета како статички, односно тоа не е под влијание на објектини
модификации. Ако треба да се создаде еден динамички текст,кој прикажува на менување на вредности на објектот, одберете
сродни објект од _објекти_ списокот на спуштање. Соодветното име е прикажано, затворенo во сива кутија, во _Измени_
поле, и неговата вредност се прикажува во _Преглед" кутија. Со десен клик на сивото поле ви овозможува да изберете
"Дефиниција" или "вредност" за секој динамичен објект._

Исто така е можно да се изврши алгебарски операции или се применуваат посебни команди за овие објекти, само кликање на
сивата кутија и пишување на алгебарскa операција или Геогебра xref:/commands/Текст.adoc[Текст Наредба] . Резултатите од
овие операции ќе бидат динамички прикажани во текстот од резултатот, во Графички поглед.

Најдобари визуелни резултати се добиени при користење на латекс форматирање за формули. Неговата употреба е едноставна и
интуитивна: само провери на _LaTeX формула_ , и изберете ja саканaта формула дефинирана од списокот на спуштање. Можете
исто така да изберете различни математички симболи и оператори од _Симболи_ од списокот на спуштање.

== Види исто така

* xref:/Текстови.adoc[Текстови]
* xref:/LaTeX.adoc[LaTeX]
* xref:/commands/Текст_Наредби.adoc[Текст Наредби]
