= Пресек на два објекти Алатка
:page-en: tools/Intersect
ifdef::env-github[:imagesdir: /mk/modules/ROOT/assets/images]

Пресечни точки на два објекти можат да бидат создадени на два начини (види и xref:/commands/Пресек.adoc[Пресек]
Наредба).

* Изборот на два објекти ги создава сите пресечни точки (ако е можно).
* Директно кликнување на пресекот на два објекти создава само _една пресечна точка_.

[NOTE]
====

Понекогаш е корисно да се прикаже само делови од пресекот на објекти во близина на пресечната точка. За да го направите
тоа, десен клик на пресечната точка, и изберете ја опцијата _Прикажи ги исечените линии на пресекот_ во _Основниот_ таб
од _Дијалог прозорец за карактеристики_ на објектот, потоа да се скрие пресекот на објекти.

====

== Надворешни Пресеци

За отсечки, полуправи, или лакови можете да наведете дали сакате да _Дозволите надворешни пресеци_ на _Основниот_ таб од
xref:/Дијалог_прозорец_за_карактеристики.adoc[Дијалог прозорец за карактеристики]. Ова може да се користи за да се добие
пресечни точки кои лежат на продолжувањето на објектот. На пример, продолжувањето на еден отсечка или полуправа е права
линија.
