= アクセシビリティ
:page-en: Accessibility
ifdef::env-github[:imagesdir: /ja/modules/ROOT/assets/images]

[NOTE]
====

アクセシブルなアプレットの例と詳細については， https://www.geogebra.org/m/r2EF8uRx[GeoGebraのアクセシビリティ]をご覧ください．

====

アプレットを設計する場合，すべての生徒が（できるだけ）アクセスできるようにすることが重要である．

:toc:

== フォントの大きさ，色， コントラスト

良いコントラストを持つ大きなフォントの使用は重要ある．アプレットをデザインする前に，オプション ->
フォントサイズで大きいフォントサイズを選択する．また，キーボードショートカットの [.kcode]#Ctrl# + [.kcode]#2#
を使用して，すべてのフォントを大きくし，すべての線を太くすることができる．[.kcode]#Ctrl# + [.kcode]#3#
は，新規オブジェクトのデフォルトを黒色で塗りつぶしなしに設定する．

白地に濃い色を使い，太い線を引くのが理想的である．純粋な
https://snook.ca/technical/colour_contrast/colour.html#fg=FF0000,bg=FFFFFF[赤] と
https://snook.ca/technical/colour_contrast/colour.html#fg=00FF00,bg=FFFFFF[緑] はコントラストがあまりよくないので
https://snook.ca/technical/colour_contrast/colour.html#fg=0000FF,bg=FFFFFF[青] ，
https://snook.ca/technical/colour_contrast/colour.html#fg=226600,bg=FFFFFF[濃い緑] ，
https://snook.ca/technical/colour_contrast/colour.html#fg=990033,bg=FFFFFF[濃い赤] など，濃い色を使うとよい．

もし似たようなオブジェクトを色で区別している場合は，そのうちの一つに破線を使用することも検討されたい．また，自分の配色が良いかどうかをチェックできるウェブサイトもある．例：
https://www.vischeck.com/

== スライダー

スライダーはできるだけ長くすることで，細かい動作が苦手な生徒でも使いやすくする．また，スライダーの両端に _減少_ と
_増加_ のボタンを追加することも検討する．

== キーボードショートカット

生徒は，[.kcode]##Tab##キーを使用して，ワークシート内のオブジェクト間を移動することができる．選択されたくないオブジェクトについては，オブジェクトプロパティ
-> 上級 で **"選択を許す"
のチェックを外しておく**ことが重要である．デスクトップ版では，ボタン，スライダー，チェックボックス，点，入力ボックス以外のオブジェクトのプロパティを切り替えるためのキーボードショートカット
[.kcode]#Ctrl# + [.kcode]#Shift# + [.kcode]#D# がある．

矢印キー[.kcode]##→##，[.kcode]#←#，[.kcode]#↑#，[.kcode]##↓##は，スライダとポイントを選択すると，その移動に使用できる．

[.kcode]#スペース#
は，ボタンのアクティブ，チェックボックスの切り替え，スライダーのアニメーションの開始/停止に使用できる．

[.kcode]#ESC# はワークシートから離れるときに，[.kcode]#Enter# は戻るときに使用する（1ページに複数のGeoGebraワークシートがある場合に便利）．

[.kcode]#+# と [.kcode]#−# は，パス上（例：円上）で点を移動させるために使用することができる．

GeoGebra
アプレットは完全にタッチにも対応しているので，生徒は必要に応じて特別な大型タブレットでアプレットを使用することができる．

== ツールチップ

見出しプロパティを使用し，xref:/ツールチップ.adoc[ツールチップ]の表示方法を変更することで，特定のオブジェクトにカスタムツールチップを提供することができる．（できなくなった）

== スクリーンリーダー

スクリーンリーダー スクリーンリーダーが読み上げるために，グラフィックスビューにテキストを添付できる．

GeoGebraで `++altText++` , `++altText2++` ,
 `++altText3D++` という名前のテキストオブジェクトを作成すると，それぞれグラフィックスビュー1，グラフィックスビュー2，空間図形ビューに添付される．
