= Dialogboks for egenskaper
:page-en: Settings_Dialog
ifdef::env-github[:imagesdir: /nb/modules/ROOT/assets/images]

Dialogboks for innstillinger finn du ved å gå til _Avansert..._ i menyen xref:/Meny_for_innstillinger.adoc[Instillinger]
eller ved å høyreklikke i grafikkfeltet og velge _Grafikkfelt_. I menyen øverst kan du velge mellom _Utforming_,
_Standardinnstillinger_ og _Avansert_ i tillegg til innstillinger for xref:/Grafikkfelt.adoc[grafikkfelt],
xref:/CAS_delen.adoc[CAS] og xref:/Regneark.adoc[regneark] som er aktive. Menyvalget helt til høyre er det samme som
xref:/Egenskaper.adoc[dialogboks for egenskaper].

== Egenskaper

Tar deg til xref:/Egenskaper.adoc[dialogboks for egenskaper].

== Utforming

Lar deg plassere xref:/Inntastingsfelt.adoc[inntastingsfeltet], xref:/Verktøylinje.adoc[verktøylinjen] og
xref:/Oppsett.adoc[oppsettmenyen] der du vil ha de, samt velge hvilke av de som skal vises. Du kan også velge om
overskriftslinjen skal vises.

== Standardinnstillinger

Her kan du sette standardinnstillinger for ulike typer av objekt. For punkt kan du sette standardinnstillingene for hver
av de fem typene av punkt. Innstillingene settes på samme måte som i xref:/Egenskaper.adoc[dialogboks for egenskaper].

== Avansert

[cols=",",]
|===
|* _Vinkelmål_: |Lar deg velge mellom _grader_ og _radianer_.
|* _Type markering av rett vinkel_: |Lar deg velge hvilket symbol som skal brukes for rette vinkler i grafikkfeltet.
|* _Koordinater_: |Lar deg velge hvilke koordinater skal vises.
|* _Kontinuitet_: |Dersom kontinuitet er _På_ vil GeoGebra prøve å sette nye kalkulerte punkt nær de originale.
|* _Bruk parametrer for sti og område_: |
|* _Virtuelt tastatur_: |Du kan velge språk, høyde og bredde for det virtuelle tastaturet.
|* _Størrelse på avkryssingsboksen_: |Bytt mellom vanlige og store avkryssingsbokser.
|* _Skriftstørrelse_: |Lar deg sette skriftstørrelsen til tekst og navn på objekt.
|* _Verktøytips_: |Du kan velge språk for verktøytips og hvor lenge de skal vises.
|* _Språk_: |Du kan bruke siffer og punktnavn spesifisert av språket ditt.
|* _Oppsett_: |Lar deg ignorere dokumentoppsett.
|* _Diverse_: |Her kan du aktivere scripting, java-fonter med mer.
|===

== Grafikkfelt 1/2

Gir deg valg for å tilpasse xref:/Grafikkfelt.adoc[grafikkfeltet]: dimensjoner, akser, farge, linjestil, rutenett med
mer. Se siden xref:/Innstillinger_for_grafikkfeltet.adoc[innstillinger for grafikkfeltet] for detaljer.

== Regneark

Gir deg valg for å tilpasse xref:/Regneark.adoc[regnearket]: inntastingsfelt, rutenett, overskrifter, rullefelt med mer.

== CAS

Lar deg sette en timeout i sekund for beregninger i xref:/CAS_delen.adoc[CAS-delen].
