= Eksporter til LaTeX (PGF, PSTricks) og Asymptote
:page-en: Export_to_LaTeX_(PGF_PSTricks)_and_Asymptote
ifdef::env-github[:imagesdir: /nb/modules/ROOT/assets/images]

:toc:

== Eksporter - Grafikkfelt som animert GIF...

Når en dynamisk konstruksjon avhenger av en xref:/commands/Glider.adoc[glider] vil dette menypunktet gi deg mulighet til
å lagre xref:/Grafikkfelt.adoc[grafikkfeltet] som en animert GIF-fil. Dra et markeringsrektangel rundt den delen av
konstruksjonen som du vil eksportere (eller endre størrelsen på GeoGebra-vinduet), gå til
xref:/Filmeny.adoc[Fil-menyen], _Eksporter_ og _Eksporter som animert GIF..._. En dialogboks åpnes der du får velge
glider, sette tiden mellom hvert bilde i animasjonen og velge om den skal gå som en loop.

== Eksporter - Grafikkfelt som PSTricks…

Tastatursnarvei: [.kcode]#Ctrl# + [.kcode]#Shift# + [.kcode]#T# (MacOS: [.kcode]#Cmd# + [.kcode]#Shift# + [.kcode]#T#)

Dette menypunktet lar deg lagre xref:/Grafikkfelt.adoc[grafikkfeltet] som en
http://tug.org/PSTricks/main.cgi/[PSTricks]-bildefil. Det er et xref:/LaTeX.adoc[LaTeX] bildeformat.

== Eksporter - Grafikkfelt som PGF/TiKZ…

Dette menypunktet lar deg lagre xref:/Grafikkfelt.adoc[grafikkfeltet] som en
http://sourceforge.net/projects/pgf/[PGF]-bildefil. Det er et xref:/LaTeX.adoc[LaTeX] bildeformat.

== Eksporter - Grafikkfelt som asymptote…

Dette menypunktet lar deg lagre xref:/Grafikkfelt.adoc[grafikkfeltet] som en
http://asymptote.sourceforge.net/[asymptote]-bildefil.

== Begrensninger for disse eksporteringsfunksjonene

Foreløpig kan de følgende objektene ikke eksporteres til disse formatene:

* implisitte kurver
* geometriske steder (lokuser)
