= Geometriske objekt
:page-en: Geometric_Objects
ifdef::env-github[:imagesdir: /nb/modules/ROOT/assets/images]

GeoGebra kan bruke mange forskjellige typer geometriske objekter:

* xref:/Punkt_og_vektorer.adoc[Punkt og vektorer]
* xref:/Linjer_og_akser.adoc[Linjer og akser]
* xref:/Kjeglesnitt.adoc[Kjeglesnitt og buer]
* xref:/Funksjoner.adoc[Funksjoner]
* xref:/Kurver.adoc[Kurver]
* xref:/Ulikheter.adoc[Ulikheter]
* xref:/Intervall.adoc[Intervall]
== Stier

Lister av punkt, geometriske steder og noen av de ovennevnte objektene(linjer, kjeglesnitt, buer, polygoner, funksjoner,
ulikheter, intervall) omtales som _stier_. Man kan definere et xref:/Punkt_og_vektorer.adoc[punkt] til å tilhøre en sti
med xref:/commands/Punkt.adoc[Punkt kommandoen]. Hvert punkt på en sti har en stiparameter, som er et tall fra 0 til 1.
For å få denne parameteren, kan du bruke xref:/commands/StiParameter.adoc[StiParameter kommandoen].

[NOTE]
====

*Merk:* En xref:/Lister.adoc[liste] av andre stier er også en sti.

====

== Områder

Du kan også begrense punkt til et _område_ (polygon, kjeglesnitt, bue, ulikhet) med kommandoen
xref:/commands/PunktI.adoc[PunktI] eller verktøyet xref:/tools/Punkt_på_objekt.adoc[Punkt på objekt].

== Se også

xref:/tools/Fest_frigjør_punkt.adoc[Fest / frigjør punkt].
