= Inntastingsfelt
:page-en: Input_Bar
ifdef::env-github[:imagesdir: /nb/modules/ROOT/assets/images]

Inntastingsfeltet er som standard plassert i bunnen av GeoGebra-vinduet. Du kan vise eller skjule det via
xref:/Vis_meny.adoc[vis-menyen].

Inntastingsfeltet lar deg lage og redefinere matematiske objekter ved xref:/Kommandoer.adoc[Kommandoer] eller direkte
ved algebraiske representasjoner (f.eks verdier, koordinater, likninger). Den algebraiske representasjonen er vist i
xref:/Algebrafelt.adoc[algebrafeltet]. Se xref:/Geometriske_objekt.adoc[Geometriske objekt] og
xref:/Generelle_objekt.adoc[Generelle objekt] for flere detaljer om objekter og representasjonen av de.

[NOTE]
====

*Merk:*

* Trykk alltid [.kcode]#Enter# etter du har skrevet uttrykket eller kommandoen ferdig i inntastingsfeltet.
* Hvis du ønsker å avbryte/fjerne inntastingen, kan du bruke tasten [.kcode]#Esc#.
* Til en hver tid kan du bytte fokus mellom inntastingsfeltet og xref:/Grafikkfelt.adoc[grafikkfeltet] ved å trykke
[.kcode]#Enter#. Dette gjør at du kan skrive inn uttrykk og kommandoer i inntastingsfeltet uten å måtte klikke på det
med musen først.

====

[EXAMPLE]
====

* `++A=(1,1)++` oppretter et xref:/Frie_objekt_avhengige_objekt_og_hjelpeobjekt.adoc[fritt] punkt _A_ med koordinater
_(1,1)_.
* `++A=Midtpunkt [(2,0), (4,0)] ++` redefinerer _A_ fra eksempelet over. _A_ blir et
xref:/Frie_objekt_avhengige_objekt_og_hjelpeobjekt.adoc[avgengig] punkt.

====

== Vis historien til inntastingsfeltet

Etter å ha plassert markøren i inntastingsfeltet kan du bruke piltastene [.kcode]#↑# opp og [.kcode]#↓# ned på
tastaturet for å navigere gjennom tidligere kommandoer og uttrykk steg for steg.

== Hente navn, verdi eller definisjon til et objekt fra grafikkfelt til inntastingsfeltet

Det kan være nyttig å bruke xref:/Grafikkfelt.adoc[grafikkfeltet] for å hente navn, verdi eller definisjon til et objekt
når en ikke ønsker å taste dette inn manuelt.

* Hvis du ønsker å bruke *navnet* til et objekt i inntastingsfeltet kan du xref:/Valg_av_objekt.adoc[velge] objektet med
musen og så trykke [.kcode]#F5# på tastaturet. Dette er nyttig når en ikke er sikker på hvilket navn et objekt har.
* Hvis du ønsker å bruke *verdien*(f.eks. en linje med verdi 3x - 5y = 12) til et objekt i inntastingsfeltet kan du
xref:/Valg_av_objekt.adoc[velge] objektet du ønsker verdien av og deretter trykke på [.kcode]#F4# på tastaturet.
* Hvis du ønsker å bruke *definisjonen* kan du gjøre det på to måter:
** Hold inne [.kcode]#Alt# mens du klikker på objektet.
** Velg objektet og trykk deretter på [.kcode]#F3# på tastaturet.

[NOTE]
====

*Merk:* Når du henter navn og verdi vil navnet eller verdien komme der tekstmarkøren var sist, mens når du henter en
definisjon vil det erstatte uttrykket som allerede var i inntastingsfeltet.

====
