= Intervall
:page-en: Intervals
ifdef::env-github[:imagesdir: /nb/modules/ROOT/assets/images]

Et intervall er et sett med nummer mellom øvre og nedre grense. For å opprette et intervall, skriv f.eks.
`++2 < x < 3++` i xref:/Inntastingsfelt.adoc[inntastingsfeltet]. Intervallet i det tidligere eksempelet er åpent. Du kan
lage et lukket intervall med `++2 ≤ x ≤ 3++` og et delvis lukket intervall med `++2 ≤ x < 3++`.

For å fastslå om et nummer _c_ hører til et intervall _r_ tast inn `++r(c)++` i _inntastingsfeltet_, resultatet vil være
en boolsk verdi. En generalisering av intervaller er xref:/Ulikheter.adoc[ulikheter].

== Se også

* xref:/Boolske_verdier.adoc[Boolske verdier]
* Kommandoene xref:/commands/Min.adoc[Min[ <Intervall> ]], xref:/commands/Maks.adoc[Maks[ <Intervall> ]] - Returnerer
nedre eller øvre grense til intervallet. Resultatet er uavhengig av om intervallet er åpnet, lukket eller delvis lukket.
* Kommandoen xref:/commands/Midtpunkt.adoc[Midtpunkt[ <Intervall> ]] - Returnerer midtpunktet til intervallet:
stem:[\frac\{a+b}2]. Resultatet er uavhengig av om intervallet er åpnet, lukket eller delvis lukket.
* Kommandoen xref:/commands/Punkt.adoc[Punkt[ <Intervall> ]] - Returnerer et flyttbart punkt
xref:/Punkt_og_vektorer.adoc[punkt], hvor x-koordinaten hører til intervallet og y-koordinaten er 0.
* xref:/commands/PunktI.adoc[PunktI[ <Intervall> ]] - Returnerer et flyttbart punkt, hvor x-koordinaten hører til
intervallet og y-koordinaten kan endres vilkårlig.
