= Legg inn i CMS, VLE (Moodle) og Wiki
:page-en: Embedding_to_CMS_VLE_(Moodle)_and_Wiki
ifdef::env-github[:imagesdir: /nb/modules/ROOT/assets/images]

For å lage en webside som inkluderer interaktive GeoGebra-konstruksjoner, kan du laste opp konstruksjonen med
xref:/Eksporter_dialogboks_for_arbeidsark.adoc[dialogboksen for eksportering] og deretter bruke knappen _Embed_ når du
er inne på arbeidsarket som lærer.

Du kan lime inn HTML-koden i ditt publiseringssystem (Content Mangagement System, CMS) eller
https://en.wikipedia.org/wiki/no:L%C3%A6ringsplattform[læringsplattform] så lenge de har støtte for ren HTML. Du kan
også lime HTML-koden inn i en teksteditor, legge til tekst over eller under og deretter lagre som en HTML-fil.

== Avanserte innstillinger

Når du laster opp arbeidsarket har du på første side en knapp som heter *Avanserte innstillinger...*. Her kan du endre
på funksjonaliteten til arbeidsarket. For eksempel kan du velge om det skal være ikon for tilbakestilling av figuren, om
verktøylinjen skal vises, om det skal tillates å flytte etikketer, osv.

*Innstillinger for brukergrensesnitt*

* _Tillat høyreklikk, zooming og tastaturendring_: Gir brukeren mulighet for høyreklikking som gir tilgang til
kontekstmenyen (som blant annet lar brukeren xref:/tools/Vis_eller_skjul_objekt.adoc[vise/skjule objekt/navn],
xref:/Sporing.adoc[slå sporing på/av] og xref:/Egenskaper.adoc[åpne egenskapene til objekt]). Det vil også være mulig
for eleven å bruke xref:/s_index_php?title=Tastatursnartveier_action=edit_redlink=1.adoc[tastatursnarveiene].
* _Tillat flytting av etiketter_: Lar eleven flytte etiketter i arbeidsarket.
* _Vis ikon for å tilbakestille figuren_: Viser et ikon i øvre høyre hjørne slik at eleven kan nullstille arbeidsarket.
* _Tillat skift-dra og zoom_: Tillater eleven å zoome i arbeidsarket.
* _Vis menylinje_: Viser menylinjen i det interaktive arbeidsarket.
* _Vis verktøylinje_: Viser verktøyene slik at de kan brukes.
* _Vis inntastingsfelt_: Viser inntastingsfeltet, slik at eleven kan bruke algebraiske uttrykk og kommandoer.
* _Foretrukket applet-type_: Her kan du velge om du vil at arket skal være _Standardinnstilling_ (samme som HTML5),
_HTML5_ eller _Java_ (fungerer kun på PC).

[NOTE]
====

*Merk:* Hvis størrelsen på arbeidsarket er veldig stort (over 1024x768 piksler), anbefales det at størrelsen reduseres
før arbeidsarket blir eksporterer til GeoGebra. Dette for at arbeidsarket ikke skal komme utfor skjermen på enheter med
lav oppløsning (for eksempel nettbrett).

====
