= Regneark
:page-en: Spreadsheet_View
ifdef::env-github[:imagesdir: /nb/modules/ROOT/assets/images]

I GeoGebras regneark har hver celle et bestemt navn som lar deg direkte adressere hver celle. For eksempel vil cellen i
kolonne A og rad 1 heter A1.

[NOTE]
====

*Merk:* Disse cellenavnene kan brukes i uttrykk og kommandoer for å adressere innholdet av tilsvarende celle.

====

I cellene i regnearket kan du ikke bare legge inn tall, men alle typer xref:/Generelle_objekt.adoc[generelle] og
xref:/Geometriske_objekt.adoc[geometriske objekter] som støttes av GeoGebra (f.eks koordinater til punkt,
xref:/Funksjoner.adoc[funksjoner], xref:/Kommandoer.adoc[kommandoer]). Hvis det er mulig, viser GeoGebra umiddelbart
grafisk representasjon av objektet du skrev i cellen i xref:/Grafikkfelt.adoc[grafikkfeltet] også. Objektets navn i
grafikkfeltet samsvarer med navnet på cellen(e) i regnearket som brukes for å lage det.

[EXAMPLE]
====

Skriv (1,1) i en celle. Punktet (1,1) vises i grafikkfeltet med navnet på cellen du skrev det inn i.

====

[NOTE]
====

*Merk:* Som standard er regneark objekter klassifisert som
xref:/Frie_objekt_avhengige_objekt_og_hjelpeobjekt.adoc[hjelpeobjekt] i xref:/Algebrafelt.adoc[algebrafeltet].

====

== Relative cellenavn

Som standard, hvis du kopierer innhold fra en celle til en annen, endres alle referanser tilsvarende målets posisjon.

[EXAMPLE]
====

La A1=1, A2=2. Sett B1 til `++(A1, A1)++`. Ved å kopiere B1 til B2 (enten via [.kcode]#Ctrl# + [.kcode]#C#,
[.kcode]#Ctrl# + [.kcode]#V# eller ved å dra i cellens hjørne), får du `++(A2, A2)++` i B2.

====

[NOTE]
====

*Merk:* På Mac er kopier og lim xref:/Tastatursnarveier.adoc[snarveien] [.kcode]#Cmd# + [.kcode]#C# og [.kcode]#Cmd# +
[.kcode]#V#.

====

For å unngå dette problemet, kan du sette $ før kolonnen og/eller raden med den refererte cellen. `++$A1++` låser kun
kolonnen, `++A$1++` låser kun raden og `++$A$1++` låser både rad og kolonne.

[EXAMPLE]
====

I eksempelet over, sett B1 til `++($A$1,A1)++` for å låse den ene referansecellen ved kopiering. Når B1 kopieres til B2
vil B2 inneholde `++(A1,A2)++`.

====

== Få data inn i regnearket

Foruten å manuelt legge til oppføringer i regnearket, kan du bruke xref:/commands/FyllKolonne.adoc[FyllKolonne],
xref:/commands/FyllRad.adoc[FyllRad] eller xref:/commands/FyllCeller.adoc[FyllCeller]. Se også kapittelet
xref:/Sporing.adoc[sporing til regneark].

== Bruk regnearkdata i andre visninger

Du kan behandle regnearkdata ved å velge flere celler, høyreklikke og velge et element fra "Lag"-undermenyen.
