= Zip 명령
:page-en: commands/Zip
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

Zip( <Expression>, <Var1>, <List1>, <Var2>, <List2>, ...)::
  Creates xref:/s_index_php?title=Lists_action=edit_redlink=1.adoc[list] of objects obtained by substitution of
  variables in the expression by elements of corresponding lists. If the number of variables matches the number of
  lists, each variable is taken from the following list. If the number of variables exceeds number of lists by one, the
  last variable takes values from 1, 2, 3, ..., _k_ where _k_ is the length of the shortest list. Length of the
  resulting list is minimum of lengths of input lists.

[EXAMPLE]
====

Let _list1=\{1, 2, 5}_ be a list of numbers. `++Zip(Simplify(a*x^(b-1)), a, list1,b)++` returns the list _\{1, 2x,
5x²}_.

====

[EXAMPLE]
====

Let _list1=\{x^2, x^3, x^6}_ be a list of polynomials. `++Zip(Degree(a), a, list1)++` returns the list _\{2, 3, 6}_.

====

[EXAMPLE]
====

Let P, Q, R, S be some points. `++Zip(Midpoint(A, B), A, {P, Q}, B, {R, S})++` returns a list containing
xref:/s_index_php?title=Midpoint_Command_action=edit_redlink=1.adoc[midpoints] of segments _PR_ and _QS_.

====

[NOTE]
====

In each list the elements must be of the same type.

====

== New possibility > 5.0.258 , functions allowed as variables

[EXAMPLE]
====

`++Zip(f(2), f, {x+1,x+3})++` returns the list _\{3, 5}_.

====
