= 가장가까운점 명령
:page-en: commands/ClosestPoint
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

ClosestPoint( <Path>, <Point> )::
  Returns a new point on a xref:/s_index_php?title=Geometric_Objects_action=edit_redlink=1.adoc[path] which is the
  closest to a selected point.

[NOTE]
====

For xref:/s_index_php?title=Functions_action=edit_redlink=1.adoc[Functions], this command now uses closest point (rather
than vertical point). This works best for polynomials; for other functions the numerical algorithm is less stable.

====

ClosestPoint( <Line>, <Line> )::
  Returns a new point on the first line which is the closest to the second line.

== [#가장가까운점_명령_2]####[#.EA.B0.80.EC.9E.A5.EA.B0.80.EA.B9.8C.EC.9A.B4.EC.A0.90_.EB.AA.85.EB.A0.B9_2]##가장가까운점 명령##

가장가까운점( <경로>, <점> )::
  선택된 점에 가장 가까운
  https://wiki.geogebra.org/ko/%EA%B8%B0%ED%95%98%EC%A0%81_%EB%8C%80%EC%83%81#%EA%B2%BD%EB%A1%9C[경로]위의 새로운 점을
  반환한다.

[NOTE]
====

https://wiki.geogebra.org/ko/%ED%95%A8%EC%88%98[함수]에 대해서 이 명령어는 이제 (수직인 점이 아닌) 가장 가까운 점을
사용한다. 이 명령어는 다항식에 대하여 가장 잘 작동한다. 다른 함수에 대해서는 수치적 알고리즘이 덜 안정적이다.

====

가장가까운점( <직선>, <직선> )::
  두 번째 직선에 가장 가까운 첫 번째 직선 위의 새로운 점을 반환한다.
