= 곡선 명령
:page-en: commands/Curve
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

Curve( <Expression>, <Expression>, <Parameter Variable>, <Start Value>, <End Value> )::
  Yields the Cartesian xref:/s_index_php?title=Curves_action=edit_redlink=1.adoc[parametric curve] for the given
  _x_-expression (first <Expression>) and _y_-expression (second <Expression>) (using parameter variable) within the
  given interval [_Start Value_, _End Value_].

[EXAMPLE]
====

`++Curve(2 cos(t), 2 sin(t), t, 0, 2π)++` creates a circle with radius _2_ around the origin of the coordinate system.

====

Curve( <Expression> , <Expression> , <Expression> , <Parameter Variable> , <Start Value> , <End Value> )::
  Yields the 3D Cartesian parametric curve for the given _x_-expression (first <Expression>), _y_-expression (second
  <Expression>) and _z_-expression (third <Expression>) (using parameter variable) within the given interval [_Start
  Value_, _End Value_].

[EXAMPLE]
====

`++Curve(cos(t), sin(t), t, t, 0, 10π)++` creates a 3D spiral.

====

[NOTE]
====

* _End Value_ must be greater than or equal to _Start Value_ and both must be finite.
* _x_, _y_ and _z_ are not allowed as parameter variables.
* See xref:/s_index_php?title=Curves_action=edit_redlink=1.adoc[Curves] for details, also see the
xref:/s_index_php?title=Derivative_Command_action=edit_redlink=1.adoc[Derivative Command] and the
xref:/s_index_php?title=ParametricDerivative_Command_action=edit_redlink=1.adoc[Parametric Derivative Command].

====
