= 랜덤 명령
:page-en: commands/RandomBetween
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

RandomBetween( <Minimum Integer> , <Maximum Integer> )::
  Generates a random integer between _minimum_ and _maximum_ (inclusive).
RandomBetween( <Minimum Integer> , <Maximum Integer> , <Boolean Fixed> )::
  If _Boolean Fixed_ = "true", it generates a random integer between _minimum_ and _maximum_ (inclusive), which is
  updated just once (when file is loaded and also on undo/redo).

[EXAMPLE]
====

`++RandomBetween(0, 10, true)++` yields a number between _0_ and _10_ (inclusive)

====

[EXAMPLE]
====

`++RandomBetween(0, 10)++` yields a number between _0_ and _10_ (inclusive)

====

[NOTE]
====

Press [.kcode]#F9# to see the difference between those two syntaxes.

====

[NOTE]
====

See also xref:/s_index_php?title=SetSeed_Command_action=edit_redlink=1.adoc[SetSeed command],
xref:/s_index_php?title=RandomElement_Command_action=edit_redlink=1.adoc[RandomElement command],
xref:/s_index_php?title=RandomBinomial_Command_action=edit_redlink=1.adoc[RandomBinomial command],
xref:/s_index_php?title=RandomNormal_Command_action=edit_redlink=1.adoc[RandomNormal command],
xref:/s_index_php?title=RandomPoisson_Command_action=edit_redlink=1.adoc[RandomPoisson command],
xref:/s_index_php?title=RandomUniform_Command_action=edit_redlink=1.adoc[RandomUniform command].

====
