= 반복 명령
:page-en: commands/Iteration
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

Iteration( <Function>, <Start Value>, <Number of Iterations> )::
  Iterates the function _n_ times (_n_ = number of iterations) using the given start value.

[EXAMPLE]
====

* After defining `++f(x) = x^2++` the command `++Iteration(f, 3, 2)++` gives you the result (3^2^)^2^ = 81.
* _Repeated addition_: To obtain the repeated addition of 7 to the number 3, define `++g(x) = x + 7++`, then
`++Iteration(g, 3, 4)++` yields (((3+7) +7) +7) +7 = 31.

====

Iteration( <Expression>, <Variable Name>, ..., <Start Values>, <Number of Iterations> )::
  Iterates the expression _n_ times (_n_ = number of iterations) using the given start value. The result is then the
  last element of the output of xref:/s_index_php?title=IterationList_Command_action=edit_redlink=1.adoc[IterationList
  Command], with the same parameters.

[EXAMPLE]
====

 :`++Iteration(a^2+1,a,{(1+ί)/(sqrt(2))},5)++` will do a repeated iteration on a complex number

====

[NOTE]
====

See xref:/s_index_php?title=IterationList_Command_action=edit_redlink=1.adoc[IterationList Command] for further details.

====
