= 배경색지정 명령
:page-en: commands/SetBackgroundColor
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

SetBackgroundColor( <Object>, <Red>, <Green>, <Blue> )::
  Changes the background color of given object. This is used for _Texts_ and for objects in the _Spreadsheet_. The red,
  green and blue represent amount of corresponding color component, 0 being minimum and 1 maximum. Number _t_ exceeding
  this interval is mapped to it using function stem:[2\left|\frac\{t}2-\mathrm round\left(\frac\{t}2\right)\right|].
SetBackgroundColor( <Object>, <"Color"> )::
  Changes the background color of given object. This is used for _Texts_ and for objects in the _Spreadsheet_. The color
  is entered as xref:/s_index_php?title=Texts_action=edit_redlink=1.adoc[text], that may be:
  * an English color name (see /s_index_php?title=Reference:Colors_action=edit_redlink=1.adoc[Reference:Colors]). Some
  of them can be also used in national languages and are listed below.

[NOTE]
====

If you use this command in a GeoGebraScript, you must use the English color names

====

* an hexadecimal string of the type #AARRGGBB or #RRGGBB, where _AA_ defines transparency (00 full transparency to FF
full opacity), _RR_ defines the red component, _GG_ the green one and _BB_ the blue one.

[EXAMPLE]
====

`++SetBackgroundColor(text1, "#80FF0000")++` sets the background color of exixting _text1_ as Red, with a 50%
transparency.

====

SetBackgroundColor( <Red>, <Green>, <Blue> )::
  Changes the background color of the active Graphics View
SetBackgroundColor( <"Color"> )::
  Changes the background color of the active Graphics View

[NOTE]
====

If you use this command in a GeoGebraScript, you must use the English color names

====

* 검정
* 어두운 회색
* 회색
* 어두운 파랑
* 파랑
* 어두운 녹색
* 녹색
* 마룬
* 크림슨
* 빨강
* 마젠타
* 인디고
* 자주
* 갈색
* 오렌지
* 금색

* 라임
* 시안
* 터콰이즈
* Light Blue
* 아쿠아
* 은색
* 밝은 회색
* 분홍
* 바이올렛
* 노랑
* 밝은 노랑
* 밝은 오렌지
* 밝은 보라
* 밝은 자주
* 밝은 녹색
* 흰색

 
