= 역연산 명령
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

역연산[ <행렬> ]::
  Inverts the given matrix.
  Invert[ <Function> ];;
    Gives the inverse of the function.
      [EXAMPLE]

  ====

  `++Invert[sin(x)]++` yields _asin(x)_.

  ====
  [NOTE]

  ====

  The function must contain just one _x_ and no account is taken of domain or range, for example for f(x) = x^2 or f(x)
  = sin(x). If there is more than one _x_ in the function another command might help you:

  [EXAMPLE]

  ====

  Both `++Invert[PartialFractions[(x + 1) / (x + 2)]]++` and `++Invert[CompleteSquare[x^2 + 2 x + 1]]++` yield the
  inverse functions.

  ====

  ====

[EXAMPLE]
====

`++Invert[{{1, 2}, {3, 4}}]++` yields stem:[ \begin\{pmatrix} -2 & 1\\ 1.5 & -0.5 \end\{pmatrix} , the inverse matrix of
\begin\{pmatrix} 1 & 2\\ 3 & 4 \end\{pmatrix} ].

====

== CAS 창

역행렬[ <행렬> ]::
  Inverts the given matrix.
  Invert[ <Function> ];;
    Gives the inverse of the function.
      [EXAMPLE]

  ====

  * `++Invert[(x + 1) / (x + 2)]++` yields _stem:[\frac\{-2x + 1}\{x - 1}]_.
  * `++Invert[x^2 + 2 x + 1]++` yields _stem:[\sqrt x - 1]_.

  ====
  [NOTE]

  ====

  In the xref:/s_index_php?title=CAS_View_action=edit_redlink=1.adoc[CAS View], the command also works if the function
  contains more than one _x_.

  ====

[EXAMPLE]
====

`++Invert[{{a, b}, {c, d}}]++` yields stem:[ \begin\{pmatrix} \frac\{d}\{ad- bc} & \frac\{-b}\{ad- bc}\\ \frac\{-c}\{ad-
bc}& \frac\{a}\{ ad- bc} \end\{pmatrix} , the inverse matrix of \begin\{pmatrix} a & b\\ c & d \end\{pmatrix} ].

====
