= 음악연주 명령
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

음악연주[ <음표>, <시간>, <악기> ]::
  MIDI 음표를 연주한다.
  _음표_ 는 아래의 표에 의해 주어진 음악 악보를 나타내는 0부터 127까지의 숫자이다. 음표가 60이면 가온다(C)를 연주한다.
  _시간_ 은 음표가 연주되는 시간이다.
  _악기_ 는 음표를 연주하는 데 사용되는 합성된 악기를 나타내는 정수이다. 연주 가능한 악기는
  http://www.classicalmidiconnection.com/General_Midi.html[기술적인 세부사항] 에서 참조할 수 있다.
  대부분의 악기가 지원되지만, 컴퓨터 운영체제 사이의 차이가 존재할 수 있다.

*MIDI 음표*

옥타브

C

C#

D

D#

E

F

F#

G

G#

A

A#

B

*0*

0

1

2

3

4

5

6

7

8

9

10

11

*1*

12

13

14

15

16

17

18

19

20

21

22

23

*2*

24

25

26

27

28

29

30

31

32

33

34

35

*3*

36

37

38

39

40

41

42

43

44

45

46

47

*4*

48

49

50

51

51

53

54

55

56

57

58

59

*5*

60

61

62

63

64

65

66

67

68

69

70

71

*6*

72

73

74

75

76

77

78

79

80

81

82

83

*7*

84

85

86

87

88

89

90

91

92

93

94

95

*8*

96

97

98

99

100

101

102

103

104

105

106

107

*9*

108

109

110

111

112

113

114

115

116

117

118

119

*10*

120

121

122

123

124

125

126

127

음악연주[ <음표열>, <악기> ]::
  http://www.jfugue.org[JFugue] 음악 스트링을 사용한 MIDI 악보와 명령문을 연주한다.
  _음표열_ 은 JFugue 문자 명령을 사용한 텍스트 스트링이다.
  _악기_ 는 스트링이 연주될 때 사용되는 기본 MIDI 악기이다.
  기본 명령은 아래와 같다. 모든 명령들은 http://www.jfugue.org/jfugue-chapter1.pdf[The Complete Guide to JFugue] (영어)
  에 기술되어 있다.

*기본 JFugue 명령*

문자

명령

A-G

5 옥타브에서 글자로 주어진 음표를 연주한다.

반음 올림과 반음 내림을 위해 b 또는 # 을 붙인다.

옥타브를 변경하려면 옥타브 번호를 붙인다. 예. A4

음표 길이는 다르게 지정되지 않는 한 4분 음표이다.

{empty}[정수]

정수(0-127)로 주어진 MIDI 음표를 연주한다.

+

화음으로 음표를 함계 연주한다. 예. C+E+G

R

쉼표

w, h, q, i, s

음표나 쉼표 뒤에 추가하여 길이를 지정한다.

w = 온음표

h = 2분음표

q = 4분음표

i = 8분음표

s = 16분음표

/n

음표나 쉼표 뒤에 추가하여 n(실수)로 길이를 지정한다.

/1 = 온음표

/.5 = 2분음표

/.25 = 4분음표

/2 = 2배

I[정수]

악기를 지정한다.

V

V 뒤의 0부터 15까지의 수는 MIDI 채널을 지정한다. "V9" 는 MIDI 타악기 채널을 지정한다.

공백

이전 음표, 음표 또는 쉼표의 조합을 연주한다.

[EXAMPLE]
====

`++음악연주["C+E+G  Rw  Ai Bi Ci  A4i B4i C4i ", 0]++`

4분음표의 CEG 화음을 연주하고, 온쉼표로 쉬고, 8분음표로 A, B, C를 연주한 후, 한 옥타브 낮게 다시 연주한다.

피아노가 악기로 사용된다.

====

[EXAMPLE]
====

`++음악연주["I[56] C5q D5q I[71] G5q F5q", 0]++`

다양한 악기로 악보를 연주한다. 트럼펫=56, 클라리넷=71.

====

[EXAMPLE]
====

`++음악연주["V0 A3q B3q C3q B3q V1 A2h C2h", 0]++`

다른 소리로 화음으로 악보를 연주한다.

====

음악연주[ <파일> ]::
  JFugue 스트링을 포함한 MIDI 파일 (*.mid) 또는 텍스트 파일(* .txt) 을 연주한다.
  "파일" 은 해당 파일의 폴더 경로이다. 예. 음악연주["c:\myFile.mid"]

음악연주[ <함수>, <최솟값>, <최댓값> ]::
  정의역이 구간 [-1, 1]인 함수에 의해 생성된 소리를 연주한다. 시간 단위는 초(sec)이며, 소리는 시간의 최솟값부터
  최댓값까지 연주된다. 소리는 초당 8000 샘플의 비율로 얻어진 8-비트 샘플에 의해 생성된다.

[EXAMPLE]
====

`++음악연주[sin(440 2Pi x), 0, 1]++`

이 명령은 사인파로 1초간 440 Hz (A음)을 연주한다.

====

음악연주[ <함수>, <최솟값>, <최댓값>, <표본 비율>, <표본 깊이> ]::
  정의역이 구간 [-1, 1]인 함수에 의해 생성된 소리를 연주한다. 시간 단위는 초(sec)이며, 소리는 시간의 최솟값부터
  최댓값까지 연주된다. 샘플링 방법은 "샘플 깊이"와 "샘플 비율"에 의해 지정된다.
  "샘플 비율" 은 각각의 초(sec)를 취하는 샘플 함수의 수이다. 가능한 값은 8000, 11025, 16000, 22050, 44100 이다.
  "샘플 깊이" 는 비트에서 샘플의 데이터 크기이다. 가능한 값은 8, 16이다.

음악연주[ <진릿값 연주여부> ]::
  연주를 정지하거나 시작한다.
  음악연주[true] = 연주, 음악연주[false] = 정지.
