= 직사각형합 명령
:page-en: commands/RectangleSum
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

RectangleSum( <Function>, <Start x-Value>, <End x-Value>, <Number of Rectangles>, <Position for rectangle start> )::
  Calculates between the _Start x-Value_ and the _End x-Value_ the sum of rectangles with left height starting at a
  fraction _d_ (0 ≤ _d_ ≤ 1) of each interval, using _n_ rectangles.
  When _d_ = 0 it is equivalent to the xref:/s_index_php?title=LeftSum_Command_action=edit_redlink=1.adoc[LeftSum]
  command, and when _d_ = 1 it computes the right sum of the given function.

[NOTE]
====

* This command draws the rectangles of the left sum as well.
* This command is designed as a visual aid so won't give accurate answers if the number of rectangles is too large.
* See also the commands: xref:/s_index_php?title=UpperSum_Command_action=edit_redlink=1.adoc[UpperSum],
xref:/s_index_php?title=LowerSum_Command_action=edit_redlink=1.adoc[LowerSum],
xref:/s_index_php?title=LeftSum_Command_action=edit_redlink=1.adoc[LeftSum] ,
xref:/s_index_php?title=TrapezoidalSum_Command_action=edit_redlink=1.adoc[TrapezoidalSum].

====
