= 최소제곱법 명령
:page-en: commands/Fit
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

Fit( <List of Points>, <List of Functions> )::
  Calculates a linear combination of the _functions_ that best fit the _points_ in the list.

[EXAMPLE]
====

* `++Fit({(-2, 3), (0, 1), (2, 1), (2, 3)}, {x^2, x})++` yields _0.625 x^2 - 0.25x_.
* Let _L = \{A, B, C, ...}_, _f(x) = 1_, _g(x) = x_, _h(x) = e^x_, _F = \{f, g, h}_. `++Fit(L, F)++` calculates a
function of the form _a + b x + c e^x_ that fits the points in the list.

====

Fit( <List of points>, <Function> )::
  Calculates a minimum squared error function to the points in the list. The _function_ must depend on one or more
  sliders, that are taken as start values of parameters to be optimized. The non-linear iteration might not converge,
  but adjusting the sliders to a better starting point might help.

[EXAMPLE]
====

Let _a_ be slider with interval from _-5_ to _5_ and increment 1. `++Fit({(-2, 3), (0, 1), (2, 1), (2, 3)}, a + x^2)++`
yields _-1 + x^2_.

====

[NOTE]
====

* See also xref:/s_index_php?title=FitExp_Command_action=edit_redlink=1.adoc[FitExp],
xref:/s_index_php?title=FitGrowth_Command_action=edit_redlink=1.adoc[FitGrowth],
xref:/s_index_php?title=FitLine_Command_action=edit_redlink=1.adoc[FitLine],
xref:/s_index_php?title=FitLineX_Command_action=edit_redlink=1.adoc[FitLineX],
xref:/s_index_php?title=FitLog_Command_action=edit_redlink=1.adoc[FitLog],
xref:/s_index_php?title=FitLogistic_Command_action=edit_redlink=1.adoc[FitLogistic],
xref:/s_index_php?title=FitPoly_Command_action=edit_redlink=1.adoc[FitPoly],
xref:/s_index_php?title=FitPow_Command_action=edit_redlink=1.adoc[FitPow] and
xref:/s_index_php?title=FitSin_Command_action=edit_redlink=1.adoc[FitSin]
* If you work with big/small numbers, you should consider normalizing them for a more accurate result, see
xref:/s_index_php?title=Normalize_Command_action=edit_redlink=1.adoc[Normalize Command].

====
