= 카이제곱 명령
:page-en: commands/ChiSquared
ifdef::env-github[:imagesdir: /ko/modules/ROOT/assets/images]

ChiSquared( <Degrees of Freedom>, x )::
  Creates cumulative density function (cdf) of https://en.wikipedia.org/wiki/Chi-square_distribution[Chi squared
  distribution] with the appropriate degrees of freedom.
ChiSquared( <Degrees of Freedom>, x, <Boolean Cumulative> )::
  If the logical value is _true_, creates cumulative distribution function of Chi squared distribution, otherwise
  creates pdf of Chi squared distribution.
ChiSquared( <Degrees of Freedom>, <Variable Value> )::
  Calculates the value of cumulative distribution function of Chi squared distribution at _Variable Value_ _v_, i.e. the
  probability _P(X ≤ v)_ where _X_ is a random variable with Chi squared distribution with the appropriate degrees of
  freedom.

[EXAMPLE]
====

`++ChiSquared(4, 3)++` yields stem:[\gamma(2, \frac\{3}\{2})], which is approximately _0.44_.

====

[NOTE]
====

Returns the probability for a given _x_-coordinate's value (or area under the Chi squared distribution curve to the left
of the given _x_-coordinate).

====
